### ISSUE TITLE
What does "Storage" mean in a Collab?

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#10]
When clicking on "Storage" in a collab I am presented with a screen  have no idea what this is about. There is also no mention about "Storage" in the Overview documentation. 

![screen shot 2017-09-29 at 12 07 07](https://user-images.githubusercontent.com/12729291/31011634-496c30a4-a50f-11e7-9b47-22f1a2531cd2.png)

Suggestion: 

- Add small description in the Overview page
- Add some small hints in the Storage page itself, like a more meaningful title, or rename "Storage" altogether (like "Personal Storage Space")

**Comment by jdcourcol** [comment]
this is for https://forum.humanbrainproject.eu/
