### ISSUE TITLE
Config file error although config file choosen

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#100]
### Expected behavior

Use case shows me the results table at the end

### Actual Behavior

Popup with error message: 

"This is not a config file"

![selection_112](https://user-images.githubusercontent.com/12729291/33593877-be7e9876-d991-11e7-8696-50737a5a3fa6.png)

### Steps to reproduce the problem

Run the use case, select trace 20, choose "config.txt" as config file, press on "Results table"

### Optional infrastructural data (user, platform, browser, environment, ...)

Chrome, Linux

**Comment by clupascu** [comment]
Can you add me as a team member of this collab? I need to take a look at the config file. Thanks.

**Comment by alex4200** [comment]
@clupascu : I added you to Collab Test-A3-5

**Comment by clupascu** [comment]
I fixed this. Can you test again please? Thanks.

**Comment by alex4200** [comment]
Yes fixed
