### ISSUE TITLE
"Launch simulation" does not seem to work

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#101]
### Expected behavior

Simulation is started once "Launch simulation" is pressed

### Actual Behavior

When pressing the  "Launch simulation" button a popup appears briefly stating the simulation is started, but then vanishes, and the GUI does not change. I can press the button "Launch simulation"  again...

![selection_113](https://user-images.githubusercontent.com/12729291/33594582-c4176576-d994-11e7-95ac-7db0a8565824.png)
![selection_115](https://user-images.githubusercontent.com/12729291/33594616-df7da7bc-d994-11e7-81a9-d267710841c5.png)

### Steps to reproduce the problem

Just follow the description for "Cell Optimization"

### Optional infrastructural data (user, platform, browser, environment, ...)

Linux, Chrome

**Comment by lbologna** [comment]
I added a notification message after submission.
Could you please check again?
Thanks!

**Comment by alex4200** [comment]
Testing blocked by #116

**Comment by alex4200** [comment]
Yes perfect, much better now, thanks
