### ISSUE TITLE
Unable to check if I am logged in 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#102]
When I run the HH Neuton Builder use case and I select the "optimization settings" button, I might be required to provide my username and password for NSG. 

![selection_116](https://user-images.githubusercontent.com/12729291/33595359-0918fc2c-d998-11e7-9dd5-9ceaa061431a.png)

However, I have no way to see if the data I have provided is correct. 

Suggestion: A small button below the user data that provides feedback if the NSG userdata are correct.

**Comment by lbologna** [comment]
Hello,

I modified the code so as to notify the user if she/he inserts wrong credentials. In this case the panel is not closed until the "Cancel" button is pressed or the correct credentials are inserted.

In case the correct credentials are typed, the panel closes (without notification) and the bottom bar in the "Optimization settings" panel of the "Workflow" page turns green.

Could you check if this works fine please?

Thanks.

**Comment by alex4200** [comment]
Ok very good, seems to work...
