### ISSUE TITLE
Fetching results from NSG takes a very long time

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#103]
### Expected behavior

Fetching results is 'fast' (say less than 1 minute). 

### Actual Behavior

Even after 20 minutes I see the "Fetching job list" screen with a rotating arrow. 

![selection_118](https://user-images.githubusercontent.com/12729291/33595791-bda44ce0-d999-11e7-9419-554087f130d4.png)

### Steps to reproduce the problem

Following the steps for "Single Cell Simulation Run" and select "Fetch results" from NSG. Applying username/password and click on "Apply"

### Optional infrastructural data (user, platform, browser, environment, ...)

Linux, Chrome

**Comment by lbologna** [comment]
This should be fixed. Could you test again please? Thanks

**Comment by alex4200** [comment]
Yes works much faster now ;-)
