### ISSUE TITLE
NameError for BestFit in Synaptic Events Fitting

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#104]
### Expected behavior

Seeing best fit results

### Actual Behavior

NameError, probably some small issue with the code:
```
NameError                                 Traceback (most recent call last)
<ipython-input-14-9b6523263e1e> in bestfit(_)
    529         for k in range(len(paramname)):
    530             vecparamsf.append(data[NAMES[k+3]][indexplot])
--> 531         if RB1.value=='local':
    532             fitness.filename3=file_widget.filename
    533         else:

NameError: name 'RB1' is not defined
```

![selection_122](https://user-images.githubusercontent.com/12729291/33615321-2abf7d46-d9da-11e7-9704-3286711091e9.png)

### Steps to reproduce the problem

Follow the use case, use the files you have sent me, select trace 20, click on "Best Fit"

### Optional infrastructural data (user, platform, browser, environment, ...)

Linux, Chrome

**Comment by clupascu** [comment]
I fixed this. Can you test again please? Thanks.

**Comment by alex4200** [comment]
@clupascu There still seems to be an error: 

![selection_124](https://user-images.githubusercontent.com/12729291/33647628-622c1d8a-da56-11e7-8c27-dd206b20d3bf.png)

**Comment by clupascu** [comment]
It should be fixed now. You can't test it now though. After the platform update, neuron can't be imported anymore (see issue #107). When issue #107 is fixed, you can try again to test Best fit button.

**Comment by alex4200** [comment]
@clupascu Seems there is still some error:

```
IOErrorTraceback (most recent call last)
<ipython-input-33-177e04478b62> in bestfit(_)
    570         vclamp.amp[0] = Vrest
    571 
--> 572         with open(fitness.filename3) as ff:
    573             searchlines=ff.readlines()
    574         for kk, line in enumerate(searchlines):

IOError: [Errno 2] No such file or directory: 'exp3syn.mod\n'
```

It looks you have an '\n' in the filename. Can you check that?

Thanks

**Comment by clupascu** [comment]
I fixed this. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Work! thanks
