### ISSUE TITLE
User message in case of a bad fit 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#105]
In case the fitting does not give any meaningful results (and there is no CSV file), the user should see an appropriate message like

The computation did not reveal any suitable fit

**Comment by clupascu** [comment]
In case the fitting does not give any meaningful results, there is an empty csv file in the output folder. In this case the user sees a message like this 'Results file is empty. No fitting was within threshold'

In case an error occurred in the submitted job, there is not a csv file in the output folder. In this case the user sees a message like this 'no txt or csv files in the output folder. Take a look at the stderr and stdout files in the storage. If there are no stdout and stderr files, an error occurred with the job on the HPC. Try to submit the job again to the HPC.'

Is this more clear now?

**Comment by alex4200** [comment]
Yes, that is much clearer now... thanks
