### ISSUE TITLE
Clarification of example

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#106]
In the use case the user can choice between an example and the actual result of the fit. It should be noted that the 'default' selection is such an example...

![selection_123](https://user-images.githubusercontent.com/12729291/33615580-cb7a9fea-d9da-11e7-9355-c4afd1c624ae.png)

**Comment by clupascu** [comment]
I replaced 'default' by 'example'. Thanks.

**Comment by alex4200** [comment]
Thanks, is working..
