### ISSUE TITLE
"No module named neuron"

### ISSUE THREAD

**Issue by SteMasoli** [cnr-ibf-pa/hbp-bsp-issues#107]
### Expected behavior
Presence of the basic simulation environment program - NEURON simulator.

### Actual Behavior
Cerebellar granule cells notebooks:
Error - "No module named neuron"

### Steps to reproduce the problem
The notebook stops at this line:
nrn = ephys.simulators.NrnSimulator()
with this error.
ImportError: No module named neuron

### Optional infrastructural data (user, platform, browser, environment, ...)
Update to the platform. 6 december 2017.

**Comment by clupascu** [comment]
Write to the platform team and ask if neuron is installed in the latest image of the notebooks that they released today.

**Comment by SteMasoli** [comment]
Done it. Waiting for news.

**Comment by SteMasoli** [comment]
The platform team responded that, yes NEURON is missing from the image they deployed yesterday.
They will patch it today or tomorrow.

**Comment by alex4200** [comment]
@clupascu  @SteMasoli The Collab image has been updated with NEURON installed...
