### ISSUE TITLE
"View simulations" page unclear

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#108]
Looking at the "View Simulations" page:

![selection_125](https://user-images.githubusercontent.com/12729291/33701290-77c8f032-db1e-11e7-984e-e16bedd17b2d.png)

- Does the checkmark in 'Simulation Step' means the simulation finished sucessfully?
- Does clicking on 'Analysis' in Analysis step means to run the analysis?

![selection_126](https://user-images.githubusercontent.com/12729291/33701333-9fbd9e80-db1e-11e7-92f2-d300ba50115b.png)

- Do I have to create another job for the analysis?
- Why do I have to copy files? Is this the analysis or a copy job? 

![selection_127](https://user-images.githubusercontent.com/12729291/33701622-ea518050-db1f-11e7-9a7d-2ad14c63ac0e.png)

- Now the analysis seems completed. But where do I fond the results? What are the results? If I click on 'Analysis' I seem to rerun the analysis. I am confused....

**Comment by antonelepfl** [comment]
@alex4200 I changed the '> Analysis' button for 'Run' due it is under Analysis step and as you suggested makes more sense of what we are going to do.
![screen shot 2018-01-03 at 10 54 12](https://user-images.githubusercontent.com/24406041/34515866-866b5f24-f074-11e7-883c-981b4c3bdd71.png)

I added a description in the launcher form so I can explain more about the process.
![screen shot 2018-01-03 at 10 54 26](https://user-images.githubusercontent.com/24406041/34515867-86851cd4-f074-11e7-84ef-5f7fdfa1996f.png)


Do you think this description should be a helper like 
![screen shot 2018-01-03 at 10 57 44](https://user-images.githubusercontent.com/24406041/34515973-0bbf190e-f075-11e7-9f62-5287aedcfc87.png)
And then do not show it anymore if the user closes it?

**Comment by antonelepfl** [comment]
Deployed. Please try it and close it after you tested it.

**Comment by alex4200** [comment]
Great, looks fine to me...
