### ISSUE TITLE
Dropdown boxes party invisible

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#109]
### Expected behavior

I can see the content of the dropdown boxes

### Actual Behavior

They are party hidden:

![selection_128](https://user-images.githubusercontent.com/12729291/33701692-35c5f9ee-db20-11e7-98b2-3489f44796a2.png)

### Optional infrastructural data (user, platform, browser, environment, ...)

Only on FF, Chrome seems to be ok

**Comment by antonelepfl** [comment]
Deployed. Please try it and close it after you tested it.

**Comment by alex4200** [comment]
Yes fixed
