### ISSUE TITLE
How to use own morphology in morph. analysis?

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#11]
When using the Jupiter morphology analysis, an example is given by using a morphology from without. But how to use my own morphology from within the collab storage, for example?

**Comment by alex4200** [comment]
Not sure what this was about

**Comment by jdcourcol** [comment]
@alex4200 it is probably missing an example where the end user is using a morphology from neuromorpho.org or a morphology from his local file system
