### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#110]
Documentation in Guidebook: General description for the user of the scope of the use case and what the user can do in general

Detailed technical documentation: directly within the notebook  (also avoids the need to update screenshots whenever there is a change)

**Comment by alex4200** [comment]
changes have been pushed

**Comment by SteMasoli** [comment]
The documentation is now online

**Comment by alex4200** [comment]
@SteMasoli: Thanks for this update; I think content-wise this description is absolutely sufficient. 

However, I have some suggestions regarding some wording/phrasing:

1. Instead of having the title "Mono compartmental Cerebellar Granule cell running on the collab" I would say just "Mono compartmental Cerebellar Granule cell optimization"  as the use cases are on the Collab anyway. (same for the multi-compartemental use case)
2. In the next two sections you have twice the sentence "Mono compartmental cerebellar granule cell optimized with BluePyOpt.." It reads a bit weird. 
3. There are also some periods '.' missing in some sentence or are double
4. One last thing: Please make sure you write "Collab" instead of "collab" as we decided this is a proper name...


Thanks

**Comment by SteMasoli** [comment]
Pull request just done.
Deleted the duplicated paragraph, in the mono compartmental granule cell guide and the repeated titles (1.) (2.) (3.).
Modified in both files (4.)

**Comment by lbologna** [comment]
The Guidebook has been updated on the BSP. Would you please check? Thanks.

**Comment by alex4200** [comment]
Yes seems to be done thanks
