### ISSUE TITLE
Usage of '/home/jupyter' instead  `/home/jovyan`

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#111]
### Expected behavior

No error

### Actual Behavior

OSError: [Errno 2] No such file or directory, line 62:

```
<ipython-input-7-cdc45f67112e> in on_w3_clicked(change)
     60     outputHTML.layout.display='none'
     61     plotly.offline.init_notebook_mode()
---> 62     os.chdir("/home/jupyter/BPOPTANALYSIS")
     63     if c1.value=='GitHub':
     64         os.chdir(w3.value)
```

### Steps to reproduce the problem

Run the Analysis notebook on storage results.

**Note: The error appears for BOTH use cases**

**Comment by clupascu** [comment]
I fixed this. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Yes works again, thanks
