### ISSUE TITLE
Suggestion regarding ipywidgets

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#113]
Currently, you have the message regarding downgrading `ipywidgets` showing up at the top of every notebook all the time. 

However, once the user has downgraded its version of `ipywidgets` you can do a simple check if the installed version is compatible with the required version for your notebook. Then the user sees this `ipywidgets`-downgrade message only once. 

Suggested code change: 

```
...
version_required = "OLD"

if version_required != message_params['version']:
    display(HTML('''
    <script>
        $('.input').hide();
        function run_all() {
            setTimeout(() => Jupyter.notebook.execute_all_cells(), 1000);
        }
        Jupyter.notebook.events.on('kernel_ready.Kernel', run_all);
    '''))

    button = widgets.Button(description=button_text)
    button.on_click(lambda b: install_widgets(versions_to_install))
    display(button)
    display(Markdown(message.format(**message_params)))
```

**Comment by clupascu** [comment]
I fixed the code as you suggested. Now the upgrade button is not displayed anymore if the user has downgraded its version of ipywidget. Can you please test? Thanks.

**Comment by alex4200** [comment]
Works as expected, thanks
