### ISSUE TITLE
Analysis buttons active although no results available...

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#114]
### Expected behavior

When there are  no results to plot (i.e. no fit is available), the buttons shown at the bottom of the page should be inactive or being replaced by some box saying something like "No fits available"

### Actual Behavior

Buttons active, and upon clicking them an error occurs (because no results are available)...

### Steps to reproduce the problem

Probably just run anything...

**Comment by clupascu** [comment]
I fixed this. Can you please test again? (you can just create an empty output_... folder in the resultsNSG folder in the storage in order to test this part) Thanks.

**Comment by alex4200** [comment]
Yes, work!
