### ISSUE TITLE
Feature Extraction in the Neuron Builder seems to 'hang'. 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#116]
### Expected behavior

When I selected the traces in the Feature extraction part of the HH Neuron builder I expect the workflow to move on. 

### Actual Behavior

I click on the 'Confirm' button after I click on th 'Next' button, and I get back to the 'Trace selection/upload' page. 

![screen shot 2017-12-18 at 14 30 02](https://user-images.githubusercontent.com/12729291/34108538-bbecdc7a-e400-11e7-8442-9cd71702b0d6.png)
![screen shot 2017-12-18 at 14 30 09](https://user-images.githubusercontent.com/12729291/34108542-c034d47c-e400-11e7-8bc5-aca3be16a386.png)

### Steps to reproduce the problem

- Select 'Initiate a new workflow
- Click on 'Cell Optimization'
- Select 'Extract Features'
- follow the workflow until the 'Trace selection/upload' page. 

### Optional infrastructural data (user, platform, browser, environment, ...)

On the Test notekook in the section "** TESTING apps **".

**Comment by lbologna** [comment]
Hello,

I cannot reproduce this error: the "Confirm" button works well for me.
Is this error reproducible?

Thanks.

**Comment by alex4200** [comment]
@lbologna : Hm seems to work now. Maybe it was a transient problem. Closing for now...
