### ISSUE TITLE
"Please wait" panel for loading the traces in "Feature Extraction"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#117]
Luca is about to add a "please wait" panel until all traces are loaded in the "Feature Extraction" use case as Its very hard for the selenium tests otherwise. 

@lbologna: Issues based on our email conversation...

**Comment by lbologna** [comment]
This should be fixed. Could you test again please? Thanks

**Comment by alex4200** [comment]
Yes works great.
