### ISSUE TITLE
New Hippocambal Cell placement and connectome use cases.

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#118]
The idea is to replace the current notebook use-cases with proper GUI like use cases. 

- [ ] Preparing use case
- [ ] Preparing user documentation

**Comment by arsenius7** [comment]
Being indirectly blamed for ignoring this ticket (which despite its form is a fair call), I feel obliged to write down, that I do not plan to work on it in the near future.
If you feel uncomfortable about that, please check with @jdcourcol.

**Comment by alex4200** [comment]
@arsenius7: Thanks for the update...

**Comment by alex4200** [comment]
Update from @jdcourcol : 

- Placement: there is an issue with the numpy library for which there are too many CPUs available. Clarification going on
- Connectome: There was an incompatible recipe, should be fixed.

**Comment by jdcourcol** [comment]
I will fallback to the original workflow in a notebook.
