### ISSUE TITLE
Documentation update for splitting notebooks

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#119]
For the use cases regarding "Synaptic events fitting" (normal, user data, user model) it looks like you have splitted the notebooks in two parts: starting the computation and analyzing the results. 

That should be mentioned somehow on the guidebook https://collab.humanbrainproject.eu/#/collab/1655/nav/18580 etc.

**Comment by clupascu** [comment]
Thanks to @lbologna I changed the guidebook. Could you please check? Thanks.

**Comment by alex4200** [comment]
@clupascu, @lbologna : Thanks for the update, but I have several feedback points on the changes:

1. I suggest to write "... two Jupyter Notebooks are cloned in a private existing/new Collab" instead of "... 2 Jupyter Notebooks are cloned in a private existing/new collab"
2. You describe the first notebook on the documentation page, and a link leads to the description of the second notebook. What speaks against including the description of the second notebook on this page as well? Maybe you can use some headings to make the separation more clear
3. I suggest to take out the entire 'Warnings' section, as this is very technical and should not be part of this general user description. 


Thanks

**Comment by clupascu** [comment]
We fixed as suggested. Could you please check? Thanks.
