### ISSUE TITLE
Use Case Name of "Synaptic events fitting"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#12]
### Expected behavior

When added to the Collab, the name should be the same

### Actual Behavior

When added to a Collab, it shows up as "Fitting GUI" and not as "Synaptic events fitting"

### Steps to reproduce the problem

Just add the use case to a new/old Collab

**Comment by clupascu** [comment]
I fixed this. Can you please test again?

**Comment by alex4200** [comment]
Retest ok
