### ISSUE TITLE
Optimization of CA3 cells (rat)

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#120]
The task is to have a new model (for the CA3 region for rat), for which electrophysiological data are required (from external sources).

Similar tasks: #91 #92

**Comment by mmigliore** [comment]
Still unavailable. Will not be available during SGA1.
Please move it to SGA2

**Comment by mmigliore** [comment]
electrophysiological traces not available to date.

**Comment by mmigliore** [comment]
traces not available

**Comment by mmigliore** [comment]
traces still not available

**Comment by alex4200** [comment]
This item will not be completed.
