### ISSUE TITLE
Trailing zero omitted in Synaptic Events Fitting

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#122]
### Expected behavior

When I enter a value of '-60' for the VCLAMP AMP value, I expect to see it in the results file

### Actual Behavior

I enter '-60', but I see a value of '-6'.

### Steps to reproduce the problem

- Start a new 'Synaptiv events fitting with user data'
- For the exp file select 'exp5.txt'
- Insert the values 82, -60 and 0 on the second tab.
- Save the values in the third tab
- Without changing anything else log in to NSG, use the demo usecase and start the simulation
- The check the results after the simulation has completed

![screen shot 2018-01-10 at 15 29 10](https://user-images.githubusercontent.com/12729291/34779838-9d993362-f621-11e7-8560-cf2b1035d34f.png)

### Optional infrastructural data (user, platform, browser, environment, ...)

Collab 'Test143'

**Comment by clupascu** [comment]
I cannot reproduce this. I inserted -60 in the second tab and I get -60 in the config file. I used Firefox on a Mac machine.

**Comment by alex4200** [comment]
Hm strange, I will check it again in more detail...

**Comment by alex4200** [comment]
Cannot be reproduced
