### ISSUE TITLE
"Invalid date" on Simulation List

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#124]
### Expected behavior

To see no error or some error with more details

### Actual Behavior

All jobs are marked with "Invalid date" and I have no idea what this means

### Steps to reproduce the problem

Not sure

![screen shot 2018-01-10 at 16 30 58](https://user-images.githubusercontent.com/12729291/34781563-739284ce-f626-11e7-86a3-40821b0108df.png)

**Comment by antonelepfl** [comment]
This one is a strange error. I usually get that when it is loading the information but after it is loaded it is replaced. I would like to see this one.
