### ISSUE TITLE
Unable to find Analysis results

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#125]
### Expected behavior

To see a page with analysis results, or have a link to get to the page to see the final analysis. 

### Actual Behavior

- On the Simulation List I see a link to 'Analysis', but it opens just another popup to start a new analysis?
![screen shot 2018-01-10 at 16 23 07](https://user-images.githubusercontent.com/12729291/34781744-f1a890e2-f626-11e7-9c33-4d8a6fd260c7.png)

- When clicking on the details for the job, there are no analysis results:
![screen shot 2018-01-10 at 16 52 32](https://user-images.githubusercontent.com/12729291/34781772-ff6e6ddc-f626-11e7-94af-7c2dc8e9d3b2.png)

### Steps to reproduce the problem

- Start a simulation
- Start the analysis

**Comment by antonelepfl** [comment]
So the analysis should be shown in the Detail view of the simulation.
In this case you don't get any analysis result due you run the analysis on a simulation that did not produce any output file (even though it finished Successfully), in consequence analysis is empty.

**Comment by alex4200** [comment]
Issue solved by displaying an indicator in case no results are generated.
