### ISSUE TITLE
Running Analysis step unclear

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#126]
After the simulation has completed, I start the Analysis step and see the following popup:

![screen shot 2018-01-10 at 16 23 07](https://user-images.githubusercontent.com/12729291/34781837-34ced1ce-f627-11e7-9e73-f6442f9f5708.png)

- What does psth and raster mean
- What does the Cells percentage mean?
- How important is the Nodes number to run the analysis?
- The explanation text below contains errors.

**Comment by antonelepfl** [comment]
@romani79 How PSTH and Raster plots should be explained ?

**Comment by alex4200** [comment]
Number of cells
1 Node as default

**Comment by antonelepfl** [comment]
@alex4200 Could you please check this and let me know any issue / suggestion?
