### ISSUE TITLE
Running the simulations should require at least one stimulus and one report

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#127]
### Expected behavior

A check before I start the simulation to verify at least one stimulation and one report is defined. Running a simulation without either does not make much sense. 

### Actual Behavior

Simulation can only be started if at least one stimulus and one report is defined.

**Comment by antonelepfl** [comment]
@alex4200 Could you test it in the dev env? https://bbp.epfl.ch/public/dev.simulationapp/index.html#/

**Comment by alex4200** [comment]
Seems to work - but shouldn't it be named 'Oops'?
