### ISSUE TITLE
Enable simulation for every selectable computer

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#129]
Slice
 - [x] JULIA
 - [x] JURECA (booster partition)
 - [x] JUQUEEN
 - [ ] MARCONI (KNL partition)

FullCA1
 - [ ] JULIA
 - [ ] JURECA (booster partition)
 - [x] JUQUEEN
 - [ ] MARCONI (KNL partition)

**Comment by mmigliore** [comment]
We want all the following systems able to run a simulation: JUQUEEN, JULIA, JURECA (booster partition), MARCONI (KNL partition). It means that the software stack must be installed and sistematically updated on all of them. In SGA2, after the publicaiton of the paper on the circuit, we would like to add the Neuroscience Gateway system to the list.

**Comment by alex4200** [comment]
@antonelepfl: I seem to be unable to run a simulation on JULIA. I just start the default simulation (without changing anything) on JULIA. The submit seems to take forever:

![selection_232](https://user-images.githubusercontent.com/12729291/36382085-13739b24-1588-11e8-9b79-3ccdb703af95.png)

**Comment by antonelepfl** [comment]
Julia worked only with a small version of the user.target if we use the full one we don't have enough nodes/cpus to load the simulation

**Comment by mmigliore** [comment]
Yes, you can close it.

 

Da: Stefano Antonel <notifications@github.com> 
Inviato: 26 March, 2018 10:20 AM
A: cnr-ibf-pa/hbp-bsp-issues <hbp-bsp-issues@noreply.github.com>
Cc: mmigliore <michele.migliore@cnr.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [cnr-ibf-pa/hbp-bsp-issues] Enable simulation for every selectable computer (#129)

 

@mmigliore <https://github.com/mmigliore>  I think We can close this issue due the Slices work (with the old circuit in all computers) I don't have access to Marconi so I cannot launch it there.
For the FullCA1 The only computer that can do that is JUQUEEN right?
I have made some test and it is working now in JUQUEEN

**Comment by alex4200** [comment]
Closed then...
