### ISSUE TITLE
Configuring and running a hippocampus circuit simulation on Juqueen

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#13]
Acceptance criteria:
* the end user can select "target regions" to stimulate.
* the end user can configure the stimulus.(type of stimulus, parameter stimulus, duration, start time).
* the end user can select "target regions" to record from.
* the end user can configure how it records (variable name to record, duration, start_time )
* the end user can launch the simulation: he names the experiment, he defines the project he wants to use, the number of compute nodes.
* the end user can see the status of the simulation, and the current logs.
* the status should be completed once it is completed.

**Comment by antonelepfl** [comment]
This should be Juron now?
I tried this morning but I received an error like:

> app.bundle.js:753 Could not submit job: eu.unicore.security.AuthorisationException: There are no accessible targetsystem factories for: Name: CN=Stefano Antonel 302505,O=HBP
Xlogin: uid: [], gids: [addingOSgroups: true]
Role: anonymous: default role
Security tokens: User name: CN=Stefano Antonel 302505,O=HBP
Delegation to consignor status: true, core delegation status: false
Message signature status: UNCHECKED
Client's original IP: 128.178.97.34 Please check your security setup!

@jdcourcol I'm not sure if I have to contact Bernd to fix this. I have an account already in Juron under PCP0 project

**Comment by mmigliore** [comment]
Are you sure that it is Juron the machine you want to use?
The hippocampus is installed on Julia
Michele

antonelepfl <notifications@github.com> ha scritto:

**Comment by antonelepfl** [comment]
Ok so for the record: I asked Bernd (Juliech - unicore) about this issue and he has to map manually the user with new computers so he told me that so far each time that we apply for a new computer and we get this error we need to contact him. This is the 'normal' procedure so far.

**Comment by antonelepfl** [comment]
@jdcourcol So currently for the simulation we are sending a sh script with the following information 
``` bash
#!/bin/sh
date
hostname
whoami
source /homec/bp0/bp000022/modulecmd/3.2.10/init/bash
module use /homec/bp0/bp000022/modulesfiles
module purge
module load nix/hpc/neuron-hippocampus/7.5-201706
mkdir -p output
/homec/bp0/bp000024/simulation_launch_venv/bin/simulation_launch.py -vv --blueconfig BlueConfig --output output```

I tried to copy the file from /homec/bp0/bp000024/simulation_launch_venv/bin/simulation_launch.py but I don't have access to that folder. How can I proceed?

**Comment by antonelepfl** [comment]
For the records, the scripts that are running are:

**Julia**
`#!/bin/sh
unset LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/global/opt/slurm/default/lib64/
module purge
module use /gpfs/work/pcp0/pcp0085/x64/modulefiles
module load nix/hpc/neuron-hippocampus/7.5-201707
mkdir -p output
python /gpfs/homeb/pra098/pra09809/test/simulation_launch.py -vv --blueconfig blueconfig.json --usertarget /gpfs/homeb/pra098/pra09809/test/user.target.mod --output output`

> The configuration: 1 Node, 1 CPU, 86400 Timeout, Slice-4 Circuit Target

**Juqueen**
`source /homec/bp0/bp000022/modulecmd/3.2.10/init/bash
module use /homec/bp0/bp000022/modulesfiles
module purge
module load nix/hpc/neurodamus-hippocampus/1.9.0-201710/
mkdir -p output
python /homeb/pra098/pra09809/test/simulation_launch.py -vv --blueconfig blueconfig.json --usertarget /homeb/pra098/pra09809/test/user.target.mod --output output`
> The configuration: 1 Node, 8 CPU, 1800 Timeout, Slice-4 Circuit Target

**Comment by alex4200** [comment]
@antonelepfl What is the status for this issue?

**Comment by jdcourcol** [comment]
This is implemented with the limitation of a Full CA1 replay.
