### ISSUE TITLE
Poisson stimulus: Neuroscientific clearly defined stimulus?

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#130]
Is that stimulus clear for every neuroscientist who might be use this use case? 

Need to check with Armando

**Comment by alex4200** [comment]
@antonelepfl @romani79 
I think we decided to let it as it is now, with the possibility to add other stimuli in future...

**Comment by antonelepfl** [comment]
So I disable the option to select another type of stimulus so leaving Poisson as default and not changeable value. If we need to add new stimuli we will at that time
