### ISSUE TITLE
Naming of help text

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#131]
The text "The strength of the created synapse" might be wrong, as no synapsed are created, but electrical signals. 

Need to clarify with Armando.

**Comment by antonelepfl** [comment]
@lbologna I would need if you can add romani79 (Armando) as a contributor so I can ask him about these issues.

**Comment by lbologna** [comment]
Ok.
I just invited Armando.

**Comment by alex4200** [comment]
@antonelepfl 
Suggestion for the text 'weight': "The strengths of the added synapses"
Suggestion for the text 'Number of synapses': "Number of synapses to add per neuron"

And I suggest to change the order of these two boxes. First you define how many synapses to add, then you set their strength...
