### ISSUE TITLE
"View Simulation" page very unclear

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#133]
### Actual Behavior

Current situation:
- You have to select the computer on which you run the simulation or analysis
- Looking at the Details page for an _Analysis_ job does not show you the results of the analysis. You have to select the actual 'Simulation' job ... I find that very confusing
- An Analysis step is listed under "Simulation step". Very confusing

### Suggested behavior

- On the top of the page remove the selection according to the used computer. Just keep the job-name-filter and the selection for a given status.
- Clearly list the status for the two steps in their correct columns. (If required, add the computer, that was used to perform that step, to the status in small font). 
- Have only ONE link to the Details page, with Analysis results (if available) and the information about the used computer system.

**Comment by alex4200** [comment]
I suggest to revisit this next week...

**Comment by antonelepfl** [comment]
@alex4200 Could you please check this and let me know any issue / suggestion?
