### ISSUE TITLE
Project/User should be selectable to run job

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#139]
### Expected behavior
You can pass the userid or project that you want the job to be run on.
The problem is that for Julich infrastructure this is not possible. 

If you go to https://collab.humanbrainproject.eu/#/collab/3656/nav/29207 you will only see one userid by project.

**Comment by mmigliore** [comment]
I have discussed this possibility with Bernd. I will raise the point again in the next tech. coordination meeting on wed.

**Comment by mmigliore** [comment]
please move it to SGA2

**Comment by antonelepfl** [comment]
Now you have a selector for Run Simulation and for the Analysis
![screen shot 2018-03-26 at 10 15 28](https://user-images.githubusercontent.com/24406041/37894544-d878ad12-30de-11e8-9633-0416bde87e4e.png)

**Comment by alex4200** [comment]
Done
