### ISSUE TITLE
Analyzing a simulation of an hippocampus circuit on Jureca

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#14]
Acceptance Criteria:
* The end user configures the analysis (plurals) he wants to run:
-  that can be a percentage of cells to visualize in the analysis
* The end user names the analysis job, define the project he wants to use, the number of nodes, if possible pre-filled based on the simulation configuration.
* Once started, he can see the status in the graphical user interface and access logs
* Once finished, he can see the plots for these analysis in relation with the simulation.

**Comment by antonelepfl** [comment]
So for now I'm just creating a config.json file with the % of cells and the types of analysis in the job directory in Jureca.
We would need to modify the file so it can read it and generate the corresponding analysis.

**Comment by alex4200** [comment]
@antonelepfl What is the status for this issue?

**Comment by antonelepfl** [comment]
I add the file but the analysis is not picking up this file and configuring the analysis so, we have to modify the script.

**Comment by jdcourcol** [comment]
This is done.
