### ISSUE TITLE
Replacement of Fast Spiking use case

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#140]
- Update notebook on collab with new version. 
- System description. Scientific work.  Who is intended user? 
- Brain simulation -> guidebook: Top level description what can be done
- Technical details in notebook

**Comment by alex4200** [comment]
Should be expected by 26 Jan (Alexander Kozlov)

**Comment by a1eko** [comment]
The optimized cell and optimization notebook are uploaded to private HBP Collab 
https://collab.humanbrainproject.eu/#/collab/7840/nav/59620
The notebook is self-documented and runs a small demo example.

**Comment by a1eko** [comment]
I rewrote the notebook so that it should be possible to run an optimization demo example with any cell uploaded to the Collab's Storage directory Optimizations.
If this works, it would make sense then to merge three suggested use cases, D1 MSN, D2 MSN, FS, to one _Optimization of single cell_ for striatal models, I think.

**Comment by antonelepfl** [comment]
Hi @a1eko as we said in the last Monday meeting to use only a notebook with different models you just need to send me the information about the models and put a placeholder in your notebook so I can replace it with the name of the model.
We are doing the same thing for the [morphology](https://collab.humanbrainproject.eu/#/collab/1655/nav/20841) there you have the usecase, then the models and last the notebook is copy using the model that you selected.
I would need the information as you see in the models section.
Are you able to get the models based on the name?

**Comment by alex4200** [comment]
@antonelepfl will put usecase on BSP after @a1eko sends the link to public collab.

**Comment by a1eko** [comment]
I have uploaded an example optimisation of striatal fast-spiking cell to our public collab SP6 - Basal Ganglia
https://collab.humanbrainproject.eu/#/collab/376/nav/63146

**Comment by alex4200** [comment]
Use cases in the brain simulation platform available.
