### ISSUE TITLE
Implementing of usecase MSD2

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#142]
- Update notebook on collab with new version. 
- System description. Scientific work.  Who is intended user? 
- Brain simulation -> guidebook: Top level description what can be done
- Technical details in notebook

**Comment by Hjorthmedh** [comment]
This should be merged with #140?

**Comment by alex4200** [comment]
Merged with #140 as its the same use case, only different model/
