### ISSUE TITLE
Results table is missing a column name

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#143]
### Expected behavior

First column to be named (e.g. with the hash sign '#' to indicate this is just a running number). 

OR take out that column altogether, as it does not seem to be very important...

### Actual Behavior

First column not names

### Steps to reproduce the problem

See the results table in the Analysis notebook

![selection_156](https://user-images.githubusercontent.com/12729291/35152871-78661984-fd24-11e7-8a40-fbde2bbc25e2.png)

**Comment by clupascu** [comment]
I hided the index functionality in the pandas dataframe. Please test again. Thanks.

**Comment by alex4200** [comment]
Thanks seems to work. Looks better to me now...
