### ISSUE TITLE
Some remarks to the best fit plot

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#144]
- Axis labels would be useful (time, voltage, units, ...)

![selection_157](https://user-images.githubusercontent.com/12729291/35154157-647de276-fd29-11e7-8663-2e8f559fd928.png)

- Not sure how this related to the actual data in the exp file. Plotting column number 34 of the exp file I find something like the following: 

![test](https://user-images.githubusercontent.com/12729291/35154177-801d98f0-fd29-11e7-999f-e5ebaf9c43cf.png)

Maybe I took the wrong trace, but neither number 33 or 35 look like the one of the best fit...

**Comment by clupascu** [comment]
I added axis labels. How do you plot column number 34? Is this a fitted trace? Thanks.

**Comment by alex4200** [comment]
@clupascu : Maybe I do not quite understand what the 'original' line is. I had the impression that this is one of the timeseries given in the 'exp5.txt' file I select at the start of the usecase. 

If that is not the case, where does the 'original' timeseries data come from?

**Comment by clupascu** [comment]
The 'original' line is actually one of the timeseries given in the 'exp5.txt', that was clipped to avoid
overlapping synaptic activations that could significantly distort the time course of an individual event.

**Comment by alex4200** [comment]
@clupascu : Yes, I verified its a part of one of the original traces, shifted in time and in voltage:

![test_0122](https://user-images.githubusercontent.com/12729291/35223644-6b724954-ff82-11e7-8856-09706b27ec4a.png)

I have two question/issues: 

1. As the y-axis offset has been shifted, the y-axis is just a relative scale anymore.  It starts at a value of zero, although this matches a value of something like -35 on the original trace. But as this is only comparing the data to the model, that is fine for me. No need  to change anything
2. You indicate the y axis as current in pA. I think this is incorrect, as the traces are voltages traces and the units are mV (milli Volt). That should be corrected. But please correct me if I am wrong...


Thanks

**Comment by clupascu** [comment]
The traces are spontaneous inhibitory synaptic currents and the units are in pA.

**Comment by alex4200** [comment]
Ok, then I am wrong. Case close. Thanks
