### ISSUE TITLE
In downloadable voltage trace file: name of first column is missing

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#145]
### Expected behavior

The resulting CSV file contains a name for each column.

### Actual Behavior

The CSV file looks like follows: 

,time,soma[0]_0
0,0,-70
1,0.0023549001815310906,-70.01562582599722
2,0.005973178181114874,-70.03586071331355
3,0.012322667473723016,-70.06583368680117
...

Should instead contain something like:

index,time,soma[0]_0

### Steps to reproduce the problem

Just run any case

**Comment by genric** [comment]
Should be fixed now, please retest. Thanks.

**Comment by alex4200** [comment]
Yes fixed, thanks
