### ISSUE TITLE
Mouseover text incorrect

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#147]
### Expected behavior

When the mouse is hold over an error indicator the text should read:

The holding current must be ...

### Actual Behavior

The text reads:

Hypamp must be ...

### Steps to reproduce the problem

Type a large number into the 'holding current' box

**Comment by genric** [comment]
Should be fixed now, please retest. Thanks.

**Comment by alex4200** [comment]
Yes fixed, thanks
