### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#148]
User Documentation need to be added to the Guidebook https://collab.humanbrainproject.eu/#/collab/1655/nav/18580

**Comment by antonelepfl** [comment]
@alex4200 I have created a PR (pull request) https://github.com/lbologna/hbp-sp6-guidebook/pull/15

**Comment by antonelepfl** [comment]
@lbologna Could you please check it out and merge it if is ok for you?

**Comment by lbologna** [comment]
Done.

**Comment by antonelepfl** [comment]
Thank you
