### ISSUE TITLE
"Cell Optimization" Job submission status unclear

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#149]
Reading the user documentation on the "Cell optimization" in the guidebook (https://collab.humanbrainproject.eu/#/collab/1655/nav/18580) its not clear to me how and where to see the status of the submitted job. 

Suggestion: Add a sentence to the end of the "Cell optimization" documentation to let users know they can check the status of the submitted job in the next step ("Single Cell Simulation Run") ...

**Comment by lbologna** [comment]
This should be fixed. Could you please check again? Thanks

**Comment by alex4200** [comment]
Yes, ok
