### ISSUE TITLE
"Cell Optimization" Job ID inconsistent

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#150]
When starting a job in the "Cell Optimization" step of the use case the user can see a 'Workflow id'. But when fetching the results, its a different ID. So the user cannot see which is which. 

Also the times listed in the Fetched list seems to be Pacific time, which makes it even more hard to figure out what the status of a job is.

The fetching results also seem to show other results?

Tested with NSG

**Comment by alex4200** [comment]
@lbologna Any update on this issue?

**Comment by lbologna** [comment]
Now, both the id of the workflow from which the job was launched and the job id are given (note that jobs launched so far have no correspondence to workflow id because the association was not implemented).
Could you please check again?
Thanks

**Comment by alex4200** [comment]
Thanks, seems to work fine
