### ISSUE TITLE
Incorrect error shown when continuing saved workflow

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#151]
### Expected behavior

Error: "Optimization parameters NOT set" not shown as the optimization has already been submitted before. 

### Actual Behavior

Error shown:

![selection_161](https://user-images.githubusercontent.com/12729291/35209591-16d3c1b2-ff4f-11e7-9945-1961e8263c92.png)

### Steps to reproduce the problem

- Select Collab 'Test157'
- Select "Ongoing workflow"
- Choose the download of the single workflow

**Comment by lbologna** [comment]
This should be fixed. Could you test again please? Thanks
