### ISSUE TITLE
Unable to Run Simulation

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#152]
### Expected behavior

Able to load a model to NaaS

### Actual Behavior

Error: Model load error

![selection_163](https://user-images.githubusercontent.com/12729291/35210103-24ea28ca-ff51-11e7-8d8e-e4a7a86a29c4.png)

### Steps to reproduce the problem

- Select use case and Collab 'Test158'
- Select "Ongoing workflow"
- Choose the download of the single workflow of the storage
- "Fetch results" and download the following result:

![selection_162](https://user-images.githubusercontent.com/12729291/35210147-4a6aa002-ff51-11e7-82be-47e813ebd905.png)
- Click on "Run Simulation"

**Comment by lbologna** [comment]
Hello,

The error shown might depend on the folder structure contained in the .zip file the user is trying to upload (or the system is generating after fetching the results from hpc systems (nsg)).

I added the same screenshot as Naas to explain the user the structure the zip file must have and implemented different error messages visualization depending on the missing parts (please click on "Single Cell Simulation Run" -> "Upload file" to check).

If the folder structure is not correct, the zip is not uploaded anymore, while if the needed files and folders are present, the zip file is passed to the Naas.


Nonetheless, I believe the error ("Model loading failed") might still occur if the content of the uploaded file is wrong. @genric could you confirm this please?

In this case, I think the reason why the model is not loaded should be displayed in the Naas window, given that the Naas is using/opening the files, while the HHNB is taking care of the packaging but not the simulation itself.

@genric @alex4200 would you agree with this?

Thanks.

**Comment by alex4200** [comment]
@lbologna : Yes I agree with that. Its not the absolute perfect solution, but I expect having an issue with a wrong model only in very rare cases...

Should I close this ticket then?

**Comment by lbologna** [comment]
Yes, please.

Thanks
