### ISSUE TITLE
Unable to save the workflow

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#153]
### Expected behavior

Able to save the workflow at any point

### Actual Behavior

Workflow does not save at some point. Even after 20 minutes I still this:

![selection_164](https://user-images.githubusercontent.com/12729291/35211246-fae416b2-ff55-11e7-8942-5c46b4c61b31.png)

### Steps to reproduce the problem

- Select use case and Collab 'Test158'
- Select "Ongoing workflow"
- Choose the download of the single workflow of the storage
- "Fetch results" and download the following result:
- Click on 'Save'.

**Comment by lbologna** [comment]
Hello. This looks more like a server error than an error occurring when saving the workflow to the storage.
In the latter case, in fact, the displayed message should be the following:

<img width="823" alt="screen shot 2018-02-04 at 13 05 42" src="https://user-images.githubusercontent.com/9949990/35777313-2786c54c-09ac-11e8-93f4-859918d8b480.png">

If this is the case, can we close this issue and add a comment to issue #42 about checking also why the fetching&analysing is breaking the pipeline?

Thanks

**Comment by alex4200** [comment]
@lbologna : Yes sure. Add a link to this issue then...

**Comment by lbologna** [comment]
Please refer to issue #42 

Closing.
