### ISSUE TITLE
Raster plot in analysis does not show Y axe

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#155]
### Expected behavior
The Raster plot should show the Y axe.
### Steps to reproduce the problem
Run an analysis and after it finished in the simulation details you should see that there is no Y axe in the raster plot
### Optional infrastructural data (user, platform, browser, environment, ...)
JURECA

The script for the analysis is under:
```/homec/bp0/bp000024/jureca/venv_bluepy_analysis/bin/analysis_launch.py```

**Comment by alex4200** [comment]
@antonelepfl Is this still an open issue?

If so I would appreciate if you can adjust the milestone to the new M milestones.

Thanks a lot

**Comment by antonelepfl** [comment]
I think the issue here is that there is no GID definition for each row of the plot.

**Comment by alex4200** [comment]
Hi @mgeplf, can you please check this ticket as it is assigned to you? Is there any update?

**Comment by alex4200** [comment]
Can be closed.
