### ISSUE TITLE
StriatumScaffoldModel usecase (Unicore)

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#157]
Network export to SONATA format for running on collab

**Comment by Hjorthmedh** [comment]
Updated the in-line documentation in the code, to better explain the use case:

https://collab.humanbrainproject.eu/#/collab/7598/nav/57859

**Comment by alex4200** [comment]
@Hjorthmedh Very nice!

**Comment by Hjorthmedh** [comment]
Going to try and see if I can get it to run on Unicore also.

**Comment by alex4200** [comment]
@Hjorthmedh : Aplied for an  account

**Comment by alex4200** [comment]
@Hjorthmedh Can you please give a short update here?

**Comment by Hjorthmedh** [comment]
I now have access to Unicore. Able to submit jobs. In the process of updating the environment so my code can run on the machine.

**Comment by alex4200** [comment]
Update from Johannes 9.3.: 

> I messaged the Julia support team back on Tuesday to ask for updates on the installation of all the required packages, but have not received any update yet.

**Comment by Hjorthmedh** [comment]
The microcircuitry code can now launch but it hangs when querying the engines. Debugging.

**Comment by Hjorthmedh** [comment]
The microcuitry generation code now runs through sbatch on Julia. Working on triggering it through unicore interface.
Then running network in neuron next step.

**Comment by Hjorthmedh** [comment]
The network creation now works in parallel on unicore. The circuit analysis after is done in serial.

This is just the building of the network not the running.

**Comment by alex4200** [comment]
@Hjorthmedh That is great news! Let me know when you have a test-worthy version available...

**Comment by Hjorthmedh** [comment]
Input generated for simulation. Testing neuron run on Julia.

**Comment by Hjorthmedh** [comment]
Single core usecase is up on the platform accessible from user interface. Alex is testing.

Have applied for Jureca account also since reviewers will use that and not Julia.

**Comment by antonelepfl** [comment]
Working on Sonata conversion.
No Unicore so far

**Comment by Hjorthmedh** [comment]
We now have a set of SONATA files and we need help to run it on the platform. It would be good to have a person we can continuously talk to for a few weeks as we debug and get it operational. 

This is a blocking issue.

**Comment by Hjorthmedh** [comment]
From a bash shell on julia, how do I run my SONATA files?
Do I need to initialise the environment in any way?
If I want to run it locally, how do I setup Neurodamus on my own machine?

**Comment by alex4200** [comment]
@arsenius7  Do you have any input here?

**Comment by jdcourcol** [comment]
@Hjorthmedh : the simulator is not ready for supporting SONATA natively yet. The plan is to deliver that in SGA2.
We are building our implementation plans currently so I cannot give you a timeline right now.
However, you can consider to test the visualization of your circuit with RTNeuron. This would already validate that your files are readable and  give some insights related to the structure of your network.

**Comment by Hjorthmedh** [comment]
@jdcourcol I thought the SONATA to Neurodamus converter was up and running. 

Or do you mean that the converter works, but that Neurodamus will at some point natively read the SONATA file format?

In the meantime, where can I find information about how to run the RTNeuron visualiser?

**Comment by Hjorthmedh** [comment]
Do you think we will have the Neurodamus SONATA format done before the end of the year?

**Comment by arsenius7** [comment]
Unlikely.

As Neurodamus is a central piece of our scientific S/W stack with many scenarios supported, full migration to SONATA can get quite tricky (and might call for some enhancements of the format itself).

However, we'll strive for a smooth transition, to support _at least subset_ of SONATA as early as possible (still a matter of weeks rather than days).
If you prefer not to wait for the full support, we can discuss how to fit your use case into this "transition roadmap".

**Comment by Hjorthmedh** [comment]
I got help from Kael Dai at the Code Jam in Palermo. We are currently updating my export tool to the latest version of the SONATA format. Then as soon as that is done and it passes their validation script we will try to run it using the Allen Institute simulator.

Once there is SONATA support from Neurodamus, as long as it is compatible with the Allen Institute SONATA format, our simulations should be able to run in Neurodamus also.

**Comment by alex4200** [comment]
Replaced by ticket #378
