### ISSUE TITLE
Change default title of the jobs if the field is empty.

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#159]
### Expected behavior
The default name of the job should be `unnamed job `
### Actual Behavior
The default name of the job is `Bash Shell`
### Steps to reproduce the problem
Run a simulation without adding any value in the title

**Comment by antonelepfl** [comment]
@alex4200 Do you agree with the new name? Suggestions?

**Comment by alex4200** [comment]
@antonelepfl What about 'unnamed job' (without quotes). Will avoid issues with the brackets, and maybe even more clear...
