### ISSUE TITLE
Login to NSG is unclear in the use case "rebuild an  existing single hippocampal cell model"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#16]
### Expected behavior

When clicking "Login NSG" on this use case there should be some indication whether the login succeeded or not. 

### Actual Behavior

Click on "Login NSG" does not provide any feedback

### Steps to reproduce the problem

Follow the notebook until step 9

**Comment by clupascu** [comment]
I added a pop-up window with an authentication message. It is just a message. If you provide wrong credentials, it does not prevent to click on Run NSG anyway.

**Comment by alex4200** [comment]
@clupascu: I think this simple text feedback makes the login much more transparent and useable...
