### ISSUE TITLE
New Category field in Use Cases statistics

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#161]
### Expected behavior
A new field should be added in the statistic that shows the category of the use case like `traceanalysis`, `singlecellmodeling`, etc.

### Optional infrastructural data (user, platform, browser, environment, ...)
https://docs.google.com/forms/d/1mm1_c5diTOh7uswl1BCk5YbxwaP0wMDvA0KaClcEVW8/edit

**Comment by antonelepfl** [comment]
@lbologna I already merged this change.

**Comment by lbologna** [comment]
Thanks Stefano.
