### ISSUE TITLE
Boxplot result details

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#163]
Suggestion: 

- Add a sentence in the guidebook about what the boxplot results show. 

![selection_165](https://user-images.githubusercontent.com/12729291/35220460-c5581662-ff76-11e7-98e2-45fe363c71f5.png)

- And even better add something to the plot itself (e.g. like the examples in here: https://plot.ly/python/box-plots/)
- Display only 3 significant figures ( like  0.0351 instead of 0.035172634763)
- Add a sentence in the guidebook regarding the possibilities to export it to plot.ly and that you can do more stuff on it there...

**Comment by clupascu** [comment]
I am working on this too, on displaying only 3 significant figures. What example here  https://plot.ly/python/box-plots/ you were referring to?

**Comment by alex4200** [comment]
@clupascu just hover with the mouse over the first plot (in section "Basic Box Plot") and you see that the pop-up numbers will not just be numbers but something like

`max: 4.02...`

**Comment by clupascu** [comment]
Unfortunately, as it can be seen here https://community.plot.ly/t/hover-on-boxplot-median-q1-q3-are-not-display-in-python-plotly/6870 "The boxplots in the documentation were posted long time ago. In the newer Plotly versions the strings q1, median, q3, are not displayed anymore." I only simplified the boxplot and the best fit by displaying only 2 significant figures. I will add a sentence in the guidebook about what the boxplot results show and a sentence regarding the possibilities to export it to plot.ly and that you can do more stuff on it there.

**Comment by alex4200** [comment]
Good enough, thanks.
