### ISSUE TITLE
Voxcellview should display multiple plots in one container

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#165]
### Expected behavior
Voxcellview should overlap different plots in one container
### Actual Behavior
Each time that we call voxcellview it creates a new container with information

**Comment by alex4200** [comment]
@antonelepfl : Any update on this issue?

**Comment by antonelepfl** [comment]
No time for that. Sorry

**Comment by alex4200** [comment]
@antonelepfl Is this still an open issue?

If so I would appreciate if you can adjust the milestone to the new M milestones. (M6, M12, ...)

Thanks a lot

**Comment by antonelepfl** [comment]
Hi Alex, I don't think we are going to implement that any time soon due we want to avoid using voxcellview as a visualization tool becasue we have Pair Recording, BlueNaas etc as tools
