### ISSUE TITLE
Able to click on "Run NSG Simulation" repeatedly

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#166]
### Expected behavior

I can click on this button only once. When I have clicked on it I expect to see it greyed out or so

### Actual Behavior

Can click on it multiple times, not sure what it is doing in that case.

![screen shot 2018-01-26 at 10 38 18](https://user-images.githubusercontent.com/12729291/35433955-9dfd6b3c-0285-11e8-94a2-1dc4ff9b6948.png)

### Steps to reproduce the problem

Just follow the main use case workflow

**Comment by clupascu** [comment]
I fixed this. Can you test again please? Thanks.

**Comment by alex4200** [comment]
Yes fixed...
