### ISSUE TITLE
Model Selection: Shows 'No results' although model(s) are available

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#169]
### Expected behavior

When a model could be found, there should be no text 'No results'.

### Actual Behavior

A model is being found, and the user gets the message 'No results'

![selection_174](https://user-images.githubusercontent.com/12729291/35512661-d33739e0-0500-11e8-92d0-a2feb1833211.png)

### Steps to reproduce the problem

- Select e.g. the Morphology Visualization use case
- enter: "bAC 01101"

### Optional infrastructural data (user, platform, browser, environment, ...)

FF and Chrome

**Comment by antonelepfl** [comment]
@alex4200 I have also remove the `No results` from the list
