### ISSUE TITLE
Short documentation for Single Cell use cases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#17]
Each notebook use case should have a brief documentation header to remind people on how to run this particular use case (Either to do "Run All", or run step by step etc), including a link to the relevant section of the Guidebook.

**Comment by alex4200** [comment]
@clupascu: Suggestion for your notebooks: Because they need to be "Run All" at the beginning, I suggest to insert a cell at the very top with the following Markdown, to make it clear the user has to 'run all' first, and why. This affects three use cases in "Trace Analysis" and two in "Single Cell Building"...

## Important note

Before executing this use case, please run all cells of this notebook (Selection *Run All* in the menu *Cell*). This will create a simple user interface for easier user interaction.

**Comment by clupascu** [comment]
I inserted a markdown in the top-level notebook cell of all my usecases. Please let me know if the text is clear. Thanks.
