### ISSUE TITLE
Exporting files for Neurodamus

### ISSUE THREAD

**Issue by Hjorthmedh** [cnr-ibf-pa/hbp-bsp-issues#170]
### Missing information

- What file format should be used for the input spikes?

- When specifying synapse location, how can SEC_ID and SEC_X be derived from the morphology in the swc file? What is the algorithm that does the numbering of the sections? I have the coordinates of the synapses.

**Comment by Hjorthmedh** [comment]
Just to confirm, SEC_ID is the ID:s for a compartment assigned in the SWC file?

**Comment by Hjorthmedh** [comment]
Also received info from JD regarding input format:

> 1) spike format:
> the spike will be a single HDF5 sorted by gids
> 
> * data (dtype: float, shape: number_of_spikes)
> 
> * index_pointer(d:type: int, shape: number_of_gid + 1)
> 
> so you retrieve the spikes for a gid with:
> 
> data[index_pointer[gid]: index_pointer[gid+1].
> 
> However, my current implementation does not support this format yet. It supports a csv file with 2 columns, one for spike time and the other one for the gids.
>

**Comment by alex4200** [comment]
@Hjorthmedh : Any news on this issue?

**Comment by Hjorthmedh** [comment]
Have worked on converting synapse coordinates to section ID and section X used by Neurodamus. Most recently wrote a plot tool to visually inspect the conversion. 

This week and probably a while longer will be working on synaptic input, more specifically how to best create it and determine input locations.

**Comment by Hjorthmedh** [comment]
Code for generating input written. Next step exporting it.

**Comment by jdcourcol** [comment]
File format GitHub is here:
https://github.com/AllenInstitute/sonata

**Comment by Hjorthmedh** [comment]
Would it be ok to use a csv file for input spikes. What is the neurodamus internal file format? 
Is it:
neuroninputlocA, time1, time2, ...
neuroninputlocB, time1, time2, ...
Etc

**Comment by Hjorthmedh** [comment]
Emailed King & friends asking about Neurodamus file input format.

**Comment by Hjorthmedh** [comment]
Sent one more reminder asking about file format for input spikes.

**Comment by alex4200** [comment]
@Hjorthmedh Just to clarify: This ticket is about the SONATA file format which you are trying to use in ticket #157 ?

**Comment by jdcourcol** [comment]
@Hjorthmedh I think this should go to the sonata issues. https://github.com/AllenInstitute/sonata/issues

**Comment by jdcourcol** [comment]
@Hjorthmedh the spike file format is documented here:
https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md#spike-file

**Comment by Hjorthmedh** [comment]
The issue is that I want to verify and run the SONATA simulation through Neurodamus. I have already a first version of the SONATA files created.

That Allen Brain Institute tracker you linked to is more about the SONATA format, and not Neurodamus' ability to read the format?
