### ISSUE TITLE
Naming of the analysis results

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#171]
When creating an analysis, the naming of the results is imprecise and maybe incomplete:

 - psth
 - raster

Better names possible?

![selection_176](https://user-images.githubusercontent.com/12729291/35667922-addaadcc-072f-11e8-8822-60280e3660e2.png)

**Comment by jdcourcol** [comment]
raster: Spike Raster Plot
PSTH: Peristimulus Time Histogram

**Comment by antonelepfl** [comment]
@alex4200 I did a review for this item.
I also added `Voltage Traces Plot` that Armando wanted to have.
Remember that this last plot is not produced yet.
