### ISSUE TITLE
Python error " No module named document_service.service_locator"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#172]
When running all cells of the use case, I get the following error in the fourth cell:

```
ImportErrorTraceback (most recent call last)
<ipython-input-4-867be06c8a53> in <module>()
----> 1 from hbp_service_client.document_service.service_locator import ServiceLocator
      2 from hbp_service_client.document_service.client import Client
      3 from hbp_service_client.document_service.requestor import DocNotFoundException, DocException
      4 
      5 import requests

ImportError: No module named document_service.service_locator
```

**Comment by clupascu** [comment]
I don't get this error. It is a repeated error?

**Comment by alex4200** [comment]
@clupascu What is the version of the hbp_service_client? Its 1.1.0 for me.

**Comment by clupascu** [comment]
It's 0.0.3 for me.

**Comment by appukuttan-shailesh** [comment]
The `hbp-service-client` package seems to have changed quite a bit between 0.0.3 to 1.1.0:

> The module `hbp_service_client.document_service` was renamed to `hbp_service_client.storage_service`

For other changes, see here:
https://github.com/HumanBrainProject/hbp-service-client/blob/master/CHANGELOG.md

**Comment by alex4200** [comment]
@clupascu Cannot reproduce this error. But you should really update to version 1.0.0 or 1.1.0 of the hbp-service-client ...

**Comment by alex4200** [comment]
This issue still persists. Its an error I get in the 'Analysis' Notebook...

**Comment by clupascu** [comment]
I will try to take a look at what @appukuttan-shailesh suggested. Thanks @appukuttan-shailesh.

**Comment by clupascu** [comment]
It should be fixed. Can you test again everything please? Thanks.

**Comment by alex4200** [comment]
@clupascu: Now I get the following error (cell 6 in the Rebuild Single HippoCell use case):

```

AttributeErrorTraceback (most recent call last)
<ipython-input-6-ebca06528aef> in <module>()
      5     listfilenames.append(filename)
      6 if 'Work-in-progress3.png' not in listfilenames:
----> 7     storage.download_file(os.path.join(os.path.sep,'BSP', 'OnlineUseCases', 'TraceAnalysis','FittingGUI','Work-in-progress3.png'), 'Work-in-progress3.png')
      8 foldernameOPTstring = model_url

<ipython-input-4-0056f2ebcb7e> in download_file(self, path, target_path)
     77 
     78     def download_file(self, path, target_path):
---> 79         entity = self.client.get_entity_by_query(path=path)
     80         assert entity['entity_type'] == 'file'
     81 

AttributeError: 'Client' object has no attribute 'get_entity_by_query'
```

**Comment by alex4200** [comment]
Created new issue #179
