### ISSUE TITLE
Calcium transient should be a possible variable for the report

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#173]
Update use case

## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | Report calcium concentration
Expert | Andras Ecker, Chindemi Giuseppe
Deadline | Low importance
Dependencies |
 
**Remove anything that does not apply**
## List of additional/changed features 

The idea from Michele is to report on calcium concentration (cai variable, writtem by cacum.mod) mostly in the soma and selected dendrites.

### Tasks

- [ ] Local experimentation if this gives a meaningful insight and how much time and space is used.
- [ ] Do the actual implementation (if prev. step is ok)

**Comment by alex4200** [comment]
@jdcourcol @antonelepfl Is this still an open issue? 

If so I would appreciate if you can 

- add some more details
- Adjust the milestone to the new M milestones.

Thanks a lot

**Comment by antonelepfl** [comment]
We need to ask Michele for this. IIRC he was asking Jim about this in Neurodamus but I'm not 100% sure.
We have updated the Milestone yesterday

**Comment by alex4200** [comment]
@mmigliore Can you please comment on this issue? Thanks...

**Comment by markovg** [comment]
Calcium reporting is for plasticity simulations.  
Giuseppe @pineider should be able to clarify the neurodamus reporting for calcium in that context

**Comment by pineider** [comment]
We have to distinguish between synaptic calcium transients and (general) dendritic ones. The former can be recorded using the Synapse report, but you are required to replace the default synapse model with GluSynapse. The latter are accessible via Summation reports on the "ica" variable, provided that the compartment you are accessing has any mechanisms writing ica.

**Comment by mmigliore** [comment]
Yes. It is a good way to compare simulation and experimental data, especially with CA imaging in denrites during synaptic activity.

**Comment by alex4200** [comment]
@andrisecker This is the ticket we talked about.

**Comment by alex4200** [comment]
@andrisecker Do you have updates from the conversation with Michele on this ticket?

**Comment by andrisecker** [comment]
@alex4200 just got an answer from @mmigliore :
What he meant was reporting on calcium concentration (`cai` variable, writtem by `cacum.mod`) mostly in the soma and selected dendrites.
I think this should be straightforward from the engineering point of view, but let us try out first locally and see if it gives any meaningful insight and how much time and space does it take.

**Comment by alex4200** [comment]
@mmigliore/ @jdcourcol : @andrisecker is not able to work on this task anymore. Can you find another assigneee for that task?

**Comment by jdcourcol** [comment]
@alex4200 I think this "just" needs to have the GUI to let the end user to record the cai variable.
So I think it is up to @antonelepfl  to see if it is feasible.

**Comment by antonelepfl** [comment]
Let's suppose that I was able to run a simulation reporting on `cai` is there any way to check that this report is correct? How can I know that the calcium report is different from the voltage (normal) one?

**Comment by mmigliore** [comment]
If we want to compare with experimental data you should report the
intracellular Calcium concentration, not the current (which may be useful
for other things anyway). The corresponding range variable should be cai
but you need to check with Jim.
Just keep in mind that the resting cai value should be very small, around
50e-6 (mM), instead of the -75 (mV) value for the resting voltage, v.

**Comment by alex4200** [comment]
The items to be fixed:

 - [ ] Report name for analysis selection (so the user knows what the report is about)
 - [x] "Trace plot from Report"
 - [ ] Image title and units

**Comment by antonelepfl** [comment]
To keep it simple I have renamed **Voltage Trace** to **Trace plot from Report**
