### ISSUE TITLE
Saving workflow takes very long time

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#174]
### Expected behavior

Saving a workflow should take no longer than 30 seconds

### Actual Behavior

Even after 5 minutes I see the workflow saving screen

![selection_179](https://user-images.githubusercontent.com/12729291/35845935-c75eb93a-0b14-11e8-80f3-6099b4fdad52.png)

### Steps to reproduce the problem

Perform all steps of the use case, including the 'Run Simulation' step (NaaS). Then press the 'go back' arrow on the browser (google chrome), and click on 'Save'.

### Optional infrastructural data (user, platform, browser, environment, ...)

google chrome, Linux

**Comment by lbologna** [comment]
Hello,

this issue does not seem to happen anymore. 
Could you please check again?

Thanks

**Comment by alex4200** [comment]
Clarification on 'Completed' jobs needed.

**Comment by lbologna** [comment]
I added a link to NSG job status definition in the Guidebook and gave some explanation.
The saving seems to be still working.
Could you please check if this is fine?

Thank you.

**Comment by alex4200** [comment]
I think its working now
