### ISSUE TITLE
Add models selection for Basal ganglia optimization

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#176]
### Expected behavior

- Select the Optimization use case.
- Show a list of the models (so far only one).
- Change the parameter in the jupyter notebook so it loads the selected model.

This optimization is not published yet so the use case is **not** in the BSP.

Alez Kozlov sent the images, title and description for the model.

There are two parameter files in config/ -- parameters.json and parameters-demo.json. The first one is intended for full optimization on an HPC machine with offspring_size=400 and ngenerations=100. The second one parameters-demo.json is for a small example run which still gives sensible results (offspring 10, ngen 3).

If we choose the demo version, we should add perhaps a discalimer to the description:

"This version runs directly on the collaboratory and it is limited to small optimizations."

**Comment by antonelepfl** [comment]
Based on [this](https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/140#issuecomment-365005203) comment the public Collab is [here](https://collab.humanbrainproject.eu/#/collab/376/nav/63146)

Item should be added in the BSP with the following information:

**Title**: Optimize a striatal fast-spiking interneuron

**Description** : Fit parameters of a striatal fast-spiking interneuron model to the experimental data. Optimization uses BluePyOpt as well as  the realistic morphology, channel kinetics and extracted neurophysiological features. This version runs directly on the collaboratory and it is limited to small optimizations.

**Image**:

![fs](https://user-images.githubusercontent.com/24406041/36156892-bb6e6124-10d8-11e8-9f15-bcde7657d508.png)

**Comment by antonelepfl** [comment]
@a1eko this item should be in the BSP under `Single Cell Building`? otherwise please let me know where should I place it.
Thank you in advance

**Comment by a1eko** [comment]
Yes, Stefano, it should be in Single Cell Building of BSP. Thank you!

**Comment by antonelepfl** [comment]
@a1eko Please could you modify the public [collab ](https://collab.humanbrainproject.eu/#/collab/376/nav/63146) removing some of the cells like in the attachement?

![screen shot 2018-02-15 at 15 15 52](https://user-images.githubusercontent.com/24406041/36260992-416e9c4a-1263-11e8-8859-25ad7e5e6588.png)

And please I would need you to modify this [file](https://github.com/antonelepfl/usecases/blob/striatal_optimization/src/assets/config_files/models.json#L83).
You can do it directly from the UI using the Pencil icon
![screen shot 2018-02-15 at 15 19 41](https://user-images.githubusercontent.com/24406041/36261147-b31e06e6-1263-11e8-901a-db7e4581197a.png)
Adding the description and another picture if you want (I putted the same as the usecase so far)
and then commit it to the `striatal_optimization` branch I think it automatically will tell you to do that.

Please let me know if you have any other question
Stefano
