### ISSUE TITLE
Python error in use case Synaptic Events Fitting.

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#18]
### Expected behavior

No error when the job completes 

### Actual Behavior

"No such file or directory" error when the job has finished.

### Steps to reproduce the problem

Follow the use case

### Optional infrastructural data (user, platform, browser, environment, ...)

![selection_030](https://user-images.githubusercontent.com/12729291/31370851-32f7eca0-ad8e-11e7-9f30-d398d143f2d5.png)

**Comment by clupascu** [comment]
I fixed this. Now I check if the output file test.csv has been created on NSG before trying to transfer it to the kernel. Please test again.

Thanks.

**Comment by clupascu** [comment]
When testing select the demo radio button. It is very quick.

**Comment by alex4200** [comment]
Ok, seems to be fixed, thanks.
