### ISSUE TITLE
Mouseover text for unfinished steps

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#181]
### Expected behavior

When the mouse is over the icon (see screenshot), I expect a message more like "Step has not been run."

### Actual Behavior

The text reads "Waiting for simulation ends" which gives the impression something is running and the user just needs to wait.

**Comment by antonelepfl** [comment]
I did a review for this.. @alex4200 let me know in the review if the texts look good for you
