### ISSUE TITLE
Plots in the Analysis section still missing

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#182]
- The three plots for the analysis are still missing
- Axis labels incomplete
- Titles need to be adjusted

**Comment by antonelepfl** [comment]
@alex4200 for the axis label and the other plot I would need to see who is going to be in charge of that. If it's me or Mike or another person.
@jdcourcol who do you think it is the better way to tackle that?

**Comment by jdcourcol** [comment]
Please ask Mike for help.

**Comment by alex4200** [comment]
@arsenius7 : As far as I know you are working on this task. What is the status on it?

**Comment by arsenius7** [comment]
I would add voltage collage to BluePy today (although eventually it won't go there).
Don't know if anything else is expected from me here. ^^

**Comment by alex4200** [comment]
@antonelepfl : will you add the script to the simulationUI/analysis when Arseny is done?

**Comment by arsenius7** [comment]
@antonelepfl , is there any specific requirement how voltage collage should look like apart from the code snippet you provided (which in turn is taken from [Post Simulation Workflow](https://developer.humanbrainproject.eu/docs/projects/postsimulationutils/0.0.10/pswf.html#workflow-overview), I believe)?

I.e., would this one do:
![voltage_collage](https://user-images.githubusercontent.com/18440108/36978155-789655f2-207b-11e8-9df7-8de05639eac2.png)

**Comment by alex4200** [comment]
Plots are present, look good to me. Closing ticket
