### ISSUE TITLE
Uploading file possible although no file selected

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#184]
### Expected behavior

I should be unable to click the 'Upload' button as long no file has been selected. 

### Actual Behavior

Still able to click the upload button if no file is selected, resulting in an error or course

![selection_219](https://user-images.githubusercontent.com/12729291/36299976-9e40f78c-12ff-11e8-96f5-f71cea400aff.png)

**Comment by lbologna** [comment]
This should be fixed now. Could you please test again? Thanks

**Comment by alex4200** [comment]
Yep, done
