### ISSUE TITLE
Small python error in validation notebook

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#186]
The first cell of the "Optimized BG model validation" use case has a small error. 

Incorrect:

```
try:
    pkg_resources.get_distribution('bluepyopt')
    # do version checking if required
except:
    !pip install --quiet bluepyopt
import bluepyopt.ephys as ephys

try:
    pkg_resources.get_distribution('bluepyopt')
except:
    # do version checking if required
    !git clone https://github.com/appukuttan-shailesh/basalunit
    !pip install --quiet ./basalunit
import basalunit
from basalunit.utils import CellModel
```

correct:
```

try:
    pkg_resources.get_distribution('bluepyopt')
    # do version checking if required
except:
    !pip install --quiet bluepyopt
import bluepyopt.ephys as ephys

try:
    pkg_resources.get_distribution('basalunit')  ## HERE
except:
    # do version checking if required
    !git clone https://github.com/appukuttan-shailesh/basalunit
    !pip install --quiet ./basalunit
import basalunit
from basalunit.utils import CellModel
```

also in the end of the second cell:
```

if jp_value == "":    ## HERE (instead of a single '=')
    junction_potential = 9.5 # mV
else:
    junction_potential = float(jp_value)
```

**Comment by appukuttan-shailesh** [comment]
The notebook isn't ready for testing :)
An hour or two more....

**Comment by apdavison** [comment]
@lbologna please could you add @appukuttan-shailesh to the list of collaborators for this repository, so that this ticket can be assigned to him instead of to me? ;-)

**Comment by alex4200** [comment]
@apdavison I cna take care of that...

**Comment by appukuttan-shailesh** [comment]
Hi @alex4200 ,
The usecase is now more or less ready. There is one issue with regards to viewing the final report within the Jupyter notebook. I am looking into this (seems to be to do with the large file size, as the same code has worked previously for me with smaller files.) Also trying to offer a download link. But right now, the location for the report is merely displayed at the end of the test, and the user has to manually download it. Shall try to fix this soon.

Looking forward to your feedback.

**Comment by appukuttan-shailesh** [comment]
@alex4200 : The PDF problem has been fixed. Ready to be tested.

p.s. In case anyone finds this useful in future, here is the solution to the PDF issue:
https://forum.humanbrainproject.eu/t/problem-with-iframe-in-jupyter-notebook/528
