### ISSUE TITLE
Python error in first cell of "Optimized BG model validation"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#188]
There seems to be still some error in the first cell of that use case:

![selection_223](https://user-images.githubusercontent.com/12729291/36370171-61e2e0e6-155e-11e8-917b-724d844f1b64.png)

**Comment by appukuttan-shailesh** [comment]
Is this reproducible? I tested this now with two different accounts, in two different collab environments and it worked. 

If reproducible, would it be possibly for you to break down the cell and identify where it is giving this error?

**Comment by alex4200** [comment]
@appukuttan-shailesh Update: When I run the following command before the `basalunit` install it worked:

`!pip install --upgrade setuptools`

**Comment by appukuttan-shailesh** [comment]
Oh ok. Thanks for identifying that; now we know how to fix it! I am wondering if it's something too generic, and whether it needs to be handled within the usecase? What do you think?

**Comment by alex4200** [comment]
I am not sure about that. It happened in my main HBP account where I try out a lot of things. So quite probable that I 'misconfigured' something. 

For now I would suggest to close this ticket and see if this issue will occur again...

**Comment by appukuttan-shailesh** [comment]
Sure. I agree with that.
