### ISSUE TITLE
More detailed comments for each cell

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#189]
### Expected behavior

A title and some sentences about what is going on for each cell in  the notebook. I suggest a short and concise title, and then some concise text.

Example:

![selection_226](https://user-images.githubusercontent.com/12729291/36370414-145a5060-155f-11e8-9116-6b55f32c4b04.png)

### Actual Behavior

![selection_224](https://user-images.githubusercontent.com/12729291/36370420-179dfa06-155f-11e8-92c8-e12aededc875.png)

**Comment by appukuttan-shailesh** [comment]
Sure, will make the documentation more descriptive.

**Comment by appukuttan-shailesh** [comment]
Completed.

**Comment by alex4200** [comment]
@appukuttan-shailesh : Overall, I think the documentation given in the notebook is really great and clear in order to guide the user through it. 

However, I found some (minor) spelling issues and suggestions: 

First text cell: 

- Suggestion: "hall_of_fame.json" -> `hall_of_fame.json`
- collab -> Collab

Cell "Specifying model ..."
 -  registed -> registered

**Comment by appukuttan-shailesh** [comment]
Thanks @alex4200 for going through this meticulously. I have now made the changes that you recommended.

**Comment by alex4200** [comment]
Perfect, thanks.
