### ISSUE TITLE
Unclear situation when I start another job in Synaptic Events Fitting

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#19]
### Expected behavior

I expect to have only one image "job submitted" 

### Actual Behavior

Once submitting a job again, I get another image of "job submitted". Because the button "Check NSG simulation " appears only later, how do I know which simulation this button now refers to? 

### Steps to reproduce the problem

Start a job and after having finished, start another job

### Optional infrastructural data (user, platform, browser, environment, ...)

![selection_031](https://user-images.githubusercontent.com/12729291/31370928-932491d2-ad8e-11e7-8b15-2ef6c8a5a986.png)

**Comment by clupascu** [comment]
I fixed this. I disabled the "Run NSG simulation" button, while a job is still running. Please test again.

Thanks.

**Comment by alex4200** [comment]
Seems ok now. Thanks
