### ISSUE TITLE
Username for Validation

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#190]
### Expected behavior

Instead of having the user edit the cell, there is a way to get the name of the user automatically: 

```
from bbp_client.identity_service.client import Client as IC
ic = IC.new(token=oauth.get_token())
HBP_USERNAME = ic.me()['username']
```

see https://collab.humanbrainproject.eu/#/collab/509/nav/24072

### Actual Behavior

User needs to edit the cell.

**Comment by appukuttan-shailesh** [comment]
The `username` is infact (intended) already optional, when the notebook is being run inside the Collaboratory. It has been kept in cell 4, just in case a user wishes to download the notebook and run it locally.

Another potential (less likely) reason for allowing user to specify the username (even within the Collaboratory) is in dealing with access permissions (wanting to run the test with different credentials).

**Comment by appukuttan-shailesh** [comment]
@alex4200 : Shall we close this?

**Comment by alex4200** [comment]
I would appreciate if you can update the inline documentation a bit, i.e. mention explicitly in the 'MarkDown' box above that there is no need to change the username.

**Comment by appukuttan-shailesh** [comment]
Done.
