### ISSUE TITLE
Use Case Grouping in BSP

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#191]
Suggestion: 

1. Remove the use case group 'Validation-framework Use Cases'
2. Move the use case group 'Highly integrated workflows' on top of the group 'Online Courses'

![selection_227](https://user-images.githubusercontent.com/12729291/36370949-e9586af8-1560-11e8-92c4-246b45984409.png)

**Comment by antonelepfl** [comment]
@alex4200 I don't know who created the Validation usecase.
I moved it down but I don't want to remove it if I don't know how did it and why they put it there.
@jdcourcol do you know something about it?

**Comment by apdavison** [comment]
This was created a long time ago, with some demonstrations of/documentation of the prototype version of the Validation Framework. @appukuttan-shailesh do you think we can archive the contents of this and then delete it? (Lungsi was the original author, but he is on vacation at the moment...)

**Comment by appukuttan-shailesh** [comment]
I see that the demo is actually hosted at `https://lungsi.github.io/HVF-walkthrough`, so we have a reliable backup. So I think it is safe to go ahead and remove this from the Collaboratory. Also, I shall remove the `IPython example demo` jupyter notebook and shall include this within the 'Validation' use case menu.

@apdavison : does this seem fine?

**Comment by appukuttan-shailesh** [comment]
The part dealing with 'Validation-framework Use Cases' has been taken care of.
