### ISSUE TITLE
Insert the Mouse Purkinje cell into the Brain Sim. Platform

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#192]
The Mouse Purkinje cell use case needs to be inserted into the brain simulation usecase. 

To my understanding this use case should go to the 'Single Cell Building' use case. 

The use case is to be found here, but needs to be made 'public'.

https://collab.humanbrainproject.eu/#/collab/7959/nav/60494

 Then it can be simply linked ...

**Comment by SteMasoli** [comment]
I have uploaded all the files on the BSP storage and added it to the list of usecases (pull request pending). There is no more need to link the collab.
I'll upload the guidebook as soon as possibile

**Comment by antonelepfl** [comment]
I think the usecase is already [here](https://collab.humanbrainproject.eu/#/collab/1655/nav/66852)
@SteMasoli if you agree that is there, you can close the ticket.

**Comment by SteMasoli** [comment]
Yes the usecase is entirely on the BSP.
