### ISSUE TITLE
Link to legend for definitions

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#193]
In the Feature Extraction GUI it would be nice to have a link (maybe on the top) to the definitions of the features

e.g. http://bluebrain.github.io/eFEL/eFeatures.html

or some similar page. 

![selection_230](https://user-images.githubusercontent.com/12729291/36381470-f418c5b2-1585-11e8-8992-c5efaae9339a.png)

**Comment by lbologna** [comment]
I added a link before the feature selection panels. Could you please check if this is fine?
Thanks.

**Comment by alex4200** [comment]
Yes, nice...
