### ISSUE TITLE
Explanation for user what to find in the resulting json files

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#194]
In the introduction page of the Feature Extraction use case

![selection_231](https://user-images.githubusercontent.com/12729291/36381617-7c57402a-1586-11e8-9199-727db3f74c45.png)

a sentence or two might be needed to advise the user 'what to do' with the created json files. 

(outcome of user testing)

**Comment by lbologna** [comment]
I added a brief explanation on the introduction page. Could you please check if this is fine?
Thanks.

**Comment by alex4200** [comment]
Thanks
