### ISSUE TITLE
Technical documentation still incomplete

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#197]
The technical documentation here is still incomplete:

https://docs.google.com/document/d/19Ni5fGFv6PTTM1D_D2FN4dj5IRhtfq1D0V2OWjXxJww/edit#bookmark=id.mcie7vrvjvug

**Comment by Hjorthmedh** [comment]
Documentation for striatum scaffold has been updated.

**Comment by alex4200** [comment]
Yes, fixed
