### ISSUE TITLE
User experience labelling

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#198]
There should be a single 'user experience' labeling; either 'Everybody' or 'Power users'. 

![selection_234](https://user-images.githubusercontent.com/12729291/36424223-e24befe0-1642-11e8-9524-533dc0bde739.png)

**Comment by clupascu** [comment]
I have modified the user experience labeling for  UC_HippoCellModel_Own  to Power users only.
