### ISSUE TITLE
User experience labeling 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#199]
There should be a single 'user experience' labeling; either 'Everybody' or 'Power users'. 

![selection_234](https://user-images.githubusercontent.com/12729291/36424223-e24befe0-1642-11e8-9524-533dc0bde739.png)

**Comment by SteMasoli** [comment]
Done.

**Comment by alex4200** [comment]
@antonelepfl : Can you merge these changes to prod please?

**Comment by antonelepfl** [comment]
Done.
Please have a look on Prod

**Comment by alex4200** [comment]
Thanks
