### ISSUE TITLE
Authorize Screens are confusing

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#2]
When navigating in the BSP and opening some new pages/screens/use cases sometimes there is a screen asking for authorisation:

![approvalrequired](https://user-images.githubusercontent.com/12729291/31008505-a81521de-a504-11e7-8799-ef87fbf4fdab.png)

To me as user it is not clear what this means. What or whom do I authorise of what? To me it looks like that I am authorising myself. 

It should be made much clearer and more obvious what is authorising what  for whom etc.

**Comment by jdcourcol** [comment]
I agree but it is for https://forum.humanbrainproject.eu/
