### ISSUE TITLE
AttributeError when running use case "Rebuild an existing single hippocampal cell model"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#20]
### Expected behavior

No error

### Actual Behavior

AttributeError                            Traceback (most recent call last)
<ipython-input-3-dbf304d56262> in refresh(_)
    193     storage = get_bbp_client().document
    194     if storage.exists(get_collab_storage_path() + os.path.sep+ "BluePyOptAll"+os.path.sep+"resultsNSG"+os.path.sep+res.json()['username']):
--> 195         jobsstorage=storage.ls(get_collab_storage_path() + os.path.sep+ "BluePyOptAll"+os.path.sep+"resultsNSG"+os.path.sep+res.json()['username'])
    196         for j in range(len(jobsstorage)):
    197             dirsubf=jobsstorage[j]

AttributeError: 'Client' object has no attribute 'ls'

### Steps to reproduce the problem

Start a NSG simulation, open the Job Manager notebook, and press the 'Reaload' button.

### Optional infrastructural data (user, platform, browser, environment, ...)

FF

![selection_032](https://user-images.githubusercontent.com/12729291/31371002-f11e6f4c-ad8e-11e7-9651-b368ce357ccd.png)

**Comment by clupascu** [comment]
I fixed this. Can you please test it again?
Thanks.

**Comment by alex4200** [comment]
@clupascu : This defect has been resolved, but another one appeared: #25

**Comment by alex4200** [comment]
Closing this one
