### ISSUE TITLE
Unable to launch job on  JULIA

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#202]
When starting the default job on JULIA the submit screen is shown only 

![selection_248](https://user-images.githubusercontent.com/12729291/36590835-40889ae6-1890-11e8-8568-4480f689ab77.png)

**Comment by antonelepfl** [comment]
@alex4200 let's try tomorrow because I don't get this issue.

**Comment by alex4200** [comment]
Some remarks: 
1. I am not sure a 'normal' user will understand what is meant by that message "more details in console" . 
2. When opening the console at this point, there is no error. 
3. When you open the console and repeat the actions leading to this error, there does not seem to be an error anymore in the console.

Couldn't you 'catch' the console error message and show it on the popup? That would be much more user friendly...

**Comment by alex4200** [comment]
@antonelepfl : With the current implementation I get the 'error popup' even when I submit a job on JUQUEEN. 

1. I start a job on JUQUEEN 
2. I get the error popup
3. Then I get the OK popup. 
4. Job is shown in the list of jobs

**Comment by alex4200** [comment]
@antonelepfl  Error log to be shown to the user

**Comment by antonelepfl** [comment]
I'm not able to log the error due it is not in the response that comes, it is in the browser side.
![screen shot 2018-03-12 at 13 03 50](https://user-images.githubusercontent.com/24406041/37282760-e3bec7b8-25f5-11e8-9ca2-985315a9e342.png)
Please see that the response in `undefined` and the stack does not show the real error.

**Comment by antonelepfl** [comment]
This one should be linked to [#233](https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/233)
As the error is shown (`network error`) I think showing the full should not be a priority for now.
Probably we can change the tag to 'Small_task'

**Comment by alex4200** [comment]
Yes I guess so
