### ISSUE TITLE
Update backend optimization operations with new optimization repository .py script

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#203]
### Expected behavior
Optimization are submitted correctly

### Actual Behavior
Optimization cannot be submitted with success

### Steps to reproduce the problem
Go through the optimization procedure and launch the optimization on NSG

**Comment by alex4200** [comment]
Update expected until end of week (i.e. 2 March)

**Comment by lbologna** [comment]
This should be fixed now. Could you please test again? Thanks

**Comment by alex4200** [comment]
@lbologna : Not sure how to test this. Whenever I try to download the results ("Fetch results"), I get the message "No output file downloaded"...

**Comment by alex4200** [comment]
Works with the given instructions.
