### ISSUE TITLE
Documentation about updating use cases 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#204]
Stefano is about to update some documentation of the workflow on how to update the use cases, in order to have them available in a dev/test environment before putting them in the productive environment. 

Documentation to be added to: https://github.com/antonelepfl/usecases

**Comment by antonelepfl** [comment]
* New [Workflow](https://github.com/antonelepfl/usecases#to-deploy-in-a-dev-environment)
* New way to [add a use case](https://github.com/antonelepfl/usecases/blob/dev/documentation/add_new_usecase.md#add-new-usecase-in-an-existing-domain)
