### ISSUE TITLE
Replacement for ksearch service

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#205]
The use case 

`Synaptic events fitting `

use the ksearch service for which a replacement need to be found. Andrew Davison and Jeff Muller are involved.

**Comment by alex4200** [comment]
@clupascu will clarify the state of this use case (SGA1/SGA2) with Michele.

**Comment by clupascu** [comment]
I clarified the state of this use case with Michele. Unfortunately, due to delays in making the data available for searching in the new NIP search service, the use case will not be online back again before the end of SGA1.

**Comment by clupascu** [comment]
I enabled again this usecase, even if it is not possible yet to search for the data in the Knowledge Graph. I use for now a list of direct links to the containers. Can you test this usecase again please? Thanks.

**Comment by alex4200** [comment]
Now, when I click on "Run simulation" I get the following error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-6cc794d8c5cf> in runNSG(_)
    640     RBM.layout.display='none'
    641     TR.layout.display='none'
--> 642     if msg=='Authenticated successfully':
    643         IN.layout.display=''
    644         display(IN)

NameError: global name 'msg' is not defined
```

**Comment by clupascu** [comment]
Sorry about this. Should be fixed now.

**Comment by alex4200** [comment]
@clupascu Now I get the following error:

StorageArgumentException: The path must be a string, start with a slash (/), and be longer than 1 character.

Suggestion: Make sure that `storeto` is of type `str`. And in both cases (NSG, UNICORE)

**Comment by clupascu** [comment]
This should be fixed now.

**Comment by alex4200** [comment]
Yes, thats ok for now...
