### ISSUE TITLE
500 Server error 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#207]
Probably because filenames have changed. The path to the pdf to display is incorrect.

**Comment by clupascu** [comment]
This is fixed. Can you try again please? Thanks.

**Comment by clupascu** [comment]
I checked the Dev 2 Collab and the pdf's are displayed.
![schermata 2018-03-01 alle 22 31 07](https://user-images.githubusercontent.com/22050958/36870770-6a5f9f58-1da0-11e8-9192-6368ab82b3bd.png)

**Comment by alex4200** [comment]
@clupascu I have redone the analysis in the Collab 'Dev2'. I started the Config notebook again (after removing the paths in storage) with the default settings (i.e. taking the already marked models etc). 

After the NSG job has finished, I clicked on 'Storage' just to see the Server error again. I have verified there is only one result and it contains an 'output.tar.gz' file. 

I further checked what is going on in the code (around line ~250): I printed out the content of the folder

`./BPOPTANALYSIS/CA1_int_cAC_010710HP2_20180302100726/OUTPUTBPOPT/CA1_int_cAC_010710HP2_20180302100726/figures`

and it is empty. It looks like no pdf files have been generated, leading to the 500 Server error. 

Where are they being generated? in that 'analysis.py' file?

**Comment by clupascu** [comment]
They are actually created in the opt_neuron.py. I will take a look again at this. For the github examples it works isn't it?

**Comment by alex4200** [comment]
@clupascu : Yes; for the github examples its working and then I see the pdf files. 

(I am available on skype now...)

**Comment by clupascu** [comment]
I am trying to send you a message and it is not working. Can you call me?

**Comment by clupascu** [comment]
This should be fixed. Can you test again please? Thanks.

**Comment by alex4200** [comment]
Yes seems to work now, thanks
