### ISSUE TITLE
BlueConfig file is missing

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#209]
### Expected behavior

Once I have submitted a job to Juelich, I expect to see the BlueConfig file I have submitted. 

### Actual Behavior

BlueConfig file is not available in some cases:

![selection_250](https://user-images.githubusercontent.com/12729291/36718742-28fa0c1e-1ba3-11e8-82a2-e83797369f04.png)

### Steps to reproduce the problem

Jobs with a exceeding wall clock time?

**Comment by antonelepfl** [comment]
Yes I understand this problem but how the launch script works is the following.
You can pass it a JSON file and then it will convert to our `standard` format of BlueConfig and then, starts the simulation.
If you have an error let's say in the allocation of the job (before the parsing and running part) the parse is not done so I cannot show BlueConfig format.

I have the possibility to show `blueconfig.json` file but I don't want the people to get confused with the json... 
Here do you have an example of what a blueconfig.json looks (left) and BlueConfig (right)

![screen shot 2018-02-28 at 17 44 262](https://user-images.githubusercontent.com/24406041/36800488-f69cb48e-1caf-11e8-9b7e-f0efd4079573.png)

Even thought it is pretty similar when I showed the json to Michele and Armando, they did not get it right away

**Comment by alex4200** [comment]
To me it looks pretty much the same... - however, maybe its possible to show some small text in case the BlueConfig is not available; something like

`    BlueConfig not available because of error on job; please check the logs. `
