### ISSUE TITLE
NameError for use case "Build your own single hippocampal cell model using HBP data"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#21]
### Expected behavior

No error while submitting a job in notebook "BluePyOpt Browse All"

### Actual Behavior

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-4b1637799f57> in runNSG(_)
     63 
     64     global CRA_USER, PASSWORD, KEY, URL, TOOL
---> 65     CRA_USER = username
     66     PASSWORD = password
     67     KEY = 'Application_Fitting-DA5A3D2F8B9B4A5D964D4D2285A49C57'

NameError: global name 'username' is not defined

### Steps to reproduce the problem

Just follow the use case

### Optional infrastructural data (user, platform, browser, environment, ...)

Firefox

![selection_034](https://user-images.githubusercontent.com/12729291/31371529-a14d5e3a-ad91-11e7-96b1-29c11d881281.png)

**Comment by clupascu** [comment]
Have you clicked on Login NSG button before running NSG simulation?

**Comment by alex4200** [comment]
@clupascu: I am sure I have, but when repeating this use case it seems to work. Therefore, I close this issue for now...
