### ISSUE TITLE
Documentation missing from Guidebook

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#212]
User documentation is missing from the guidebook; see here: https://collab.humanbrainproject.eu/#/collab/1655/nav/18580

**Comment by SteMasoli** [comment]
https://github.com/lbologna/hbp-sp6-guidebook/pull/19

**Comment by lbologna** [comment]
This was integrated in the Guidebook.
Could you please check again?

Thanks.

**Comment by SteMasoli** [comment]
It is fine. 
Thank you

**Comment by lbologna** [comment]
Ok.
Closing the issue.
