### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#216]
Again the 500 Server Error for the "Feature Extraction GUI" use case. 

Environment: Production

**Comment by lbologna** [comment]
Actually bug fixes for the Server Errors have not been uploaded to
Production yet.
I will keep you up to date with the next upload.

**Comment by lbologna** [comment]
This is actually still under test, although a few causes for this error should be solved.
I am going through the log to solve the last ones. I will keep you up to date.

**Comment by alex4200** [comment]
Ok I leave it open...

**Comment by lbologna** [comment]
One of the error triggering the Server Error, apparently depends of the token management at the oidc level. I will get in contact with the collab team and keep the issue up-to-date

**Comment by jdcourcol** [comment]
Backend to be modified based on collab team command (probably logout the user).

**Comment by lbologna** [comment]
The token refresh procedure was implemented and the server error did not occur anymore to me.
@alex4200 given that you have now access to the uwsgi.log, I propose that we close this issue and open more specific ones is the error occurs again. Thanks.

**Comment by alex4200** [comment]
Agreed
