### ISSUE TITLE
Unable to upload models to Naas

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#217]
### Expected behavior

After selecting and loading a model to the NAAS through:

https://collab.humanbrainproject.eu/#/collab/1655/nav/66854

when the upload button is clicked, a zip file is loaded or rejected.

### Actual Behavior
The Upload splash panel is frozen when a .zip file is selected and the Upload button is clicked

### Steps to reproduce the problem
Go to:
https://collab.humanbrainproject.eu/#/collab/1655/nav/66854
Select a model.
After the model is loaded, click on the up-left menu and then click "Upload model".
Choose a .zip file and click Upload.

### Optional infrastructural data (user, platform, browser, environment, ...)
Tested with MacOSX with both firefox and chrome

**Comment by alex4200** [comment]
The same issue happens when using the page 

https://blue-naas.humanbrainproject.eu/

as the entry point. After I click 'Upload' the page freezes. 

Console: 
```

Unhandled promise rejection 
Error: Internal Server Error
Stack trace:
response/<@https://blue-naas.humanbrainproject.eu/app.5a3ae916699a3d75cf2e.bundle.js:28:23246

```

**Comment by genric** [comment]
Should be back to normal now. Please retest. Thanks.

**Comment by alex4200** [comment]
Yep seems to work again, thanks
