### ISSUE TITLE
Use case name inconsistent

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#218]
### Expected behavior

I expect the name of a use case the same in the actual use case and its documentation

### Actual Behavior

In use cases: Simulation and validation of a mouse Purkinje cell multicompartmental model
In Guidebook: Multi compartmental mouse Purkinje cell simulation and validation

Suggestion: Change the title in the Guidebook

**Comment by SteMasoli** [comment]
Done the title update
