### ISSUE TITLE
Notebook instructions in "Cell placement - cerebellum" unclear

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#22]
### Expected behavior

Clear description on how to proceed / a way to follow just the notebook in a linear fashion

### Actual Behavior

User should 'reload' notebook. Save notebook first? Reload whole page? Frame reload?

![selection_035](https://user-images.githubusercontent.com/12729291/31371912-bcf68272-ad93-11e7-90cd-aa4ff904414f.png)

**Comment by jdcourcol** [comment]
investigate to be installed by default.

**Comment by antonelepfl** [comment]
Based on the nb-extensions webpage, they say that we need to reload the page 

> If you reload the notebook after enabling a notebook extension, the extension will be loaded. You can check the Javascript console to confirm.

(https://github.com/ipython-contrib/jupyter_contrib_nbextensions/wiki/Home-4.x-%28Jupyter%29)

I talked with the collab team and they are loading some nb-extensions in the kernel so the user don't have to install it, just use it.
The thing that I don't like is that we need to install it for EVERY user in the kernel and I don't know what will happen if we need to upload the extension to a new version.
We will lose an specific configuration (or version) that the user will have in his notebook.

**Comment by alex4200** [comment]
But if an user decided to run this particular workbook and installs these extensions, he will have it anyway in EVERY collab he creates from then on. Every new collab he crated or he uses will have this extension ... 

But basically I agree. Only a minimum set of packages should be installed for a user in the first place...

**Comment by alex4200** [comment]
Suggestion for a better text:

### Important step
Having arrived here, please restart the kernel (by clicking on the notebook reload icon) and continue executing the cells below.

**Comment by antonelepfl** [comment]
@alex4200 I don't think that only restarting the kernel fix the problem. I tried and it did not work.
IMHO I think this issue should be closed because it is a limitation of the technology used and not the way that we develop the Notebooks.

**Comment by antonelepfl** [comment]
@alex4200 Something like this you think is enough?
![screen shot 2017-11-13 at 09 50 21](https://user-images.githubusercontent.com/24406041/32716928-253daa52-c858-11e7-9e72-52c54ac750e0.png)

**Comment by alex4200** [comment]
@antonelepfl : Maybe explicitly mention "... brower page ..." so its clear to reload the browser page, and not the kernel. Also, is a standard "F5" page reload enough or does the user have to reload the page with "CTRL F5" (to force a cache refresh)?

**Comment by antonelepfl** [comment]
With normal reload it should be fine.
I updated them could you test it please?

**Comment by alex4200** [comment]
@antonelepfl: Much clearer, but one more suggestion: 

"Please reload the brower page so the visualization extension is enabled - continue with the next step below"

to make clear to continue with the next step below.
Also: Why not put every command of the first 4 cells in one cell and add the '%%capture' magic so no logout is produced?

**Comment by alex4200** [comment]
@antonelepfl : Any update on this issue? Or do you disagree? If you agree, can you do it quickly so this issue can be closed...?

**Comment by antonelepfl** [comment]
@alex4200 So I changed it could you please recheck it?

**Comment by alex4200** [comment]
perfect
