### ISSUE TITLE
Setting 'config.txt' as the default config file

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#220]
### Expected behavior

The user can proceed with his analysis without the need to select what the configuration file is. 

### Actual Behavior

The user must manually select the name of the config file

**Comment by clupascu** [comment]
Setting 'config.txt' as default config file is done. I tried also to verify all the possible situations (config file not in the folder to analyse, experimental file not in the folder to analyse, results folder not in the folder to analyse and so on) and give feedback to the user. Can you test please and give feedback? Thanks.

**Comment by alex4200** [comment]
Checked the various possibilities. Looks good to me, thanks.
