### ISSUE TITLE
Link to "HBP Validation Framework App"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#222]
### Expected behavior

To see a link or something that guides the user to the "HBP Validation Framework App".

### Actual Behavior

This App is mentioned in the notebook - but neither a link nor an explanation where to come to that app...

![screen shot 2018-03-07 at 08 37 54](https://user-images.githubusercontent.com/12729291/37080162-8c94b95c-21e5-11e8-8e10-a57139599d51.png)

**Comment by appukuttan-shailesh** [comment]
This is (in all likelihood) a Collaboratory issue. I have raised it [here (almost 3 weeks ago)](https://forum.humanbrainproject.eu/t/problem-with-iframe-in-jupyter-notebook/528) but received no response.

The current code works perfectly run when running the notebook locally. As a test, one could just run the following to verify:
```
from IPython.display import IFrame    
IFrame("./myfile.pdf", width=900, height=650)
```
This above method worked on the Collaboratory till last week (I am sure you would have seen the PDFs at the end of the use case before). If you can help looping in someone from the Collab team to help fix/identify the issue, it would be great. Not sure there is much I can do in the meantime (probably no sense in finding other workarounds if they are likely to fail on the Collab in some weeks; better to receive a confirmation from their end).

**Comment by appukuttan-shailesh** [comment]
This was easy to to fix, but to make it better we intend to provide direct links to the specific model and the result inside the app. This will avoid having the user to navigate their way inside the apps. But this requires a small update of the apps, and is expected soon.

In the meantime, I have just provided links to the apps. But let's close this issue once the above is handled.

**Comment by appukuttan-shailesh** [comment]
@alex4200 : This is now complete. Direct links to the model and results have now been provided.

**Comment by alex4200** [comment]
yes...
