### ISSUE TITLE
pdfs are not shown

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#223]
### Expected behavior

The pdfs are displayed

### Actual Behavior

The pdfs are not shown:

![screen shot 2018-03-07 at 08 37 39](https://user-images.githubusercontent.com/12729291/37080208-b1fd53a2-21e5-11e8-9293-3761392e92ab.png)

### Steps to reproduce the problem

Follow all steps of the use case "Optimized BG model validation" to the end

**Comment by appukuttan-shailesh** [comment]
This is (in all likelihood) a Collaboratory issue. I have raised it [here (almost 3 weeks ago)](https://forum.humanbrainproject.eu/t/problem-with-iframe-in-jupyter-notebook/528) but received no response.

The current code works perfectly run when running the notebook locally. As a test, one could just run the following to verify:
```
from IPython.display import IFrame    
IFrame("./myfile.pdf", width=900, height=650)
```
This above method worked on the Collaboratory till last week (I am sure you would have seen the PDFs at the end of the use case before). @alex4200: If you can help looping in someone from the Collab team to help fix/identify the issue, it would be great. Not sure there is much I can do in the meantime (probably no sense in finding other workarounds if they are likely to fail on the Collab in some weeks; better to receive a confirmation from their end).

**Comment by clupascu** [comment]
@appukuttan-shailesh I am displaying pdf's with something like this display(IFrame(                              os.path.join('.','report','HBP_VF_Report_20180307-083020.pdf'),width=600, height=300)), when I already moved to the folder containing the pdf file. I hope it may help.

**Comment by appukuttan-shailesh** [comment]
Thanks a lot @clupascu! That works! :+1: 

Any idea if/how we can make it also work with URLs? E.g.
display(IFrame("http://www.stackoverflow.org", width=900, height=650))

**Comment by apdavison** [comment]
The URL might need to be https, otherwise it won't display inside the Collaboratory.

**Comment by appukuttan-shailesh** [comment]
Yupp that's right! Thanks! Will update on the forum for future reference.

**Comment by alex4200** [comment]
Solved, thanks
