### ISSUE TITLE
Error when user forgets to log in to NSG

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#225]
Minor task! Please check only when time ...

### Expected behavior

Better error handling. In this case I clicked on 'Run Simulation' without having clicked on 'Login NSG', so the username was not set. 

### Actual Behavior

NameErrorTraceback (most recent call last)
<ipython-input-12-09632869b4d0> in runNSG(_)
 492     clients = get_hbp_service_client()
 493     global CRA_USER, PASSWORD, KEY, URL, TOOL
--> 494 CRA_USER = username
 495     PASSWORD = password
 496     KEY = 'Application_Fitting-DA5A3D2F8B9B4A5D964D4D2285A49C57'

NameError: global name 'username' is not defined

### Steps to reproduce the problem

Follow the use case with the example input as described in the test plan:

Select an exp file resources/test_synaptic_events_fitting/exp5.txt
Select an mod file resources/test_synaptic_events_fitting/exp3syn.mod
Set the correct values (third page):

    Number of traces: 82
    VCLAMP AMP: -60
    REVERSAL POTENTIAL: 0

Set some values on fourth page
0 synapse.tau1 0.1 0 10
1 synapse.tau2 10 0 10
2 synapse.tau3 5 0 10
3 netstim.start 5.2 0 10
4 netcon.weight[0] 0.6e-3 1e-8 1e-1

### Optional infrastructural data (user, platform, browser, environment, ...)

DEV

**Comment by clupascu** [comment]
This should be fixed now. Can you test again please? Thanks.

**Comment by alex4200** [comment]
Yes done..
