### ISSUE TITLE
Simulation GUI: the analysis UI shows a green checkbox for a failed job

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#228]
### Expected behavior
A failed analysis should be displayed with a red checkbox (a cross actually) in the analysis summary
### Actual Behavior
It is reported with a green checkbox
### Steps to reproduce the problem
Any failing analysis

**Comment by antonelepfl** [comment]
This also should be done.

**Comment by alex4200** [comment]
yep
