### ISSUE TITLE
Indication of job name useful

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#229]
Minor task:

An indication of the name of the job in the notebook that starts the simulation would be useful. 

On the "Analysis" page I can see job names like 

userdata_output_demo_14686468

would be nice to have this name indicated on the 'config' page as well. Maybe in the row of the 'status'.

**Comment by clupascu** [comment]
The name of the job in the notebook that starts the simulation can be traced only when the job is submitted. When the status is different from submitted, there will not be a number associated to it. The other information (the use case and demo) will be rendundant, as the title of the notebook, the widget that you already selected will remind you how the job was submitted. I don't think this change is necessary.

**Comment by clupascu** [comment]
The submission time was added next to the status of a job submitted through NSG on the 'config' page. This is enough? Can you test again please? Thanks.

**Comment by alex4200** [comment]
Unfortunately, I get the following error now:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-6cd64f11e513> in checksimnsg(CheckSNSG)
    638             STN.layout.display=''
    639             STN.value=child.text+' '+\
--> 640             parser.parse(job_submissiontime).astimezone (pytz.timezone('CET')).strftime("%d/%m/%Y %H:%M:%S")
    641             jobstage=child.text
    642         if child.tag == 'terminalStage':

NameError: global name 'job_submissiontime' is not defined
```

It really looks the variable is never defined anywhere...

**Comment by clupascu** [comment]
This should be fixed now.

**Comment by alex4200** [comment]
Yes it works.
