### ISSUE TITLE
Warning must be placed for firefox

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#233]
When a user uses the SimUI with firefox a warning must be placed to let the user know there is an unsolvable certification error and the user MUST use google chrome and no other browser.

**Comment by alex4200** [comment]
@antonelepfl : Sending error to @jdcourcol

**Comment by antonelepfl** [comment]
@jdcourcol The error that we receive in **Firefox** is the following:

> hbp-unic.fz-juelich.de:7112 uses an invalid security certificate.The certificate is not trusted because the issuer certificate is unknown.The server might not be sending the appropriate intermediate certificates.An additional root certificate may need to be imported.Error code: SEC_ERROR_UNKNOWN_ISSUER

**Comment by antonelepfl** [comment]
This should be fixed now.

**Comment by antonelepfl** [comment]
@alex4200 can you double-check this?

**Comment by alex4200** [comment]
Seems to run on firefox. What was the fix?

**Comment by antonelepfl** [comment]
I don't know, Bernd did something related to it.
