### ISSUE TITLE
Redoing "Run Simulation" does not work

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#236]
### Expected behavior

When I have done "Run Simulation" I can do it again.

### Actual Behavior

Model load error:

![selection_261](https://user-images.githubusercontent.com/12729291/37292756-ea1816a2-2611-11e8-9576-152fbc0903ec.png)

### Steps to reproduce the problem

1. Follow the workflow as described in the doc
2. Start "Run Simulation"
3. Go back to workflow.
4. Start "Run Simulation" again

 DEV environment

**Comment by lbologna** [comment]
This should work now. Could you please test again? 
Thanks

**Comment by alex4200** [comment]
Fixed, thanks
