### ISSUE TITLE
Small typos in the validation notebooks

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#237]
I found some small typos in the validation use cases:

- In "Model Selection": exisitng -> existing (all three notebooks)
- in "Gather Additional Info": ther -> their ? (only BG usecase)
- "Specifying the parameter sets of interest;": rougly -> roughly (only BG usecase)

**Comment by appukuttan-shailesh** [comment]
Thanks @alex4200  for identifying these. Fixed now.

**Comment by alex4200** [comment]
Thanks
