### ISSUE TITLE
NameError in use case "Optimize a cerebellar granule cell multicompartmental model with BluePyOpt running on NSG"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#24]
### Expected behavior

Use case goes through

### Actual Behavior

Name error after NSG simulation is complete:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-632aa2065dd1> in checksimnsg(CheckSNSG)
    182                 copy2(dirloc+os.sep+'OUTPUTBPOPT'+os.sep+'BPOPT'+os.sep+'figures'+os.sep+'neuron_responses.pdf',dirloc)
    183         else:
--> 184             copy2(dirloc+os.sep+'OUTPUTBPOPT'+os.sep+'BPOPT'+os.sep+'checkpoints'+os.sep+'checkpoint.pkl',dirloc)
    185         r = requests.get(selfuri, auth=(CRA_USER, PASSWORD), headers=headers)
    186         root = xml.etree.ElementTree.fromstring(r.text)

NameError: global name 'copy2' is not defined
```

And possible followup error (see second screenshot)

### Steps to reproduce the problem

Follow the use case

### Optional infrastructural data (user, platform, browser, environment, ...)

Firefox, NSG account

![selection_037](https://user-images.githubusercontent.com/12729291/31383570-d6cc885e-adbb-11e7-8acc-edeb4f252e55.png)

![selection_038](https://user-images.githubusercontent.com/12729291/31383596-eeb7887e-adbb-11e7-814a-0149a60cbb9c.png)

**Comment by SteMasoli** [comment]
The missing best.txt is the file with the result generated by the optimization.
The error is linked to the fact that the optimization was not yet finished, or the file not retrieved from NSG and so the script does not find the correct file to do the simulation and visualization of the best result.

**Comment by alex4200** [comment]
@SteMasoli : But in the notebook it says "completed"...

**Comment by SteMasoli** [comment]
I tested it on two different PCs, both linux and windows, and always stuck itself on "submitted" with no changes even after waiting for two hours. This was not the case back in May and June.
On my request, the usecase is now offline from the BSP.

**Comment by alex4200** [comment]
@SteMasoli: Yes, there is an issue with NSG itself currently. Maybe Carmen @clupascu  can comment  on it in the meeting in 5 minutes...

**Comment by antonelepfl** [comment]
By the request of @SteMasoli I removed this use case.
