### ISSUE TITLE
File not found error when forgetting to write config file

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#241]
### Expected behavior

When I forget to click on "write config file" (or when there is no config.txt available), the "Run NSG simulation" might be deactivated; or a message should pop up. ...

### Actual Behavior

I forgot to click on "write config file" and clicked on "Run NSG simulation" resulting in an error `No such file or directory: '/home/jovyan/GUIUM/config.txt'`

### Steps to reproduce the problem

1. Fill in the four tabs with all required parameters WITHOUT clicking on "Write config file"
2. Choose JURECA or NSG and log in
3. Click on "Run NSG simulation"

**Comment by clupascu** [comment]
This should be fixed. Can you test again please? Thanks.

**Comment by alex4200** [comment]
Yes done
