### ISSUE TITLE
Small image missing for Basal Ganglia use case

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#242]
The preview image in the use case group is missing:

![selection_268](https://user-images.githubusercontent.com/12729291/37658382-aec0a172-2c4d-11e8-8cf0-9ec45e3aad35.png)

**Comment by a1eko** [comment]
This use case is replaced with "Optimize a striatal fast-spiking interneuron" from [BSP / Online Use Cases / Single Cell Building](https://collab.humanbrainproject.eu/#/collab/1655/nav/66852).

Please remove the use case "Optimise a fast spiking interneuron in the Basal Ganglia".

**Comment by antonelepfl** [comment]
Done [here](https://github.com/antonelepfl/usecases/commit/1018c002c45d1b5334ad402c523758cf0bc9f3a5)

**Comment by alex4200** [comment]
Yes fixed, thanks
