### ISSUE TITLE
Other file problem

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#243]
In the notebook there is another error with a file:

![selection_270](https://user-images.githubusercontent.com/12729291/37699271-2258ddf4-2ce7-11e8-9eb3-afd22cd0304a.png)

It looks like that the downloading lines are wrong; the following lines seem to work:

```
model = client.download_file(bsp_folder+'functional_scaffold.py','functional_scaffold.py' )
params = client.download_file(bsp_folder+'scaffold_params.py','scaffold_params.py' )

file_pos_name = client.download_file(bsp_folder+'to_connectome.txt', 'to_connectome.txt')
```

**Comment by SelezioneCasuale** [comment]
There's something strange with this error; I and Elisa have no problems with the original download lines, they work just fine. 
Maybe we have different versions of `bbp-client` ? Could it be?
Mine is 0.4.4.  (and `bbp-services` is  0.0.15)
I checked this with 

`!pip3 list`

Could you please check if your version is different?

**Comment by elisamarenzi** [comment]
We are still working on this use case, see comment on the other issue (Job submission failed #244 ).
