### ISSUE TITLE
Unable to download files from the HBP Validation Framework app

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#245]
### Expected behavior

Able to download figs and results from the Validation Framework

### Actual Behavior

Clicking on the Download button does not result in any download (firefox and chrome)

![selection_272](https://user-images.githubusercontent.com/12729291/37702888-4694d7a6-2cf4-11e8-8a11-5c20f09b9838.png)

### Steps to reproduce the problem

- used "Hippocampus single cell validation"
- Selected model #40 
- Run the notebook until the end with the direct links to the  HBP Validation Framework app

### Optional infrastructural data (user, platform, browser, environment, ...)

FF, GC

**Comment by appukuttan-shailesh** [comment]
@alex4200 : Can you send me the UUID ('Test result ID') mentioned on the top of the page for your specific result.

**Comment by appukuttan-shailesh** [comment]
Resolved. Ready to be tested.

**Comment by alex4200** [comment]
Yes, fixed, thanks
