### ISSUE TITLE
Retrieve unicore jobs

### ISSUE THREAD

**Issue by clupascu** [cnr-ibf-pa/hbp-bsp-issues#246]
### Expected behavior
Retrieve and check status of unicore jobs and move output to storage in order to be analyzed 

### Actual Behavior
Unicore jobs cannot be retrieved once the config web page is closed.

**Comment by clupascu** [comment]
This is included now in the Synaptic Events Fitting use cases in the analysis jupyter notebook. The first tab of the accordion widget included in the graphical user interface displays the jobs submitted on HPC and the user can move to storage the results of the completed jobs. This should be tested.

**Comment by alex4200** [comment]
@clupascu Before that change I saw maybe one job. Now I have a very large list of results. How to know what is the one I just finished in the other notebook? I also did not submit jobs close to midnight....

**Comment by alex4200** [comment]
Ok this works fine basically. Please see related ticket #268
