### ISSUE TITLE
User Documentation for Validation use cases requires updates 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#249]
In the guidebook:

https://collab.humanbrainproject.eu/#/collab/1655/nav/18580

the validation use cases needs to be updated to the (currently) four cases in the brain simulation platform.

**Comment by appukuttan-shailesh** [comment]
This is done now:
https://github.com/lbologna/hbp-sp6-guidebook/pull/22

**Comment by lbologna** [comment]
Update on BSP.

Could you please check?

https://collab.humanbrainproject.eu/#/collab/1655/nav/18580

Thanks

**Comment by appukuttan-shailesh** [comment]
Thanks. It looks fine :+1:

**Comment by alex4200** [comment]
Very nice and very quick, thanks
