### ISSUE TITLE
Unable to copy NSG result to Storage for "Rebuild an existing single hippocampal cell model"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#25]
### Expected behavior

When the NSG job has finished in 'NSG Manager' I expect to be able to copy the result to the storage

### Actual Behavior

The job has finished, but I am not able to click on the big right arrow button to move the result to the storage. The mouse cursor changes to a 'unavailable' symbol:

![symbol](http://www.rw-designer.com/cursor-view/83769.png)

### Steps to reproduce the problem

Following the example, Related to #20 

### Optional infrastructural data (user, platform, browser, environment, ...)

Firefox

![selection_041](https://user-images.githubusercontent.com/12729291/31437366-516b5c1a-ae85-11e7-9dfc-cc770a38c15a.png)

**Comment by clupascu** [comment]
I fixed this. Can you test again please?
Thanks.

**Comment by alex4200** [comment]
@clupascu 

Now this arrow was clickable, but I get other multiple errors when clicking the arrow or the refresh button (do not remember the order). When I completely reload the notebook AFTER the job has completed, the copy to the storage works. 

Not sure if there was some 'hickup' before the job was finished, or something else, but here are the two errors I encountered before:

ValueError                                Traceback (most recent call last)
<ipython-input-3-95a36583fb01> in store(_)
     16 def store(_):
     17     global listtoprint, jobslistfile
---> 18     storage = collab_get_storage_client()
     19     hdr = get_bbp_client().task.oauth_client.get_auth_header()
     20     my_url = 'https://services.humanbrainproject.eu/idm/v1/api/user/me'

<ipython-input-3-5465b1808fc6> in collab_get_storage_client()
     11 
     12 def collab_get_storage_client():
---> 13     return desktop_get_storage_client(oauth.get_token())
     14 
     15 import hashlib

<ipython-input-3-5465b1808fc6> in desktop_get_storage_client(bearer_token)
      8 
      9 def desktop_get_storage_client(bearer_token):
---> 10     return Storage(bearer_token)
     11 
     12 def collab_get_storage_client():

<ipython-input-3-5465b1808fc6> in __init__(self, bearer_token)
     36     def __init__(self, bearer_token):
     37         sl = ServiceLocator.new()
---> 38         self.oidc_url = sl.get_service_url('user','v1')
     39         self.document_service_url = sl.get_service_url('document','v1')
     40         self.client = Client.new(bearer_token)

/home/jupyter/.local/lib/python2.7/site-packages/hbp_service_client/document_service/service_locator.pyc in get_service_url(self, service, version)
     38                 The URL where the service is located
     39         '''
---> 40         return self.__get_services()[service][version]
     41 
     42     def __get_services(self):

/home/jupyter/.local/lib/python2.7/site-packages/hbp_service_client/document_service/service_locator.pyc in __get_services(self)
     42     def __get_services(self):
     43         '''Wrapper function around requests'''
---> 44         return requests.get(self.__services_url).json()

/usr/local/lib/python2.7/dist-packages/requests/models.pyc in json(self, **kwargs)
    824                     # used.
    825                     pass
--> 826         return complexjson.loads(self.text, **kwargs)
    827 
    828     @property

/usr/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    336             parse_int is None and parse_float is None and
    337             parse_constant is None and object_pairs_hook is None and not kw):
--> 338         return _default_decoder.decode(s)
    339     if cls is None:
    340         cls = JSONDecoder

/usr/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
    364 
    365         """
--> 366         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    367         end = _w(s, end).end()
    368         if end != len(s):

/usr/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
    382             obj, end = self.scan_once(s, idx)
    383         except StopIteration:
--> 384             raise ValueError("No JSON object could be decoded")
    385         return obj, end

ValueError: No JSON object could be decoded

ERROR:jupyter_collab_storage.oauth_token_handler:Error in token refresh, return None (HTTP 502: Server Hangup)

---------------------------------------------------------------------------
DocForbiddenException                     Traceback (most recent call last)
<ipython-input-3-95a36583fb01> in store(_)
     22     global res
     23     res = requests.get(my_url, headers = headers2)
---> 24     if storage.exists(get_collab_storage_path() + os.path.sep + "listjobsNSG_"+res.json()['username']+".txt"):
     25         storage.download_file(get_collab_storage_path() + os.path.sep + "listjobsNSG_"+res.json()['username']+".txt", "listjobsNSG_"+res.json()['username']+".txt");
     26     with open("listjobsNSG_"+res.json()['username']+".txt") as f:

<ipython-input-1-e5c9216abc25> in get_collab_storage_path()
     12     else:
     13         list_method = client.storage.list_projects
---> 14     return '/{}'.format(list_method(collab_id=5469)['results'][0]['name'])

/home/jupyter/.local/lib/python2.7/site-packages/hbp_service_client/document_service/client.pyc in list_projects(self, hpc, access, name, collab_id, page_size, page, ordering)
    389         params = self._prep_params(locals())
    390 
--> 391         return self._requestor.send_and_return_body('GET', 'project', params=params)
    392 
    393     def get_project_details(self, project_id):

/home/jupyter/.local/lib/python2.7/site-packages/hbp_service_client/document_service/requestor.pyc in send_and_return_body(self, method, endpoint, headers, **kwargs)
     99 
    100         """
--> 101         resp = self.send(method, endpoint, headers, **kwargs)
    102 
    103         if resp.headers.get('Content-Type', None) == 'application/json':

/home/jupyter/.local/lib/python2.7/site-packages/hbp_service_client/document_service/requestor.pyc in send(self, method, endpoint, headers, **kwargs)
     69 
     70         if resp.status_code == requests.codes.forbidden:
---> 71             raise DocForbiddenException('You are forbidden to do this.')
     72 
     73         if resp.status_code == requests.codes.not_found:

DocForbiddenException: You are forbidden to do this.

**Comment by clupascu** [comment]
Can you try again everything from the beginning in a new collab with an empty storage? It should work. Please report only one error at a time. It was not clear to me what you have done. 

Thanks.

**Comment by alex4200** [comment]
I will redo the whole analysis tomorrow...

**Comment by alex4200** [comment]
Original error is fixed, thanks
