### ISSUE TITLE
Code error in notebook "Connectome Cerebellum"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#250]
### Expected behavior

Code does not fail

### Actual Behavior

In cell 4 the code fails probably because of an incorrect syntax:

![selection_275](https://user-images.githubusercontent.com/12729291/37714791-b46808ea-2d1a-11e8-9e39-eef6f1283b21.png)

Suggested fix:

client.download_file(bsp_folder+filename, filename)

Similar errors in the second-to-last cell...

### Steps to reproduce the problem

Just run the notebook

**Comment by SelezioneCasuale** [comment]
The issue should now be solved
