### ISSUE TITLE
Model load error for CA1 cNAC 970509HP2

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#254]
### Expected behavior

Model can be loaded

### Actual Behavior

"Model loading failed"

### Steps to reproduce the problem

On PROD select Single Cell In Silico Experiments (BlueNaaS) and select the model "CA1 cNAC 970509HP2"

![screen shot 2018-03-23 at 10 28 17](https://user-images.githubusercontent.com/12729291/37821917-4eae61a4-2e85-11e8-8ccd-c60b56f31cb5.png)

### Optional infrastructural data (user, platform, browser, environment, ...)

FF, PROD

**Comment by genric** [comment]
This model CA1_int_cNAC_970509HP2_20180117154753 in hoc file loads a different morphology 970627BHP1.asc which is not present in morphology folder. The one present in morphology folder is called 970509HP2.asc

**Comment by genric** [comment]
The model has been fixed, thanks! I resynced models in BlueNaaS, should work as expected now.

**Comment by clupascu** [comment]
@genric Are you using the container https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/hippocampus_optimization or github? In the near future github repository will be decomissioned.

**Comment by genric** [comment]
I'm using this repo to upload all the model to HBP Nexus.

**Comment by jdcourcol** [comment]
@clupascu ( I mentioned that during the technical meeting) be aware that we have:
1- HBP Knowledge Graph (nexus) and corresponding storage at CSCS. Entity registered in HBP KG should comply to one of the schema https://github.com/INCF/neuroshapes/tree/master/modules/simulation/src/main/resources/schemas/neurosciencegraph/simulation and stored in one of the dedicated CSCS storage
2- The GitHub bsp-data-repository (that will be decomissioned).
3- an instanciation of the bsp-data-repository in  the /hippocampus_optimization CSCS storage

I hope 3) will be migrated at some point to 1). Genrich is adding the "ME-Model" into it. what is in 3) is a bit more than a "ME-Model" as it contains the optimization and provenance information  which are not recorded into 1) as of now.

**Comment by clupascu** [comment]
@jdcourcol 2) will be decomissioned soon as we are reaching the quota imposed by github, so we will use 3) to store new optimizations until 1) is ready. The provenance information which is included in 2) and 3) are used by @wvangeit for the circuit and I think it is used also by @genric for the BlueNaas. This information should be stored in 1) as well, in order for the migration to be seamless for everyone.

**Comment by wvangeit** [comment]
I'm slightly worried about the period after 2) and between 3) and 1).
Is 2) a git (not github obviously) repo ?
BluePyMM requires as input a git repo to run hippocampus MM. And I assume @genric 's script to import into 1) also start from a git repo.
If 2) is not a git repo we would need to adapt the import methods during the 2) period.

**Comment by clupascu** [comment]
@wvangeit 2) is the usual git repo that everybody used (and I used too to run hippocampus MM). It is available on github (hence the size problem) at https://github.com/lbologna/bsp_data_repository

**Comment by wvangeit** [comment]
Sorry, I meant 3) in that last sentence ...

**Comment by genric** [comment]
Is it still broken? Please check the comment 11 days ago:
> The model has been fixed, thanks! I resynced models in BlueNaaS, should work as expected now.
