### ISSUE TITLE
SimUI Analysis Step: trace plot not created

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#255]
### Expected behavior

When the user selects the trace plot, it should be created

### Actual Behavior

trace plot not created; Analysis step shown as failed. 

Error in log:  libgomp: Thread creation failed: Resource temporarily unavailable 

![screen shot 2018-03-23 at 15 01 31](https://user-images.githubusercontent.com/12729291/37833234-1a172400-2eab-11e8-8149-d4c09efa1e18.png)

### Steps to reproduce the problem

- Start default siulation in JUQUEEN
- After finish, start analysis with all 3 plots
- Repeated this twice...

**Comment by antonelepfl** [comment]
@alex4200 this should be fixed now in [DEV](https://bbp.epfl.ch/public/dev.simulationapp/index.html#/)

**Comment by alex4200** [comment]
Does not seem to work. I get an error or not an error, but no traces plots. 

Examples of the log file:

```
 DEBUG:__main__:No configfile was passed. Using the default
DEBUG:__main__:analysis_config.json {u'number_of_cells': 5, u'report_analysis': u'slice-4_report_0', u'list_analysis': [u'voltage_collage'], u'target_analysis': u'slice-4'}
DEBUG:__main__:BlueConfig: ./blueconfig.json
DEBUG:__main__:Output image path: .
DEBUG:__main__:Output root: /work/unicore_jureca/42374f92-0a56-4f11-a67b-7e96c22a5476
WARNING:bluepy_configfile.configfile:Invalid absolute path: /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b
WARNING:bluepy_configfile.configfile:Invalid absolute path: /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b/S2F
WARNING:bluepy_configfile.configfile:Invalid absolute path: /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b/MorphologyRelease/07_h5v1
WARNING:bluepy_configfile.configfile:Invalid absolute path: /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b/ccells
WARNING:bluepy_configfile.configfile:Invalid absolute path: /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b/user.target
DEBUG:__main__:kwargs: {'sample': 5, 'group': u'slice-4'} 
```

and in another case:

```

No log available
Job failed before script was executed 
```

**Comment by antonelepfl** [comment]
Let's have a look tomorrow.

**Comment by antonelepfl** [comment]
@alex4200 Can we close this?

**Comment by alex4200** [comment]
Seems to work...
