### ISSUE TITLE
Notebook user documentation inconsistent

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#256]
The documentation in the notebook for the use cases "Rebuild Single HippoCell" and " Build your own single hippocampal cell model using HBP data" is inconsistent!

It says: "Run All cells at the beginning", but that is wrong! The user must run some cells by its own in order to see of an update/downgrade is required. When the user runs all the cells, the notebook fails and the user might be confused of what to do. 

I suggest to split the notbook into two parts: 

1. Step-by-step part which checks for compatibility of the used packages
2. Runn-all part creating the notebook-GUI

**Comment by clupascu** [comment]
@alex4200 are you sure that when the user runs all the cells the notebook fails? It shouldn't fail. The user should run all cells at the beginning. If upgrade/downgrade is necessary, this is done in the first cells automatically and the kernel is restarted, before running all the cells, hence the notebook shouldn't fail.

**Comment by alex4200** [comment]
@clupascu Hm ok I see. Let me check that again. 

I had some automated tests failing - could be that those tests could not handle the restart at all...

**Comment by alex4200** [comment]
Yes, maybe the installations are being done automatically and the page is loaded anew. But then the user still has to click on the 'Run All' again. Is that correct?

**Comment by clupascu** [comment]
Of course. The user still has to click on the "Run All" again.

**Comment by alex4200** [comment]
Ok, then its ok usability wise. I might need to adjust my test cases then ...
