### ISSUE TITLE
500 error for Analysis stage for "Rebuild an existing single hippocampal cell model" 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#26]
### Expected behavior

I am able to view the analysis from the Storage. 

### Actual Behavior

I get a 500 Internal server error (see screenshot). Using files from GitHub works.

### Steps to reproduce the problem

Run the complete analysis, and in the last notebook 'BluePyOpt Analysis' select 'Storage' and wait until the graph shows up and the button 'View analysis' becomes clickable. Then click on this button

![selection_042](https://user-images.githubusercontent.com/12729291/31497909-c1792fd8-af60-11e7-8afb-ae0ec92e3e2b.png)

**Comment by clupascu** [comment]
Can you add me as a member of this collab so that I can take a look at the storage?

**Comment by alex4200** [comment]
@clupascu  Added you to collaboration "Restest25b"

**Comment by clupascu** [comment]
I checked out the storage. The checkpoints folder inside the output.tar.gz file is empty. I am thinking now on how to give a feedback to the user in this case.

**Comment by clupascu** [comment]
I added feedback when the checkpoints folder is empty. Can you please test again?
Thanks.

**Comment by alex4200** [comment]
Solved
