### ISSUE TITLE
Documentation for "Synaptic Events Fitting"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#260]
Although the use case "Synaptic Events Fitting" is disabled, there is still a section in the Guidebook describing it. 

Can this section be 'disabled' as well?

**Comment by clupascu** [comment]
The use case is enabled again, so the section in the Guidebook describing it shouldn't be removed anymore. I close this issue.

**Comment by alex4200** [comment]
Agreed
