### ISSUE TITLE
wrong location for a "Hippocampus single cell validation" collab

### ISSUE THREAD

**Issue by mmigliore** [cnr-ibf-pa/hbp-bsp-issues#264]
### Expected behavior
the collab is created in a user's space following one of the links listed in the "Online Use Cases" --> "Model Validation" group
### Actual Behavior
one instance of the collab is present in the main navigation menu
### Steps to reproduce the problem
go to the Brain Simulation Platform; the link appears as last item in the main navigation menu.

**Comment by alex4200** [comment]
Entry removed from main navigation...
