### ISSUE TITLE
Analysis notebook change for SynapticEventsFitting

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#268]
New Analysis notebooks require: 

 - [x] User documentation update required to explain the new GUI to the user
 - [x] Notebook documentation update required to show the timestamp to the user and have the user remember it for the Analysis step
 - [x] Make sure that in either case (NSG, Jureca) the correct (European) time is shown
 - [x] Documentation in the Analysis notebook:

The user has three choices to view analysis results:

A. Use the results that are available in the Storage (e.g. created by the notebook in the same Collab)
B. Use one of the github examples
C. Use some other results from NSG/JURECA. 

For choice 'A': User must click "View Analysis"
For choice 'B': User must click "View Analysis"
For choice 'C': User must click "View simulations" first, then use choice 'A'.

That must be made clear and explicit in the Analysis notebook!

Without such explanations I always thought I have to run the "View simulations" step before executing the "View analysis" step (for the analysis done in the same Collab), without realizing the data I need are ALREADY in the storage. I can skip the first step "View simulations" alltogether! No need to wait for all the simulations to be loaded - I can go directly with "View analysis"! (for choice 'A').

**Comment by clupascu** [comment]
The user has two choices to view analysis results:

A. Use the results that are available in the Storage (e.g. moved from the HPC storage space to the Storage, when the user is checking the status of the job in the 'config' notebook OR moved from the HPC storage space to the Storage, when the user is viewing the simulations in the first tab of this notebook)

B. Use one example

You don't have necessary to run the "View simulations" step before executing the "View analysis" step. In fact, the data you need might be ALREADY in the storage. You can skip indeed the first step "View simulations" alltogether! No need to wait for all the simulations to be viewed - you can go directly with "View analysis"!

If you need to analyse some data that is not already in the storage you have to go first to 'view simulations', move the data from the HPC storage space to the Storage and then 'view analysis'.

I will explain this better in the Guidebook. If you think I have to insert some markdown text directly in the notebooks, please let me know. Thanks.

**Comment by clupascu** [comment]
ok.

**Comment by clupascu** [comment]
I updated the documentation to explain the new GUI to the user.  I updated the notebook documentation to show the timestamp to the user and have the user remember it for the Analysis step. I converted NSG submission time to CET time. I included also a short explanation in the notebook itself too in order to make it more clear that if the user wants to view analysis of simulations that are already in the storage of the Collab, he or she may skip the 'View simulations' tab and may go directly to the 'View analysis' tab. 
Can you please check? Thanks.

**Comment by clupascu** [comment]
I fixed the small typo on the Analysis notebook.

**Comment by alex4200** [comment]
Screenshot: 

![selection_298](https://user-images.githubusercontent.com/12729291/39130478-74cc059e-470d-11e8-869f-277d4c6fdf90.png)

Collab: Dev26 (I have added you...)

**Comment by clupascu** [comment]
The name of the folder does not contain date/time information. The date/time information is printed next to the status of the job in the config notebook (when the user checks the status of the job) or it is printed when the user fetch the list of the jobs submitted through an HPC system in the analysis notebook. In the job you submitted, the name of the job (TestJob Data) should be enough to retrieve the job you are searching for).

**Comment by alex4200** [comment]
Ok thanks, makes sense. Case closed...
