### ISSUE TITLE
OSError when Saving again in "Rebuild an existing single hippocampal cell model"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#27]
### Expected behavior

I can change the parameters for the simulation even after I have clicked on "Create zip file".

### Actual Behaviour

Once I save the new parameters and create the zip file, clicking on "save new parameters" results in the following error:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-18-b02a92922ebc> in saveparamfile(_)
     49 def saveparamfile(_):
     50     os.chdir(foldernameOPTstring)
---> 51     os.chdir(foldernameOPTstring)
     52     os.chdir('config')
     53     with open('parameters.json','w') as f:

OSError: [Errno 2] No such file or directory: 'CA1_int_bAC_011017HP2_20170510120000'

### Steps to reproduce the problem

- Start "BluePyOpt One" job  
- Click on "Save new parameters"
- Click on "Create zip file"
- Click on "Save new parameters again"

### Optional infrastructural data (user, platform, browser, environment, ...)

FF or GC

![screen shot 2017-10-13 at 10 20 48](https://user-images.githubusercontent.com/12729291/31538625-77ac7062-b006-11e7-8714-dffa1563f99f.png)

**Comment by clupascu** [comment]
I disabled the buttons after you clicked once to prevent mistaken clicks. Test again please.
Thanks.

**Comment by alex4200** [comment]
@clupascu : Ok seem to work, thanks.
