### ISSUE TITLE
List of saved workflows duplicated in HH use case

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#270]
### Expected behavior

When I repeatedly click on the button "Select a completed/ongoing workflow" I get a correct list of saved workflows from the Collab.
        
### Actual Behavior

I get a list of saved workflows, in which the entries repeat. First time click: All fine. Second time click: Entries are repeated over...

![selection_284](https://user-images.githubusercontent.com/12729291/38542516-54fda418-3ca2-11e8-9354-1ff09f7468c6.png)

### Steps to reproduce the problem

1. Create a workflow and save it
2. Create another workflow and save it
3. Then go to 'Home', click on "Select a completed/ongoing workflow" and "Cancel"
4. Repeat step 3

**Comment by lbologna** [comment]
This should be fixed.
Could you please test again?
Thanks

**Comment by alex4200** [comment]
Done...
