### ISSUE TITLE
Unclear user messages for HH use case

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#271]
Sometimes the download of a job results in an unclear message (in the step "Fetch results")

![selection_286](https://user-images.githubusercontent.com/12729291/38542433-23a6ed84-3ca2-11e8-8e15-31358952ec47.png)
![selection_287](https://user-images.githubusercontent.com/12729291/38542441-25dd458a-3ca2-11e8-973f-5d715c7d1858.png)

How to reproduce: Unknown.

**Comment by lbologna** [comment]
This should be fixed (no more "undefined" message) and more explicative message when the optimization gave no result.
Could you please check again?
Thanks

**Comment by alex4200** [comment]
Thanks; tested some cases and so far only well-explained error messages...
