### ISSUE TITLE
Voxcellview issues in Cell Placement Hippocampus notebook

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#272]
I noticed two issues with the Voxcell widget in the Cell Placement Hippocampus notebook:

1. When you just do "Run All Cells" you might end up with an 'empty' plot:

![selection_289](https://user-images.githubusercontent.com/12729291/38553994-472d0bac-3cc1-11e8-82cb-7521fd170599.png)

2. If the plots are generated, they are rather small. I would prefer to enlarge them and rotate/zoom etc. but I do not see any option to do so...

3. Also if I increase the size of the points I see they are not points. Just a black square image of a circle?

![selection_290](https://user-images.githubusercontent.com/12729291/38554127-b25a1f32-3cc1-11e8-9741-bcaa0cc0bbf5.png)

**Comment by alex4200** [comment]
I will move this to SGA2 ...

**Comment by jdcourcol** [comment]
@alex4200 can we please split that in 3 tickets ?
@antonelepfl can you investigate if the widgets infrastructure is more reliable these days ? The question is should keep that architecture or move to something else ?

**Comment by alex4200** [comment]
Split into three separate tickets: #338 #339 #340
