### ISSUE TITLE
Synaptic Events Fitting Analysis cannot be started

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#274]
### Expected behavior

I can select an storage entry and then some analysis results (Synaptic Events Fitting Analysis with user data)

### Actual Behavior

I can select an storage entry, but do not see the buttons for the analysis results. When using 'example' instead it seems to work

![screen shot 2018-04-11 at 13 21 42](https://user-images.githubusercontent.com/12729291/38613835-72a81f18-3d8b-11e8-8441-e3a74ba7fbab.png)

### Steps to reproduce the problem

Run an example and open the notebook; Collab 'Dev31'

### Optional infrastructural data (user, platform, browser, environment, ...)

DEV

**Comment by clupascu** [comment]
Strange. I can see the buttons for the analysis results in Collab 'Dev31'.
![immagine11042018](https://user-images.githubusercontent.com/22050958/38617770-21714360-3d98-11e8-8f9c-b5b0d0b8e5dc.png)

**Comment by alex4200** [comment]
Tried it again on firefox and chrome, the problem persists. 

I also encountered an additional issue with chrome:

![screen shot 2018-04-11 at 15 42 49](https://user-images.githubusercontent.com/12729291/38620595-1cc938d4-3d9f-11e8-88db-e73966d793e5.png)

**Comment by clupascu** [comment]
Also on chrome it works fine for me...

**Comment by alex4200** [comment]
@clupascu: Oh the kernel is active all the time. I did not see this! It takes the kernel about 10 seconds(!) to register the change. Then the buttons appear.

I close this ticket....
