### ISSUE TITLE
Multiple occurrences of jobs in 'Fetch list'

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#276]
### Expected behavior

To see one job only once

### Actual Behavior

When I try to download a job which gives no results and click on 'Fetch results'  again to try to download a different file, the entries appear twice. 

In the following example I got a 'no output' twice and clicked on 'Fetch results'  three times. Hence all entries are seen three times...

![selection_296](https://user-images.githubusercontent.com/12729291/39124870-5016b4e8-46fd-11e8-9b98-6fb389fd434c.png)

### Steps to reproduce the problem

1. Some workflow
2. Need to  'Fetch results' from a job that did not create results
3. Fetch again

**Comment by lbologna** [comment]
This should be fixed. Could you please test again?
Thank you.

**Comment by alex4200** [comment]
Done, thanks
