### ISSUE TITLE
Some models seem to miss an image

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#277]
### Expected behavior

When opening  a model from the model catalog such as https://collab.humanbrainproject.eu/#/collab/1655/nav/75901
I expect to see the morphology image (when applicable).

### Actual Behavior

For some models like CA1_pyr_cACpyr_oh140807_A0_idG_20170915113354 the image seems to be broken:

![selection_300](https://user-images.githubusercontent.com/12729291/39132032-2be20b22-4711-11e8-9aae-dbefe16b615c.png)

### Steps to reproduce the problem

- Go to model catalog
- Select the mentioned model

**Comment by appukuttan-shailesh** [comment]
@alex4200 : fixed now

**Comment by alex4200** [comment]
Seems to be fixed, thanks
