### ISSUE TITLE
JURECA simulation does not work for SynapticEvents Fitting

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#279]
### Expected behavior

When selecting JURECA and pressing "Run JURECA simulation" something should happen (i.e. JOB submitted, no access etc.)

### Actual Behavior

Nothing visible happens

![selection_307](https://user-images.githubusercontent.com/12729291/39509378-65402daa-4de6-11e8-8a59-f8608bb50a5a.png)

### Steps to reproduce the problem

- Run all Cells
- Select the first exp. data set
- Fill out boxes as shown

### Optional infrastructural data (user, platform, browser, environment, ...)

- PROD environment
- The test user does NOT have a JURECA account.

**Comment by clupascu** [comment]
Can you add me as a team member of the collab? Thanks.

**Comment by clupascu** [comment]
For me it works. The job is submitted and the final status is successfull
![immagine02052018](https://user-images.githubusercontent.com/22050958/39513188-cfd3b076-4df3-11e8-9e92-16b940c541ee.png)
You can check in the storage of the collab you shared. Everything is saved there.

**Comment by alex4200** [comment]
@clupascu : I was using a different HBP user. 

Normally, I am using user 'adietz' and vsk2513, then it works for me too. 
But now I used an user 'alextestuser002' and vsk2513, and nothing happens when I click on the button. 

For the review this is probably without consequences as they all will have their access anyway...

**Comment by clupascu** [comment]
@alex4200:  Is 'alextestuser002' enabled to submit jobs with vsk2513 account?

**Comment by alex4200** [comment]
@clupascu No. But I would expect some error message in that case or something...

**Comment by clupascu** [comment]
Can you execute this 

auth = get_oidc_auth() 
base_url = get_sites()['JURECA']['url']
role=get_properties(base_url, auth)['client']['role']['selected']

with 'alextestuse002' and tell me what role is?

When I try with my HBP user and a wrong Jureca account I get the message 'This account is not enabled to submit jobs on JURECA'.

**Comment by alex4200** [comment]
The output is 'anonymous'.

**Comment by alex4200** [comment]
@clupascu : For the use cases with user data/user model I get a correct error message: "This account is not enabled to submit jobs on JURECA" But not for the basic "Synaptic Events Fitting" use case. Did you forget to update that use case?

**Comment by clupascu** [comment]
I see the comment in the code also for the basic "Synaptic Events Fitting". Are you sure you cloned the last version of the code?

**Comment by alex4200** [comment]
@clupascu When I checked the notebooks I saw there is a NEW version available for the following use cases:

- Synaptic events fitting with user model
- Synaptic events fitting with user data

but not for the use case

- Synaptic events fitting

**Comment by alex4200** [comment]
Works fine...
