### ISSUE TITLE
 "Synaptic Events Fitting": Unable to select NIP data

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#28]
### Expected behavior

When starting the use case I expect to see the selectable experimental data.

### Actual Behavior

The description of the experimental data is too log to be shown in the browser window, vanishing into the right side of the collaboratory framework. I cannot read the complete description, see screenshot.

Workaround: Leave full-screen mode, shift browser window to the left, extend browser window to the right

### Steps to reproduce the problem

Open the "Synaptic Events Fitting" and click on "Run All".

### Optional infrastructural data (user, platform, browser, environment, ...)

FF and GC on MacBook Air

![screen shot 2017-10-13 at 14 05 39](https://user-images.githubusercontent.com/12729291/31545667-ab2d4cf8-b020-11e7-9069-e5b22c85bc4a.png)

**Comment by clupascu** [comment]
The browser window and the jupyter notebook frame should be maximized.

**Comment by alex4200** [comment]
@clupascu Although I selected the notebook and the frame and maximized it, I still cannot see some of the data:

![selection_056](https://user-images.githubusercontent.com/12729291/31981746-6f13581e-b955-11e7-919f-80733d9a76c6.png)

**Comment by alex4200** [comment]
Unable to reproduce this issue...
