### ISSUE TITLE
Widgets not shown on Cerebellum placement use case

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#280]
### Expected behavior

Dropdown box correctly shown

### Actual Behavior

Not shown, also no javascript error:

![selection_310](https://user-images.githubusercontent.com/12729291/39522041-4dbed3cc-4e11-11e8-8aa0-793e5f2e80ba.png)

### Steps to reproduce the problem

Unsure. I had the container for that test user just reset the day before. But some other use case must interfere with the settings. 

SUGGESTION: Do not use the widgets at all, just let the user select the options like follows:

save_on = True
plot_on = False
netsize = 300

### Optional infrastructural data (user, platform, browser, environment, ...)

PROD environment

**Comment by SelezioneCasuale** [comment]
This should now be fixed; I simply followed yout suggestion

**Comment by alex4200** [comment]
Thanks, seems to work...
