### ISSUE TITLE
Previous output visible in Connectome Cerebellum use case

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#281]
### Expected behavior

When I clone the notebook I expect to see no output

### Actual Behavior

But I can see old output of a freshly cloned notebook:

![selection_311](https://user-images.githubusercontent.com/12729291/39522630-224bdde6-4e13-11e8-8842-fbd443adc689.png)

### Steps to reproduce the problem

Just clone the notebook from DEV

### Optional infrastructural data (user, platform, browser, environment, ...)

DEV environment

**Comment by SelezioneCasuale** [comment]
Now should work; I redirect the output to .txt file, so it is not displayed on screen
