### ISSUE TITLE
Unable to upload changed files to HH Cell Optimization Workflow

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#284]
MINOR issue! Therefore for SGA2

### Expected behavior

I want to be able to clone a workflow after I have launched an optimization, change a file, and launch a different optimization.

### Actual Behavior

After I have cloned the workflow I can delete one of the files, but cannot upload a new one. 

Workaround: Go to Home, select that workflow again. Then you are able to upload files again...

### Steps to reproduce the problem

1. Create a new workflow
2. In "Cell Optimization": Select files for each step, choose HPC system
3. Click on "Launch optimization"
4. Clone the workflow
5. Delete Optimization file or Feature extraction file

### Optional infrastructural data (user, platform, browser, environment, ...)

PROD, GoogleChrome

**Comment by lbologna** [comment]
This had been already fixed in dev and now uploaded to prod.
Could you please test again?

Thanks

**Comment by alex4200** [comment]
Yes seems to work, thanks...
