### ISSUE TITLE
Negative numbers for HPC parameters (HH use case)

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#285]
### Expected behavior

Unable to choose negative values for some HPC parameters

### Actual Behavior

However, its possible:

![selection_313](https://user-images.githubusercontent.com/12729291/39687625-977d8686-51cf-11e8-95c3-1820a55a6531.png)

**Comment by lbologna** [comment]
This should be fixed. Could you please test again?

Thanks.

**Comment by alex4200** [comment]
Yes, fixed; thanks
