### ISSUE TITLE
Performance in Model Catalogs.

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#287]
### Expected behavior

Model Catalog to be faster OR models to be selected by right-clicking etc.

### Actual Behavior

1. When you load the model catalog it takes 18 seconds to load. 
2. Also, I cannot just select a model and go back to select a different 
model. It takes to long also. And I cannot right-click on a model to 
open it in a different tab. 

Shailesh: 
1.  We are working on ways to reduce the load time. The 
large number of additions to the model catalog in recent times is 
causing this delay. Shall let you know if we find a quick fix.

2. We are working on a solution. Adding an option right-click 
and open in new tab should be relatively easy. I shall keep you posted 
on this.

**Comment by appukuttan-shailesh** [comment]
Right-click feature implemented on our local server and the changes shall be available for everyone soon (in a day or two).

p.s. Reducing the load time will need longer to fix.

**Comment by pedroernesto** [comment]
Well, right-click functionality is ready. But reducing loading-time, as decided, will be done later.

**Comment by alex4200** [comment]
Yes works fine, thanks

**Comment by jdcourcol** [comment]
We should create another ticket for that as "feature" and put it for SGA2 milestone

**Comment by alex4200** [comment]
see #304
