### ISSUE TITLE
Workflow saving behavior for HH use case

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#288]
I am not sure what the expected behavior is, but here is what I have observed: 

1. I did some testing of the use case in a Collab 'p233', including saving some workflows. They all show up in the Collab's storage

![selection_316](https://user-images.githubusercontent.com/12729291/39700299-f4c4b10c-51fc-11e8-84a9-dc64b8c999b3.png)

2. I wanted to test something else and created Collab 'p235' - and also saved a workflow in the regarding the HH use case. 

3. Later, I went back to Collab 'p233', and tried to fetch a list of the workflows. Now, the workflows stored in 'p235' are shown, but NOT the original workflows I stored in Collab 'p233' in step 1

![selection_317](https://user-images.githubusercontent.com/12729291/39702038-afcb1d82-5203-11e8-9a46-a3be340fbb05.png)

4. I expected to see the workflows of the Collab I am in, or all workflows. But not the workflows of a different Collab...

**Comment by alex4200** [comment]
Update available today or tomorrow (14/15 May)

**Comment by lbologna** [comment]
This should be fixed. Could you please test again?
Thanks

**Comment by alex4200** [comment]
Yes seems to work now...
