### ISSUE TITLE
"Synaptic Events Fitting": Text box too small

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#29]
### Expected behavior

Text fits in box, or box is large enough for the text

### Actual Behavior

Text overlaps the text box

### Steps to reproduce the problem

Just follow the use case in google chrome. Firefox it works fine.

![screen shot 2017-10-13 at 14 22 42](https://user-images.githubusercontent.com/12729291/31546113-490cb21e-b022-11e7-9242-51d77ba85c78.png)

**Comment by clupascu** [comment]
I checked this and when the jupyter notebook frame is maximized it works fine. We should specify in the guidebook that the graphical user interface is better displayed with the jupyter notebook frame maximized and with the web browser window maximized too.

**Comment by alex4200** [comment]
@clupascu  Although I selected the notebook frame and maximized it on my screen I still cannot see the whole text for some data: 

![selection_056](https://user-images.githubusercontent.com/12729291/31981703-3ee1efc0-b955-11e7-8483-f9f8cf724df0.png)

**Comment by alex4200** [comment]
Ok so far. We need to mention to maximise the notebook somewhere else...
