### ISSUE TITLE
"Issues" section in BSP not updated

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#290]
The "Issues" section in the BSP is still the old version:

![selection_319](https://user-images.githubusercontent.com/12729291/39981247-0d5b801c-5750-11e8-88cf-8427065b0e82.png)

**Comment by antonelepfl** [comment]
@alex4200 I did that change [BSP](https://collab.humanbrainproject.eu/#/collab/1655/nav/41698)
