### ISSUE TITLE
Link broken in 'Models' section and SGA1 Review Collab

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#292]
* Page "Molecular Models": 
  * The link to webSDA (https://mcm.h-its.org/WebSDA) seems to be broken

* Page on SGA1 Review Collab: https://collab.humanbrainproject.eu/#/collab/9510/nav/84858
  * Link to Product 6 broken

**Comment by antonelepfl** [comment]
@alex4200 Could please check that?

**Comment by apdavison** [comment]
Hi @alex4200, I'm not sure why you assigned me and @appukuttan-shailesh to this. Neither of us has anything to do with WebSDA or the In silico experimentation lab.

**Comment by alex4200** [comment]
@apdavison Any idea who is responsible for this webpage?

**Comment by apdavison** [comment]
The "WebSDA" link is actually fixed on the Molecular Models page, just not in this ticket. It should be https://mcm.h-its.org/webSDA (needs lower-case "w")

**Comment by apdavison** [comment]
ok, I've fixed the Product 6 link as well, it was just a mangled URL.
