### ISSUE TITLE
Coloring by mtype rebders the screen unusable

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#294]
When I select 'mtype' for coloring the neurons on the initial screen, I get an unusable screen:

![screen shot 2018-05-17 at 11 11 31](https://user-images.githubusercontent.com/12729291/40168220-3ca2c644-59c3-11e8-8914-ac45ba21b574.png)

If there are so many mtypes anyway with so many similar colors - does it make sense to color the neurons by mtype in the first way?

**Comment by pgetta** [comment]
I've limited `Color by` control to use only cell properties, where there are no more then 20 unique values. Looks like it's not that necessary to have coloring by mtype.
