### ISSUE TITLE
Unable to see any synapses

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#296]
I selected gid:18087 as the starting cell and gid:20643 as an afferent cell, but the next screen does not seem to show any synapses. I have activated 'synapses visible' as seen in the screenshot...

![screen shot 2018-05-17 at 12 04 09](https://user-images.githubusercontent.com/12729291/40171038-7b7e8446-59ca-11e8-89c0-214d463f1a70.png)

**Comment by jdcourcol** [comment]
it is unclear too if we have to put something into prop / value field to make synapse visible

**Comment by pgetta** [comment]
Some UI changes have been implemented to make interaction with synaptic input control more straightforward:
* Now component will show poptips with short guides what needs to be filled.
* Synapses visibility toggle is disabled and greyed out while component don't have all necessary information

@alex4200 could you please evaluate this?
Any ideas on how this control can be improved even further would be highly appreciated.

**Comment by alex4200** [comment]
Much better thanks
