### ISSUE TITLE
in context "add stimulus | add report

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#297]
### Expected behavior
In simulation config, click on a segment. One should see the tooltip with button to add a stimulus or a report
### Actual Behavior
no tool tip shows up.
### Steps to reproduce the problem
select 2 neurons, go to simulation config, click on a neurite.
### Optional infrastructural data (user, platform, browser, environment, ...)
Firefox, MacOS

**Comment by pgetta** [comment]
Should be fixed now.

**Comment by alex4200** [comment]
Yes, fixed on Firefox and Chrome
