### ISSUE TITLE
Marker does vanish

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#298]
It seem to happen that the marker of a selected item (i.e. soma) vanishes. In this case I probably just selected two neutrons, changes to the "Simulation config" screen, made the selection, went back to the "Circuit" screen and back again to  "Simulation config" screen

![screen shot 2018-05-17 at 12 09 24](https://user-images.githubusercontent.com/12729291/40171391-682d124e-59cb-11e8-883d-23eb2f6bfe7e.png)

**Comment by jdcourcol** [comment]
> selected two neutrons
I assume it is in a past life @alex4200  ?

**Comment by alex4200** [comment]
I meant neurons, ha...

**Comment by pgetta** [comment]
Should be fixed now. Could you please test?

**Comment by alex4200** [comment]
Yes seems to be fixed...
