### ISSUE TITLE
Section naming in the BSP Collab inconsistent

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#3]
Looking at the sections provided on the left hand side of the collab I see the naming 

- inconcisely named (there is a link named 'Links to ...')
- the reading flow is somewhat not nice ('Online use cases' folder and 'model collabs' folder interrupted by 'Highly Integrated workflows'. 

The left panel should be made more uniform. Suggestion: 

```
   Overview
   Guidebook
> Online Use Cases
    - Trace Analysis
    -  ...
    - Online Courses
    - Highly Integrated Workflows
> Model Collabs
   - ...
   - ...
> Open Source Tools
   - ...
   - ...
> News and Activities
   - News
   - Community Activities
   - Dashboard
> About Us
   - Who we are
   - Publications
   - Acknowledgements
 Settings  
 Storage
 Contacts
```

I see the following advantages:

- Fewer Top Level menus
- Shorter Top Level names
- Expandable menus all appearing together 
- Maybe the defunct 'issues' menu can be incorporated into the 'Contacts' menu?

**Comment by mmigliore** [comment]
ok, I agree. Please proceed to change the main menu.

**Comment by antonelepfl** [comment]
@alex4200 Could you please check this? https://collab.humanbrainproject.eu/#/collab/1655/nav/28538

**Comment by alex4200** [comment]
Yes looks fine to me
