### ISSUE TITLE
Mouse input too sensitive for neuron selection

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#300]
### Expected behavior

Selecting a cell by clicking on it

### Actual Behavior

A mouse click might be interpreted as a movement and not as a click. 

### Optional infrastructural data (user, platform, browser, environment, ...)

MacBook Air with Chrome, wireless mouse.

**Comment by pgetta** [comment]
Does this issue still exist, @alex4200 ?

**Comment by alex4200** [comment]
I tried with a different mouse, and it works much better. Seems my wireless mouse is not the best one. Case closed.
