### ISSUE TITLE
Tags in small screen were overlapping

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#301]
### Expected behavior
The tags on the Use Cases do not overlap.
![screen shot 2018-05-22 at 11 19 18](https://user-images.githubusercontent.com/24406041/40353530-02be11d4-5db2-11e8-8ea8-d04be081dd52.png)

### Actual Behavior
In some screen sizes the tags are overlapping.
![screen shot 2018-05-22 at 11 19 54](https://user-images.githubusercontent.com/24406041/40353595-2c276458-5db2-11e8-8a90-a7b848b4e4cf.png)

### Steps to reproduce the problem
Resize the page size.

**Comment by antonelepfl** [comment]
@alex4200 could you please check that on [DEV](https://collab.humanbrainproject.eu/#/collab/8444/nav/65633)?

**Comment by alex4200** [comment]
@antonelepfl   Seems to be fine on DEV
