### ISSUE TITLE
Removing a recording does not work

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#303]
### Expected behavior

After I have done a simulation, I want to remove a recording, change something and simulate again. 

### Actual Behavior

The removed recording still shows up in the 'Traces' section

### Steps to reproduce the problem

1. Select a setup with two soma
2. Select the two somas for recording 
3. Run Simulation -> Two traces
4. In the tab 'Recordings' remove one of the soma recordings
5. Run Simulation again: Still the traces from the two soma present

**Comment by pgetta** [comment]
Just tried, works as expected. Could you please test this again, @alex4200 ?

**Comment by alex4200** [comment]
Yes that seems to be working...
