### ISSUE TITLE
 Performance loading the Model Catalogs. 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#304]
### Expected behavior

Model Catalog should load faster 

### Actual Behavior

When you load the model catalog it takes 18 seconds or longer to load.

From ticket #287

**Comment by appukuttan-shailesh** [comment]
This has now been resolved... load time less than 5 seconds.

**Comment by alex4200** [comment]
Yes much better now, thanks..
