### ISSUE TITLE
Test in Simulation Launcher V0.0.4

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#305]
## Things to be checked
- [x] Show Unicore Logs
- [x] When load a file like Stderr a spinner should appear and then the text and the Download button
- [x] Get reports in analysis launch form
- [x] List of jobs are loaded correctly
- [ ] Launch analysis form: the tips (blue window) should only be visible if we are running analysis from a different computer than Jureca
- [x] Delete Job
- [x] Delete Analysis
- [x] State icons in analysis have to show an icon associated
- [x] JUQUEEN needs to be taken out of the list (because decommissioned)
- [ ] Reload link in Simulation Details does a reload. Not sure it does now.

**Comment by antonelepfl** [comment]
I have deployed the latest version.
I removed Juqueen and I aligned the analysis (it looks weird but to compare I think is better)
Let me know if you find something else that you want to improve.

**Comment by alex4200** [comment]
One of the remaining items is not valid anymore; the other one will not be fixed as a new version of the application is in development (and its not a major issue). Therefore closing this ticket
