### ISSUE TITLE
First prototype of subcellular experiment

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#307]
This first prototype will have the following steps:
neuron selection -> synapse selection -> protein selection.

Further steps will be implemented in a different ticket

**Comment by alex4200** [comment]
@jdcourcol @pgetta : Can you please update the proper milestone for SGA2 (M06, M12 etc)?

Thanks

**Comment by alex4200** [comment]
Duplicate of #327
