### ISSUE TITLE
TypeError when using 'Storage' data in "Synaptic events fitting"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#31]
### Expected behavior

See the results table of the finished simulation

### Actual Behavior

Python error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-11-e2f0e7a7b364> in tabledata(_)
    156         if storage.exists(get_collab_storage_path()+os.sep+'resultsNSG')==True:
    157             if storage.exists(get_collab_storage_path()+os.sep+'resultsNSG'+os.sep+SF.value)==True:
--> 158                 storage.download_file(get_collab_storage_path()+os.sep+'resultsNSG'+os.sep+SF.value+os.sep+myboxRB.children[0].value,myboxRB.children[0].value)
    159                 storage.download_file(get_collab_storage_path()+os.sep+'resultsNSG'+os.sep+SF.value+os.sep+myboxRB.children[1].value,myboxRB.children[1].value)
    160                 storage.download_file(get_collab_storage_path()+os.sep+'resultsNSG'+os.sep+SF.value+os.sep+myboxRB.children[2].value,myboxRB.children[2].value)

TypeError: coercing to Unicode: need string or buffer, NoneType found
```

### Steps to reproduce the problem

Select a model, choose the 'demo' trace, start the simulation until it has finished. Then choose "Select data" from storage and select "Result table"

### Optional infrastructural data (user, platform, browser, environment, ...)

FF

![selection_043](https://user-images.githubusercontent.com/12729291/31599322-33a683fa-b252-11e7-9972-4d31f8300c4c.png)

**Comment by clupascu** [comment]
Can you add me as a team member of this collab? I have to take a look at the storage. 
Thanks.

**Comment by alex4200** [comment]
@clupascu : I invited you to collab Retest31a

**Comment by clupascu** [comment]
I fixed this. Can you please test again in a new collab?
Thanks.

**Comment by alex4200** [comment]
@clupascu: Does not work, there is still some error:

![selection_050](https://user-images.githubusercontent.com/12729291/31668198-cb714fda-b351-11e7-8dc5-c78afdf8e403.png)

**Comment by clupascu** [comment]
I solved this by checking experimental file and configuration file choice and I give a simple text feedback to the user. Please test again.

**Comment by alex4200** [comment]
@clupascu : After clarification no error anymore.
