### ISSUE TITLE
Synapses vanish the changing tabs

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#315]
### Expected behavior

Synapses always visible once they were visible

### Actual Behavior

Synapses 'vanish' when changing the tabs

### Steps to reproduce the problem

1. I select a single cell
2. I select the soma and define some synaptic inputs: synapses visible
3. I go back to the 'Circuit' tab
4. I click on 'Proceed to simulation config' 

Although the synaptic input has not changed, the red synapes dots have vanished.

**Comment by pgetta** [comment]
Should be fixed now, could you please check, @alex4200 ?

**Comment by alex4200** [comment]
Yes works, thanks
