### ISSUE TITLE
Documentation for PairRecording App is missing in Guidebook

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#318]
In the guidebook the documentation for this app is missing. 

https://collab.humanbrainproject.eu/#/collab/1655/nav/18580

It should also contain examples on how the various stimuli/inputs etc look like etc...

**Comment by pgetta** [comment]
Guidebook entry has been deployed to prod: https://humanbrainproject.github.io/hbp-sp6-guidebook/online_usecases/small_circuit_in_silico_experiments/pair_recording_app/pair_recording_app.html.
