### ISSUE TITLE
Martinotti loop for the Rat hippocampus 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#319]
When selecting the Martinotti loop in the Rat hippocampus circuit you get just some random 3 cells it seems. 

Suggestion: Present preconfigured examples based on the circuit selected...

**Comment by mmigliore** [comment]
…there is no such a thing as a Martinotti loop in the hippocampus….

Please delete it from the list of preconfigured circuits. Leave the list empty for now.

Thank you

Michele

**Comment by mmigliore** [comment]
It is fixed, but I noticed other problems:

 

-          After selecting a cell afferents and efferents, and their intersection, the zoom does not work anymore.

-          Zooming also does not work when I go to the simulation panel.

-          In Geneva you also showed me how to center the zoom on a cell. Is it already implemented in the use case? If yes, it does not work for me.

 

Skype me if you need more details.

Best

Michele

**Comment by alex4200** [comment]
For me the zooming works in every panel (mouse/rat/chrome/FF), but the 'center' feature only works for mouse, not for rat...

**Comment by pgetta** [comment]
As I remember when we had Skype call with Michele other problems described above have been resolved.
"Center" feature works as well.

And regarding main topic of this issue: Martinotti loop isn't present any more in preconfigured circuits.

Would be good to close this ticket, @alex4200 could you please confirm app still works as expected with respect to described issues?

**Comment by alex4200** [comment]
Yes everything seems to work. Closing ticket
