### ISSUE TITLE
Integration validation into single cell model pipeline

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#322]
## Summary
  
Aspect | Detail
------------ | -------------
Summary | Model registration and validation to be appended to model building workflow, so the user just need "to click one button" for model registration. Model building e.g. "Rebuild Existing ..."
Usecase Group | Validation
State | Probably update existing (if agreed by single cell modeling team)
Expert | Shailesh
Scientific User | All
Deadline | M12 (March 2019)
Target audience | All
Target interface | Notebook
HPC Requirements | Depends on existing single cell modeling UseCase
Dependencies | None
Nominal runtime | To be determined (once implemented)
  
## List of features
The features of single cell modeling usecases will be extended by appending the registration of these new models in the model catalog, and optionally also undertake their validation. This will allow the creation of a new model variant and its validation (as well as registration of results on the HBP validation framework) in a single workflow.

### Tasks
 
- [ ] Wait on completion of #85 
- [ ] Create a combined UseCase for model development and its validation

## Acceptance Criteria
Confirm that user is able to generate new model variant and carry out its automated validation.
  
### System
Depends on existing Hippocampus single cell modeling UseCase
  
### Performance
To be determined (once implemented)

**Comment by appukuttan-shailesh** [comment]
As this isn't too urgent, we have decided to attend to this after we complete the switch to KnowledgeGraph. The current milestone (M12) seems appropriate.

**Comment by alex4200** [comment]
Requires completion of #85 first.

**Comment by alex4200** [comment]
Will be started in 2019

**Comment by appukuttan-shailesh** [comment]
This proposed UseCase can be dropped as there is no pressing demand for it. 

Also if deciding to have this done in future, since we have several single-cell model building UseCases following different workflows, it would be more appropriate to have this implemented within those existing UseCases.
