### ISSUE TITLE
Update validation use cases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#323]
## Summary
  
Aspect | Detail
------------ | -------------
Summary | Add notebook cells to include principal components of the neurites and test average features of a cells population against experimental data
Group | Morphology Analysis
State | Update?
Expert | Pedro
User |
Deadline |
Target audience |
Target interface | Notebook
HPC Requirements |
Dependencies |
Nominal runtime |
  
**Remove anything that does not apply**
## List of features
*What does your use case do (or the new/changed features)? What activities can users perform while using it? What makes it different from similar use cases? List the main functions that you will build into your product here. Also specify the priority ‘mandatory’, ‘important, ‘nice to have’.*

- [x] Add notebook cells to include principal components of the neurites 
- [ ] Add 'test average features of a cells population against experimental data.'

## Acceptance Tests
*Define here the acceptance tests to evaluate the use case’s compliance with the requirements as defined above. Also possible end users for testing can be included here.*
  
### System
*Does this use case require any special system requirements (any special software package)? Does this use case require HPC access? If so, which ones? List detailed system requirements here.*
  
### Performance
*What are additional performance requirements for this use case? What time should it take to run from start to end?*

**Comment by pedroernesto** [comment]
I have the code for this part almost ready. I am currently at SfN'19, but this usecase will get finished during the first weeks of December.

**Comment by pedroernesto** [comment]
Addition of validation for principal extents of neurites (axon or dendrite) was already done in:
https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/391

**Comment by alex4200** [comment]
@pedroernesto Are you saying this task is already done?

**Comment by pedroernesto** [comment]
This issue refers to the validation use case 'Basal Ganglia Morphology Validation' and it is not completed. I mean that the first part stated in the summary is done. 

It is missing the population study, i.e. _test average features of a cells population against experimental data_. I am working on it.

**Comment by alex4200** [comment]
@pedroernesto Thanks for the clarification.

**Comment by pedroernesto** [comment]
@alex4200 I just finished the correction of the Python code for this part, and the Jupyter notebook for this use case runs already smoothly locally.
However, when trying at the Collab I get an error message. I will contact the support team to fix this.

**Comment by pedroernesto** [comment]
A new usecase, containing what was proposed in this issue, is now available at Collab 8123 _Model validation suites_, and entitled as:
 _Basal Ganglia Population Morphology Validation_

**Comment by alex4200** [comment]
@pedroernesto  The use case has been merged to DEV. 

Please also remember to update the documentation for this new use case in the guidebook!

**Comment by pedroernesto** [comment]
I just created the pull request here:
https://github.com/lbologna/hbp-sp6-guidebook/pull/74

**Comment by alex4200** [comment]
Use cases updated
