### ISSUE TITLE
Naming of JURECA simulation results

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#325]
### Expected behavior

To have a clear naming of the simulation artefacts to be used for analysis

### Actual Behavior

In the Submission page I can name the simulation, like 'Demo Test':

![selection_395](https://user-images.githubusercontent.com/12729291/43440567-15a202a2-9498-11e8-9769-ccb2987be2b2.png)

When I go to the Analysis page, however, the name is not shown anymore

![selection_396](https://user-images.githubusercontent.com/12729291/43440584-2542b292-9498-11e8-8727-6b196888ed06.png)

(I would expect to see 'Demo Test' in the 'Name' column). 

Later on, I have two folders to choose from although I had done only one analysis. I find that very confusing...

![selection_397](https://user-images.githubusercontent.com/12729291/43440611-43d685a8-9498-11e8-8139-6b8525a8328f.png)

**Comment by clupascu** [comment]
Can you please add me to the team of this collab? Thanks.

**Comment by clupascu** [comment]
I fixed the name issue in the "View simulations" page. Now names containing whitespaces are also displayed. 

I don't understand the second issue. The one with the two folders displayed in the "View analysis" tab. When you select "storage", all the folders in the storage are displayed. You can choose on which one you want to perform analysis.

**Comment by alex4200** [comment]
The second issue: Its just that I run 1 simulation, but I end up having 2 results in the local storage. Why do I have two if I only ran one simulation? That is what I find strange...

**Comment by alex4200** [comment]
I just was unable to reproduce the latter issue. Closing this ticket.
