### ISSUE TITLE
Simplify detailed neuron network

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#326]
## Summary
  
Aspect | Detail
------------ | -------------
Summary | Simplify detailed neuron network using Oren's method .
Usecase Group |
State | New Application
Expert | Jean-Denis
Scientific User |
Deadline | Work can start only in about March 2019. Deadline around May 2019?
Target audience |
Target interface |
HPC Requirements |
Dependencies |
Nominal runtime |
  
## List of features
*What does your use case do (or the new/changed features)? What activities can users perform while using it? What makes it different from similar use cases? List the main functions that you will build into your product here. Also specify the priority ‘mandatory’, ‘important, ‘nice to have’.*

 - The first milestone will be to re-rerun a nixified version of the simplification pipeline (M8)

### Tasks
 
- [ ] Task 1
- [ ] Task 2
- [ ] ...
  
## Acceptance Criteria
*Define here the acceptance tests to evaluate the use case’s compliance with the requirements as defined above. Also possible end users for testing can be included here.*
  
### System
*Does this use case require any special system requirements (any special software package)? Does this use case require HPC access? If so, which ones? List detailed system requirements here.*
  
### Performance
*What are additional performance requirements for this use case? What time should it take to run from start to end?*

**Comment by jdcourcol** [comment]
The description should change. We are not simplifying to point neuron models in that ticket. But we use Oren's method to simplify detailed models.
We can remove the link to JP-UC15 as it is not related anymore based on SP6-SP10 meeting output.

**Comment by jdcourcol** [comment]
Alexei should be assigned to that ticket. I don't have his github id at hand now.

**Comment by alex4200** [comment]
@asanin-epfl Can you please give an update on this ticket?

**Comment by jdcourcol** [comment]
We are waiting simulator support for SONATA. 
current prediction is November.

**Comment by alex4200** [comment]
@jdcourcol Is there any update on this task? Did the estimated date change?

**Comment by asanin-epfl** [comment]
Currently the reduction has been upgraded to our support of Sonata but unfortunately I don't have any good networks to test it so I'm working on creating a new small network complaint with our Sonata support that can be used for tests.

**Comment by alex4200** [comment]
@asanin-epfl  Do you have any updates related to this task?

**Comment by asanin-epfl** [comment]
Hi! I'm working on a Docker instance for this project.

**Comment by alex4200** [comment]
@asanin-epfl  @jdcourcol  Hi, what is the status on this task right now? Should it be moved to SGA3?

**Comment by asanin-epfl** [comment]
The current status is that we are waiting for Python3 to be deployed on PizDaint because the module requires Python3.
The module itself has been tested and works properly locally and on BB5.

**Comment by alex4200** [comment]
Is there a related task for the Python3 deployment? Which one is it?

**Comment by asanin-epfl** [comment]
https://bbpteam.epfl.ch/project/issues/browse/BSD-112

**Comment by alex4200** [comment]
BSD-112 issue fixed on 3.4.2020.

**Comment by alex4200** [comment]
@asanin-epfl Anything new on this task?

**Comment by asanin-epfl** [comment]
I always forgot to comment here. It should work on PizDaint since 3.4.2020.

**Comment by mmigliore** [comment]
I would like to use it. Can you send me more detailed info?
michele.migliore@cnr.it
Thank you

**Comment by alex4200** [comment]
@asanin-epfl Can you be more precise on what should be working? Is this a tool, an application, a web application, a use case, a notebook? Where to find the final product? And what IS the final product?

**Comment by mgeplf** [comment]
> I would like to use it. Can you send me more detailed info?

We're in the process of adding a reduced hippocampus circuit to the SimUI; we'll get back to you when that's done.

> @alex4200  Can you be more precise on what should be working? 

We'll dicuss this today.

**Comment by mmigliore** [comment]
I am not interested in using a reduced model but in doing the reduction on
my own.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mgeplf** [comment]
We will provide a jupyter notebook as a use case in the brain simulation
platform to run the reduction on the example of the hippocampus O1.

In its current form it takes as input a SONATA circuit, so whatever circuit you
have needs to be in this format.  In addition we had to support a limited
portion of the SONATA specification because the circuit needs to be loadable by
NEURON.

**Comment by alex4200** [comment]
@mgeplf @asanin-epfl Is there any update on this jupyter notebook?
When is it ready to be tested and/or ready to be included into the BrainSimulation Platform?

**Comment by alex4200** [comment]
@mgeplf @asanin-epfl Is there any update on this jupyter notebook?

**Comment by asanin-epfl** [comment]
Hi! This notebook has been simplified for the end-user. Currently I'm waiting for a final approval of it. It can't be given until PizDaint is running. PizDaint should be running again tomorrow.

**Comment by asanin-epfl** [comment]
Unfortunately I still can't access collab Notebooks. We have to wait again until they are up and running.

**Comment by alex4200** [comment]
@asanin-epfl  The notebooks seem to be back running.

**Comment by asanin-epfl** [comment]
Yes! I tried just now but I still can't create jobs on PizDaint, 500 error. Can you?

**Comment by antonelepfl** [comment]
I cannot run it neither https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/501#issuecomment-633442366

**Comment by alex4200** [comment]
use case implemented and documentation added.
