### ISSUE TITLE
eFEL GUI: data filtering based on Contributors

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#33]
### Expected behavior
Filter electrophysiology data based on the contributors

### Actual Behavior
Not Implemented

### Optional infrastructural data (user, platform, browser, environment, ...)
Data on platform

**Comment by alex4200** [comment]
@lbologna : can you please assign this issue to a milestone? Thanks

**Comment by lbologna** [comment]
Done.

**Comment by lbologna** [comment]
This has been implemented, could you please check?
Thanks.

**Comment by alex4200** [comment]
Yes seems to work
