### ISSUE TITLE
Analysis of Hippocampus-CA1 circuit

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#331]
## Summary
  
Aspect | Detail
------------ | -------------
Summary | New test to  compare the synapses distribution of different m-type cells across the CA1 layers. The outcome will be a notebook showing how to use a test for synapses distributions of the Hippocampus CA1 circuit BBP-model.
Usecase Group | Validation
State |
Expert | Pedro
Scientific User |
Deadline | June 2019
Target audience | Experts in CA1
Target interface | Notebook
HPC Requirements |
Dependencies |
Nominal runtime |
  
**Remove anything that does not apply**
## List of features
*What does your use case do (or the new/changed features)? What activities can users perform while using it? What makes it different from similar use cases? List the main functions that you will build into your product here. Also specify the priority ‘mandatory’, ‘important, ‘nice to have’.*
  
## Acceptance Tests
*Define here the acceptance tests to evaluate the use case’s compliance with the requirements as defined above. Also possible end users for testing can be included here.*
  
### System
*Does this use case require any special system requirements (any special software package)? Does this use case require HPC access? If so, which ones? List detailed system requirements here.*
  
### Performance
*What are additional performance requirements for this use case? What time should it take to run from start to end?*

**Comment by pedroernesto** [comment]
Better to move the deadline to June/2019. It depends on setup completion of several tools and HPC resources.

**Comment by alex4200** [comment]
Task included in #332.
