### ISSUE TITLE
SimUI run analysis from non-unicore simulations

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#335]
### Expected behavior
Simulation launcher GUI should be able to launch some analysis of some simulation that the user has run from their own (not thru the Simulation launcher GUI).

For that the user should have to specify specifying the location of the simulation in Jureca and probably some extra parameters.

**Comment by jdcourcol** [comment]
Can the user see the filesystem of another user through the unicore API ? @antonelepfl @clupascu do you have any clue ?

**Comment by antonelepfl** [comment]
Alex gave me read access thru the terminal but even though I'm able to see the files from the terminal, when I ask unicore to give me the files I get empty list. So I guess no directly thru Unicore but you can launch a job that do something (input.sh) that access those files / directory

**Comment by clupascu** [comment]
@antonelepfl Do you have access to someone else's directory? Even when I am using ssh I can't access someone else's directory of a job launched through unicore.

**Comment by antonelepfl** [comment]
I have asked for access to Alex for example :) We don't get access normally

**Comment by clupascu** [comment]
@antonelepfl you are asking unicore to give you Alex's files using your hbp account?

**Comment by antonelepfl** [comment]
No no. I have physically Alex in front of me in the office and I asked him

**Comment by alex4200** [comment]
Wait for SimulationUI version 2.0

**Comment by jdcourcol** [comment]
So this will have the following limitations:
- no file selector: the user has to copy paste the filepath to the GUI
- The BlueConfig has to be available to the end user (that is not generally the case between end-users)

@mmigliore does that work for you ?

**Comment by alex4200** [comment]
See also #333

**Comment by antonelepfl** [comment]
Based on out talk with Michele, I'll implement this feature. The limitations mentioned above are not a blocker to proceed.

**Comment by antonelepfl** [comment]
I have implemented that in DEV version (only available for Jureca and Piz-daint)

**Comment by alex4200** [comment]
On DEV this seems to work fine. Please put it on PROD.

**Comment by antonelepfl** [comment]
Pushed to PROD
