### ISSUE TITLE
Support Simulation on "normal" partition

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#336]
booster partition is going to be down from mid-September to end of October.
Support normal partition instead from the Simulation GUI use case.

**Comment by mmigliore** [comment]
I am getting the same error too, and I opened a ticket. I’ll keep you posted.

-M

**Comment by antonelepfl** [comment]
I have also another question .. Should we remove Julia from the possible HPC systems?
It has been down for a couple of week iirc.

**Comment by mmigliore** [comment]
Yes. Julia has serious problems and no maintenance contract….I think we will not see it up again in the near future.

**Comment by mmigliore** [comment]
The allocation on the normal partitions (batch, mem256, etc) starts on Sep.1st (Saturday)

I have asked to have it open as soon as possible, but no answer so far. I’ll keep you posted.

In any case, it should be available from Saturday.

-M

**Comment by mmigliore** [comment]
Hello,

The normal partitions (batch, mem256, etc)  are available.

-M

**Comment by antonelepfl** [comment]
@mmigliore Do you know what is the configuration for **batch** partition? I have tried with `--ntasks-per-node=68` but it says `More processors requested than permitted`

**Comment by clupascu** [comment]
24 processors is the maximum you can use

**Comment by antonelepfl** [comment]
For simulations we are using `batch` partition with 68 ntasks-per-node
