### ISSUE TITLE
Documentation for Validation Service

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#34]
### Expected behavior
User's documentation for Validation Service integrated in the BSP's guidebook

- [x] [Model Catalog app in Guidebook](https://lbologna.github.io/hbp-sp6-guidebook/reference/model_catalog.html) 
- [x] [Python client standalone documentation](http://hbp-validation-client.readthedocs.io)
- [x] Python client in Guidebook
- [x] Model Validation app in Guidebook
- [x] REST API standalone documentation
- [x] REST API in Guidebook

**Comment by alex4200** [comment]
@apdavison : Do you know when you can finish this task?

**Comment by apdavison** [comment]
The end of November seems like a reasonable target.

**Comment by alex4200** [comment]
@apdavison : Goal is to have a working notebook end of January

**Comment by appukuttan-shailesh** [comment]
We intend to add the API documentation this week. The guidebook entry would simply point to this.

**Comment by alex4200** [comment]
Ok thanks, closing ticket
