### ISSUE TITLE
Information displayed in GUI element too big 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#346]
### Expected behavior

Information of simulations expected to be confined to the 'box'.

### Actual Behavior

The window extends way out of the box to the right window of the browser (google chrome, 69.0.3497.100). This is also the case in firefox. 

![selection_487](https://user-images.githubusercontent.com/12729291/47989500-75020780-e0e5-11e8-8a5c-0e7422da0a06.png)

### Steps to reproduce the problem

- Start a simulation
- Go to the 'Synaptic events fitting with analysis' notebook and run it
- Check the SA simulations

**Comment by rcsm17** [comment]
To fit the box I had to split the job id in to lines and increase the heights of all elements.
![screenshot from 2018-11-05 18-38-39](https://user-images.githubusercontent.com/44343476/48015821-4b1f0400-e12a-11e8-8f0d-ab09c57eaba6.png)
