### ISSUE TITLE
'Move' button clickable even if simulation not done yet. 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#347]
### Expected behavior

'Move' button disabled or something until some results can be moved.

### Actual Behavior

'Move' button enabled and clickable. Can click on it, and get a 'Warning'.

![selection_487](https://user-images.githubusercontent.com/12729291/47989588-b4305880-e0e5-11e8-94e8-8bf95072642d.png)

**Comment by rcsm17** [comment]
I fixed the behavior. Now the button of the running job is disabled. To avoid any mistake I added the "still waiting" and "already moved" tooltip on the buttons.

![already moved](https://user-images.githubusercontent.com/44343476/47997120-12b40180-e0fb-11e8-91ae-813f95becc48.png)
![still waiting](https://user-images.githubusercontent.com/44343476/47997130-1ba4d300-e0fb-11e8-8fd9-67c266d6a9c0.png)

**Comment by alex4200** [comment]
This is done and has been tested.
