### ISSUE TITLE
Name for simulation not used later

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#348]
### Expected behavior

A user should be able to track her/his simulation across the notebooks, i.e. from the notebook "Synaptic events fitting" to "Synaptic events fitting with analysis" with the same name. 

### Actual Behavior

Although I have been given to name a simulation, this name later is not mentioned any more. 

### Steps to reproduce the problem

1. Start a new simulation (e.g. on NSG) and give the simulation a name, like "Test 0711":

![screen shot 2018-11-07 at 09 43 24](https://user-images.githubusercontent.com/12729291/48121747-0d2ef680-e276-11e8-8ffd-bc09b488ca30.png)

2. Check the simulation on the same notebook: Name is still mentioned together with the start time (09:43:56)

![screen shot 2018-11-07 at 09 44 16](https://user-images.githubusercontent.com/12729291/48121769-1a4be580-e276-11e8-91e0-b9c7d961fe55.png)

3. Run the other notebook "Synaptic events fitting with analysis". Here you see only part of the original name ("Test" instead of "Test 0711"). Look at the timestamp which is the correct one.

![screen shot 2018-11-07 at 09 47 45](https://user-images.githubusercontent.com/12729291/48121892-77e03200-e276-11e8-9b56-896d3b48d6d3.png)

4. Finally, when you MOVE the results into the storage and look into the storage, you see the following content:

![screen shot 2018-11-07 at 09 55 24](https://user-images.githubusercontent.com/12729291/48121919-8e868900-e276-11e8-82c1-f1bd3793c50c.png)

No mention of the name nor the timestamp! Only by checking the storage I see that the files for this folder "NGBW-JOB-NEURON75_TG-3BD6F706C79F4A45B1D7783F0D36A986" have been created on the same day, so I can assume this is the correct output...

### Optional infrastructural data (user, platform, browser, environment, ...)

Investigation done in Collab 'p003'.

**Comment by clupascu** [comment]
I will fix this soon and in the same time I will switch synaptic events fitting use cases from JURECA to PizDaint.

**Comment by clupascu** [comment]
It should be fixed. Can you test again please? Thanks.

**Comment by alex4200** [comment]
Seems to be working now, tested with all available HPC systems
