### ISSUE TITLE
ACTION ITEMS

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#351]
## Action items

This is a list of tasks to be worked on by the assigned person. 

These tasks are about updating other tickets (kind of meta-tasks)

**Please update the respective tickets, not this ticket.**

- [ ] @genric @apdavison Elaborate and update ticket #359.
- [ ] @pgetta Update tickets for #354 and #353

**Comment by appukuttan-shailesh** [comment]
@alex4200 : I have updated my tickets with preliminary info that I have. It would be possible to provide more details after the work is initiated (in Feb 2019).

**Comment by lbologna** [comment]
@alex4200 : I have updated  #334 and #344.
I also checked the #330 checkbox in that our team involvement in #330 (concerning hippocampal models) is currently being discussed in #349

**Comment by appukuttan-shailesh** [comment]
@alex4200 : I might not be the right person to update ticket #349.... my work on it is restricted to BlueNaaS integration with the model catalog. The issue in context seems to be more specific.

**Comment by appukuttan-shailesh** [comment]
@genric : I saw your email, and currently trying it out. If all ready, we need to update the GUI for model catalog to expose this feature. 

But that apart, for this specific issue (#349) I am not sure if the two models in context are already registered on the model catalog (if not, they should be registered... probably by @SteMasoli ). The models should be stored in the appropriate BlueNaaS accepted formats in a public CSCS storage container (with the locations mentioned in their model catalog entries). Also, somebody needs to handle the adding of these models to the 'UseCase' list (see Figs. 3 and 4 in #349 ).

**Comment by SteMasoli** [comment]
@appukuttan-shailesh  I have uploaded, on cerebellum CSCS container, the zip files for the mono and multi granule cell compartmental models. In the google document i have added the links to the new files and defined as "outdated" the previous versions already uploaded on the model catalog. The file already on the mode catalog need to be deleted.
