### ISSUE TITLE
Pair recording application with plasticity

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#353]
## New Use Case
  
Aspect | Detail
------------ | -------------
Summary | This is the same use case as the current pair recording application except that the user will define which mod files he wants to use when loading the models.
Usecase Group | small circuit experiment
Expert | Michele Migliore
Scientific User | Michele Migliore
Deadline | M12
Target audience | any user
Target interface | pair recording application
HPC Requirements | none
Dependencies | plasticity model
Nominal runtime |
  
**Remove anything that does not apply**
## List of features

These should be two different use cases:

UC1: using a previously run sim
1. The user selects a reference simulation and a neuron from the circuit.
2. User then selects one or more other neurons that make incoming syn connections with the ref neuron.
3. a subset of synapses to be analyzed is selected. This can be a random selection or synapses from specific neuron(s).
4. The simulation is replayed to see how the synaptic weights in the ref neuron evolve with time.

UC2: in silico exp on plasticity
1. The user selects a reference neuron from a circuit.
2. User then selects one or more other neurons that make incoming syn connections with the ref neuron.
3. a subset of synapses to be analyzed is selected and their activation is configured.
4. The simulation is carried out to see how the synaptic weights in the ref
neuron evolve with time.

The difference between the two is that on UC1 synaptic activation times are read from a previously run simulation, whereas in UC2 synapses are activated with a user-defined pattern.

---

We have to define if we can get the list of possible models (may be we will have to hardcode that.)
We have to define if we can have several instance of models living together.
We have to define what can be parametrized. 

### Tasks
 
- [ ] Task 1
- [ ] Task 2
- [ ] ...
    
## Acceptance Criteria
*Define here the acceptance tests to evaluate the use case’s compliance with the requirements as defined above. Also possible end users for testing can be included here.*
  
### System
*Does this use case require any special system requirements (any special software package)? Does this use case require HPC access? If so, which ones? List detailed system requirements here.*
  
### Performance
*What are additional performance requirements for this use case? What time should it take to run from start to end?*

**Comment by alex4200** [comment]
@mmigliore: Can you provide some more details of what you want to have exactly?

**Comment by mmigliore** [comment]
These should be two different use cases:
UC1: using a previously run sim
-The user selects a reference simulation and a neuron from the circuit.
-User then selects one or more other neurons that make incoming syn
connections with the ref neuron.
-a subset of synapses to be analyzed is selected. This can be a random
selection or synapses from specific neuron(s).
-The simulation is replayed to see how the synaptic weights in the ref
neuron evolve with time.

UC2: in silico exp on plasticity
-The user selects a reference neuron from a circuit.
-User then selects one or more other neurons that make incoming syn
connections with the ref neuron.
-a subset of synapses to be analyzed is selected and their activation is
configured.
-The simulation is carried out to see how the synaptic weights in the ref
neuron evolve with time.

The difference between the two is that on UC1 synaptic activation times are
read from a previously run simulation, whereas in UC2 syanspes are
activated with a user-defined pattern.

**Comment by wvangeit** [comment]
@mmigliore, just want to confirm with you before we start implementing this.

Our synapses have the variables g_AMPA and g_NMDA for exc synapses and  g_GABAA  and  g_GABAB for inh synapses.
(these are the variables which are affected by our STP and which ultimately used for the final e.g. i_AMPA = g_AMPA*(v-e))
If these variables are plotted during the run, would that comply with your use case ?

**Comment by mmigliore** [comment]
Not really. The name of the variables that need to be reported depend from
the mod file used for synaptic plasticity.
As far as I know, the current mod file does not have plasticity.



Il gio 14 mar 2019, 11:38 Werner Van Geit <notifications@github.com> ha
scritto:

**Comment by wvangeit** [comment]
Ah ok, you are not using ProbAMPANMDA_EMS and ProbGABAAB_EMS for the synapses in the hippocampus circuit ?

**Comment by mmigliore** [comment]
I am probably usign them, although I have not the privilege to know it
directly (:)), but I am almost sure that their mod file does not have any
plasticity code inside. So, plotting their weight at this time would not be
useful.
However, I am involved in the implementation of a few mod files that have
plasticity. In this case their weight need to be plotted.
I think that before you work on this we should have a skype (possibly also
with Jim and/or Jean-Denis) to explain in better details what I have in
mind.
Tuesday or wednesday in the period 11:00-13:00 would work for me.
Best
Michele

**Comment by wvangeit** [comment]
Ok, sure we can have a skype call.
ProbAMPANMDA_EMS and ProbGABAAB_EMS do have short plasticity 
So the weight is changing in time.

But maybe we're talking about different types of plasticity (you probably mean LTD/LTP ? ) ?

**Comment by mmigliore** [comment]
Oh, yes of course. I am talking about LTP/LTD.
Not particularly interested in short-term facilitation/depression in the
context of a circuit simulation at this time.

**Comment by wvangeit** [comment]
Ok, thanks, that was the piece of the puzzle I was missing :-)

**Comment by alex4200** [comment]
@wvangeit (@pgetta ) Is there any news on this specific task?I have not heard anything about this being implemented into the Pair Recording application.

**Comment by alex4200** [comment]
This issue will not implemented for SGA2, closing it.
