### ISSUE TITLE
Synaptic Events Fitting Analysis: NSG login mask visible after HPC change

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#355]
### Expected behavior

When you select first NSG as your system the NSG login mask appears. If you select a different system (like JURECA) this login mask should be hidden.

### Actual Behavior (please include screenshot if possible)

NSG login mask still visible even when JURECA has been chosen.

![screen shot 2018-11-28 at 11 31 33](https://user-images.githubusercontent.com/12729291/49146064-99768b80-f301-11e8-853f-322aaf082bed.png)

### Steps to reproduce the problem

1. Start the 'Analysis' notebook
2. Select NSG in 'View Analysis'
3. Select JURECA in 'View Analysis'

**Comment by clupascu** [comment]
This should be fixed now. @alex4200 Can you test again please? Thanks.

**Comment by alex4200** [comment]
Yes that seems to work now, thanks.
