### ISSUE TITLE
Integrating BlueNaas with Model catalog

### ISSUE THREAD

**Issue by appukuttan-shailesh** [cnr-ibf-pa/hbp-bsp-issues#357]
Implement feature to allow launching of models in BlueNaaS. 
For implementation details, see here:
https://github.com/HumanBrainProject/hbp-validation-framework/issues/228

Aspect | Detail
------------ | -------------
Summary | Launch BlueNaaS compatible models from the Model Catalog
Expert | All
Deadline | Dec 2018 (M9)
Dependencies | BlueNaaS
 
### Tasks

- [x] Allow BlueNaaS to accept external URLs (completed by @genric )
- [x] Update model catalog GUI to accommodate new feature

## Acceptance Criteria
Check if model instances that expose this feature on the model catalog are able to properly launch the models in BlueNaaS.
Note: not all models will have this feature... only meant for BlueNaaS compatible models.

**Comment by appukuttan-shailesh** [comment]
This task is now completed. Implementation details are as specified in https://github.com/HumanBrainProject/hbp-validation-framework/issues/228

In short: append `?bluenaas=true` at the end of the URLs for models that are capable of using BlueNaaS. These models will have a button titled "Launch in BlueNaaS" next to their download location field on the model catalog.

@mmigliore , @clupascu, @lbologna : The above has been appropriately updated for all the models described in the Live Paper.

**Comment by mmigliore** [comment]
Great work!

**Comment by alex4200** [comment]
@appukuttan-shailesh Can you provide some model names so I can test this feature? Thanks

**Comment by appukuttan-shailesh** [comment]
@alex4200 you can pick any model from the list under "optimization" tab of the live paper here: https://cnr-ibf-pa.github.io/hbp-bsp-live-papers/migliore_et_al_2018/migliore_et_al_2018.html

(I am away till the 15th, so won't be attending our calls during this period.)

**Comment by alex4200** [comment]
@appukuttan-shailesh That is cool and seem to work. Closing this ticket.
