### ISSUE TITLE
Index all models in the HBP KG search app

### ISSUE THREAD

**Issue by genric** [cnr-ibf-pa/hbp-bsp-issues#359]
Once models are integrated with the HBP KG please make sure they are also indexed and appear in https://www.humanbrainproject.eu/en/explore-the-brain/search/. Thanks.

**Comment by alex4200** [comment]
The model integration is being delayed (but should be done by March 2019), and also handled by @apdavison .

**Comment by alex4200** [comment]
This task will be worked on after finishing #380

**Comment by apdavison** [comment]
Note that not _all_ models should be available through the KG Search app, only _released_ models. The KG can also contain work-in-progress and/or exploratory models; such models will be accessible through the Model Catalog, but not through KG Search.

**Comment by appukuttan-shailesh** [comment]
Is it correct to add that only "curated" model catalog entries would be made available on the KG search app?

**Comment by apdavison** [comment]
yes, curation is required prior to release

**Comment by alex4200** [comment]
@apdavison You wanted to comment on this task about the general status of the curated models

**Comment by appukuttan-shailesh** [comment]
@yzerlaut can you update the status on this?

**Comment by yzerlaut** [comment]
> @yzerlaut can you update the status on this?

Curation is still in progress for quite a large fraction of the models. If you want details about the specific status of the models, get in touch by email, I'll send you our status summary. And yes, they will then appear in the KG search.

**Comment by alex4200** [comment]
@yzerlaut Hi, can you provide some basic statistics of how many models are already curated and will appear in the KG graph, and how many models are not yet curated, and the time by which they will be? 

No exact numbers needed, just some rough values.

**Comment by yzerlaut** [comment]
> @yzerlaut Hi, can you provide some basic statistics of how many models are already curated and will appear in the KG graph, and how many models are not yet curated, and the time by which they will be?
> 
> No exact numbers needed, just some rough values.

- Models released in the KG: 32
- Models curated, ready for KG released: ~10 (Release time ~ 1 week)
- Models under curation: ~40  (Curation time ~ 1-2 months)

Then there are ~100 models left in the Model Catalog. Their "curation status" is hard to determine, some of them are not intended to be released (e.g. tests), some are private models for sharing between collaborators, some should enter the curation pipeline. I will update here the status of those models when I get a more precise picture.

**Comment by alex4200** [comment]
Closing ticket, as there is a number of models available and this is an ongoing process outside of the scope of this project.
