### ISSUE TITLE
Hodgkin-Huxley Neuron Builder app hangs when fetching data from NSG

### ISSUE THREAD

**Issue by szkali** [cnr-ibf-pa/hbp-bsp-issues#361]
### Expected behavior
Optimization results are downloaded from NSG for a "Single cell simulation run."

### Actual Behavior (please include screenshot if possible)
![screenshot_from_hung_hh_neuron_builder_2019-01-04](https://user-images.githubusercontent.com/5347908/50692450-3250a300-1034-11e9-922b-5f26c37babfa.png)
Hangs indefinitely when trying to fetch results.

### Steps to reproduce the problem
1. Run the Hodgkin-Huxley Neuron Builder in a new collab.
2. Complete the "Cell optimization" part using the NSG (personal account), and data and models provided in the BSP.
3. Try to download the results from the NSG by pressing "Fetch results" in "Single Cell Simulation Run" (select the finished optimization run).

### Optional infrastructural data (user, platform, browser, environment, ...)
Screenshot from Firefox under Linux, but the problem was the same in other environments.

**Comment by alex4200** [comment]
@szkali: How long did you wait? Can you repeat that step and watch the network inspector tabe of your browser? Do you get any error?

For me it works, it took about 30 seconds to download the data.

**Comment by szkali** [comment]
For me, it does not finish even overnight. I attach a screenshot with the network monitor open.
![screenshot_from_hh_neuron_builder_with_network_monitor_2019-01-07](https://user-images.githubusercontent.com/5347908/50756024-21ce4180-125b-11e9-977c-123a7cadb7ee.png)
There is no apparent error, but there is a step that never completes:
GET https://bspg.humanbrainproject.eu/hh-neuron-builder/modify-analysis-py/tab_20190107075804/ec85b7b4-e27c-43c4-aa21-31e02d7048d0
(this is apparently after the download itself)

**Comment by alex4200** [comment]
@antonelepfl : Making a test run of this use case

**Comment by antonelepfl** [comment]
I was not able to reproduce the issue. Everything worked fine for me.
