### ISSUE TITLE
Framework of model metadata

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#362]
## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary |  Development of a framework regarding metadata of models, so a model can be put into Nexus and has an image etc. 
Expert | 
Timeline | Will be discussed during the Hackathon 23-25 Jan 2019. 
Dependencies |Created from #360.
 
**Remove anything that does not apply**
## List of additional/changed features 

TBD

### Tasks
TBD

## Acceptance Criteria
* TBD

**Comment by appukuttan-shailesh** [comment]
This was partly discussed during the talk on "A proposal for a SP6 Model Curation Workflow" at the Hackathon.

Metadata currently expected from (appropriate) models:
1) Model entry should have an image of the morphology with caption "Morphology"
2) Model entry should have an image of sample electrical response with caption "Responses"
3) Morphology file(s) should be indicated in the model instances' "morphology" field as a list or dict
4) For model's that are in BlueNaas compatible format (see https://blue-naas.humanbrainproject.eu/), the download location of the model's zip file should be appended with `?bluenaas=true` (see https://github.com/HumanBrainProject/hbp-validation-framework/issues/228 for more details)

**Comment by appukuttan-shailesh** [comment]
@alex4200 : The above should be sufficient guidelines to proceed for the time being. Unless anyone has any comments or further suggestions on this, we can close this ticket. This is more likely to be a constantly evolving discussion as and when new features (and thereby requirements) are made available, and best to undertake afresh when the need arises.

**Comment by alex4200** [comment]
Information has been added to the SGA2 google doc: [here](https://docs.google.com/document/d/19Ni5fGFv6PTTM1D_D2FN4dj5IRhtfq1D0V2OWjXxJww/edit#heading=h.jjoq7zp97ld3)
