### ISSUE TITLE
Code error in DEV version of "Rebuild Single HippoCell" use case

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#365]
### Expected behavior

Able to run the notebook "Rebuild Single HippoCell - Config"

### Actual Behavior (please include screenshot if possible)

When selecting "Run All" I see the following error:

`
OSErrorTraceback (most recent call last)
<ipython-input-18-721f647b8891> in <module>()
      3 diff = lambda l1,l2: [x for x in l1 if x not in l2]
      4 os.chdir('bsp_data_repository-3.1.10')
----> 5 os.chdir('optimizations')
      6 FD=diff(os.listdir('.'),['README'])
      7 for i in range(len(FD)):

OSError: [Errno 2] No such file or directory: 'optimizations'
`

![selection_538](https://user-images.githubusercontent.com/12729291/50823516-798cab80-1334-11e9-9045-5b3a9ba7ebd0.png)

### Steps to reproduce the problem

1. Select the use case from the DEV platform https://collab.humanbrainproject.eu/#/collab/8444/nav/65633
2. Run All

**Comment by clupascu** [comment]
It should be fixed now. Can you test again please? Thanks.

**Comment by alex4200** [comment]
Thanks, that seems to be fixed now.
