### ISSUE TITLE
Nuvla TSI unavailable

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#369]
### Expected behavior
TSI is available to submit jobs
### Actual Behavior (please include screenshot if possible)
Get 500 error 
`
Could not submit job: de.fzj.unicore.xnjs.tsi.TSIUnavailableException: TSI unavailable: java.net.ConnectException: Connection refused (Connection refused)
`
### Steps to reproduce the problem
POST to `https://zam2125.zam.kfa-juelich.de:9112/NUVLA/rest/core/jobs`

**Comment by antonelepfl** [comment]
@BerndSchuller Could you please restart the service? I'm not 100% sure if the issue is in your side or Nuvla's

**Comment by BerndSchuller** [comment]
restarted, definitely on the UNICORE side

**Comment by antonelepfl** [comment]
Thank you Bernd!

**Comment by antonelepfl** [comment]
Hi, I'm having the same issue now.

**Comment by BerndSchuller** [comment]
should be fine - sorry that this setup (using an ssh tunnel to the Nuvla TSI) is not very robust :-/

**Comment by antonelepfl** [comment]
Thanks

**Comment by antonelepfl** [comment]
Hi @BerndSchuller Can you restart the service please?

**Comment by BerndSchuller** [comment]
it's restarted

**Comment by antonelepfl** [comment]
Hi @BerndSchuller,
The rest API to the storage endpoint (.../rest/core/storages/90e4a...uspace/files) are extremely slow. Could you check them please?

**Comment by BerndSchuller** [comment]
better now?

**Comment by antonelepfl** [comment]
Yes thank you!

**Comment by alex4200** [comment]
@BerndSchuller When submitting a job to NUVLA I seem to run into problems. Jobs do not finish, I get a 500 ERROR, etc.

**Comment by BerndSchuller** [comment]
Hi,
in the logs I can see (this error should be also in the job's properties that you can look at on the client)

...  - Started 85ea4e8d-97c5-40b5-9967-67c1c1c50301
...  - Error submitting job.
... Reply was <TSI_FAILED: Unknown parameter: collab_oidc in node: compute...

(and later some attempts to download files like "/stderr" without authentication)

The "unknown parameter" is not a UNICORE error, it comes from the Nuvla part, so it's out of my "jurisdiction"

hope this helps!

**Comment by antonelepfl** [comment]
Hi @BerndSchuller I'm getting some 500 on Nuvla.. Is there any maintenance on Unicore going on? (it seems that Jureca is down)

**Comment by antonelepfl** [comment]
Good afternoon Bernd, could you please reset the Nuvla TSI tunnel?

**Comment by BerndSchuller** [comment]
restarted - sorry for the hassle

**Comment by antonelepfl** [comment]
Morning Bernd, this error I'm not sure if it's related to you or SixsQ but I get `Could not submit job: java.lang.IllegalThreadStateException (no further message available)` could you please have a look when you have time?
