### ISSUE TITLE
Updating Jureca deployment with latest software stack and issue with matplotlib

### ISSUE THREAD

**Issue by clupascu** [cnr-ibf-pa/hbp-bsp-issues#371]
### Expected behavior
Optimizations require matplotlib module 
### Actual Behavior (please include screenshot if possible)
No module named matplotlib can be imported

**Comment by clupascu** [comment]
@pramodk Any news on this issue?

**Comment by pramodk** [comment]
On my list for this week, will update you soon.

**Comment by pramodk** [comment]
@clupascu  : I forgot if you need this on cluster or booster. I have installed this on both **but haven't made this software stack as default** yet. I have tested with small simulation and just importing modules. Please have a look and let me know if you see any issues. And then I will update documentation and make this as **default**.

### My sample job script for cluster : 

```

#!/bin/bash
#SBATCH --nodes=xx
#SBATCH --ntasks-per-node=yy
#SBATCH --job-name=test-hippo-cluster
#SBATCH --time=6:00:00
#SBATCH --partition=batch
#SBATCH --mail-user=email
#SBATCH --mail-type=ALL
#SBATCH --account=vsk25

module --force purge all
module use /usr/local/software/jureca/OtherStages
module load Architecture/Haswell
module load Stages/2018a
module load Intel IntelMPI imkl SciPy-Stack/2018a-Python-2.7.14
module load HDF5

export MODULEPATH=/p/project/cvsk25/vsk2514/HBP/jureca-cluster/01-02-2019/modules/tcl/linux-centos7-x86_64:$MODULEPATH

module load neurodamus/hippocampus
module load py-bluepyopt

# this test just import neuron, bluepyopt and matplotlib
srun python test.py

# run actual simulation
srun --cpus-per-task=1 special -NFRAME 1024 $HOC_LIBRARY_PATH/init.hoc -mpi
```

### My sample job script for booster

```
#!/bin/bash
#SBATCH --nodes=xx
#SBATCH --ntasks-per-node=yy
#SBATCH --job-name=test-hippo-cluster-knl
#SBATCH --time=6:00:00
#SBATCH --partition=booster
#SBATCH --mail-user=email
#SBATCH --mail-type=ALL
#SBATCH --account=vsk25


module --force purge all

module use /usr/local/software/jureca/OtherStages
module load Architecture/KNL
module load Stages/2018a
module load Intel IntelMPI imkl
module load HDF5

export MODULEPATH=/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/modules/tcl/linux-centos7-x86_64:$MODULEPATH

module load neurodamus/hippocampus
module load py-bluepyopt
module load py-matplotlib

# this test just import neuron, bluepyopt and matplotlib
srun python test.py

# run actual simulation
srun --cpus-per-task=1 special -NFRAME 1024 $HOC_LIBRARY_PATH/init.hoc -mpi
```

Note that JSC doesn't provide all packages for  KNL partition (e.g. jupyter, matplotlib etc) and I have installed them myself. But booster partition may not be efficient for running matplotlib+jupyter and not sure if you want to use KNL nodes for this purpose.

**Comment by clupascu** [comment]
@pramodk I am using this module on booster. As in my script I need to use an IPython controller

export USEIPYP=1
export IPYTHONDIR="`pwd`/.ipython"
export IPYTHON_PROFILE=ipyparallel.${SLURM_JOBID}
# ipython profile create --profile=${IPYTHON_PROFILE}
ipcontroller --init --sqlitedb --ip='*' --profile=${IPYTHON_PROFILE} &
sleep 30
srun ipengine --profile=${IPYTHON_PROFILE} &

CHECKPOINTS_DIR="checkpoints/run.${SLURM_JOBID}"

I get this error with the newly installed modules

rc = Client(profile=os.getenv('IPYTHON_PROFILE'))
          File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-ipyparallel-6.2.2-dyilyr/lib/python2.7/site-packages/ipyparallel/client/client.py", line 415, in __init__
rc = Client(profile=os.getenv('IPYTHON_PROFILE'))
rc = Client(profile=os.getenv('IPYTHON_PROFILE'))
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-ipyparallel-6.2.2-dyilyr/lib/python2.7/site-packages/ipyparallel/client/client.py", line 415, in __init__
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-ipyparallel-6.2.2-dyilyr/lib/python2.7/site-packages/ipyparallel/client/client.py", line 415, in __init__
    raise IOError(no_file_msg)
IOError        : raise IOError(no_file_msg)
raise IOError(no_file_msg)
You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.
IOErrorIOError: : You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.

Any suggestion?

**Comment by pramodk** [comment]
@wvangeit  : do you have any suggestion about this? 

I am not familiar with ipyparallel stuff. I tested simulations and checked if all modules are working.

**Comment by wvangeit** [comment]
@clupascu could you provide the full output of messages you get ? Something might be going wrong during the ipcontroller command.

**Comment by clupascu** [comment]
@wvangeit this is the full output

Traceback (most recent call last):
  File "opt_neuron.py", line 86, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "opt_neuron.py", line 86, in <module>
  File "opt_neuron.py", line 86, in <module>
    rc = Client(profile=os.getenv('IPYTHON_PROFILE'))
          File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-ipyparallel-6.2.2-dyilyr/lib/python2.7/site-packages/ipyparallel/client/client.py", line 415, in __init__
rc = Client(profile=os.getenv('IPYTHON_PROFILE'))
rc = Client(profile=os.getenv('IPYTHON_PROFILE'))
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-ipyparallel-6.2.2-dyilyr/lib/python2.7/site-packages/ipyparallel/client/client.py", line 415, in __init__
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-ipyparallel-6.2.2-dyilyr/lib/python2.7/site-packages/ipyparallel/client/client.py", line 415, in __init__
    raise IOError(no_file_msg)
IOError        : raise IOError(no_file_msg)
raise IOError(no_file_msg)
You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.
IOErrorIOError: : You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.

where line 86 in opt_neuron.py is rc = Client(profile=os.getenv('IPYTHON_PROFILE'))

**Comment by wvangeit** [comment]
@clupascu this looks like the full output of the error. But actually I need the full output of the script.

(and is there a place I can access your scripts ?)

**Comment by clupascu** [comment]
@wvangeit you can access the scripts here /p/scratch/cvsk25/unicore-jobs/88d7499d-3085-42ee-bcce-6d286d7bce11/mouse2_changekmb_prova. In one minute I will change permissions and you can access the scripts.

**Comment by wvangeit** [comment]
Which of the scripts in this directory are you running ?

**Comment by clupascu** [comment]
ipyparallel.sbatch

**Comment by wvangeit** [comment]
I think I know what it might be, but I need the full output your script print to the screen / log files. Can you attach these please.

**Comment by clupascu** [comment]
[ipyparallel_6746570.log](https://github.com/cnr-ibf-pa/hbp-bsp-issues/files/2828389/ipyparallel_6746570.log)

**Comment by wvangeit** [comment]
Ok, thanks. Yes, so it whas actually the first error message that was important:
+ ipcontroller --init --sqlitedb '--ip=*' --profile=ipyparallel.6746570
/var/spool/parastation/jobs/6746570: line 42: ipcontroller: command not found

@pramodk do you have any idea why your module doesn't have the 'ipcontroller' command (and ipengine command). When one pip installs ipyparallel (which is a dependency of bluepyopt), these two commands should become available in the environment.

**Comment by pramodk** [comment]
Ah, that simply because I didn't enable `ipyparallel` module and hence nothings was added to $PATH. If you reload modules, ipengine & ipcontroller should be there now.

**Comment by wvangeit** [comment]
Ok thanks. So do you need to manually enable the dependencies of e.g. bluepyopt ?

**Comment by pramodk** [comment]
> Ok thanks. So do you need to manually enable the dependencies of e.g. bluepyopt ?

no...just in [modules.yaml](https://github.com/BlueBrain/spack/blob/6297759553846a0b4a0f619a1264e7392a926df2/sysconfig/jureca-booster/modules.yaml#L33) I specify which modules should be enabled.

**Comment by clupascu** [comment]
Now it seems that the ipcontroller works, but I get some [IPEngineApp] Exception in apply request:
[ipyparallel_6748477.log](https://github.com/cnr-ibf-pa/hbp-bsp-issues/files/2829028/ipyparallel_6748477.log)

**Comment by pramodk** [comment]
```
[18:apply]: Exception: Traceback (most recent call last):
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-bluepyopt-1.6.56-7ebnxm/lib/python2.7/site-packages/bluepyopt/ephys/protocols.py", line 150, in _run_func
    cell_model.instantiate(sim=sim)
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-bluepyopt-1.6.56-7ebnxm/lib/python2.7/site-packages/bluepyopt/ephys/models.py", line 225, in instantiate
    mechanism.instantiate(sim=sim, icell=self.icell)
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-bluepyopt-1.6.56-7ebnxm/lib/python2.7/site-packages/bluepyopt/ephys/mechanisms.py", line 105, in instantiate
    raise ValueError(str(e) + ': ' + self.suffix)
ValueError: argument not a density mechanism name.: kdrb

[14:apply]: Exception: Traceback (most recent call last):
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-bluepyopt-1.6.56-7ebnxm/lib/python2.7/site-packages/bluepyopt/ephys/protocols.py", line 150, in _run_func
    cell_model.instantiate(sim=sim)
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-bluepyopt-1.6.56-7ebnxm/lib/python2.7/site-packages/bluepyopt/ephys/models.py", line 225, in instantiate
    mechanism.instantiate(sim=sim, icell=self.icell)
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-bluepyopt-1.6.56-7ebnxm/lib/python2.7/site-packages/bluepyopt/ephys/mechanisms.py", line 105, in instantiate
    raise ValueError(str(e) + ': ' + self.suffix)
ValueError: argument not a density mechanism name.: kdrb

.... 6 more exceptions ...
```
seems line from bluepyopt now.... @wvangeit  can comment about this.

**Comment by wvangeit** [comment]
So it seems Neuron can't find the ion channels. Possibly it can't load the x86_64 shared libraries. @clupascu how did you compile the MOD files ?

**Comment by clupascu** [comment]
nrnivmodl mechanisms and I got 
Successfully created x86_64/special

**Comment by pramodk** [comment]
One thing :   by default we compile neuron with `linux_nrnmech=no`. I wonder if that is the issue.

**Comment by wvangeit** [comment]
@clupascu is the nrnivmodl being executed in an environment where the module is loaded.
@pramodk does the option you're using imply one 'has' to use the special to load the MOD files ? If that's the case then that's probably the reason. The Neuron installation we use should be as close as possible to default Neuron (apart from the GUI).

**Comment by clupascu** [comment]
yes. nrnivmodl is being executed in an environment where the module is loaded. We cannot test again today as Jureca is in maintenance.

**Comment by pramodk** [comment]
> @pramodk does the option you're using imply one 'has' to use the special to load the MOD files ? If > that's the case then that's probably the reason. The Neuron installation we use should be as close as > possible to default Neuron (apart from the GUI).

this is what "prefer" as a developer...if we compiled with `linux_nrnmech=no` then special is `real` binary that is understood by debugger and profilers. Its easy during development. Otherwise special created is bash script with dlopen stuff :

```
#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
        NRNHOME="/p/project/cvsk25/vsk2514/HBP/jureca-cluster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/neuron-2018-10-cx25aa"
fi
if test "x${NRNBIN}" = "x" ; then
        NRNBIN="/p/project/cvsk25/vsk2514/HBP/jureca-cluster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/neuron-2018-10-cx25aa/x86_64/bin/"
fi
if test "" = "yes" ; then
        NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
        NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll /p/project/cvsk25/vsk2514/HBP/jureca-cluster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/neurodamus-hippocampus-56jv3q/lib/libnrnmech.so
```

Any way, I updated deployment to be as close to default Neuron installation.

**Comment by clupascu** [comment]
Now it works. Thank you @pramodk and @wvangeit. We can close this issue.
