### ISSUE TITLE
display a spine model in 3D for a live paper

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#373]
## New Use Case
  
Aspect | Detail
------------ | -------------
Summary | display a spine model (obj file) in 3D
Usecase Group | Live Paper
Expert | Pablo Serna @pabloserna
Scientific User | Pablo Serna
Deadline | Should be done by May 2019
Target audience | for a live paper 
Target interface |
HPC Requirements |
Dependencies |
Nominal runtime |
  
## List of features

The idea is to show a new live paper (in prep.) which shows a 3D model of a dendrite spine (see example https://pabloserna.github.io/Testpage/). 
    
## Acceptance Criteria
*Define here the acceptance tests to evaluate the use case’s compliance with the requirements as defined above. Also possible end users for testing can be included here.*

**Comment by alex4200** [comment]
Pablo created a 3D spine model here:  https://pabloserna.github.io/Testpage/

**Comment by alex4200** [comment]
@pabloserna Can you please provide an update for this issue?

**Comment by p-serna** [comment]
We used [three.js](https://threejs.org/) as a 3d viewer to show correctly a 3d mesh of a dendritic spine and to control the perspective view, as in https://pabloserna.github.io/Testpage/spine.html
In principle, it can be used with any 3d mesh in with .obj format
