### ISSUE TITLE
Add info icon to HH-Neuron Builder panels

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#376]
## Use Case Update
 Aspect | Detail
------------ | -------------
Summary | @orena1 requested to add an info icon on the HHNB panels
Expert | @lbologna 
Deadline | M12
Dependencies | None
 
## List of additional/changed features 
* The user will be able to point an info icon and have a summary of what the relative step of the HH Neuron Builder does.
Priority: 'Nice to have'

### Tasks

- [x] Add icons with hover-over description

## Acceptance Criteria
* The user hovers over the info icon and a popup appears with some description of what the operation contained in the panel is intended for
 
### System
None

**Comment by lbologna** [comment]
Finalized on the dev/test platform: https://collab.humanbrainproject.eu/#/collab/1256/nav/29703
@alex4200 could you please have a look? If it works I will move it to prod. Thanks!

**Comment by alex4200** [comment]
@lbologna Please move it to production, Let me know when you have copied it to production

**Comment by lbologna** [comment]
Moved to production
