### ISSUE TITLE
RT Neuron support SONATA synapses

### ISSUE THREAD

**Issue by Hjorthmedh** [cnr-ibf-pa/hbp-bsp-issues#379]
RT Neuron needs support for reading synapses from SONATA.

Reason: Visualise network, and also used to validate network files in SONATA.

 
Aspect | Detail
------------ | -------------
Summary | RT neuron should be able to read synapses from SONATA files
Expert | juan.hernando@epfl.ch
Deadline | Soon-ish...
Dependencies |

**Comment by alex4200** [comment]
@Hjorthmedh: No new features are being added to RTNeuron anymore. 'Brayns' will replace RTNeuron; for that this feature can be possibly added.

**Comment by Hjorthmedh** [comment]
Okay. Then this issue can be closed.
