### ISSUE TITLE
Hodgkin-Huxley neuron builder: documentation in guidebook

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#38]
### Expected behavior
CDP2-P1 documentation inserted in BSP-Guidebook

### Actual Behavior
Documentation not present

**Comment by lbologna** [comment]
The documentation has been added.

**Comment by alex4200** [comment]
There are two small typos in the sentence "Upon successfull submission, the flag icon is changed and the submission button disactivated so as to forbid a second submission with the same workflow id (see figure below).":

- successfull -> successful
- disactivated -> deactivated

**Comment by lbologna** [comment]
This should be fixed now. Would you please check again? Thanks

**Comment by alex4200** [comment]
Ok thanks!
