### ISSUE TITLE
Integrate the KnowledgeGraph to Validation use cases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#381]
## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | Use the KnowledgeGraph to access models for the validation use cases
Expert | @apdavison 
Deadline | ~June 2019
Dependencies | from #85 
 
## List of additional/changed features 
- The validation use cases use the KnowledgeGraph as backend for models.
- Ticket for general verification

## Acceptance Criteria
- [ ] Check Model Catalog
- [ ] Check Validation App
- [ ] Check validation use cases

**Comment by apdavison** [comment]
Should be achieved automatically once #380 and #425 are achieved

**Comment by appukuttan-shailesh** [comment]
The latest versions of the validation usecases make use of the KG back-end. I believe this ticket can be closed.

**Comment by alex4200** [comment]
Agreed
