### ISSUE TITLE
Show MOOC grade before sending to EDX

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#384]
Based on what I talked with Anne, **EDX** has **changed** the way that they manage **grading**. Now only the students that pays for the course will have the grade otherwise EDX will do anything with the grade.

So far on the MOOC backed, we generate the grade, we send it to EDX and when the response is back we show that response from EDX to the students. If the user is not paying probably an error will be the response of saving the grade.

Anne suggested to **show the grade that we calculated** on our backend and then **try to send to EDX** and if that fails, at least the user knows his/her score

**Comment by jdcourcol** [comment]
so we have to change that for the current MOOC as well ?

**Comment by antonelepfl** [comment]
They have implemented that change on Jan 2019. This will affect the new students in the current MOOCs.
So something that they should look like 

![screenshot 2019-01-29 at 16 11 02](https://user-images.githubusercontent.com/24406041/51917812-a2a6d600-23e0-11e9-9b91-9cbd459e0de8.png)

Actually looks like
![screenshot 2019-01-29 at 16 10 36](https://user-images.githubusercontent.com/24406041/51917827-afc3c500-23e0-11e9-9583-da183362c4bb.png)

I need to test what happened when I send the grade to EDX (if we modify the exercise to be not graded).
Other point in case the above does not work is to check if we can remove the check of the submission key (as we don't have submission)

**Comment by antonelepfl** [comment]
I have tested and if the exercise is not graded, the current setup still work correctly.
I have talked to Anne and she is going to modify some weeks so they are not graded (kind of revision test)
