### ISSUE TITLE
Code error in Validation use cases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#386]
Error in the PRODUCTION versions of these noteboosk. Should be fixed in the DEV version so the PROD notebook can be replaced. 

### Expected behavior

Validation use cases should run to the end

### Actual Behavior (please include screenshot if possible)

Code error as below when not using an existing model_uuid:

![selection_587](https://user-images.githubusercontent.com/12729291/52123897-c019b100-2627-11e9-8084-7f48bc6e880b.png)

### Steps to reproduce the problem

Just run the notebook, and use the default option (i.e. "1")

**Comment by appukuttan-shailesh** [comment]
@alex4200 : This is directly related to #367; as the two notebooks are the same (dev and prod). So the solutions for them would also be the same. So better to merge these issues into a single ticket.

The issues are arising owing to updated packages, and not because of changes in the usecase. Will fix it such that we don't versioning problems in future.

**Comment by appukuttan-shailesh** [comment]
Sub-tasks:

- [x] Basal Ganglia Validation Use Case
- [x] Hippocampus Validation Use Case
- [x] Morphology Validation Use Case (valid for MSN D1, MSN D2 cell types, not for FS; see #391)
- [x] Generic BluePyOpt Validation Use Case

**Comment by alex4200** [comment]
@appukuttan-shailesh: Can I assume you fixed the `Basal Ganglia Validation Use Case`? if so then I get an error in the second cell:

```
Using existing Model Catalog app in this Collab. App nav ID: 296327

AttributeErrorTraceback (most recent call last)
<ipython-input-2-b197c8c557f1> in <module>()
     18 # check if apps exist; if not then create them
     19 MCapp_navID = modelCatalog.exists_in_collab_else_create(collab_id)
---> 20 modelCatalog.set_collab_config(collab_id=collab_id, app_id=MCapp_navID, only_if_new="True")
     21 VFapp_navID = testLibrary.exists_in_collab_else_create(collab_id)
     22 testLibrary.set_collab_config(collab_id=collab_id, app_id=VFapp_navID, only_if_new="True")

AttributeError: 'ModelCatalog' object has no attribute 'set_collab_config'
```

**Comment by appukuttan-shailesh** [comment]
@alex4200 : No they aren't ready for testing yet, as I will need to release new versions of some packages. Shall update you here when ready.

**Comment by appukuttan-shailesh** [comment]
@alex4200 : These validations Use Cases are now ready for testing.
If they pass, do let me know before you move them to Production.

(I made an extra small update to the package installation... let me know if they work; if not I will revert to previous working version)

**Comment by alex4200** [comment]
@appukuttan-shailesh I still get the same error as I describe above for the second cell:

![selection_604](https://user-images.githubusercontent.com/12729291/52995803-fa52c300-341b-11e9-9f63-4c807a8269da.png)

**Comment by appukuttan-shailesh** [comment]
@alex4200 : You are probably running an older version of the notebooks. None of the updated notebooks have the above statement producing the error. i.e.
`modelCatalog.set_collab_config...` has been changed to `modelCatalog.set_app_config...`

So if you see that statement in any of the notebooks, you basically need to have them updated with the latest version.

**Comment by alex4200** [comment]
@appukuttan-shailesh: Where can I find your up-to-date development notebooks?

**Comment by appukuttan-shailesh** [comment]
The notebooks are on Collab: https://collab.humanbrainproject.eu/#/collab/8123
(you will find them on the navigation bar on the left)

But the source files remain the same as before. The notebook UUIDs remain same as those used before and specified in `usecases.json`

**Comment by alex4200** [comment]
Use cases have been fixed and put in production.
