### ISSUE TITLE
Provide description for Connection Manipulation

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#387]
Hi @romani79, 
Could you provide a small description for those items that will be on the Simulation Launcher UI in the connection manipulation part?
The idea is that the end user understands what they are going to modify with this items:
- Source
- Destination
- Delay (ms)
- Weight
- SpontMinis
- Synapse Configuration

**Comment by romani79** [comment]
Please, use the existing documentation on BlueConfig.
See for example, documentation on the connection block:
https://bbpteam.epfl.ch/project/spaces/display/BGLIB/Connection+section

**Comment by alex4200** [comment]
The descriptions so far. The description for 'delay' might be clarified, as the delay might only affect the weights. 

* Source
  * This target defines presynaptic cells.
* Destination
  * This target defines postsynaptic cells.
* Delay (ms)
  * A delay after which the modifications are applied. 
* Weight
  * A scaling factor to adjust the synaptic strength (default = 1)
* SpontMinis
  * The Poisson mean rate for spontaneous synaptic activation.
* Synapse Configuration
  * Snippets of hoc code to manipulate additional synaptic parameters.

**Comment by alex4200** [comment]
Description available in PROD

**Comment by alex4200** [comment]
MinisFreq

The Poisson mean rate for miniature events.
