### ISSUE TITLE
CORS error in NUVLA

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#388]
Hi @BerndSchuller ,
I'm getting the CORS error in NUVLA:
`OPTIONS https://zam2125.zam.kfa-juelich.de:9112/NUVLA/rest/core 500 (Could not perform request.)`
Access to XMLHttpRequest at 'https://zam2125.zam.kfa-juelich.de:9112/NUVLA/rest/core' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by BerndSchuller** [comment]
hi Stefano 
can you try again? One of our VMs was restarted and the UNICORE/nuvla service had been stopped

**Comment by antonelepfl** [comment]
Not it worked. Thank you Bernd

**Comment by antonelepfl** [comment]
Hi @BerndSchuller,
I'm having this issue again. The strange thing was that I get this 500 using the Collab Notebook too that I think does not check CORS headers.
Could you please have a look when you have some time?

**Comment by BerndSchuller** [comment]
looks OK to me, pretty sure the 500 error was not CORS related, maybe temporarily one of the services was down.
