### ISSUE TITLE
BluePy use on Jureca: No module named bluepy

### ISSUE THREAD

**Issue by ElisabettaGiacalone** [cnr-ibf-pa/hbp-bsp-issues#389]
### Expected behavior

BluePy import on Jureca:

@antonelepfl is able to run this python code and import BluePy under his user, without loading any modules:

#!/p/project/cvsk25/vsk2512/analysis/venv_analysis_traces/bin/python
"""This is the script that launches the analysis based on a json configuration
that comes from the UI (analysisconfig) """

import argparse
import json
import logging
import os
import shutil
import matplotlib
import bluepy
from bluepy.api import Simulation, Circuit
from bluepy.v2.enums import Cell, Synapse
print('Bluepy is installed')

### Actual Behavior (please include screenshot if possible)

I run the same code under my user /p/project/cvsk25/vsk2505/connectivity/test_bluepy.py 
and I get:

- Without loading modules:

import matplotlib
ImportError: No module named matplotlib

- By import modules in #371  

import bluepy
ImportError: No module named bluepy

**Comment by pramodk** [comment]
> @antonelepfl is able to run this python code and import BluePy under his user, without loading any modules:

I don't think so...could you please see discussion in #371 ? You will see instructions to use those modules.

**Comment by clupascu** [comment]
I tested too the issue and with loading modules as in #371 I cannot import bluepy. @pramodk Modules from #371 are including bluepy too?

**Comment by pramodk** [comment]
Sorry, I missed this : it's `bluepy` and not `bluepyopt`!

I was trying to add this but seems like Jureca has issues while loading modules:

```
module --force purge
module use /usr/local/software/jureca/OtherStages
module load Architecture/Haswell
module load Stages/2018a
module load Intel IntelMPI   # stuck here
```
I will open support ticket!

**Comment by pramodk** [comment]
There is file system issue on multiple juelich systems. Will take a look once access restored.

**Comment by pramodk** [comment]
@ElisabettaGiacalone @clupascu : which functionality from bluepy you would be using? For example, do you use morphotool?

**Comment by ElisabettaGiacalone** [comment]
I usually use bluepy to access circuit and simulation data, cell properties and connectome. If by morphtool you mean to get NeuroM morphology object corresponding to gid, then  yes, I plan to use that function in the future.

**Comment by pramodk** [comment]
There is now `py-bluepy` module for booster. Could you check if this is sufficient for your current use cases?

Currently it doesnt have `neurom` and `h5py` enabled. I am discussing with developers (https://github.com/BlueBrain/spack/issues/221).

**Comment by ElisabettaGiacalone** [comment]
Hi @pramodk ,
I load modules for booster in #371 and then py-bluepy, and when I import bluepy in a python shell, I get this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-bluepy-0.12.7-3dgdw7/lib/python2.7/site-packages/bluepy/__init__.py", line 2, in <module>
    from bluepy.api import load_circuit, release_circuit, Circuit, Simulation
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-bluepy-0.12.7-3dgdw7/lib/python2.7/site-packages/bluepy/api.py", line 14, in <module>
    import h5py
ImportError: No module named h5py

**Comment by pramodk** [comment]
I can reproduce this issue...will fix this on tomorrow.

**Comment by alex4200** [comment]
@pramodk  Is this issue fixed now?

**Comment by ElisabettaGiacalone** [comment]
@pramodk news about this issue? I get the same error after import bluepy in a python shell:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-bluepy-0.12.7-3dgdw7/lib/python2.7/site-packages/bluepy/__init__.py", line 2, in <module>
    from bluepy.api import load_circuit, release_circuit, Circuit, Simulation
  File "/p/project/cvsk25/vsk2514/HBP/jureca-booster/01-02-2019/install/linux-centos7-x86_64/intel-18.0.2/py-bluepy-0.12.7-3dgdw7/lib/python2.7/site-packages/bluepy/api.py", line 14, in <module>
    import h5py
ImportError: No module named h5py

**Comment by pramodk** [comment]
@jorblancoa is working re-deploying new stack. Will update you soon.

**Comment by jorblancoa** [comment]
Hello @ElisabettaGiacalone @clupascu 

We have deployed new modules on Jureca cluster and booster partitions with the latest software stack.
You can load the modules on the cluster as 
```
module --force purge all
module use /usr/local/software/jureca/OtherStages
module load Architecture/Haswell
module load Stages/2019a
module load GCC Python/2.7.16
module load Intel ParaStationMPI/5.2.2-1-mt imkl
module load HDF5

export MODULEPATH=$MODULEPATH:/p/project/cvsk25/blancoalonso1/HBP/jureca-cluster/install/latest
echo $MODULEPATH
module load py-bluepy
module load py-bluepyopt
module list
```

And on the booster
```
module --force purge all
module use /usr/local/software/jurecabooster/OtherStages
module load Architecture/KNL
module load Stages/2019a
module load GCC Python/2.7.16
module load Intel ParaStationMPI/5.2.2-1-mt imkl
module load HDF5

export MODULEPATH=$MODULEPATH:/p/project/cvsk25/blancoalonso1/HBP/jureca-booster/install/latest

module load py-bluepyopt
module load py-bluepy
module list
```
Could you please try and let us know if this is working for you?
My complete job script for testing the simulation on booster is the following
```
#!/bin/bash
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=68
#SBATCH --job-name=test-hippo-booster
#SBATCH --time=1:00:00
#SBATCH --partition=booster
#SBATCH --account=vsk25
unset MODULEPATH
module --force purge all
module use /usr/local/software/jurecabooster/OtherStages
module load Architecture/KNL
module load Stages/2019a
module load GCC Python/2.7.16
module load Intel ParaStationMPI/5.2.2-1-mt imkl
module load HDF5

export MODULEPATH=$MODULEPATH:/p/project/cvsk25/blancoalonso1/HBP/jureca-booster/install/latest

module load neurodamus/hippocampus
srun --cpus-per-task=1 special -NFRAME 1024 $HOC_LIBRARY_PATH/init.hoc -mpi
```

If you confirm that everything works, then we will make these modules default and update the wiki page.

**Comment by ElisabettaGiacalone** [comment]
Hi, @jorblancoa , I'm testing bluepy use with a script to do analysis on the circuit.
 I get this error after import in a python shell:

from bluepy.api import Simulation, Circuit
from bluepy.v2.enums import Cell, Synapse

ImportError                               Traceback (most recent call last)
<ipython-input-1-826c14c79dd9> in <module>()
      5
      6 from bluepy.api import Simulation, Circuit
----> 7 from bluepy.v2.enums import Cell, Synapse
      8
      9

/p/project/cvsk25/blancoalonso1/HBP/jureca-booster/06-05-2019/install/linux-centos7-x86_64/gcc-8.3.0/py-bluepy-0.13.3-bahbk3/lib/python2.7/site-packages/bluepy/v2/__init__.py in <module>()
      2
      3 from bluepy.v2.enums import Cell, Direction, Synapse, Section, Segment
----> 4 from bluepy.v2.circuit import Circuit
      5 from bluepy.v2.simulation import Simulation

/p/project/cvsk25/blancoalonso1/HBP/jureca-booster/06-05-2019/install/linux-centos7-x86_64/gcc-8.3.0/py-bluepy-0.13.3-bahbk3/lib/python2.7/site-packages/bluepy/v2/circuit.py in <module>()
     11 from bluepy.exceptions import BluePyError
     12
---> 13 from bluepy.v2.cells import CellCollection
     14 from bluepy.v2.connectome import Connectome
     15 from bluepy.v2.emodels import EModelHelper

/p/project/cvsk25/blancoalonso1/HBP/jureca-booster/06-05-2019/install/linux-centos7-x86_64/gcc-8.3.0/py-bluepy-0.13.3-bahbk3/lib/python2.7/site-packages/bluepy/v2/cells.py in <module>()
      7 from bluepy.utils.url import get_file_path_by_url
      8 from bluepy.v2.enums import Cell
----> 9 from bluepy.v2.impl.mvd import MVDCellCollection
     10 from bluepy.v2.impl.target import TargetContext
     11

/p/project/cvsk25/blancoalonso1/HBP/jureca-booster/06-05-2019/install/linux-centos7-x86_64/gcc-8.3.0/py-bluepy-0.13.3-bahbk3/lib/python2.7/site-packages/bluepy/v2/impl/mvd.py in <module>()
      9 import h5py
     10 import numpy as np
---> 11 import pandas as pd
     12 import six
     13

ImportError: No module named pandas

I suppose that "pandas" should be also installed

**Comment by jorblancoa** [comment]
Hi @ElisabettaGiacalone,

Yes, your script uses pandas at some point, so installing it should fix the problem.

You would need to load the Python module to be able to use pip:
```shell
module load Python/2.7.16
pip install --user pandas
```

**Comment by clupascu** [comment]
Hi @jorblancoa,

when I run your job script for testing the simulation on booster I get this error in the output

Error: Could not open BlueConfig file 'BlueConfig'

**Comment by pramodk** [comment]
@clupascu : As error says, you need to run that in the directory with one of your BlueConfig. The job script is an example of what paths you need to set and modules you need to load for running simulation.

**Comment by ElisabettaGiacalone** [comment]
Ok, 'pandas' problem solved.

Now I can import bluepy but I cannot use any function, for example, when I try to get a single Gid from the circuit:

>>> from bluepy.api import Simulation, Circuit
>>> from bluepy.v2.enums import Cell, Synapse

>>>
>>> root_path = '/p/home/jusers/giacalone1/jureca/test-190219/'
>>> blueconfig_path = root_path + 'BlueConfig'
>>>
>>> sim = Simulation(blueconfig_path)
>>>
>>> gids=sim.v2.circuit.cells.ids(sample=1)
Illegal instruction

And the python shell crashes.

**Comment by jorblancoa** [comment]
@ElisabettaGiacalone : Could you share your python script to see if I can reproduce the issue?

**Comment by pramodk** [comment]
One thing I would like to mention : if you are using booster modules, the python script itself should run on the booster i.e. KNL. (note that the architecture of login node and booster node is different).

So make sure to run via srun for booster.

If you want to test stuff on login node directly via Python, use  cluster modules.

**Comment by ElisabettaGiacalone** [comment]
Hi, as @pramodk  suggested, using cluster modules, I don't get the same error and crashing of the python shell. However, now I can use "Simulation" object functions, but I cannot use "Circuit" functions. For example, when I execute only these lines in a python shell, I get this:

>>> from bluepy.api import Simulation, Circuit
>>> from bluepy.v2.enums import Cell, Synapse
>>>
>>> sim = Simulation('BlueConfig')
>>> gids=sim.v2.circuit.cells.ids(sample=10)
>>>
>>> circuit_path = '/p/project/cpcp0/pcp0068/CircuitRelease/r2017.06b/CircuitConfig'
>>> circuit = Circuit(circuit_path)
No handlers could be found for logger "bluepy_configfile.configfile"
>>> syn=circuit.v2.connectome.pathway_synapses(gids, gids,properties=[Synapse.PRE_GID,Synapse.POST_GID,Synapse.G_SYNX])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/project/cvsk25/blancoalonso1/HBP/jureca-cluster/06-05-2019/install/linux-centos7-x86_64/gcc-8.3.0/py-lazy-1.2-m7x5q2/lib/python2.7/site-packages/lazy/lazy.py", line 28, in __get__
    value = self.__func(inst)
  File "/p/project/cvsk25/blancoalonso1/HBP/jureca-cluster/06-05-2019/install/linux-centos7-x86_64/gcc-8.3.0/py-bluepy-0.13.3-45c4dv/lib/python2.7/site-packages/bluepy/api.py", line 283, in v2
    return Circuit2(self.config)
  File "/p/project/cvsk25/blancoalonso1/HBP/jureca-cluster/06-05-2019/install/linux-centos7-x86_64/gcc-8.3.0/py-bluepy-0.13.3-45c4dv/lib/python2.7/site-packages/bluepy/v2/circuit.py", line 130, in __init__
    self._config = _parse_blueconfig(config)
  File "/p/project/cvsk25/blancoalonso1/HBP/jureca-cluster/06-05-2019/install/linux-centos7-x86_64/gcc-8.3.0/py-bluepy-0.13.3-45c4dv/lib/python2.7/site-packages/bluepy/v2/circuit.py", line 57, in _parse_blueconfig
    result['cells'] = _find_mvd(blueconfig)
  File "/p/project/cvsk25/blancoalonso1/HBP/jureca-cluster/06-05-2019/install/linux-centos7-x86_64/gcc-8.3.0/py-bluepy-0.13.3-45c4dv/lib/python2.7/site-packages/bluepy/v2/circuit.py", line 30, in _find_mvd
    raise BluePyError("No MVD file found at %s" % circuit_path)
bluepy.exceptions.BluePyError: No MVD file found at /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b

**Comment by ElisabettaGiacalone** [comment]
@jorblancoa this is the python script to reproduce problem:

from bluepy.api import Simulation, Circuit
from bluepy.v2.enums import Cell, Synapse

sim = Simulation('/p/home/jusers/giacalone1/jureca/test-190219/BlueConfig')
gids=sim.v2.circuit.cells.ids(sample=10)

circuit_path = '/p/project/cpcp0/pcp0068/CircuitRelease/r2017.06b/CircuitConfig'
circuit = Circuit(circuit_path)

syn=circuit.v2.connectome.pathway_synapses(gids, gids,properties=[Synapse.PRE_GID,Synapse.POST_GID,Synapse.G_SYNX])

**Comment by pramodk** [comment]
@ElisabettaGiacalone : the error is : 

```
bluepy.exceptions.BluePyError: No MVD file found at /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b
```

This is not related to software deployment. The path above is pointing to BBP system : 

```
[kumbhar1@jrl01 ~]$ cat /p/project/cpcp0/pcp0068/CircuitRelease/r2017.06b/CircuitConfig

Run Default
{
    CircuitPath    /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b
    nrnPath        /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b/S2F
    MorphologyPath /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b/MorphologyRelease/07_h5v1
    METypePath     /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b/ccells
    TargetFile     /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b/user.target
    BioName        /gpfs/bbp.cscs.ch/project/proj42/CircuitRelease/r2017.06b/etc
}
```

These paths must be changed. Could you check with the team who copied the circuit?

**Comment by antonelepfl** [comment]
I'm having some issues after the maintenance...
When I try to load a circuit 
```
from bluepy.v2 import Circuit
c = Circuit('/p/project/cvsk25/vsk2512/O1/20181114/circuit/CircuitConfig')
print(c.cells)
```
I get `Illegal instruction` and the scripts exits.

@ElisabettaGiacalone , @clupascu , are you having a similar issue?

**Comment by ElisabettaGiacalone** [comment]
Hi @antonelepfl, I  tried your script, after loading cluster modules in https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/389#issuecomment-490813607, and I don't get "Illegal instruction".

In [1]: from bluepy.v2 import Circuit,Simulation

In [2]: c = Circuit('/p/project/cvsk25/vsk2512/O1/20181114/circuit/CircuitConfig')

In [3]: print c.cells
<bluepy.v2.cells.CellCollection object at 0x2b49140faad0>

**Comment by antonelepfl** [comment]
I'm using _booster_ partition and with the _batch_ I confirm that I don't have any issue.
I guess I can switch temporally to _batch_ until they upgrade the booster modules in October and check if after that I'm able to run it.
In the batch partition are you able to run simulate some slices of the CA1 or it is just for small simulations?

**Comment by mmigliore** [comment]
We do not have an allocation on the batch partition.

Il mer 18 set 2019, 16:25 Stefano Antonel <notifications@github.com> ha
scritto:

**Comment by ElisabettaGiacalone** [comment]
I have always run simulations on booster partition. Also for optimizations we use booster partition.
@clupascu are you aware of the reason?

Anyway I tried to run a simulation on batch partition, and I don't get any results, though the job is COMPLETED.
This is the log:
/p/home/jusers/giacalone1/jureca/test-180919-batch/slurm-7552774.out

**Comment by ElisabettaGiacalone** [comment]
Ok, this is the reason. Thanks

**Comment by alex4200** [comment]
@ElisabettaGiacalone  Can this issue be closed? If so, please close it.

**Comment by ElisabettaGiacalone** [comment]
Hi, I want to test bluepy with the new version of the circuit before closing this issue. I am waiting for the circuit to be available and working on Jureca.

**Comment by pramodk** [comment]
I believe this is fixed and we should close this.
