### ISSUE TITLE
Updated backend software in the Feature Extraction Use Case

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#390]
## Details description of the task
The latest (dev) version of the software (BluePyEfe) used for the feature extraction and data formatting in the Feature Extraction Use Case has been installed. 
This update fixes a minor bug in the visualization of the traces (the title of individual traces overlapped when the name of the file was too long).

## Description of how to test it
Run the Feature Extraction Use Case by selecting a few traces from the dataset at the same stimulus amplitudes and check that the results are meaningful and well formatted

**Comment by alex4200** [comment]
Tests are ok
