### ISSUE TITLE
BlueNaaS: add the ability to change the color and width of the attached voltage traces

### ISSUE THREAD

**Issue by orena1** [cnr-ibf-pa/hbp-bsp-issues#393]
Can you please add an option to add blue-nass the ability to change the colors and width of the attached voltage traces (and maybe also the opacity)

I want to make it so that eventually it will look like this:

![to_oren](https://user-images.githubusercontent.com/8983713/52913782-f747bd80-32c9-11e9-897c-398a7bbee8c3.png)

@guyeyal

Thanks,
@genric

**Comment by genric** [comment]
I added some transparency to the experimental traces.

**Comment by genric** [comment]
@orena1, I am not too much in favor of having configurable trace color palette but if it is strictly necessary I'm open for suggestions on how this could be configured.
Anyways, I improved the current behavior, so please let me know if it looks any better now and if we could live with that, thanks.

**Comment by alex4200** [comment]
I have tested this with the model cell0603_03_model_476 and now I see an output as follows:

![selection_606](https://user-images.githubusercontent.com/12729291/53176478-70a71f00-35ee-11e9-857e-dd46dc65f38f.png)

I will close this ticket as this seems to be a workable solution. 
@orena1 please reopen this ticket if you disagree, or wanted something else.

**Comment by orena1** [comment]
I'll ask my PI (idan segev) and will reopen if he can not live with it :)  thanks
@genric  by they way, try this:
https://blue-naas.humanbrainproject.eu/#/url/human_cells/cell0603_03_model_476.zip?delay=120.33&vinit=-86&dt=.025&amp=0.7&tstop=1500&dur=1000

It creates a better example

**Comment by genric** [comment]
@orena1 just checking with you if you are aware of the zoom functionality of the trace component described over here at **7.** https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/single_cell_in_silico/single_cell_clamp/single_cell_clamp.html ? It gives a better insights if you want to compare them.

**Comment by orena1** [comment]
I am now, thanks
