### ISSUE TITLE
BlueNaaS: extra section (spines) and synapses are not visible in the correct location

### ISSUE THREAD

**Issue by orena1** [cnr-ibf-pa/hbp-bsp-issues#396]
We added a model with spines and synapses, the spines and synapses are created in an external python file named ```fig8_distributed_synapses.py```

But there are two problems:
1. We can not see the synapses (which are on the spines)
2. The spines do not look like they are connected to the morphology 

![image](https://user-images.githubusercontent.com/8983713/52952927-be255100-338e-11e9-871f-d5cef94139a3.png)

![image](https://user-images.githubusercontent.com/8983713/52952991-e1e89700-338e-11e9-8af7-f2729dc4e900.png)

This is how it looks in NEURON:

Upload the attached zip to BlueNaaS to see the results
[cell0603_11_model_937.zip](https://github.com/cnr-ibf-pa/hbp-bsp-issues/files/2875703/cell0603_11_model_937.zip)

Thank you!

@guyeyal @genric

**Comment by genric** [comment]
Wow, that looks really not how it suppose to look :) investigating...
The model you provided before was giving me something like this: https://blue-naas.humanbrainproject.eu/#/model/test_model_syn_123

**Comment by orena1** [comment]
Thank @genric  that test case that I gave you work well, see this example:
```https://blue-naas.humanbrainproject.eu/#/url/neuron_reduce/detailed.zip```
I would add a small rotation to each synapse.

But this new test case that in this ticket is a bit different.

Thank you

**Comment by genric** [comment]
Ok, I see. But even detailed.zip doesn't look too nice :) I had those rotations but didn't see if they made any difference on that simple model. I'll try to prettify it as well.
And there are multiple synapses per segment... which breaks everything :) Ok, I'll have a look.
Thanks for the feedback!

**Comment by orena1** [comment]
> And there are multiple synapses per segment... which breaks everything :)

We do not have to see all the synapses... if some of the synapses are overlapping it will be ok. But I wonder how it will look with rotation 👍 
Thanks

**Comment by genric** [comment]
Finally I'll try to look into those spine visualizations. I've noticed that this model(https://blue-naas.humanbrainproject.eu/#/model/cell0603_11_model_937) gives some weird output form NEURON(full message is available in the js console) @orena1 is this fine or model needs to be fixed?

**Comment by orena1** [comment]
It is something with the way the code is different between neuron versions, I changed it so it will work the same in all version (and there will not be weird output).
Also, there was some python2 vs python3 int casting problem, it did not change the main results but I fixed it, thanks!

https://blue-naas.humanbrainproject.eu/#/url/human_cells/Figure_8_Eyal_et_al_Elife/distributed_input/cell0603_11_model_937.zip?delay=0&vinit=-86&dt=.025&amp=0&tstop=500&dur=0&celsius=37

**Comment by genric** [comment]
Hi @orena1, you can check the model, spines should be well positioned now. Feel free to close this issue if you are happy with the result :)

**Comment by alex4200** [comment]
I checked the new implementation which seems to work.  Closing the ticket now. Feel free to OPEN this ticket if there are some other issues.

**Comment by orena1** [comment]
Hi @genric I forgot to update. It works well, thank you!
