### ISSUE TITLE
BlueNaaS: update about with NEURON version

### ISSUE THREAD

**Issue by orena1** [cnr-ibf-pa/hbp-bsp-issues#397]
I think the about section of BlueNaaS should be updated to contain the version of NERUON that is been used, (and maybe also the python version)?

![image](https://user-images.githubusercontent.com/8983713/52996464-633f3880-3426-11e9-8592-db426c7891e5.png)

Mainly because of having the ability to compare the results that we one get from BlueNaaS to the results he gets on bbpv5 or on his own PC. It will also help debugging.

It should also have @genric  as the developer.

**Comment by alex4200** [comment]
Again, an update has been made: 

![selection_607](https://user-images.githubusercontent.com/12729291/53176587-b19f3380-35ee-11e9-88b2-256cc2b361b9.png)

I will close that ticket.
@orena1 If you think something important is missing, please reopen this ticket
