### ISSUE TITLE
BlueNaaS: should output NERUON log (on failure?)

### ISSUE THREAD

**Issue by orena1** [cnr-ibf-pa/hbp-bsp-issues#398]
I think it would be extremely efficient if BlueNaaS will show the output of NEUORN at the end of the simulation, or maybe just in failures of simulation.
I'll explain why, yesterday because of an update to the default of BlueNaaS (specifically the default dt, changed to variable dt), my examples stop working. It took me a good couple of hours to understand that the problem is the change to a variable dt (my mod files [which are from the nmc column] does not support variable dt). 
If I would have seen the output of NERUON, which look like this:
```
NEURON: AMPANMDA_EMS cannot be used with CVODE
 near line 0
 {gCa_HVAbar_Ca_HVA(1.0000000000) = 0.0000555000}
                                                 ^
        CVode[0].active(1)
      NumericalMethodPanel[0].iscvode()
    NumericalMethodPanel[0].isvar()
  NumericalMethodPanel[0].varstep(1)
and others
```

I would understand the problem in **1 second** instead of **5 hours**.

Thanks.

This is the example zip:
https://blue-naas.humanbrainproject.eu/#/url/neuron_reduce/detailed.zip

**Comment by genric** [comment]
Sorry about that @orena1. We didn't anticipate too much those use cases that BlueNaaS will be used to upload/debug models, it was more like me, curating/uploading the models, making sure they work.
And all those recent feature additions just added multiple points of failure. We'll try to improve on that. I think I had before more detailed report log from NEURON which I'll try to bring back.

**Comment by orena1** [comment]
Thanks

**Comment by alex4200** [comment]
@orena1  Can you please check with the example 
https://blue-naas.humanbrainproject.eu/#/url/neuron_reduce/detailed.zip
if that is fine with you (and close the ticket in that case?)

**Comment by orena1** [comment]
Just checked and I can now see the error message, thanks

**Comment by appukuttan-shailesh** [comment]
Just curious.... once we get an error message. Shouldn't the user be allowed to change the parameters on the GUI (such as switch to variable dt, or fixed time dt) and run the simulation again. Currently the "simulation" panel gets disabled and no further simulations can be run.

**Comment by genric** [comment]
For this to work I would need to know how to un'crash the NEURON :) Currently any NEURON failure is treated as critical and the container is cleaned-up. But maybe this one can be recovered from, I'll check with @wvangeit

**Comment by wvangeit** [comment]
I wonder if you could run NEURON in a separate process ? That way at least your main thread wouldn't crash and you could 'recover' by restarting the NEURON process.

Btw, @genric, I saw in the top of this thread that apparently bluenaas uses variable dt by default. You've to be careful with the NMC portal models, because the cells with stochastic channels probably don't work / crash with this setting.
