### ISSUE TITLE
Adding scaffolding model for Striatum to notebook. BLOCKING ITEM: python module mpi4py missing on collab's servers

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#40]
### Expected behavior
Notebook working in the Collaboratory

### Actual Behavior
Notebook works locally. BLOCKING ITEM:   python module mpi4py missing on collab's servers

**Comment by alex4200** [comment]
@lbologna : Can you give details why you need that module on the collaboratory? 

Are you asking for it to be installed as a simple 'pip install mpi4py' will run into errors?


Thanks
Alex

**Comment by jdcourcol** [comment]
it seems strange to require mpi in a collaboratory jupyter kernel.
I think this is for Hjorth not @lbologna

**Comment by Hjorthmedh** [comment]
This has been resolved.
