### ISSUE TITLE
Integrate Medium spiny neuron into model list

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#401]
## Details description of the task
Integrate Medium spiny neuron [model](https://collab.humanbrainproject.eu/#/collab/1655/nav/75901?state=model.2e2b7998-45b0-4075-9a59-beae74939f85) into:
- Morphology visualization
- Single cell in silico experiments (BlueNaaS)

**Comment by antonelepfl** [comment]
@a1eko are the places where your model need to appear correct or it should be added in some other Use Case?

**Comment by a1eko** [comment]
It will be used in the LivePaper we are preparing. For the moment, it is fine if it is simply registered correctly in the Model Catalog.

**Comment by antonelepfl** [comment]
OK you can reopen this ticket when you want the model to appear on the BSP use cases
