### ISSUE TITLE
Model catalog not showing hippocampus models

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#402]
### Expected behavior
The model catalog shows Hippocampus models
### Actual Behavior (please include screenshot if possible)
There are only a couple of models in the whole catalog
### Steps to reproduce the problem
Go to [model catalog](https://collab.humanbrainproject.eu/#/collab/1655/nav/75901?state=model.n) and filter by brain region (Hippocampus). No models are shown.

**Comment by apdavison** [comment]
Can you try now?

**Comment by alex4200** [comment]
@apdavison Now it seems to work. What was the problem?

**Comment by apdavison** [comment]
I've been updating the Model Catalog database to make it more consistent with the Knowledge Graph. Simple things like renaming "Hippocampus" to "hippocampus". It seems this led to some inconsistency in the app configuration. Resetting the latter seemed to fix the problem.

**Comment by alex4200** [comment]
@apdavison: If these updates on the Model Catalog database contain several changes, maybe it is best to open a separate ticket here. Then I can do a quick test after the changes. 

I will close this ticket for now
