### ISSUE TITLE
Blue-NaaS:  can not download voltage trace

### ISSUE THREAD

**Issue by orena1** [cnr-ibf-pa/hbp-bsp-issues#403]
It seems that I can not download a voltage trace from a finished simulation.
This is the simulation:
https://blue-naas.humanbrainproject.eu/#/url/neuron_reduce/simplified.zip?dt=0.025&tstop=2500&dur=0&amp=0&celsius=37

I click here:
![image](https://user-images.githubusercontent.com/8983713/53482540-1b548d00-3a88-11e9-9e90-65be9e233538.png)
but nothing happens, I  tried with firefox and with chrome.

Thanks.
@genric

**Comment by genric** [comment]
I just tried and it worked for me, although it was quite slow to prepare the download. Can you try a shorter simulation(tstop=1000)? I suspect browser might be having troubles handling 100k points...

**Comment by orena1** [comment]
It worked with tstop=500, but not 1000. But I actually need a trace that is 2500 ms long. Can this be corrected? Thanks
@genric  did you try with chrome?

**Comment by genric** [comment]
Yep, doesn't work in chrome anymore, I'll have a look.

**Comment by genric** [comment]
It should work now, @orena1 could you please retry?

**Comment by orena1** [comment]
@genric  I am trying to test, but the website: https://blue-naas.humanbrainproject.eu/ does not load

**Comment by genric** [comment]
Hmm, not an improvement I was expecting :)
Could you please send me the logs from the JavaScript web console of your browser? And did you try it from multiple browsers?
@alex4200 does it work for you?

**Comment by orena1** [comment]
OK, now it works!
But now its stuck at this state for much longer:
![image](https://user-images.githubusercontent.com/8983713/53570689-c55b1480-3b6f-11e9-9218-6e920ca7a587.png)

It is good enough for me, but maybe it would be better to show a higher resolution trace (but not full resolution), and have some sand-clock that show that the full resolution trace is loading.

Anyway, thanks!

**Comment by genric** [comment]
Yes, I'll try to improve this. Thanks for you feedback!

**Comment by alex4200** [comment]
@genric, @orena1 Can this ticket be closed?

**Comment by alex4200** [comment]
Download seems to work on FF and GC.
