### ISSUE TITLE
Missing information about groups in Jureca and Piz-daint

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#404]
### Expected behavior
All HPC should work correctly with Unicore.
### Actual Behavior (please include screenshot if possible)
When I try to submit a job in the different HPC I get different errors:

- NUVLA:
```
Could not submit job: eu.unicore.security.AuthorisationException: There are no accessible targetsystem factories for: Name: CN=ANONYMOUS,O=UNKNOWN,OU=UNKNOWN↵Xlogin: uid: [], gids: [addingOSgroups: true]↵Role: anonymous: No role information available↵Security tokens: Delegation to consignor status: false, core delegation status: false↵Message signature status: UNCHECKED↵Client's original IP: 128.179.156.98 Please check your security setup!
```

- PIZ_DAINT & JURECA
I have missing information in /core.
Available Groups does not appear on client.xlogin.**availableGroups**

@BerndSchuller 
Could you please check those systems and let update the status on this ticket?

HPC working:
- [x] Nuvla
- [x] Jureca
- [x] Piz-daint

**Comment by BerndSchuller** [comment]
at the moment there is a problem with the authentication (Unity server) for the whole UNICORE infrastructure. Since the admins are on holiday it might take some time to find out what the problem is and get it fixed

**Comment by BerndSchuller** [comment]
luckily a restart of the Unity server has already helped - the authentication should be back to normal

**Comment by antonelepfl** [comment]
Thank you Bernd for the update
