### ISSUE TITLE
Update "Live Papers" item on BSP Menu

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#405]
## "Live Papers" Update

Link on BSP: https://collab.humanbrainproject.eu/#/collab/1655/nav/306845

Aspect | Detail
------------ | -------------
Summary | Direct link to individual "Live Papers" have been replaced with an HTML page
Expert | @lbologna 
Deadline | M12
Dependencies | None
 

## List of additional/changed features 

Direct links to Collabs created for individual "Live Papers" have been replaced with an HTML page containing both a link to an external page and a link to the live paper related collab.
Additionally, a paper by Lindroos et al. (2018) has been added to the paper list
*mandatory*

### Tasks

- [x] Insert Index page for "Live Papers" in the BSP
- [x] Insert Lindroos et al. (2018) paper

## Acceptance Criteria
All links of the index page and on the individual "Live Papers" work correctly.

**Comment by alex4200** [comment]
The implementation seems to work fine, all links seem to work from either place. Closing ticket,
