### ISSUE TITLE
Tools providing web-access to molecular level tools for guiding systems level modelling

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#408]
## New Use Case
  
Aspect | Detail
------------ | -------------
Summary | C1997 (Platforms providing web-access to molecular level tools for guiding systems level modelling)
Usecase Group | Molecular Level
Expert | Adam Hospital, Aurélien Luciani (IRB Barcelona)
Scientific User |
Deadline | M18
Target audience | New users of molecular modelling/simulation tools
Target interface | GUI and notebooks (latter for tutorials)
HPC Requirements | none
Dependencies | nglview, GROMACS, BioExcel building blocks library (biobb), ACPype, Ambertools, OpenBabel
Nominal runtime |

## Use case 1: Preparing a protein to run an atomistic Molecular Dynamics simulation

DEV SETUP: https://collab.humanbrainproject.eu/#/collab/62174/nav/426322
DEV: https://collab.humanbrainproject.eu/#/collab/62174/nav/423317

Running a Molecular Dynamics setup from a protein in PDB format to obtain a system ready to be used as input for an MD simulation. Using [GROMACS](http://www.gromacs.org/) MD package and the [building blocks library](https://github.com/bioexcel/biobb) from the [BioExcel](http://www.bioexcel.eu) project.

### Mandatory features
- Takes as input a [PDB format](http://www.wwpdb.org/documentation/file-format) file describing the 3D atomic structure of a protein.
- Model missing information (amino acids side chains, hydrogen atoms).
- Energetically minimize the protein with the newly added atoms.
- Add solvent box surrounding the protein.
- Add counter ions to neutralize the charge and/or reach a desired ionic concentration.
- Energetically equilibrate the whole system (protein + solvent + ions).
- Run a short free MD simulation to check for a correct system equilibration.

### Important features
- Visualize the intermediate structures using nglview jupyter widget.

### To do
- [x] Create the jupyter notebook with all the required dependencies.
- [x] Write markdown cells with information about the workflow and the different steps.
- [x] Test the workflow with different input proteins.
- [x] Make the notebook publicly available.

## Use case 2: Small molecule force field parametrization for atomistic Molecular Dynamics simulations

DEV SETUP: https://collab.humanbrainproject.eu/#/collab/62050/nav/426321
DEV: https://collab.humanbrainproject.eu/#/collab/62050/nav/422512

Generate force field ([GAFF](http://ambermd.org/antechamber/gaff.html)) parameters for a small molecule in PDB format to use it in atomistic Molecular Dynamics simulations. Using [ACPype](https://github.com/alanwilter/acpype), [Ambertools](http://ambermd.org/AmberTools.php) and [OpenBabel](http://openbabel.org/wiki/Main_Page) programs, and the [building blocks library](https://github.com/bioexcel/biobb) from the [BioExcel](http://www.bioexcel.eu) project.

### Mandatory features
- Takes as input a [PDB format](http://www.wwpdb.org/documentation/file-format) file describing the 3D atomic structure of a small molecule.
- Model hydrogen atoms from a desired pH.
- Energetically minimize the molecule with the newly added atoms.
- Generate the force field parameters using ACPype.

### Important features
- Visualize the intermediate structures using nglview jupyter widget.

### To do
- [x] Create the jupyter notebook with all the required dependencies.
- [x] Write markdown cells with information about the workflow and the different steps.
- [x] Test the workflow with different input small molecules.
- [x] Make the notebook publicly available.

## Use case 3: Preparing a protein-ligand complex to run an atomistic Molecular Dynamics Simulation

DEV SETUP: https://collab.humanbrainproject.eu/#/collab/62053/nav/426323
DEV: https://collab.humanbrainproject.eu/#/collab/62053/nav/422538

Running a Molecular Dynamics setup from a protein-ligand complex in PDB format to obtain a system ready to be used as input for an MD simulation. Extending the use case 1 (MD setup) adding a small molecule. Using [GROMACS](http://www.gromacs.org/) MD package and the [building blocks library](https://github.com/bioexcel/biobb) from the [BioExcel](http://www.bioexcel.eu) project.

### Mandatory features
- Takes as input a [PDB format](http://www.wwpdb.org/documentation/file-format) file describing the 3D atomic structure of a protein-ligand complex.
- Take force field parameters for the ligand from the [CNS API](http://mmb.irbbarcelona.org/webdev/slim/CNS/public/api) (when available), or generate them using the notebook from use case 2.
- Model missing information (amino acids side chains, hydrogen atoms).
- Energetically minimize the complex with the newly added atoms.
- Add solvent box surrounding the complex.
- Add counter ions to neutralize the charge and/or reach a desired ionic concentration.
- Energetically equilibrate the whole system (protein-ligand + solvent + ions).
- Run a short free MD simulation to check for a correct system equilibration.

### Important features
- Visualize the intermediate structures using nglview jupyter widget.

### To do
- [x] Create the jupyter notebook with all the required dependencies.
- [x] Write markdown cells with information about the workflow and the different steps.
- [x] Test the workflow with different input protein-ligand complexes.
- [x] Make the notebook publicly available.

**Comment by alex4200** [comment]
Update from @aurel-l 15.4.2019:

```
The progress I've made is mainly on the website we are planning on using to present user with protein dynamics simulation data and visualisations (mainly, integrating a PCA analysis).
We still need to add more simulations that we have in our folders to our exposed data.
This week I'll get back to working on redacting some text and documentation for the guidebook and see how what we have fits within the platform. And also trying to gain access to the colllab's storage from with our embedded websites.
```

**Comment by adamhospital** [comment]
We have been in contact with the HBP support regarding the possibility to connect our jupyter notebooks with HPC centers. Dr. Bernd Schuller from Jülich sent us some examples on how to do it, and it looks promising. We will work on that and present what we found in the next technical meeting.

**Comment by clupascu** [comment]
@adamhospital of course you can count also on my help as I already have some experience on connecting jupyter notebooks with HPC centers. Please contact me if you need help.

**Comment by alex4200** [comment]
@adamhospital @aurel-l  Is there any progress with the notebooks/use cases? Are DEV versions available? What is the timeline for putting them into the brain simulation platform?

**Comment by adamhospital** [comment]
Hi, we have dev versions in our own premises, still working on them. Will try to upload some of them to the platform before August.

**Comment by adamhospital** [comment]
https://collab.humanbrainproject.eu/#/collab/62174/nav/423317

**Comment by alex4200** [comment]
@adamhospital I took a look at the notebook and it basically seems to work. However I have two comments:

- Instead of naming the setup notebook just `Initial Setup Process` I rather would name it a bit more specific, like `Molecular Dynamics Setup Process` (to make sure for the user that this is a Setup especially for the Molecular Dynamics notebooks, and not possibly other notebooks)¨
- I tried to run the notebook with two user accounts, and in one I saw just  an output `NGLWidget():`instead if an image:

![Screenshot 2019-09-06 at 08 51 18](https://user-images.githubusercontent.com/12729291/64407263-3847c980-d084-11e9-92be-8ab89679fb3a.png)

Any ideas? 

I also updated the ticket above to include the location of the DEV notebook.

**Comment by adamhospital** [comment]
Name of the setup notebooks changed to **_Working environment setting up for the "XXX" Notebook_**
No ideas for the NGLWidget problem, as I could not reproduce the error. @aurel-l can test it with his user next week and it would be good if more users could test it as well.

**Comment by adamhospital** [comment]
Use cases 1 to 3 updated with links to the notebooks.
DEV SETUP notebook needs to be run previously to setup the working environment and install all the dependencies needed.
DEV notebook is the notebook implementing the use case.

**Comment by alex4200** [comment]
The notebooks 1-3 seem to work fine on the technical side. However some questions/comments:

- Do each notebook require its own setup notebook? Or would it be possible to just have one single setup notebook to prepare the environment for all notebooks? Also can it be increased?
- When some cells have been ran, there is a big red box with some debugging information. Is there a way to turn it off, or to change the background color (as red usually implies an error)?

**Comment by adamhospital** [comment]
- **_Do each notebook require its own setup notebook?_** 
- **_Or would it be possible to just have one single setup notebook to prepare the environment for all notebooks?_**

Having one single setup would mean installing a collection of software which are not needed by all the notebooks. For instance, use case 2 (small molecule parameterization) just needs a couple of conda packages, whereas use case 3 (protein-ligand complex) needs 7, with some of them having big software tools such as GROMACS (installed as a dependency in the conda biobb_md package). It can be done, but it should be made clear that not all the dependencies being installed will be actually required to run a particular use case. Besides, conda packages are not re-installed, if they are already present in the system, the conda management system will just skip the process.  

- **_Also can it be increased?_**

Yes, use cases 4 to 6 could have different requirements, thus increasing the number of dependencies if using a single setup notebook.

- **_When some cells have been ran, there is a big red box with some debugging information. Is there a way to turn it off, or to change the background color (as red usually implies an error)?_**
 
Jupyter notebooks are displaying these output red boxes (cells) by default as **python logging** has been configured to stream over **stderr** (see https://www.dataquest.io/blog/advanced-jupyter-notebooks-tutorial/#configur5ing%20logging). 
@aurel-l kindly prepared a short javascript to change this functionality, designating different colours according to the level of logging (INFO, WARNING, ERROR). Now it is included in all the dev use cases (1 to 3), and can be disabled if users prefer to keep using the jupyter default behaviour.

**Comment by alex4200** [comment]
@adamhospital The first three notebooks are public now. What is missing is some piece of documentation for these use cases in the Guidebook. See [here](https://docs.google.com/document/d/19Ni5fGFv6PTTM1D_D2FN4dj5IRhtfq1D0V2OWjXxJww/edit#heading=h.u3wb1gexvzd9).

Also, how to test the notebooks with different input proteins? Where and what to change?
