### ISSUE TITLE
New use case groups for new use cases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#409]
## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | Creating two new usecase groups in the BSP named "Molecular level" and "Subcellular level".
Expert | Stefano
Deadline | when time (not that urgent)
Dependencies | none
 

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

## Acceptance Criteria
Two new groups are visible

**Comment by antonelepfl** [comment]
I'll create those items when we have the use cases (web apps or notebooks) defined
