### ISSUE TITLE
Unsymmetric Loading gif for "feature_extraction"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#41]
### Expected behavior

The loading wheel is symmetric

### Actual Behavior

The loading wheel woobles

### Steps to reproduce the problem

Just follow the example steps, its the screen just before the results are ready to be downloaded.

### Optional infrastructural data (user, platform, browser, environment, ...)

Firefox

![selection_049](https://user-images.githubusercontent.com/12729291/31663597-e9db2504-b342-11e7-911a-8faf050eb935.png)

**Comment by lbologna** [comment]
This should be fixed now. Would you check again please?
Thanks.

**Comment by alex4200** [comment]
@lbologna: Hi Luca, has there been a change in the GUI? The title section seems to have changed, which leads to new issues:


![selection_067](https://user-images.githubusercontent.com/12729291/32436032-0b7763a8-c2e3-11e7-94e4-2bd33a58618d.png)

**Comment by alex4200** [comment]
Fixed
