### ISSUE TITLE
Add Different colors fo the different types of cells on analysis

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#412]
### Expected behavior
The Raster plot will show different colors for the Exc and Inh cells.
### Actual Behavior (please include screenshot if possible)
The color is the same for all the types of cells.
### Steps to reproduce the problem
Run an analysis and the plot has only one color.

**Comment by antonelepfl** [comment]
@romani79 If you have ever used this functionality on BluePy please point me to a notebook or code that I can see how is done.

**Comment by romani79** [comment]
You can use the option groupby to have different color schemes in the raster plot.
For example:

from bluepy.v2.enums import Cell
sim.v2.plot.raster(gids, t_start=0, groupby=Cell.MORPH_CLASS) colors the excitatory and inhibitory cells differently.

**Comment by antonelepfl** [comment]
Would this feature replace the https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/413 functionality? I mean if we colored those items would you need to be able to select Inh-Exc?

**Comment by romani79** [comment]
Coloring Inh-Exc is useful to better read a raster which contains both populations.
Plotting only Inh and Exc is useful to look more specifically into those sub-populations.

**Comment by alex4200** [comment]
So far it seems to work. However, a legend for the colors would be good. 
But I guess this would require a change in the plotting code. This code also seem to have a bug:

Should be:

```
def _plot_spikes(gids, offset=0, label=None):
    """ Scatter plot spike times for given GIDs. """
    spikes = slf._sim.spikes.get(gids=gids, t_start=t_start, t_end=t_end)
    
    ts = spikes.index
    ys = offset + np.unique(spikes, return_inverse=True)[1]
    ax.scatter(ts, ys, s=10, marker='|', label=label)
    ax.legend()
```

**Comment by antonelepfl** [comment]
I would suggest to create a ticket in BluePy for this.
But in the meantime we can close this issue if it works

**Comment by alex4200** [comment]
Agreed
