### ISSUE TITLE
Avoid forcing the user to select stimulus and report

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#414]
### Expected behavior
You can submit jobs without Stimulus (it will use the spon-mins in the connections) or without reports.
### Actual Behavior (please include screenshot if possible)
We force the user to select Report & Stimulus
### Steps to reproduce the problem
Remove the stimulus or the report and click Continue. A popup should appear.

Steps to implement this
- [x] Allowing zero reports on timeline
- [x] Check for visualization compatibility
- [x] Check if Brayns can visualize spike-times (out.dat) [Yes it is possible but need some work to convert it into a plug-in]
- [x] Check report content for Analysis plots (e.g. blank out voltage traces)
- [x] Avoid pulling reports for analysis in Notebook

**Comment by antonelepfl** [comment]
Currently I'm not forcing the user to select any report but I realized that I need at least one report to run the analysis (voltage traces) and the visualization.
@romani79 Do you think we can restrict the user to select at least one report so we make sure that the analysis will work?

**Comment by antonelepfl** [comment]
@alex4200 I have implemented this on [DEV](https://bbp.epfl.ch/public/dev.simulationapp/index.html#/circuits/microcircuit)

**Comment by alex4200** [comment]
Tested and working. Needs to be deployed on production
