### ISSUE TITLE
Stimuli for SimUI

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#416]
### Expected behavior

Selectable stimuli make sense and are documented/explained.

### Actual Behavior (please include screenshot if possible)

Current stimuli are not clear how they work exactly. Also the stimuli useful for Armando might be missing (threshold bases noise stimuli with mode=current. Should have fields like _MeanPercent_ and _Variance_.)

**Comment by antonelepfl** [comment]
For this I would like to know:
1) ALWAYS that you use Noise stimulus you use the hyperpolarization?
2) This is for the full scale AND the microcircuit?
3) Would you hipperpolarize with another type of stimulus other than noise?

**Comment by romani79** [comment]
First of all we have to distinguish 4 use cases:
1. What I do
2. what a student should do in the MOOC
3. what a BSP user should do
4. what the simulator allows to do

So...
1. I normally run simulations without any stimulus. Only for testing I insert the following blocks in the BlueConfig:

```
Stimulus Threshold
{
	Mode Current
        Pattern Noise
        MeanPercent 95
        Variance 0.001
        Delay 500
        Duration 3500
}

StimulusInject ThresholdIntoAll
{
        Stimulus Threshold
        Target Mosaic
}

Stimulus hypamp
{
        Mode Current
  Pattern Hyperpolarizing
        Delay 0.0
  Duration 3500.0
}

StimulusInject hypamp_mosaic
{
        Stimulus hypamp
        Target Mosaic
}
```

In the past, I also used to add extra synapses on each neuron and activate them with poisson inputs

```
Stimulus SC-PC
{
    Mode Current
    Pattern NPoisson
    # mean frequency
    Lambda 5
    # synapse type
    # SynapseConfigure ExpSyn
    # addition synapses per neuron
    NumOfSynapses 100
    # synaptic weight (nS) of additional synapses
    Weight 0.2
    Delay 100.000000
    Duration 300.000000
}
```

This is not necessary anymore, since we have projections.

2. In the MOOC, I expect that the student does no more than what I do
3. Here, I think we should guarantee functions in 1 and 2, and slowly include functions in 4.
4. For the complete functionality, you should ask HPC.

**Comment by mmigliore** [comment]
A real user need to do in silico experiments. 
This means that a user must be able to independently control the number and the frequency of the stimulation. Typical cases of stimuli are those delivered during syn plasticity protocols: constant frequency and theta bursts (a series of up to 4 activations at 100-200Hz, repeated a given number of times (10-100) at a frequency of 0.1-0.5 Hz.

**Comment by alex4200** [comment]
At first I think it makes sense to decide which  stimuli should be used in the SimUI. From the comment of @romani79  I assume the only stimuli that would be useful is the Poisson stimuli. Do I understand that correctly? 

So then all the other 10 possible stimuli can be taken out from the GUI?

**Comment by antonelepfl** [comment]
I would suggest to leave a couple of them:

Stimulus | Properties
------------ | -------------
Linear | ['AmpStart', 'AmpEnd']
Pulse |  ['Width', 'Frequency', 'Offset']
NPoisson | ['Lambda', 'Weight', 'NumOfSynapses']
Noise | ['MeanPercent', 'Variance']

**Noise** will include the 2 blocks that Armando mentioned (hypamp and Threshold)

**Comment by mmigliore** [comment]
Would these be in addition to those needed to implement syn plast protocols?

**Comment by romani79** [comment]
> At first I think it makes sense to decide which stimuli should be used in the SimUI. From the comment of @romani79 I assume the only stimuli that would be useful is the Poisson stimuli. Do I understand that correctly?
Indeed, the stimulus I am currently using is the 'Threshold' not the NPoisson. Anyway, I would suggest to implement both.

**Comment by jdcourcol** [comment]
> This means that a user must be able to independently control the number and the frequency of the stimulation. Typical cases of stimuli are those delivered during syn plasticity protocols: constant frequency and theta bursts (a series of up to 4 activations at 100-200Hz, repeated a given number of times (10-100) at a frequency of 0.1-0.5 Hz.

@romani79 @mmigliore do we have a blueconfig with that somewhere ? so that we can reuse them as example for the implementation ?

**Comment by mmigliore** [comment]
Unfortunately no. As far as I know, one cannot even implement a stimulation
different from poisson in the model circuit. This is something that needs
to be implemented asap.

**Comment by romani79** [comment]
@mmigliore be aware that to the best of my knowledge the stimuli mentioned above refers to stimuli delivered via current injection or to additional synapses. Those additional synapses are just built-in simple exp synapses, which were used in the lack of projections.
If we decide to include only relevant stimuli and not to map exactly all the features of our simulator, I think the case I mentioned above (Mode Current, Pattern Noise) is sufficient for the time being.
Probably, you are looking for the possibility to deliver a pattern through the projection. This can be done by writing exactly the spike times of the presynaptic cells and set up the BlueConfig accordingly (a procedure which is called 'reply'). I am working on a new version of the projections which will allow that.
To me the ticket is solved.

**Comment by mmigliore** [comment]
No problems. Solved.
