### ISSUE TITLE
Pass to BluePy time for create plots from simulation configuration.

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#419]
### Expected behavior
The plots are render from the simulation time
### Actual Behavior (please include screenshot if possible)
As we are passing _t_start_ None to bluepy the plots start from negative time producing a wrong plot.

**Comment by antonelepfl** [comment]
I have already implemented this fix on Jureca, Piz-Daint and Nuvla

**Comment by alex4200** [comment]
Tested and seems to work
