### ISSUE TITLE
Server error when loading efel GUI from Hodgkin-Huxley neuron builder web app

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#42]
### Expected behavior
Page to be loaded correctly

### Actual Behavior
Occasional crashing of the page with Server Error message

**Comment by alex4200** [comment]
@lbologna: Could you give some steps to reproduce this problem? Is it a use case you refer to?

**Comment by lbologna** [comment]
The problem does not always rise, actually quite rarely, so the steps to reproduce it are not clear.
I am parsing the log files and it seems that the bug depends on the token lifetime: but this is still under investigation.

I will update the issue status as soon as the reasons are clarified.

**Comment by alex4200** [comment]
@lbologna Are there any updates on this issue? Do the problems still occur?

**Comment by alex4200** [comment]
still ongoing ...

**Comment by alex4200** [comment]
@lbologna : Issue will be closed after a few more days when it is made sure the issue is likely solved. 

Ticket will be reopened if the problem will occur again...

**Comment by lbologna** [comment]
After freeing the /boot partition on the vm hosting the web application and increasing the session expiration time, the server error seems solved when the common pipeline operations are performed.

Could you please check again?

Thanks.

**Comment by alex4200** [comment]
Ok, looks good at the moment. Will close the ticket...
