### ISSUE TITLE
Add Eyal et al 2018 to Live Papers

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#420]
## Live Paper page update
 
Aspect | Detail
------------ | -------------
Summary |  Add Live Paper for Eyal et al 2018 in the BSP Live Paper
Expert | @lbologna 
Deadline | M12
Dependencies | None
 
## List of additional/changed features 
* Add a new Live Paper document for Eyal et al 2018 to the BSP Live Paper page

### Tasks

- [x] Add document
- [x] Create collab for the new Live Paper
- [x] Check that all links work

## Acceptance Criteria
All links in the live paper work and all images and animation are correctly visualized

**Comment by lbologna** [comment]
The new Live Paper document for Eyal et al 2018 has been added to the Live Paper page.
All links seem to work.

@alex4200 could you please perform a final check and let me know if something does not work correctly? Thank you

**Comment by genric** [comment]
@lbologna, Alex is on vacation this week.

**Comment by genric** [comment]
I've checked the links:
* The link for the first Cell_130303 is broken for the BlueNaaS. It looks weird because under the same name the link in model catalog points to: cell1303_03_model_448.zip and for the BlueNaaS it is: cell1303_03_model_643.zip(which doesn't exist in the storage container)
* Cell_130305 looks also broken: there is hoc error.
  ```
  could not open morphology/2013_03_13_cell05_675_H42_04.asc
  NEURON: morphology/2013_03_13_cell05_675_H42_04.asc :file is not open
  ```

**Comment by orena1** [comment]
I'll check it now, thanks

**Comment by orena1** [comment]
> The link for the first Cell_130303 is broken for the BlueNaaS. It looks weird because under the same name the link in model catalog points to: cell1303_03_model_448.zip and for the BlueNaaS it is: cell1303_03_model_643.zip(which doesn't exist in the storage container)

Fixed with this:
https://github.com/HumanBrainProject/hbp-bsp-live-papers/pull/5

> Cell_130305 looks also broken: there is hoc error.

I'm not sure why we get an error, it works in my computer, also I can not see the error message in the chrome console.

**Comment by genric** [comment]
> Cell_130305 looks also broken: there is hoc error.

The issue there is the morphology file extension. It has lowercase `asc` in the hoc template and the actual file extension is all caps: `2013_03_13_cell05_675_H42_04.ASC`(I guess if you are on Windows then this doesn't make a difference).
And the error message is a bit too generic, I agree. Will try to improve it.

**Comment by orena1** [comment]
Thanks @genric nice catch, I've fixed it now (Using Mac)

**Comment by genric** [comment]
Looks like all links are working now.

**Comment by alex4200** [comment]
Retested it, seems to work.
