### ISSUE TITLE
hbp-service-client "'Client' object has no attribute 'download_file'"

### ISSUE THREAD

**Issue by SteMasoli** [cnr-ibf-pa/hbp-bsp-issues#422]
### Expected behavior
To download files from the BSP collaboratory storage with hbp-service-client 1.0.0 and 1.1.1

### Actual Behavior (please include screenshot if possible)
clients.storage.download_file('/BSP/OnlineUseCases/SingleCellModeling/Cerebellum_Opt/GrC_mono_collab/GrCmorphmono.mod', 'GrCmorphmono.asc');

AttributeErrorTraceback (most recent call last)
<ipython-input-16-2fb405fa7b2d> in <module>()
----> 1 clients.storage.download_file('/BSP/OnlineUseCases/SingleCellModeling/Cerebellum_Opt/GrC_mono_collab/GrCmorphmono.asc', 'GrCmorphmono.asc');

### Steps to reproduce the problem

Clone in a new collab the cerebellar mono compartmental granule cell and run it.

**Comment by clupascu** [comment]
Try with hbp-service-client 1.1.0. I am using this one and I can download files successfully.

**Comment by SteMasoli** [comment]
With 1.0.0 now it works.
This issue is still generated when the image, with all the modules, is upgraded or changed.
I think that a warning, to restart the kernel after an image upgrade and a series of new pip installs, could be a good idea.
