### ISSUE TITLE
E-models appearing on Single Cell category in Model Catalog

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#423]
Hi @rmiglior,
I see that there are now a couple of E-Models appearing on the Single Cell category 
As you can see here:

![Screenshot 2019-03-28 at 10 54 38](https://user-images.githubusercontent.com/24406041/55148174-03842d80-5148-11e9-9386-ae456c67be32.png)

The issue that before I had under that category the result of the optimization (with their Morphology and a representative trace plot) but now these E-Models don't have any of that information (at least attached) and the optimization for that E-Model is already on the list.

Could we create another category or let me know the way I can distinguish between the E-Models and the Optimizations? Mainly because if we have the same category in the BSP we will get a list of Models that may look like:
 
![Screenshot 2019-03-28 at 10 59 19](https://user-images.githubusercontent.com/24406041/55148477-92914580-5148-11e9-8fd9-bccbc1153dd3.png)

And I don't think is what the user will expect to see.

**Comment by clupascu** [comment]
Hi @antonelepfl,
where do you fetch the E-Models from?

**Comment by antonelepfl** [comment]
I just fetch the list of Single Cells and the e-models are there

**Comment by clupascu** [comment]
Where do you fetch from the list of Single Cells?

**Comment by appukuttan-shailesh** [comment]
@antonelepfl , @clupascu : These were created by me, as part of the process of running the validation on the BluePyMM output models (as discussed on Hippocampus VC recently).

These entries would all be migrated to the KG soon (coming weeks?). The KG has finer resolution to distinguish between the kinds of models (E-model vs ME-model). Before this migration happens, we needed a temporary way to identify the entries corresponding to E-models and thus their naming with prefix `emodel-`. I imagine it would be possible for you to filter out these entries (using the prefix) and continue as before with the remaining entries.

**Comment by appukuttan-shailesh** [comment]
Also, can you let me know the filters you are currently using to identify the "optimizations"?

**Comment by antonelepfl** [comment]
Before for the Hippocampus Models I was just doing
`https://validation-v1.brainsimulation.eu/models/?brain_region=hippocampus&organization=HBP-SP6&model_scope=single%20cell&species=Rattus%20norvegicus`

**Comment by clupascu** [comment]
@antonelepfl But essentially I think you should list only optimizations. Maybe the E-Models are used for other use cases, but not for the Single Cell Building. As you are saying the optimizations for those E-Models are already on the list anyway.

**Comment by antonelepfl** [comment]
I know that I can iterate thru the entire list of models and select those which are optimizations. My point is that I would like to use Model Catalog to find specifically what I want and not to pull most of the models to then iterate manually.
As Shailesh mentioned those e-models will be categorized better when the full integration with the KG is done. Just @appukuttan-shailesh keep me updated.

**Comment by appukuttan-shailesh** [comment]
Resolved as part of temporary fix for #437 
It can be closed after @antonelepfl  confirms this is no longer an issue.

**Comment by antonelepfl** [comment]
You can close this now
