### ISSUE TITLE
Morphology Analysis it not using updated morphology files

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#424]
### Expected behavior

Use case 'Morphology Analysis' uses the updated files from the [morphologies repo](https://github.com/lbologna/bsp_data_repository/tree/master/optimizations)

### Actual Behavior (please include screenshot if possible)

When cloning the use case the old files are being used. 

### Steps to reproduce the problem

Just clone one example of the use case, it will fail in the second code cell.

**Comment by antonelepfl** [comment]
Could you test on DEV and if it's ok we can PR to PROD?

**Comment by alex4200** [comment]
@antonelepfl  Tests on DEV works fine. 

And it looks like the notebook itself has changed slightly.

**Comment by antonelepfl** [comment]
Yes it has changed because I'm getting the morphology from the Model Catalog instead of the Github

**Comment by alex4200** [comment]
In prod and working, automated tests fine as well.
