### ISSUE TITLE
Name of NSG simulation for Synaptic Events Fitting mising

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#426]
### Expected behavior

When I run a simulation on NSG for the use case "Synaptic Events Fitting" and name the simulation, I expect the name to see on the "Analysis" notebook. 

### Actual Behavior (please include screenshot if possible)

In the Analysis notebook I see only 'true' due to a change in the NSG API:

![Selection_662](https://user-images.githubusercontent.com/12729291/55944869-d35d8400-5c49-11e9-9837-72c3989d4001.png)

### Steps to reproduce the problem

1. Start a demo simulation "Synaptic Events Fitting" on NSG, and give the simulation a name
2. Wait until simulation has finished
3. Run the "Analysis" notebook and check the NSG simulations

### Optional infrastructural data (user, platform, browser, environment, ...)

NSG used

**Comment by clupascu** [comment]
The issue should be fixed now. Can you test again please? I updated the notebooks.

**Comment by alex4200** [comment]
The naming of the jobs seems to work now (on DEV; I get the correct name in the "Synaptic events fitting with analysis" notebook, but the date seems to be off (1.4. instead 23.4.). 

I submitted a job today ("Test NSG 0423") but its date is off:

![Screen Shot 2019-04-23 at 10 11 09](https://user-images.githubusercontent.com/12729291/56565213-26bbc480-65b0-11e9-97ac-d0dbc18227c5.png)

**Comment by clupascu** [comment]
@alex4200 Is this issue still valid? I checked now and the date is on.

![Schermata 2019-04-24 alle 11 57 13](https://user-images.githubusercontent.com/22050958/56651000-6fdf4780-6688-11e9-8419-4ac15bf95ab8.png)
