### ISSUE TITLE
Code error for Validation use cases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#428]
Affected use cases:
- BasalUnit_usecase
- BG_Morphology_Validations

### Expected behavior

Use case runs without error.

### Actual Behavior (please include screenshot if possible)

Full error (after having selected "n" for using an existing model uuid). 

```
ExceptionTraceback (most recent call last)
<ipython-input-17-8435c149d415> in <module>()
     28                                 brain_region="basal ganglia",
     29                                 species="Mus musculus",
---> 30                                 description="This model is being used to demonstrate use of the Validation Service")
     31     model_uuid = str(model_uuid)
     32     print("\nModel registered on the HBP Validation Framework's Model Catalog!")

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/__init__.pyc in register_model(self, app_id, name, alias, author, organization, private, species, brain_region, cell_type, model_scope, abstraction_level, owner, project, license, description, instances, images)
   1589 
   1590         if cell_type not in values["cell_type"]:
-> 1591             raise Exception("cell_type = '" +cell_type+"' is invalid.\nValue has to be one of these: " + str(values["cell_type"]))
   1592         if model_scope not in values["model_scope"]:
   1593             raise Exception("model_scope = '" +model_scope+"' is invalid.\nValue has to be one of these: " + str(values["model_scope"]))

Exception: cell_type = 'Other' is invalid.
Value has to be one of these: ['Golgi cell', 'L1 neurogliaform cell', 'L2 inverted pyramidal cell', 'L2/3 chandelier cell', 'L2/3 pyramidal cell', 'L4 Martinotti cell', 'L5 tufted pyramidal cell', 'L6 inverted pyramidal cell', 'Purkinje cell', 'cholinergic interneuron', 'fast spiking interneuron', 'granule cell', 'hippocampus CA1 basket cell', 'hippocampus CA1 ivy neuron', 'hippocampus CA1 lacunosum moleculare neuron', 'hippocampus CA1 pyramidal cell', 'interneuron', 'medium spiny neuron', 'medium spiny neuron (D1 type)', 'medium spiny neuron (D2 type)', 'not applicable', 'other', 'pyramidal cell', 'spiny stellate neuron']
```

![Selection_676](https://user-images.githubusercontent.com/12729291/56351622-d61e2300-61cd-11e9-9d78-b505f9427fbd.png)

### Steps to reproduce the problem

1. Clone the notebook from PROD or DEV (same content as of 18.4.2019)
2. Run it cell by cell. 
3. Choose Cell Type = msn_d2
4. Do you wish to use an existing `model_uuid` -> "n"

### Optional infrastructural data (user, platform, browser, environment, ...)

DEV  notebooks (within 'UseCases Source Files) in collab 8123.

**Comment by appukuttan-shailesh** [comment]
Problem was in Cell 5..... API now required `other` instead of `Other`. Fixed now.

@alex4200 :
I propose disabling all the validation related UseCases till the move to KG is completed. It would be better to fix and test the various issues all at once, than doing temporary patchwork. (I feel it is wasting a lot of time spent on debugging, testing and fixing issues at this point.)

@apdavison: Do you think this is fine?

**Comment by alex4200** [comment]
@appukuttan-shailesh  Yes I think that is a good idea. 

@antonelepfl : Is it possible to deactivate all validation use cases in the BSP for now?

**Comment by apdavison** [comment]
The process of standardizing the existing model catalog database is now finished, so there shouldn't be any further such breakages, i.e. it shouldn't be necessary to disable the use cases.

**Comment by appukuttan-shailesh** [comment]
The UseCases have been updated. But I propose we wait 1-2 weeks for the KG version of validation app to be released, before initiating the testing of the use cases.

@alex4200 : I shall update you once it is ready for testing.

**Comment by appukuttan-shailesh** [comment]
@alex4200 :
All the five validation usecases have been updated (as mentioned above). We ran into some unexpected minor issues with the KG integration aspects. Since most are on vacation currently, this would take a while to be resolved. I spoke to Andrew about this, and we decided to "cover up" the bugs so that the usecases, and more importantly the KG integration, can be further tested by you.

Do note that these might not be fit for production use at the moment (we can determine after your own testing), and so we basically want you to dig out other possible issues so that all these can be fixed all at once once people are back.

So be expecting to find bugs and poor performance on the KG integration part. It would be great if you can dig out and post here all the different issues you encounter. Fixes for these would probably be available only after a few weeks.

Note: the KG-based validation apps (Model Catalog app, Validation Framework app) are currently on a 'slowish' server, and thus the performance isn't great. So ignore the speed for the time being, unless it is unusably slow (e.g. >1 min for opening a page). @apdavison intends to apply for a VM on CSCS to run this service in future, which should provide much better performance.

**Comment by alex4200** [comment]
@appukuttan-shailesh Thanks for the info. Is it correct that the notebooks are mostly the same, and the Knowledge graph handling is done within a new version of hbp_validation_framework only?

**Comment by appukuttan-shailesh** [comment]
Yes, that is true. And inside the notebooks this is employed by setting
`environment = "integration"` for the ModelCatalog and TestLibrary.

**Comment by alex4200** [comment]
@appukuttan-shailesh Currently I get a 500 error in the third cell for the `Basal Ganglia Morphology Validation` use case. Is there something not running?

**Comment by alex4200** [comment]
@appukuttan-shailesh In the `Basal Ganglia Morphology Validation` (and with a different test user) I now get an error in the cell after `Part 1: Hard Constraints Validation`: 
```

ImportErrorTraceback (most recent call last)
<ipython-input-17-370598d92b5c> in <module>()
     13     else:
     14         test_alias = "basalg_fs_morph_hardChecks"
---> 15     result_id, score = utils.run_test(username=HBP_USERNAME, environment="integration", model=morph_model, test_alias=test_alias, test_version="1.0", storage_collab_id=collab_id, register_result=True, client_obj=testLibrary)
     16     result_uuids.append(result_id)
     17 

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/utils.pyc in run_test(username, password, environment, model, test_instance_id, test_id, test_alias, test_version, storage_collab_id, register_result, client_obj, **params)
    433 
    434     test_config_file = prepare_run_test_offline(username=username, password=password, environment=environment, test_instance_id=test_instance_id, test_id=test_id, test_alias=test_alias, test_version=test_version, client_obj=client_obj, **params)
--> 435     test_result_file = run_test_offline(model=model, test_config_file=test_config_file)
    436     result_id, score = upload_test_result(username=username, password=password, environment=environment, test_result_file=test_result_file, storage_collab_id=storage_collab_id, register_result=register_result, client_obj=client_obj)
    437     return result_id, score

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/utils.pyc in run_test_offline(model, test_config_file)
    225     cls_name = path_parts[-1]
    226     module_name = ".".join(path_parts[:-1])
--> 227     test_module = import_module(module_name)
    228     test_cls = getattr(test_module, cls_name)
    229 

/opt/conda/envs/python2/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

/opt/conda/envs/python2/lib/python2.7/site-packages/morphounit/tests/__init__.py in <module>()
     12 
     13 for module in modules:
---> 14     exec("from %s import *" % module)

<string> in <module>()

/opt/conda/envs/python2/lib/python2.7/site-packages/morphounit/tests/test_NeuroM_MorphCheck.py in <module>()
     11 
     12 import matplotlib.backends.backend_pdf
---> 13 from neurom.apps.cut_plane_detection import find_cut_plane
     14 from neurom import load_neuron
     15 

ImportError: No module named cut_plane_detection
```

**Comment by appukuttan-shailesh** [comment]
I have fixed this now `Basal Ganglia Morphology Validation`. There was a new release of `NeuroM`, and so I had to pin the version. Should work now. Thanks.

**Comment by appukuttan-shailesh** [comment]
Regarding `Basal Ganglia Morphology Validation`, can you send a screenshot and/or complete error message you get? I am unable to reproduce the error.

**Comment by alex4200** [comment]
This ticket will be closed in favor of more specific tickets.
