### ISSUE TITLE
Test Simulation comparison feature

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#429]
## Details description of the task
@alex4200 Please test the Comparison feature on Nuvla following this temporal [link](https://bbpteam.epfl.ch/public/v2-simulation-launcher/dist/index.html#/circuits/microcircuit/view/NUVLA) 

Remember that we have a dummy notebook to compare (just fetching the data) but the important part is the process about selecting the Simulation and creation of Collab with the notebook.

**Comment by antonelepfl** [comment]
Could you test this again starting from [DEV](https://bbp.epfl.ch/public/dev.simulationapp/index.html#/circuits/microcircuit) Sim-UI ?

**Comment by alex4200** [comment]
So far it seems to work fine, tested on chrome and firefox. 

A small issue I noticed: If you rerun the cells in the 'Fetch notebook' the results are downloaded again and the dame pathcs are added to 'result.values', which then contain double the content. But I consider this not really relevant, thus closing the ticket for now.
