### ISSUE TITLE
Error when checking NSG simulation in "Synaptic events fitting".

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#43]
### Expected behavior

I am able to check the NSG simulation

### Actual Behavior

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-10-85394cf07a5a> in checksimnsg(CheckSNSG)
    743             storage.mkdir(storeto_path)
    744         # want a unique dir for each job run
--> 745         storeto = storeto_path + os.path.sep + "output_" + subname[subname.find('\'')+1:subname.find('.')-1]
    746         storage.mkdir(storeto)
    747         # download all output files

UnboundLocalError: local variable 'subname' referenced before assignment

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-10-85394cf07a5a> in checksimnsg(CheckSNSG)
    743             storage.mkdir(storeto_path)
    744         # want a unique dir for each job run
--> 745         storeto = storeto_path + os.path.sep + "output_" + subname[subname.find('\'')+1:subname.find('.')-1]
    746         storage.mkdir(storeto)
    747         # download all output files

UnboundLocalError: local variable 'subname' referenced before assignment
```

![screen shot 2017-10-27 at 09 31 57](https://user-images.githubusercontent.com/12729291/32097931-610f47b6-bb0b-11e7-94d4-09a7e926adab.png)

### Steps to reproduce the problem

 - I selected some data, log in to NSG, selected ‘demo’ the click on  “Run NSG simulation”.
 - Then I click several times on "check NSG simulation” showing me the status "INPUTSTAGING"
 - When I click on that box about 150 seconds after the start of the simulation the status is changed to "SUBMITTED" and the above error occurs.

### Optional infrastructural data (user, platform, browser, environment, ...)

**Comment by clupascu** [comment]
I removed the error display by adding a pop-up window with a message. Please test again.

**Comment by alex4200** [comment]
@clupascu Seems to work now. Closing issue
