### ISSUE TITLE
Simulations with Unicore disappear 

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#430]
### Expected behavior
All the simulations list and analysis are available on the list
### Actual Behavior (please include screenshot if possible)
After some time the simulations disappear from Unicore list of jobs.

@clupascu do you have the same issue?
@BerndSchuller is there any way to change that behaviour?

**Comment by BerndSchuller** [comment]
By default, jobs are deleted after 30 days. Is this what you mean?
If 30 days is not enough, you can manually extend this time for each job by sending a HTTP PUT call with JSON content to the job URL with the new termination (deletion) time in this format:
{
"terminationTime" : "yyyy-MM-dd HH:mm"
}

**Comment by clupascu** [comment]
@antonelepfl I don't pay attention after how much time the simulations disappear from Unicore list of jobs.

**Comment by antonelepfl** [comment]
I have implemented this PUT after a job is submitted.
