### ISSUE TITLE
Update .abf validity check with lastest version of neo

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#433]
### Expected behavior
The user is able to upload one or more .abf file/s in the feature extraction web app.

### Actual Behavior (please include screenshot if possible)
On the TEST platform: the user is not able to upload the .abf file

### Steps to reproduce the problem
On the TEST platform: Upload a .abf file in the feature extraction web app

### Optional infrastructural data (user, platform, browser, environment, ...)
The problem is present on the TEST platform where neo and bluepyefe have been updated to the latest version and work well for data in the database:
https://collab.humanbrainproject.eu/#/collab/1256/nav/29702

The PROD environment is working well with an older version and will be updated once this bug will be fixed.

**Comment by lbologna** [comment]
Bug fixed.
Moving to production by the end of the week (May 31st)

**Comment by alex4200** [comment]
Tested successfully
