### ISSUE TITLE
Extended sectionlists in BluePyOpt 

### ISSUE THREAD

**Issue by SteMasoli** [cnr-ibf-pa/hbp-bsp-issues#435]
## New Use Case
  
Aspect | Detail
------------ | -------------
Summary | Example on how to setup a custom axon with non standard sectionlists in BluePyOpt. 
Usecase Group | Tutorial and Single cell simulation.  
Expert | Stefano Masoli
Scientific User | 
Deadline | Second week of July (fourth is ok too)
Target audience | Users of BluePyOpt optimizer
Target interface |
HPC Requirements | No
Dependencies | Bluepyopt, Neuron
Nominal runtime |  15-20m
Link | https://collab.humanbrainproject.eu/#/collab/58955/nav/402211
Status | In DEV
  
## List of features

The usecase is divided into two parts:
1) the first part is a code example to explain the basic infomrmation required to build a custom axon using BluePyOpt.
2) The second part is the code of the regular cerebellar granule cell (2019) in which can be found a more complex approach in axonal building.

### Tasks

- [x] The first part is an "How to" so is informative
- [x] The second part is an actual working code.
    
## Acceptance Criteria

The first part, to be accepted, is to be clear and informative enough, that everybody can understand and benefit from it.
The second part acceptance is that the code does not break in any condition. Since is a slightly variation of the other cerebellar single cell usecases, it should work well from the start. 
  
### System
No HPC required.
No special package, only standard Bluepyopt and NEURON.
  
### Performance
Few minutes for the first part.
Up to 15m the simulations contained in the second part

**Comment by SteMasoli** [comment]
Hi.
The usecase is in queue to be accepted on the BSP dev.

**Comment by antonelepfl** [comment]
It is already in DEV. @alex4200 When you have time please check it out

**Comment by SteMasoli** [comment]
Updated the code following suggestions.

**Comment by alex4200** [comment]
@SteMasoli Thanks a lot for the update, looks much better to me then before. I will try to bring that usecase to production.

**Comment by alex4200** [comment]
The notebook is in production, closing ticket
