### ISSUE TITLE
Cerebellar granule cell (2019) validation workflow

### ISSUE THREAD

**Issue by SteMasoli** [cnr-ibf-pa/hbp-bsp-issues#436]
## New Use Case
  
Aspect | Detail
------------ | -------------
Summary | Workflow to validate the multicompartmental granule cell model (2019)
Usecase Group | "Single cell " or something else
Expert | Stefano Masoli
Scientific User | all
Deadline | Work expected in mid November 2019 (as of 14.10.2019)
Target audience | Users of Bluepyopt
Target interface |
HPC Requirements | No
Dependencies | Neuron and BluePyOpt
Nominal runtime | "not yet"
  
**Remove anything that does not apply**
## List of features

The worflow to optimize and validate a Granule cell model (2019), using current injections, recordings from non standard locations and synaptic activity. 
The workflow has been used in the the following preprint
https://www.biorxiv.org/content/10.1101/638247v1 and can be adapted to other bluepyopt models.
"other information to be added" 

*What does your use case do? What activities can users perform while using it? What makes it different from similar use cases? List the main functions that you will build into your product here. Also specify the priority ‘mandatory’, ‘important, ‘nice to have’.*
 
### Tasks
"to be defined"
 
- [ ] Task 1
- [ ] Task 2
- [ ] ...
    
## Acceptance Criteria

"to be defined"

"*Define here the acceptance tests to evaluate the use case’s compliance with the requirements as defined above. Also possible end users for testing can be included here.*"
  
### System
No HPC
No special packages
  
### Performance
To early to be estimated.

**Comment by SteMasoli** [comment]
Changed to M22.

**Comment by alex4200** [comment]
@SteMasoli Regarding your problem mentioned today, the response from support is as follows:

```
both Neuron 7.4 and Neuron 7.6 are installed in the Collaboratory. The 7.6 version is compatible with Python 3 and can be switched to using the instructions here: 
https://collab.humanbrainproject.eu/#/collab/509/nav/327793
```

see issue #476

**Comment by SteMasoli** [comment]
Since the Purkinje cell usecase contains a similar example as would have been this one, I'm thinking to change it toward something different.
