### ISSUE TITLE
eFEL GUI: give  user the possibility to upload multiple cell files

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#44]
### Expected behavior
The user can upload multiple files concerning the same cell

### Actual Behavior
Not implemented

### Optional infrastructural data (user, platform, browser, environment, ...)
user's .abf files

**Comment by alex4200** [comment]
@lbologna : can you please assign this issue to a milestone? Thanks

**Comment by lbologna** [comment]
Done.

**Comment by alex4200** [comment]
Expected to be finished by begin of March

**Comment by alex4200** [comment]
Moved to SGA2

**Comment by alex4200** [comment]
Probably start mid November. Using Nexus integration instead of backend. Depending on Nexus integration.

**Comment by alex4200** [comment]
This task is included in #334

**Comment by lbologna** [comment]
Done. Closing.
