### ISSUE TITLE
Models inconsistent with BlueNaaS convention

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#442]
### Expected behavior

Models from the model catalog need to follow the convention for BlueNaaS regarding the content of the zip file:

![Selection_722](https://user-images.githubusercontent.com/12729291/59430246-0f47cd80-8de2-11e9-9beb-b85fc1ad6733.png)

### Actual Behavior (please include screenshot if possible)
For example, [here](https://collab.humanbrainproject.eu/#/collab/1655/nav/75901?state=model.c3b8bdf4-3ffc-4db5-b27a-8372c9679325): Folder `checkpoints` contains two hoc files:
```

cell_seed5_0.hoc
cell_seed6_0.hoc
```

and not the single required one. 

### Steps to reproduce the problem

1. Go to the [model catalog](https://collab.humanbrainproject.eu/#/collab/1655/nav/75901?state=model.n)
2. Select any model
3. Try to open the model in BlueNaaS -> Error message

### Optional infrastructural data (user, platform, browser, environment, ...)

Prod

**Comment by clupascu** [comment]
@genric when opening the model in BlueNaaS the "best_cell" key and value from the _meta.json can be used in order to select the hoc file to be loaded from the checkpoints folder? The two or more cells in the checkpoints folder are unfortunately necessary.

**Comment by genric** [comment]
@clupascu I don't think _meta.json is included in the zip file. Even if it would be there then I'll have to introduce new convention for the best cell lookup for the CSCS container based models. An easy solution would be just to copy whatever best cell hoc file into `cell.hoc`. Let me know what you think.

**Comment by clupascu** [comment]
@genric ok. I will keep the two hoc files and add a new cell.hoc that will be a copy of one of the two hoc files.

**Comment by clupascu** [comment]
Now it works. @alex4200 can you please test and close the issue? Thanks.

**Comment by alex4200** [comment]
Thanks; yes the models seem to work now.
