### ISSUE TITLE
No images for cerebellum models in the platform

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#443]
### Expected behavior

When selecting a cerebellum/purkinje model I expect to see an image of the responses and the morphology. 

### Actual Behavior (please include screenshot if possible)

No image is provided for the following three models:

- Purkinje cell - Multi compartmental
- Granule cell - Multi compartmental
- Granule cell - Mono compartmental

![Selection_725](https://user-images.githubusercontent.com/12729291/59666685-9e276200-91b5-11e9-891b-a7163c254b92.png)

### Steps to reproduce the problem

1. Select "Single Cell In Silico Experiments" use case
2. Type "cerebellum" in the search box.

**Comment by SteMasoli** [comment]
Hi.
Some weeks ago, i have added the missing images directly into the model catalog entries.
Is there something else to do to have them in the BSP?

Purkinje
https://collab.humanbrainproject.eu/#/collab/19/nav/369318?state=model.d3a1a6f7-d4c6-4e4a-b1d8-76e470f20862

Multi GrC
https://collab.humanbrainproject.eu/#/collab/19/nav/369318?state=model.0c97cd83-24fd-4782-bdea-2affacc6863e

Mono GrC
https://collab.humanbrainproject.eu/#/collab/19/nav/369318?state=model.527191ca-8385-4aac-b08c-3bce022fc5cc

**Comment by appukuttan-shailesh** [comment]
@SteMasoli : the issue arises because BSP tools require the model entries to have images with captions (names) as 'Morphology' and 'Responses` as discussed [here](https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/360).

Example: https://collab.humanbrainproject.eu/#/collab/19/nav/369318?state=model.579cf0d8-62d0-49a1-891d-d16dbc06146a

**Comment by SteMasoli** [comment]
I have reuploaded the images, for the three models, with the required captions.
https://collab.humanbrainproject.eu/#/collab/19/nav/369318?state=model.d3a1a6f7-d4c6-4e4a-b1d8-76e470f20862

In the "Single Cell In Silico Experiments" are not yet visible.

**Comment by antonelepfl** [comment]
@SteMasoli I see that the Purkinje cell has the images now and it's available on the BSP.

Now I have another question. In the past we were choosing the Granule cells for Mouse and now you don't have any of them but you have for Rat instead. Can you confirm that you want to show for BlueNaaS only these 2 [granulle models](https://validation-v1.brainsimulation.eu/models/?brain_region=cerebellum&cell_type=granule%20cell&model_scope=single%20cell&species=Rattus%20norvegicus&project=Project26) + the Purkinje cell?

**Comment by SteMasoli** [comment]
The old granule cells have images too.

https://collab.humanbrainproject.eu/#/collab/19/nav/369318?state=model.0c97cd83-24fd-4782-bdea-2affacc6863e

https://collab.humanbrainproject.eu/#/collab/19/nav/369318?state=model.527191ca-8385-4aac-b08c-3bce022fc5cc

@antonelepfl 
> Can you confirm that you want to show for BlueNaaS only these 2 granulle models + the Purkinje cell?

Yes plus the 4 new  "Granule cells 2019" models. 
They are based on rats, are part of the live paper, in BlueNaaS format too, but still missing some description and images in the model catalog. 

For example.
https://collab.humanbrainproject.eu/#/collab/19/nav/369318?state=model.6f4f624e-a971-4708-ab99-a822b7f3e2a6

**Comment by SteMasoli** [comment]
Added descriptions and images for the four granule cells 2019.

**Comment by antonelepfl** [comment]
Now you can see the latest modes of Granule Cells working with BlueNaaS in [DEV]
 (https://collab.humanbrainproject.eu/#/collab/8444/nav/65635) the images are shown but some of them are quite big so if you can reduce the size to keep consistency that would be good.
