### ISSUE TITLE
Add disclaimers for the use of the current hippocampus circuit

### ISSUE THREAD

**Issue by romani79** [cnr-ibf-pa/hbp-bsp-issues#445]
Michele Migliore mentioned it should be clear to the user that the current version of the hippocampus model is there only for demo purposes and it should not be used to produce scientific results. Michele suggested to add some disclaimers before the users access the model.

**Comment by antonelepfl** [comment]
A really easy way to fix that is add some lines in the current [Terms & Conditions](https://github.com/antonelepfl/usecases/blob/dev/src/assets/config_files/terms_and_conditions.md) that we show for the use cases. We can put something generic for all the models that are available on the BSP.

**Comment by mmigliore** [comment]
No, BSP models in general are supposed to be coming from publications!
They can (and we would like them to) be used for scientific purposes.
This message instead applies only for the models that are not yet (or will
not be) published.

**Comment by antonelepfl** [comment]
And if we add in the description of the [Brain Area - Hippocampus](https://collab.humanbrainproject.eu/#/collab/1655/nav/66856) that "this models are for demo ..." until we release the new version and we remove that description?
Or we can add another 'pill' on the right of that use case that says 'demo' and when hover an explanation of it.

**Comment by mmigliore** [comment]
Better. Could you try something?

Il gio 20 giu 2019, 07:45 Stefano Antonel <notifications@github.com> ha
scritto:

**Comment by stefanoantonel** [comment]
So I have just dome some quick tests just to get an idea of what I was thinking.
So basically we will add a new icon and when the user hover a tooltip will appear (as we have for the maturity level and the experience)
Let me know what do you think and if there is an option that you like:
<img width="930" alt="Screenshot 2019-06-21 at 14 02 02" src="https://user-images.githubusercontent.com/4954312/59921173-34b18880-942d-11e9-9fd6-b9d517c6b1ce.png">
<img width="709" alt="Screenshot 2019-06-21 at 13 54 13" src="https://user-images.githubusercontent.com/4954312/59921174-354a1f00-942d-11e9-9364-29522772ff1c.png">
<img width="723" alt="Screenshot 2019-06-21 at 13 55 58" src="https://user-images.githubusercontent.com/4954312/59921175-354a1f00-942d-11e9-94af-2f87f76780ae.png">

**Comment by alex4200** [comment]
I am in favor for the first option because it contains an exclamation mark. But maybe the text can be extended to "! DEMO MODEL" or "! DEMO CIRCUIT" so it is clear what the demo refers to.

**Comment by stefanoantonel** [comment]
Remember that when you hover a more descriptive information will appear

**Comment by jdcourcol** [comment]
I tend to agree with Alex. May be "Warning: model is work in progress"

**Comment by mmigliore** [comment]
I agree, with DEMO FULL CIRCUIT
and a bigger triangle

Il ven 21 giu 2019, 14:21 alex4200 <notifications@github.com> ha scritto:

**Comment by antonelepfl** [comment]
I have deployed this in the [DEV BSP](https://collab.humanbrainproject.eu/#/collab/8444/nav/65637)
