### ISSUE TITLE
Unicore status don't reflects what UNICORE_SCRIPT_EXIT_CODE says

### ISSUE THREAD

**Issue by stefanoantonel** [cnr-ibf-pa/hbp-bsp-issues#446]
I noticed that when I start a Job on PizDaint or Jureca through unicore, and this job fails, I still get a status "SUCCESSFUL" for that job (when I do a GET on the Job). 

For example, in Jureca in folder:
`/p/scratch/cvsk25/unicore-jobs/892c0da9-62ff-495d-a0a0-360e1149b827` I started the job (as defined in input.sh), which did fail (see stderr and UNICORE_SCRIPT_EXIT_CODE). I would expect that a GET on the job then returns a FAILED and not a SUCCESSFUL. 

Do you know what is going on, or if that returned status is on a different level? Is there a way to transfer the actual Job status back to Unicore?

Thanks
Alex

**Comment by BerndSchuller** [comment]
UNICORE-wise the job was executed successfully - you need to check the exit code (GET on the job) to check the application-level status.

**Comment by BerndSchuller** [comment]
after thinking some more on this I think this behaviour should be changed for the next major release (UNICORE 8), since the "non-zero means failure" convention is almost universally accepted.
https://sourceforge.net/p/unicore/issues/249

**Comment by stefanoantonel** [comment]
Yes I think it would be more useful. Thank you Bernd
