### ISSUE TITLE
Implement CPUs in Jureca & Jureca Booster

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#447]
Hi @BerndSchuller , I would like to pass the number of **CPUs** so it's translated to #SBATCH --**ntasks**=... in the bss_submit_.. Piz-daint have already implemented this functionality.

Currently I get: `failed: Resource <TotalCPUs> is not available at this site`

**Comment by BerndSchuller** [comment]
hi Stefano,

specifying Nodes and CPUsPerNode does not work for you?

**Comment by antonelepfl** [comment]
Yes it works but to have consistency with the other systems I'm trying to pass only the CPUs and let Unicore takes care about how many nodes I need to allocate. Make it available is a lot of work?

**Comment by clupascu** [comment]
Hi Stefano,

I use this in the job descriptor

"Resources": {"Nodes": '2',"CPUsPerNode":'24'} for the booster partition.

**Comment by BerndSchuller** [comment]
no, it's not difficult, I'll get it done, for some reason our current configuration only has the Nodes+CpusPerNode. It's possible to have both, so you can choose whichever resource specification is m
more conventient.

**Comment by antonelepfl** [comment]
Yes I was using that in the past that passing the CPUs is a feature mentioned in the [documentation](https://www.unicore.eu/docstore/ucc-7.8.0/ucc-manual.html#_resources) and I prefer using the same syntax.

**Comment by antonelepfl** [comment]
Ok great that would be nice, thank you Bernd!

**Comment by BerndSchuller** [comment]
the change is deployed:

  "resources": {
        "TotalCPUs": "0.0-111520.0"
        "CPUsPerNode": "0.0-68.0",
        "GPUS": "0-4",
        "Nodes": "1.0-1872.0",
...        ],

you can give either TotalCPUs or Nodes+CPUsPerNode
let me know if things are not as you expect :-)

**Comment by antonelepfl** [comment]
It's working properly. Thank you again Bernd
