### ISSUE TITLE
Add Allen Institute traces to eFEL GUI

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#45]
### Expected behavior
User can select traces from the Allen Institute's dataset

### Actual Behavior
Not implemented

**Comment by alex4200** [comment]
@lbologna : can you please assign this issue to a milestone? Thanks

**Comment by lbologna** [comment]
Done.

**Comment by alex4200** [comment]
Expected to be finished by end of February

**Comment by alex4200** [comment]
Move it to SGA2? (14 May)

**Comment by lbologna** [comment]
A set of data from Allen Institute has been added. The application will be extended in SGA2 with a more comprehensive ensemble. Could you please check?

Thanks.

**Comment by alex4200** [comment]
Yes, done
