### ISSUE TITLE
Wrong hoc templates in models in Hippocampus models container

### ISSUE THREAD

**Issue by sasaray** [cnr-ibf-pa/hbp-bsp-issues#450]
The PLOS paper models in the container: https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/hippocampus_optimization/
contain hoc templates that still require the axon to have at least 2 sections. 
The problematic lines are in "proc replace_axon()"

         access axon[0]
         i1 = v(0.0001) // used when serializing sections prior to sim start

         access axon[1]
         i2 = v(0.0001) // used when serializing sections prior to sim start
These lines are commented out in the new models, and I think were commented out in the GitHub versions of the PLOS paper models.
As in some morphologies the axon has only 1 section, we can not run, and validate those models. This is blocking us with @appukuttan-shailesh  in creating a live paper on HippoUnit.

@mmigliore, @rmiglior, @clupascu: Could you please replace the hoc templates with the correct ones in the container?

**Comment by clupascu** [comment]
@sasaray the PLOS paper models are in https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/Migliore_2018_CA1/models/ not in https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/hippocampus_optimization/. Can you please check that the hoc templates in the PLOS paper models container above suits your requirements?

**Comment by appukuttan-shailesh** [comment]
@clupascu .... there was a confusion. @sasaray  is infact referring to the container:
https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/Migliore_2018_CA1/models/
(and not /hippocampus_optimization/)

The URLs had been picked up from the model catalog, and there we redirect to "Migliore_2018_CA1" container.
e.g.
https://collab.humanbrainproject.eu/#/collab/8123/nav/395557?state=model.b1a62b3e-55ea-4b23-939f-94862ad56516
gives the following URL:
https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/Migliore_2018_CA1/models/CA1_pyr_cACpyr_oh140807_A0_idA_20170915112548/CA1_pyr_cACpyr_oh140807_A0_idA_20170915112548.zip

**Comment by appukuttan-shailesh** [comment]
p.s. some of the models known to have this issue are:
CA1_pyr_cACpyr_oh140807_A0_idA_20170915112548
CA1_pyr_cACpyr_mpg141215_A_idA_20170915152442
CA1_pyr_cACpyr_oh140807_A0_idF_20171003112912
CA1_pyr_cACpyr_oh140807_A0_idG_20170915113354
CA1_pyr_cACpyr_oh140807_A0_idC_20170912112759
(the others seemed to be ok, but you could double-check)

**Comment by clupascu** [comment]
ok. we will fix it.

**Comment by clupascu** [comment]
I fixed CA1_pyr_cACpyr_mpg141215_A_idA_20170915152442. Can you please test that this model works for you? I actually noted that all models have this issue, not only the ones listed by @appukuttan-shailesh above.

**Comment by sasaray** [comment]
Yes, all of them has this in the hoc template, but in case of those models, that have at least 2 axonal sections, this doesn't cause any error.

**Comment by clupascu** [comment]
I fixed all the models in the PLOS paper container. Please check.

**Comment by appukuttan-shailesh** [comment]
Thanks @clupascu for the quick work on this.
I tested a few of them and they worked. Will review all and update this ticket.

**Comment by appukuttan-shailesh** [comment]
I am having a problem with "CA1_int_cNAC_970509HP2_20180117154753" model.

Error:
> NEURON: /media/shailesh/DATA3/Downloads/CA1_int_cNAC_970509HP2_20180117154753/morphology/970627BHP1.asc :file is not open

It's hoc files require to load the above morphology file "970627BHP1.asc":
```
  if(numarg() >= 2) {
    load_morphology($s1, $s2)
  } else {
    load_morphology($s1, "970627BHP1.asc")
  }
```

But the morphology directory of this model only contains "970509HP2.asc".

@clupascu : Could you fix this if it is indeed an error?

**Comment by clupascu** [comment]
@appukuttan-shailesh I fixed this. It was indeed an error.

**Comment by appukuttan-shailesh** [comment]
Thanks @clupascu ! All the problems with the live paper models have been resolved. Closing this issue now.
