### ISSUE TITLE
Model Catalog API SSLError

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#451]
### Expected behavior
The API / URL is https
### Actual Behavior (please include screenshot if possible)
Using the API I get SSLError because the certificate are not valid
### Steps to reproduce the problem
Enter to the BSP Model [Catalog](https://collab.humanbrainproject.eu/#/collab/1655/nav/75901?state=model.n) or Query using the [browser](https://validation-v1.brainsimulation.eu/models/?brain_region=cerebellum&cell_type=Purkinje%20cell&model_scope=single%20cell&name=Purkinje%20cell%20-%20Multi%20compartmenta
)
And you will see https in red

**Comment by antonelepfl** [comment]
Not very sure if you know what is going on here

**Comment by BerndSchuller** [comment]
" Peer’s Certificate has expired. "
the certificate of the server at https://validation-v1.brainsimulation.eu needs to be renewed

**Comment by alex4200** [comment]
I see an error

`The webpage at https://validation-v1.brainsimulation.eu/?ctx=6115569b-2fb1-41ff-b8ac-b33c4a3e8e1e might be temporarily down or it may have moved permanently to a new web address.`

**Comment by apdavison** [comment]
My apologies, I've now renewed the certificate

**Comment by alex4200** [comment]
I am able to access the Model Catalog again.
