### ISSUE TITLE
Rename use case

### ISSUE THREAD

**Issue by romani79** [cnr-ibf-pa/hbp-bsp-issues#453]
Could someone remove the word 'column' from the use case 'Configure and run a hippocampus column' in https://collab.humanbrainproject.eu/#/collab/1655/nav/66856?

Just rewrite it as:
Configure and run a hippocampus microcircuit
A microcircuit of detailed neuron models

**Comment by antonelepfl** [comment]
This change should be in production in a couple of minutes
@alex4200 Check it please and close this ticket

**Comment by alex4200** [comment]
Yes all looks ok, closing ticket
