### ISSUE TITLE
Jureca - 500 Server Error

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#454]
There seems to be an issue on Jureca currently. The error is 
`
Server Error</pre><h3>Caused by:</h3><pre>javax.servlet.ServletException: Failed to process POST request: javax.servlet.ServletException: Problem when forwarding a client request to a VSite: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated`

### Steps to reproduce the problem

- Try to use the SimUI 
- Try to submit a job

**Comment by BerndSchuller** [comment]
hi,
sorry for the trouble, one of our servers had an out-of-memory issue - should be fine now

**Comment by alex4200** [comment]
Thanks, 

it works again.

**Comment by antonelepfl** [comment]
I'm having this issue today too. Bernd can you check it please?

**Comment by BerndSchuller** [comment]
Looks like our HPC systems are not available at the moment - I can't login to both JURECA and JUDAC, so I suspect some issue with the shared GPFS file system. I'm sure there are people already working on it. Sorry for the inconvenience!

**Comment by BerndSchuller** [comment]
it looks to me as if things are working again now - closing
