### ISSUE TITLE
Showcase: Simulation

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#456]
## Showcase Usecase
  
Aspect | Detail
------------ | -------------
Summary | Simulation Use Case
Common document | https://docs.google.com/document/d/1sIOLMhK-jYnSb4x-xDEewmNqQXd4sztfw8nrgYsbZYs/edit#
Usecase Group |
Expert | @antonelepfl  
Scientific User | 
Deadline | **March 2020**
HPC Requirements |
Dependencies |
Nominal runtime |
  
## Description
This use case is supposed to be a showcase use case to be shown to the reviewers at the end of SGA2 in May/June 2020. This section should contain a detailed description of what exactly to show to the reviewers (like a script):
    
## Acceptance Criteria
*Define here the acceptance tests to evaluate the use case’s compliance with the requirements as defined above. Also possible end users for testing can be included here.*
  
### System
*Does this use case require any special system requirements (any special software package)? Does this use case require HPC access? If so, which ones? List detailed system requirements here.*
  
### Performance
*What are additional performance requirements for this use case? What time should it take to run from start to end?*

**Comment by antonelepfl** [comment]
## What to show (WIP)
- Configure a simulation
      - Central column (~2K cells)
  - Stimuli / Report
        - Central Column
        - 10% of central cells
  - Projection
        - Spike reply?
        - Spon Minis

- Simulation list
      - Use filters

- Launch Analysis
      - Select PSTH of Central Column
      - Select Raster of 8 specific cells (or ranges in the central)
      - Select Voltage collage of 5 random cells
      - Launch LPF on a previous run simulation (Mosaic?)

- Simulation Details
      - Download analysis picture
      - Download raw data of the plot

**Comment by alex4200** [comment]
Details see now https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/514
