### ISSUE TITLE
Add Terms&Conditions page for all Use Cases using exp data

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#46]
### Expected behavior
User is prompted a T&Cs page when clicking on use cases for cloning, so that she/he accepts the conditions for using/citing the data (mostly relevant for Jupyter notebooks)

### Actual Behavior
Not implemented

### Optional infrastructural data (user, platform, browser, environment, ...)
Use a common database for storing access but give the possibility not to add personal data? (EC would not do it)

**Comment by alex4200** [comment]
@jdcourcol clarification with Katrien

**Comment by alex4200** [comment]
@antonelepfl  to clarify with @lbologna

**Comment by antonelepfl** [comment]
I did a pull request https://github.com/antonelepfl/usecases/pull/40

**Comment by antonelepfl** [comment]
Michele replied:
> I think that the acceptance should be global for each type of use case. For example, the first time the user enters the opt use case, that is going to be valid for all use opt use cases. However it must accept again if the use case on "in silico experiment" is selected, and so on.
We need to discuss this also with Jean-Denis and Felix, to make it somewhat uniform to what they are doing in other cases, e.g. the cortex.
