### ISSUE TITLE
Feature Extraction GUI - extracting features from traces blocked

### ISSUE THREAD

**Issue by rmiglior** [cnr-ibf-pa/hbp-bsp-issues#461]
### Actual Behavior (please include screenshot if possible)
extracting features from traces does not work

![Cattura](https://user-images.githubusercontent.com/28053879/63694420-b7343b00-c816-11e9-9a97-a8b847486853.JPG)

**Comment by rmiglior** [comment]
The platform works properly if we exclude the features AP_amp1, AP_amp2, AP_width1 and so on

**Comment by lbologna** [comment]
Hello,

I updated the BluePyEfe package with the latest version, both in dev and prod, and the problem (application hangs) does not occur anymore. I tested with a few files from the platform and with several features of the AP... family.

Could you please try again and let me know if some other issues arise?
Thanks

**Comment by lbologna** [comment]
This seems to be fixed now.
Closing the ticket.
