### ISSUE TITLE
Optimized BG model validation: cell_type = 'Other' is invalid.

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#464]
### Expected behavior

I should be able to run the notebook without errors

### Actual Behavior (please include screenshot if possible)

After "Specifying model from ModelCatalog; Update info if new model entry", when I do not choose an existing model-uuid, I get the error:

```
ExceptionTraceback (most recent call last)
<ipython-input-8-8435c149d415> in <module>()
     28                                 brain_region="basal ganglia",
     29                                 species="Mus musculus",
---> 30                                 description="This model is being used to demonstrate use of the Validation Service")
     31     model_uuid = str(model_uuid)
     32     print("\nModel registered on the HBP Validation Framework's Model Catalog!")

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/__init__.pyc in register_model(self, app_id, name, alias, author, organization, private, species, brain_region, cell_type, model_scope, abstraction_level, owner, project, license, description, instances, images)
   1589         --------
   1590         >>> model = model_catalog.get_model(model_id="8c7cb9f6-e380-452c-9e98-e77254b088c5")
-> 1591         >>> model = model_catalog.get_model(alias="B1")
   1592         """
   1593 

Exception: cell_type = 'Other' is invalid.
Value has to be one of these: ['Golgi cell', 'L1 neurogliaform cell', 'L2 inverted pyramidal cell', 'L2/3 chandelier cell', 'L2/3 pyramidal cell', 'L4 Martinotti cell', 'L5 tufted pyramidal cell', 'L6 inverted pyramidal cell', 'Purkinje cell', 'cholinergic interneuron', 'fast spiking interneuron', 'granule cell', 'hippocampus CA1 basket cell', 'hippocampus CA1 ivy neuron', 'hippocampus CA1 lacunosum moleculare neuron', 'hippocampus CA1 pyramidal cell', 'interneuron', 'medium spiny neuron', 'medium spiny neuron (D1 type)', 'medium spiny neuron (D2 type)', 'not applicable', 'other', 'pyramidal cell', 'spiny stellate neuron']
```

Could be a genuine error, or related to the fact that the old validation app is still used (no KG backend). That also needs to be fixed.

### Steps to reproduce the problem

1. Run the cells one by one.
2. Choose Model Name = msn_d1_all-6-20170524
3. Choose default potential (0.5 mV)
4. Answer 'n' to use an existing model-uuid

### Optional infrastructural data (user, platform, browser, environment, ...)

DEV

**Comment by apdavison** [comment]
I will look at the problem this week

**Comment by apdavison** [comment]
I presume this refers to the Use Case "Basal Ganglia - BluePyOpt Optimized Model Validation - Multiple HOF" ?

**Comment by apdavison** [comment]
Note that this problem also occurs with the production (non-KG-based) server. The solution is to replace "Other" with "other".

@alex4200 Please can you tell me where the master copy of this notebook is, so I can update it? (Shailesh is on vacation).

**Comment by appukuttan-shailesh** [comment]
@apdavison: the source notebooks are placed in collab 8123, under a section titled (something like) "UseCase Notebooks (do not edit)". Pedro will be able to help locate these if required.

**Comment by appukuttan-shailesh** [comment]
@alex4200 : I am not sure if you tested the latest version of this notebook on dev. Because the latest versions do not permit a user to enter the UUID of model, but rather has to select the model from a displayed list. So step 4 that you indicated above is no longer present.

Collab Path: 
https://collab.humanbrainproject.eu/#/collab/8123/nav/67065 
Collab Storage ID:
https://collab.humanbrainproject.eu/#/collab/8123/nav/61645?state=uuid%3De62f67fa-7831-496b-8b44-8bd16aaabc81.

This is the notebook specified in the usecases.json config file:
https://github.com/antonelepfl/usecases/blob/dev/src/assets/config_files/usecases.json#L1806

**Comment by alex4200** [comment]
Yes, when I test the DEV version of that notebook it seems to work. More tests are pending, but I will close this issue for now.
