### ISSUE TITLE
Unable to load circuit for Pair Recording

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#470]
### Actual Behavior (please include screenshot if possible)

When using a custom config to load  circuit the 'Load' button is greyed out

![Selection_804](https://user-images.githubusercontent.com/12729291/64784363-4311cb00-d56a-11e9-9ec2-34fe6902c628.png)

### Steps to reproduce the problem

1. Use custom model
2. use any name
3. Use a correct path (see e.g. the other circuits)
4. choose a sim model

### Optional infrastructural data (user, platform, browser, environment, ...)

entry: http://bp.ocp.bbp.epfl.ch/circuits/mouse-ssx-s1-v6a-20171206

**Comment by pgetta** [comment]
Should be fixed now, @alex4200. Could you please take a look when you have some time?

**Comment by alex4200** [comment]
Yes works
