### ISSUE TITLE
Simulation Launcher GUI Improvements

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#472]
On September 16th we had Davide from Hippocampus team who gave us his inputs while using the SimLauncherUI. The feedback that we had was:

**Run simulation**
- [x] Have a section with Population (CircuitTarget) and the Duration + show the image there instead of showing it on Stimulus and Report. (this will oblige the user to use the '+' button and search on the different targets)
- [x] Summation not very clear (soma + dendrites?)
- [x] Change report Bin -> binary
- [x] Weight 0 on connections are taking in account?
- [x] Message about population(s) constancy is not visible  -> add more seconds
- [x] Files are not very user friendly (need to parse it)
- [x] Files when show download button -> mention file is too large to show in the browser. Download it.
- [x] Avoid to move the blue bar (duration)
- [x] Scroll in form autocomplete-target -> hide it.
- [x] In timeline time centered [not feasible due 3rd party library]
- [x] Download files not passing from the frontend ? [Not feasible so far due I need a backend to do this
- [x] Autocomplete targets when mouse over a target he cannot search

**View List**
- [x] Name (list of simulations) -> Title

**Analysis Launch**
- [x] Mention that for the analysis we are using random cells
- [x] Legend in raster plot for colors [If we need this I would have to implement it myself and not use BluePy for this plot]
- [x] ‘Time’ in PSTH and Raster make it Upper case [Waiting until the next version of BluePy [0.14.1]

**View details section**
- [x] Log -> Analysis logging
- [x] See the output path folder? -> do it in files section on the top together with parsed
- [x] Analysis section need to explains that you need to run analysis first after simulation finishes. Analysis results
- [x] Add logs (technical logs) block with Unicore + stderr + stdout
- [x] Analysis log smaller or analysis title bigger

**Comment by antonelepfl** [comment]
I have created 2 internal tickets for BluePy to fix the [plot axes](https://bbpteam.epfl.ch/project/issues/browse/BLPY-167) and the [legend for Raster colors](https://bbpteam.epfl.ch/project/issues/browse/BLPY-168)

**Comment by antonelepfl** [comment]
The last items regarding the plotting are deployed in DEV.
 @alex4200 you can test them.

**Comment by alex4200** [comment]
@antonelepfl The bluepy related plotting tasks seem to work fine in DEV for Jureca and PizDaint.
