### ISSUE TITLE
BluePy on PizDaint

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#473]
### Expected behavior
After using modules deployed by [BBP via spack](https://github.com/BlueBrain/spack/wiki/Piz-Daint-Deployment#sample-job-script) I expect to see the module `py-bluepy` as I see it in Jureca

### Actual Behavior (please include screenshot if possible)
I only see 
```
neurodamus/hippocampus/intel
neurodamus-hippocampus/0.2/intel
neurodamus-neocortex/0.1/intel
neuron/7.6.6/intel
```
@pramodk @jorblancoa could you have a look please?

**Comment by pramodk** [comment]
@antonelepfl : I remember multiple issues with bluepy installation on cluster vs booster. Could you tell us who/how this module will be used? interactively on login node or on compute node itself?

**Comment by mmigliore** [comment]
Hello,
they gave us a small allocation on the cluster partition during a downtime
of the booster partition.
This latter is the one to be used for everything, from optimizations to
full circuits.
We also have a small allocation on the vis cluster, to be used for
visualization through GPU, not computing nodes.
-M

**Comment by alex4200** [comment]
@pramodk Is there any news on this issue?

**Comment by pramodk** [comment]
Sorry for delay. See the [updated instructions here](https://github.com/BlueBrain/spack/wiki/Piz-Daint-Deployment#sample-job-script) where everything is updated including bluepy module.
