### ISSUE TITLE
Hippocampus single cell validation - error

### ISSUE THREAD

**Issue by clupascu** [cnr-ibf-pa/hbp-bsp-issues#478]
### Expected behavior
running all cells of the notebook should work without errors
### Actual Behavior (please include screenshot if possible)
When running cell #6, I get

Do you wish to use an existing `model_uuid` (this will register results against an existing model entry)?
Note: `model_uuid` is obtained from the HBP Validation Framework app.
If not specifying `model_uuid`, then a new model entry would be registered.
Note: If registering a new model, please verify the default model metadata in this Jupyter notebook!
Enter: y/n
n

ExceptionTraceback (most recent call last)
<ipython-input-6-13ad224e1ef6> in <module>()
     28                                 brain_region="hippocampus",
     29                                 species="Rattus norvegicus",
---> 30                                 description="This model is being used to demonstrate use of the Validation Service")
     31     model_uuid = str(model_uuid)
     32     if model_image_localPath:

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/__init__.pyc in register_model(self, app_id, name, alias, author, organization, private, species, brain_region, cell_type, model_scope, abstraction_level, owner, project, license, description, instances, images)
   1589 
   1590         if cell_type not in values["cell_type"]:
-> 1591             raise Exception("cell_type = '" +cell_type+"' is invalid.\nValue has to be one of these: " + str(values["cell_type"]))
   1592         if model_scope not in values["model_scope"]:
   1593             raise Exception("model_scope = '" +model_scope+"' is invalid.\nValue has to be one of these: " + str(values["model_scope"]))

Exception: cell_type = 'Interneuron' is invalid.
Value has to be one of these: ['Golgi cell', 'L1 neurogliaform cell', 'L2 inverted pyramidal cell', 'L2/3 chandelier cell', 'L2/3 pyramidal cell', 'L4 Martinotti cell', 'L5 tufted pyramidal cell', 'L6 inverted pyramidal cell', 'Purkinje cell', 'cholinergic interneuron', 'fast spiking interneuron', 'granule cell', 'hippocampus CA1 basket cell', 'hippocampus CA1 ivy neuron', 'hippocampus CA1 lacunosum moleculare neuron', 'hippocampus CA1 pyramidal cell', 'interneuron', 'medium spiny neuron', 'medium spiny neuron (D1 type)', 'medium spiny neuron (D2 type)', 'not applicable', 'other', 'pyramidal cell', 'spiny stellate neuron']

I choosed 
1000. CA1_int_cNAC_970911C_20180120154902
410. CA1_int_bAC_971114B_20170511120711
in cell #4

**Comment by appukuttan-shailesh** [comment]
This issue can be closed as
> Do you wish to use an existing model_uuid (this will register results against an existing model entry)?

is no longer a feature in the updated UseCases (on dev, to be moved to prod), but the user rather has to select the model from a displayed list.

**Comment by alex4200** [comment]
@carmen: I need to update the production notebooks. They are outdated.

**Comment by clupascu** [comment]
This usecase works fine. We will use this one to demo the validation during our training course in Helsinki. Thanks.
