### ISSUE TITLE
BluePyOpt optimized model validation - error

### ISSUE THREAD

**Issue by clupascu** [cnr-ibf-pa/hbp-bsp-issues#479]
### Expected behavior
The notebook should run without errors
### Actual Behavior (please include screenshot if possible)
When I am asked to enter the # of required model I can't enter it. The text field is not visible

![immagine](https://user-images.githubusercontent.com/22050958/66024244-9b961180-e4f3-11e9-84c8-32eceae4325a.png)

**Comment by appukuttan-shailesh** [comment]
I am unable to reproduce this issue when I test it:
![image](https://user-images.githubusercontent.com/24866517/66039737-fa6c8280-e515-11e9-93cd-340c067e4051.png)

@alex4200 : could you recheck this when testing the updated usecases, and let me know if it persists.

**Comment by alex4200** [comment]
@clupascu Can you retry to run the cell? Rerun the usecase? Reset the container before trying again?

**Comment by clupascu** [comment]
I retested this usecase and now, after I run cell number 6, I get this error

83


TypeErrorTraceback (most recent call last)
<ipython-input-6-31e636d32148> in <module>()
     13 print len(list_of_models)
     14 df = pd.DataFrame.from_dict(json_normalize(list_of_models), orient='columns')
---> 15 df = df.reindex(['name', 'id', 'author', 'brain_region', 'species', 'cell_type', 'model_scope', 'abstraction_level', 'description'], axis=1)
     16 df.index += 1
     17 df

/opt/conda/envs/python2/lib/python2.7/site-packages/pandas/core/frame.pyc in reindex(self, index, columns, **kwargs)
   2819     def reindex(self, index=None, columns=None, **kwargs):
   2820         return super(DataFrame, self).reindex(index=index, columns=columns,
-> 2821                                               **kwargs)
   2822 
   2823     @Appender(_shared_docs['reindex_axis'] % _shared_doc_kwargs)

/opt/conda/envs/python2/lib/python2.7/site-packages/pandas/core/generic.pyc in reindex(self, *args, **kwargs)
   2236         if kwargs:
   2237             raise TypeError('reindex() got an unexpected keyword '
-> 2238                             'argument "{0}"'.format(list(kwargs.keys())[0]))
   2239 
   2240         self._consolidate_inplace()

TypeError: reindex() got an unexpected keyword argument "axis"

**Comment by alex4200** [comment]
@clupascu  What model did you select? Did you install all the required packages? Did you restart the kernel at least once?

**Comment by appukuttan-shailesh** [comment]
It might have been a pandas issue as reported here:
https://stackoverflow.com/questions/50796039/reindex-in-pandas-is-not-accepting-axis-argument?rq=1

Have made this generic fix now (in two usecases where this was used). Should not recur.

**Comment by clupascu** [comment]
Please let me know when the fix is available in PROD. Thanks.

**Comment by alex4200** [comment]
Fix should be in PROD

**Comment by clupascu** [comment]
I tested the notebook and it works. I am closing the issue.
