### ISSUE TITLE
Results empty for Synaptic events fitting?

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#48]
### Expected behavior

To see some results at the end of the use case

### Actual Behavior

No error, but the results (table, boxplots) are empty:

![selection_063](https://user-images.githubusercontent.com/12729291/32184441-86a3d288-bd9c-11e7-8689-b72ffac1d29a.png)

### Steps to reproduce the problem

Following the usecase: 

1. Select some data
1. Select NSG
1. Select the 'demo'
1. Login to NSG
1. Run the NSG simulation. Might take a long time
1. Select the files as in the screenshot.

### Optional infrastructural data (user, platform, browser, environment, ...)

Google Chrome

**Comment by clupascu** [comment]
Can you add me to the test collab as a team member? I believe the fitting finished but the trace you choosed was not fitted (because the error exceeded the threshold), so the file test.csv is empty. If you want I can give a feedback to the user also in this case.

**Comment by alex4200** [comment]
@clupascu I added you. Its collab "Retest43a".

**Comment by alex4200** [comment]
Solution: Take model 'B4' to get some results.
