### ISSUE TITLE
Adding implementation icon to main use case

### ISSUE THREAD

**Issue by clupascu** [cnr-ibf-pa/hbp-bsp-issues#480]
Update all use cases

## Use Case Update
 
For each use case, apart from experience, maturity and access icons, an implementation icon should also be displayed.

Aspect | Detail
------------ | -------------
Summary | 
Expert | @antonelepfl 
Deadline | 
Dependencies |
 
I was thinking to use 

![immagine](https://user-images.githubusercontent.com/22050958/66552065-fc9f9400-eb48-11e9-87c7-d4c9b6b83137.png)

for the webapp usecases, and the classical https://miro.medium.com/max/518/1*FogMIj4gYwp3fTHLZuwavQ.png
![immagine](https://user-images.githubusercontent.com/22050958/66552613-f4942400-eb49-11e9-9052-f6723ca3e5ab.png)
 for the jupyter notebook.

**Comment by antonelepfl** [comment]
Ok I have done some progress in this. I have deployed this on [DEV](https://collab.humanbrainproject.eu/#/collab/8444/nav/65633).
Please let me know your thoughts.

**Comment by clupascu** [comment]
Seems good to me.

**Comment by alex4200** [comment]
Some comments:
- Would have preferred two symbols which have the same 'design'/color scheme. But I guess this is almost impossible to find.
- The 'webapp' usecases have not really something to do with the 'web'/'world', but I am not sure if there is a icon for a 'GUI' application. I did not find anything.
- So lets stick with the icons for now, but maybe the jupyter icon can be made a bit smaller? It seems to be bigger than the other icon

**Comment by antonelepfl** [comment]
Maybe 
![](https://www.pinclipart.com/picdir/middle/133-1331118_world-wide-web-icon-internet-symbol-clipart.png)
And 
![](https://miro.medium.com/max/346/0*I3hkRieQ6B3qwwhy.)
?

**Comment by alex4200** [comment]
That looks better to me, at least very similar color (and both icons actually showing two planets!). Earth's moon is missing, but that is fine (as well as 76 known moons of jupiter ;-) )

I vote for this

**Comment by clupascu** [comment]
Ok. It seems better for me too now. I agree with Alex's comments.

**Comment by antonelepfl** [comment]
Due it's implemented on DEV I'll close this

**Comment by alex4200** [comment]
But it is not implemented on PROD. To not forget to do this I reopen this ticket

**Comment by antonelepfl** [comment]
This should be in production @alex4200 Can you verify this and close it please?

**Comment by antonelepfl** [comment]
I have added also the documentation of it [here](https://github.com/antonelepfl/usecases/commit/9dea71345da2ba2ddb9eebb34d7fb1f56eca9b95)

**Comment by clupascu** [comment]
I saw it on prod. Can the icon be added next to "exp" and "hpc", or "beta" icons? I don't like it very much where it is right now. What do you think?

**Comment by alex4200** [comment]
@clupascu @antonelepfl Also the icon only seems to exist for very few use cases. I think it should be there for every use case.

**Comment by antonelepfl** [comment]
I appreciate your comments guys!
As a recommendation for future changes I would like to use DEV to get feedback and not PROD.
I did the changes on DEV and you mentioned that it was good and then in PROD it was the opposite. Please try to do the checks in DEV first :)

I'll modify this soon and regarding that they appear only in a couple of use cases I would suggest the creators of the use cases to define the type and do a Pull Request changing the `usecases.json` file.

**Comment by clupascu** [comment]
@antonelepfl I didn't notice the behaviour on DEV. Anyway, I meant that I don't like very much icons positioning when the web app window is not maximized 

![immagine](https://user-images.githubusercontent.com/22050958/69280793-65b60500-0be7-11ea-9fb6-39817a5231ae.png)

It is better of course when the window is maximized

![immagine](https://user-images.githubusercontent.com/22050958/69280847-79616b80-0be7-11ea-9a95-5a697281293d.png)

Can be the positioning improved when window is not maximized?

**Comment by antonelepfl** [comment]
I have updated DEV with these changes
Please let me know if they look correct now
I have also added the `type` for most of the use cases.

![Screenshot 2019-11-29 at 10 14 14](https://user-images.githubusercontent.com/24406041/69858189-c69da700-1291-11ea-962b-43a87b43a759.png)
![Screenshot 2019-11-29 at 10 13 39](https://user-images.githubusercontent.com/24406041/69858190-c7363d80-1291-11ea-858e-56c2a8c9196e.png)
![Screenshot 2019-11-29 at 10 13 32](https://user-images.githubusercontent.com/24406041/69858191-c7363d80-1291-11ea-9f91-e0c95d9398de.png)

**Comment by alex4200** [comment]
@antonelepfl  Yes looks good to me so far - but it seems to be missing for the "Brain Area Circuit In Silico Experiments - Hippocampus" use case.

**Comment by antonelepfl** [comment]
Good catch !
I just patched that and the changes would be online soon!

**Comment by alex4200** [comment]
Thanks, now the icons seems to be applied consistently across the BSP. I suggest to move it also to Prod.

**Comment by alex4200** [comment]
In production, closing ticket.
