### ISSUE TITLE
Download raw data of analysis plots

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#481]
We should be able to download the data of the plots from the Sim-UI so we are able to reproduce / change that plot locally.

**Comment by antonelepfl** [comment]
I have implemented this on sim-ui DEV

**Comment by alex4200** [comment]
@antonelepfl The download seems to work so far, except the data for the INT spikes on the spike raster plot. They are missing.

**Comment by antonelepfl** [comment]
I have added this on DEV. You will get the JSON with GID and types

**Comment by alex4200** [comment]
For the download of the LFP plots the data do not seem to fit. The data contains a list 'spectrum.f' which only goes from 0 to 30, but in the plots in the browser they go to 1000 (Hertz). 
Also not sure if the PSD data are correct as they can be negative in the downloaded data, but are not negative in the plot.

**Comment by antonelepfl** [comment]
I fixed this IIRC

**Comment by alex4200** [comment]
Issue has been fixed in DEV. Needs to be merged to PROD.

**Comment by antonelepfl** [comment]
Pushed to production

**Comment by alex4200** [comment]
Tested in prod. Closing ticket
