### ISSUE TITLE
Allow select population, GIDs, or random for analysis

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#482]
So the current implementation looks something like:

![Screenshot 2019-10-16 at 14 36 21](https://user-images.githubusercontent.com/24406041/66919833-6248c000-f022-11e9-8903-17c36642866d.png)

The idea would be to select some sub-population, specify some GIDs, specify a range of GIDs, or just random cells that will be used for all the different analysis.

Some mockups of how this could like:
![Screenshot 2019-10-16 at 14 33 57](https://user-images.githubusercontent.com/24406041/66919652-0847fa80-f022-11e9-8ee0-7ed0ca9fdae2.png)
![Screenshot 2019-10-16 at 14 33 50](https://user-images.githubusercontent.com/24406041/66919653-08e09100-f022-11e9-9e1c-ec1d2d6e1d88.png)
![Screenshot 2019-10-16 at 14 36 31](https://user-images.githubusercontent.com/24406041/66919848-6c6abe80-f022-11e9-96b2-b4fd30b3fb52.png)

@mmigliore Do you think this are good or what suggestion would you propose?

**Comment by mmigliore** [comment]
Hello,
the first mockup looks ok but the list of GIDs should be selected
independently for histogram/raster and voltage.
This because one can usually pick a much larger set for raster and
histogram and a smaller number of cells to show the voltage.

**Comment by antonelepfl** [comment]
Thank you Michele,

I'm thinking in several options that meet your requirements:
1) You run an analysis with Raster and Histogram and select a population, in this case the voltage trace will be disabled due population may be too big. Then if you see that the network is behaving well, you run a second analysis selecting some random GIDs or specific ones and the voltage will be available.

2) We can separate the selection so it in the way that you can specify for each type of plot, which population is going to be used:

![Screenshot 2019-10-16 at 16 52 13](https://user-images.githubusercontent.com/24406041/66930821-76e28380-f035-11e9-8dad-1e038fedcba3.png)

![Screenshot 2019-10-16 at 16 52 19](https://user-images.githubusercontent.com/24406041/66930824-76e28380-f035-11e9-8676-3f40e5098572.png)

![Screenshot 2019-10-16 at 16 52 26](https://user-images.githubusercontent.com/24406041/66930825-76e28380-f035-11e9-8685-9ea98a7fcf61.png)

The only issue with 2) is that if you select random cells they may be different for each plot but if you want to really do a deep analysis, you can enter specific GIDs

**Comment by mmigliore** [comment]
Yes, that I think that it would work.

**Comment by antonelepfl** [comment]
Which one would work? option 1 or 2

**Comment by mmigliore** [comment]
Sorry, I would say option 2

**Comment by antonelepfl** [comment]
I have implemented this on sim-ui DEV

**Comment by alex4200** [comment]
I have three remarks

- Maybe it makes more sense to set the default value for the number of traces to 5 instead of 1?
- (LowPrio) I noticed that when you choose GID e.g. '11-13' then this means only GID's 11 and 12 are used (and not 13). This is consistent with the python list implementation, but might confuse other users. 
- When selecting random cell, you can only have a maximum of 80 (for PST and Spike Raster Plot). Why the limit to 80 if the 'Whole' plot has much more data points (like 1000)?

**Comment by antonelepfl** [comment]
I implemented this already

**Comment by alex4200** [comment]
Seems to work, closing ticket
