### ISSUE TITLE
BluePyOpt issue with NEURON 7.6 and python3

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#483]
## Details description of the task

@clupascu will create a new Collab, create a python3 notebook, use neuron 7.6 and  bluepyopt to create a plasticity code example that might fail for further investigation.

Related to #476

**Comment by clupascu** [comment]
Actually will not be a plasticity code, but a normal optimization.

**Comment by clupascu** [comment]
I tried to use the bluepyopt installation from the collab with Neuron 7.6.2 to run a simple optimization. It seems working fine. The only warning I got is this /opt/conda/envs/python2/lib/python2.7/site-packages/bluepyopt/ephys/simulators.py:74: UserWarning: Unable to find Neuron hoc shared library in /home/jovyan/.local/nrn/lib/python/neuron, not disabling banner
  'not disabling banner' % nrnpy_path)
@wvangeit can you confirm that the bluepyopt installation from the Collab works with Neuron7.6.2?

**Comment by wvangeit** [comment]
Sure BluePyOpt should work just fine with 7.6 (already since a long time).
Just be careful not to mix two neuron version if they would be both installed on the Collab

**Comment by clupascu** [comment]
@wvangeit ok. Thank you. I will close this issue.
