### ISSUE TITLE
Layer colors or layers inverted?

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#484]
### Expected behavior

Layer to be colored in order: 1,2,3,4,5,6

### Actual Behavior (please include screenshot if possible)

Colors of layers 1 and 2 inverted, i.e. layer 1 comes first with color red, the layer 2 with color green, but in the graphics greens comes before red.

### Steps to reproduce the problem

Load the circuit SSCx.S1

**Comment by pgetta** [comment]
Thank you, @alex4200.
That was a pretty severe bug, affecting `etype`, `layer` and `morph_class`  properties of the circuit cells.

It's fixed now, could you please evaluate it works as expected?

**Comment by alex4200** [comment]
Yes now it looks consistent. Closing ticket
