### ISSUE TITLE
Hippocampus Validation UseCase made Python 3 compatible

### ISSUE THREAD

**Issue by sasaray** [cnr-ibf-pa/hbp-bsp-issues#485]
The Hippocampus SingleCell Validation UseCase (https://collab.humanbrainproject.eu/#/collab/8123/nav/67071) is now compatible with both Python 3 and Python 2.

@alex4200, Can you please test if everyting works fine?

**Comment by alex4200** [comment]
@sasaray Yes the notebook seems to work with python3. 

@appukuttan-shailesh Ok to update this validation use case?

**Comment by appukuttan-shailesh** [comment]
Alex can you confirm that the use case works well on the collab with both
Py2 and Py3? If so, please go ahead with updating the use case. Thanks.

**Comment by alex4200** [comment]
@appukuttan-shailesh Is there a problem with the backend? I get zero models

**Comment by appukuttan-shailesh** [comment]
@alex4200 : I do see all the models, both on the model catalog and from within the usecase.
Are you using one of your "test" accounts? Note the SGA2 accreditation required for accessing certain resources at the moment.

**Comment by alex4200** [comment]
Right, I forgot. And yes I used a test user. I will try again

**Comment by alex4200** [comment]
@sasaray  @appukuttan-shailesh I get an error in "Instantiating the model; Running model validation for selected tests": 

```
ValueErrorTraceback (most recent call last)
<ipython-input-10-0766ce18bbeb> in <module>()
     22         with open(stim_file, 'r') as f:
     23             config = json.load(f, object_pairs_hook=collections.OrderedDict)
---> 24         result_id, score = utils.run_test(username=HBP_USERNAME, environment="integration", model=cell_model, test_alias="hippo_somafeat_"+ttype, test_version="1.0", storage_collab_id=collab_id, register_result=True, config=config, specify_data_set=specify_data_set)
     25 
     26     elif test == "Somatic Features Test - JMakara data set":

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/utils.pyc in run_test(username, password, environment, model, test_instance_id, test_id, test_alias, test_version, storage_collab_id, register_result, client_obj, **params)
    434 
    435     test_config_file = prepare_run_test_offline(username=username, password=password, environment=environment, test_instance_id=test_instance_id, test_id=test_id, test_alias=test_alias, test_version=test_version, client_obj=client_obj, **params)
--> 436     test_result_file = run_test_offline(model=model, test_config_file=test_config_file)
    437     result_id, score = upload_test_result(username=username, password=password, environment=environment, test_result_file=test_result_file, storage_collab_id=storage_collab_id, register_result=register_result, client_obj=client_obj)
    438     return result_id, score

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/utils.pyc in run_test_offline(model, test_config_file)
    256     # Run the test
    257     t_start = datetime.utcnow()
--> 258     score = test.judge(model, deep_error=True)
    259     t_end = datetime.utcnow()
    260 

/opt/conda/envs/python2/lib/python2.7/site-packages/sciunit/tests.pyc in judge(self, model, skip_incapable, stop_on_error, deep_error)
    301 
    302         if deep_error:
--> 303             score = self._judge(model, skip_incapable=skip_incapable)
    304         else:
    305             try:

/opt/conda/envs/python2/lib/python2.7/site-packages/sciunit/tests.pyc in _judge(self, model, skip_incapable)
    244 
    245         # 2.
--> 246         prediction = self.generate_prediction(model)
    247         self.check_prediction(prediction)
    248         self.last_model = model

/opt/conda/envs/python2/lib/python2.7/site-packages/hippounit/tests/test_SomaticFeaturesTest.pyc in generate_prediction(self, model, verbose)
    378 
    379         run_stim_ = functools.partial(self.run_stim, model)
--> 380         traces_results = pool.map(run_stim_, stimuli_list, chunksize=1)
    381         #traces_results = traces_result.get()
    382 

/opt/conda/envs/python2/lib/python2.7/multiprocessing/pool.pyc in map(self, func, iterable, chunksize)
    251         '''
    252         assert self._state == RUN
--> 253         return self.map_async(func, iterable, chunksize).get()
    254 
    255     def imap(self, func, iterable, chunksize=1):

/opt/conda/envs/python2/lib/python2.7/multiprocessing/pool.pyc in get(self, timeout)
    570             return self._value
    571         else:
--> 572             raise self._value
    573 
    574     def _set(self, i, obj):

ValueError: unsupported pickle protocol: 3
```

It also looks like python2.7 is used here although the kernel is python3. And  pickle protocol 3 is a new protocol only for python3. 

Maybe one or more packages must be re-installed for python3?

**Comment by sasaray** [comment]
@alex4200 , @appukuttan-shailesh  This probably happens because the test has already been run on the same model using Python2 and the traces are already saved in pickle files that are supposed to be loaded instead of running the whole simulation again. Unfortunately it seems that pickle files created under Python2 can not be used under Python3 (or the other way around). 
I will try to find a solution for this.

**Comment by appukuttan-shailesh** [comment]
Great if this is easily doable, as suggested here:
https://stackoverflow.com/questions/25843698/valueerror-unsupported-pickle-protocol-3-python2-pickle-can-not-load-the-file

But otherwise, I am not sure we need to worry too much about this eventuality. In a few months we are all expected to move to Py3. Users left using Py2 don't have much right to complain after that ;-)
Also, it is unlikely that real users would want/need to switch between kernels for running a particular UseCase.

**Comment by alex4200** [comment]
I also propose to just support the python3 case. I even suggest to take out any python2 related code. The kernel is python3 when the use case is cloned, and we will only support python3 in the future.

**Comment by clupascu** [comment]
Unfortunately, as @sasaray was saying, the pickle files created under Python2 can not be used under Python3 (or the other way around). We will have a problem with all the usecases related to the optimization of single cells. All the optimizations provided until now (and all the ones already registered in the KG) have as output a pkl file created under Python2, that will be impossible to use under Python3.

**Comment by alex4200** [comment]
Maybe this can help?   https://rebeccabilbro.github.io/convert-py2-pickles-to-py3/

**Comment by alex4200** [comment]
A retest of the notebook with two test users worked fine. I have uploaded the notebook to the use cases repository (will be in PROD later this month).
