### ISSUE TITLE
Documentation and Contributors for the Validation use cases 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#489]
## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | Documentation and Contributors for the Validation use cases 
Expert | @appukuttan-shailesh 

 
**Remove anything that does not apply**
## List of additional/changed features 
*What are the changed or new features? What activities can users perform while using it? What makes it different from similar use cases? List the main functions that you will build into your product here. Also specify the priority ‘mandatory’, ‘important, ‘nice to have’.*

### Tasks

- [x] Documentation Update (see [current docu](https://collab.humanbrainproject.eu/#/collab/1655/nav/18580))
- [x] Contributors Update for the use cases
- [ ] ...

**Comment by appukuttan-shailesh** [comment]
Will be undertaken in mid-Dec along with Py3  UseCase releases.

**Comment by appukuttan-shailesh** [comment]
Completed.

**Comment by alex4200** [comment]
Guidebook updated, as well as contributors list
