### ISSUE TITLE
NSG login boxes are misaligned

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#49]
### Expected behavior

Input boxes are aligned

### Actual Behavior

Input boxes are misaligned

![selection_064](https://user-images.githubusercontent.com/12729291/32218812-72c35488-be2c-11e7-8d6e-e7de4c303536.png)

### Steps to reproduce the problem

- Select the use case
- Select the notebook NSG Job Manager and run the cells

### Optional infrastructural data (user, platform, browser, environment, ...)

Most prominent on Google Chrome, but also in Firefox

**Comment by clupascu** [comment]
I fixed this. Can you please check again? Thanks.

**Comment by alex4200** [comment]
Looks good
