### ISSUE TITLE
Deprecated function matplotlib.plt.hold  for use case "Purkinje cell simulation and validation"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#496]
### Expected behavior

Use case "Simulation and validation of a mouse Purkinje cell multicompartmental model" from the Single Cell Modelling runs without error. 

### Actual Behavior (please include screenshot if possible)

In that use case there _can_ be the following error:

`AttributeError: Module 'matplotlib.pyplot' has no attribute 'hold'. `

### Steps to reproduce the problem

1. Install matplotlib version >3 (e.g. 3.1.2)
2. Restart the kernel
3. Run the notebook

The reason is that the 'hold' attribute for  'matplotlib.pyplot'  has been removed for matplotlib version >=3. It looks like you just can remove that line in the cell where you define the function 'trace_features'. The notebook seems to run just fine (and still creates the same plots as before).

**Comment by SteMasoli** [comment]
Hi.

I have changed it to plt.close() to prevent multiple images to fuse together.
This command causes a warning that is irritating but innocuous.

**Comment by alex4200** [comment]
Thanks, work now
