### ISSUE TITLE
Synaptic plasticity

### ISSUE THREAD

**Issue by clupascu** [cnr-ibf-pa/hbp-bsp-issues#498]
## New Use Case "Synaptic plasticity use case"

Aspect | Detail
------------ | -------------
Summary | This use case allows a user to configure and test, through an intuitive GUI, different synaptic plasticity models and protocols on any of the single cell optimized models present in the model catalog. It consists of two tabs: "Config", where the user can specify the plasticity model to use and synaptic parameters such as location, initial weight, activation pattern, additional somatic current injections, or voltage clamp parameter, and  "Sim", where the user can define the recording location, weight's evolution, and also the number of simulations to run (to obtain average results). The results are plotted at the end of the simulation and the traces can be downloaded for further analysis
Usecase Group | Single cell building
Expert | Carmen Lupascu
HPC Requirements | No HPC Requirements
Dependencies |
Nominal runtime |

  
A first version is available here https://collab.humanbrainproject.eu/#/collab/72837/nav/493741 
@alex4200 please can you test it?

**Comment by alex4200** [comment]
Small image still missing

**Comment by alex4200** [comment]
@clupascu will update the image for this notebook. Then it can be closed. 

Documentation update will go in a different issue.

**Comment by clupascu** [comment]
I am closing this issue.
