### ISSUE TITLE
Math rendering in collabs do not seem to work

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#5]
When I edit the 'Overview' in a collab, the math rendering does not seem to work. I still see the Latex form of an equation...

![mycollab_math](https://user-images.githubusercontent.com/12729291/31009251-1f0c19d0-a507-11e7-92b9-17c9dffeb609.png)

**Comment by jdcourcol** [comment]
for https://forum.humanbrainproject.eu/

**Comment by alex4200** [comment]
Issue opened on the forum
