### ISSUE TITLE
No NSG login feedback.

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#50]
### Expected behavior

Feedback/popup when login to NSG

### Actual Behavior

No popup or feedback.

### Steps to reproduce the problem

Run the notebook (Run all), and log in to NSG with either correct or incorect password.

**Comment by clupascu** [comment]
I fixed this. Can you please check again? Thanks.

**Comment by alex4200** [comment]
Yes fixed
