### ISSUE TITLE
Model not available anymore for download (Morphology Analysis)

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#503]
### Expected behavior

Morphology Analysis does work

### Actual Behavior (please include screenshot if possible)

As the model is not found anymore, the notebook is broken. 

Should Nexus be used instead?

### Steps to reproduce the problem

wget https://validation-v1.brainsimulation.eu/models/?name=CA1_int_bAC_011017HP2_20180110153901

## Guidelines

When updating the notebook you might consider some of the [Guidelines](https://collab.humanbrainproject.eu/#/collab/69119/nav/469089) to provide an improved look & feel.

**Comment by apdavison** [comment]
The validation service is currently down for an upgrade (i.e. switching to the KG-based version). It should be back up by 18:00 this evening.

**Comment by apdavison** [comment]
This should now be fixed (since Friday evening)

(note that a simple wget will not work, since you need to provide the authorization token in the header)

**Comment by alex4200** [comment]
@apdavison Thanks, It works again with proper authorization.
