### ISSUE TITLE
Python3 update for Connectome Cerebellum

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#504]
### Expected behavior

Should work for python3

### Actual Behavior (please include screenshot if possible)

Several incompatibility issues. 

### Steps to reproduce the problem

1. Clone notebook
2. Change kernel
3. Run all cells

## Guidelines

When updating the notebook you might consider some of the [Guidelines](https://collab.humanbrainproject.eu/#/collab/69119/nav/469089) to provide an improved look & feel.

**Comment by stefanocasali984** [comment]
Now the Connectome use case should be Pyhton3-compatible.

[(https://collab.humanbrainproject.eu/#/collab/8124/nav/69081)]
