### ISSUE TITLE
Import error not visible for molecular/protein usecases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#506]
### Expected behavior

Notebook should fail when an import does not succeed, and the user needs to see where and what is the problem.

### Actual Behavior (please include screenshot if possible)

If an import fails there is just the message 'Problem importing a dependency. ' but it is not further specified. Furthermore, since no error is raised, the automated tests continue and the notebook fails at a later stage. Makes it hard to debug the actual problem

### Suggestion

Remove the try-except clause for the three molecular/protein usecases

### Additional information

The setup notebooks must be changed to include the following line:

`!conda install -y -c conda-forge ipywidgets==7.0.5`

Reason: It might happen that some other notebook changes the `ipywidgets` version to version 5.2.2 and in that case the version of `nglview` will not work anymore.

**Comment by adamhospital** [comment]
Should be fixed now. 
Thanks for the suggestions.

**Comment by alex4200** [comment]
@adamhospital Did you forget to change the notebook for "Preparing a protein-ligand complex to run an atomistic Molecular Dynamics Simulation"?

**Comment by adamhospital** [comment]
Sorry, it was modified, but I forgot to save it ...
Done!

**Comment by alex4200** [comment]
Yes thanks, now I tested the three again, seem to work fine. Created Pull Request.

**Comment by antonelepfl** [comment]
@alex4200 Can you confirm that these changes are already in prod?

**Comment by alex4200** [comment]
Yes in production.
