### ISSUE TITLE
Service Account PizDaint - filename with '.' (dot) are not retrievable

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#508]
If I submit a file called `input.sh` then when I use the API to get the content
```
https://bspsa.cineca.it/files/PIZDAINT/bsp_pizdaint_01/{{JOB_ID}}/{{INPUT_FILENAME}}
```
I get
```
{
    "detail": "Not found."
}
```

But if I upload / get with `input_sh` it works correctly. The same issue with `.zip`, `.txt`, etc

**Comment by rcsm17** [comment]
Hi @antonelepfl could you check again if it works ?

**Comment by alex4200** [comment]
@rcsm17 @antonelepfl  Any news on this issue?

**Comment by antonelepfl** [comment]
I'm not using this feature because I'm using the advanced endpoint.

**Comment by alex4200** [comment]
So ticket can be closed?

**Comment by alex4200** [comment]
@lbologna Asking @rcsm17

**Comment by rcsm17** [comment]
Hi, sorry for the late reply first.
So I checked the normal endpoint to fetch a file with dot notation and in my case it works. 
I tried with the "output.zip" and "CA1_int_cAC_010710HP2_20200305092603.zip" and I received them without any problem.  

If you want to check by yourself go to: https://collab.humanbrainproject.eu/#/collab/17259/nav/301898.
Here you can find the Service Account API, just compile the fields with the correct parameters and run the cell.

**Comment by antonelepfl** [comment]
Ok then, we close this one and re-open in case that someone has the same issue.
Thank you Roberto
