### ISSUE TITLE
Json error, probably transient NSG query issue

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#51]
### Expected behavior

Json error to be handled smoothly

### Actual Behavior

Error message printout

![selection_066](https://user-images.githubusercontent.com/12729291/32264181-b5dd7508-bedd-11e7-8f4f-51519ccac508.png)

### Steps to reproduce the problem

Start a job for the use case "Rebuild an existing hippo. cell model", and run the notebook "Job Manager". Check the status repeatedly.

My guess is that the data transfer from the NSG query did not work at that very time, resulting in that error. Not a big issue, but a user can be confused. Maybe put a popup with a text like "Transient communication error. Please trya gain" or something.

The full error message:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-95a36583fb01> in refresh(_)
    154 def refresh(_):
    155     global listtoprint, listtoprint1, jobslistfile
--> 156     storage = collab_get_storage_client()
    157     hdr = get_bbp_client().task.oauth_client.get_auth_header()
    158     my_url = 'https://services.humanbrainproject.eu/idm/v1/api/user/me'

<ipython-input-3-5465b1808fc6> in collab_get_storage_client()
     11 
     12 def collab_get_storage_client():
---> 13     return desktop_get_storage_client(oauth.get_token())
     14 
     15 import hashlib

<ipython-input-3-5465b1808fc6> in desktop_get_storage_client(bearer_token)
      8 
      9 def desktop_get_storage_client(bearer_token):
---> 10     return Storage(bearer_token)
     11 
     12 def collab_get_storage_client():

<ipython-input-3-5465b1808fc6> in __init__(self, bearer_token)
     36     def __init__(self, bearer_token):
     37         sl = ServiceLocator.new()
---> 38         self.oidc_url = sl.get_service_url('user','v1')
     39         self.document_service_url = sl.get_service_url('document','v1')
     40         self.client = Client.new(bearer_token)

/home/jupyter/.local/lib/python2.7/site-packages/hbp_service_client/document_service/service_locator.pyc in get_service_url(self, service, version)
     38                 The URL where the service is located
     39         '''
---> 40         return self.__get_services()[service][version]
     41 
     42     def __get_services(self):

/home/jupyter/.local/lib/python2.7/site-packages/hbp_service_client/document_service/service_locator.pyc in __get_services(self)
     42     def __get_services(self):
     43         '''Wrapper function around requests'''
---> 44         return requests.get(self.__services_url).json()

/usr/local/lib/python2.7/dist-packages/requests/models.pyc in json(self, **kwargs)
    824                     # used.
    825                     pass
--> 826         return complexjson.loads(self.text, **kwargs)
    827 
    828     @property

/usr/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    336             parse_int is None and parse_float is None and
    337             parse_constant is None and object_pairs_hook is None and not kw):
--> 338         return _default_decoder.decode(s)
    339     if cls is None:
    340         cls = JSONDecoder

/usr/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
    364 
    365         """
--> 366         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    367         end = _w(s, end).end()
    368         if end != len(s):

/usr/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
    382             obj, end = self.scan_once(s, idx)
    383         except StopIteration:
--> 384             raise ValueError("No JSON object could be decoded")
    385         return obj, end

ValueError: No JSON object could be decoded`

**Comment by clupascu** [comment]
This is a collab storage problem. I reported the problem to the collab platform team. It happens sometime, not very often, but they don't know how to solve it yet. I will see if I can reproduce it and give feedback to the user. Let's hope that the collab team will solve the problem though.

**Comment by clupascu** [comment]
The collab team claim there was an issue with how this particular json file was deployed on the hosting web server, which may have been the source of the problem. They now fixed this issue, and they ask us to report problem to them if we still encounter it. On the other side they will make changes in the client library to handle this situation better. Can you try to reproduce the issue again please?

**Comment by alex4200** [comment]
I tested it by clicking 20 times the reload button, and the issue did never appear again. Solved on the 95% level...
