### ISSUE TITLE
Python3 update for "Brownian dynamics simulation"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#510]
### Expected behavior

Should work for python3

### Actual Behavior (please include screenshot if possible)

Several incompatibility issues. 

### Steps to reproduce the problem

1. Clone notebook
2. Change kernel
3. Run all cells

## Guidelines

When updating the notebook you might consider some of the [Guidelines](https://collab.humanbrainproject.eu/#/collab/69119/nav/469089) to provide an improved look & feel.

**Comment by StefanGIT** [comment]
It looks like this is due to problems in python3 compatibility of the underlying SDA bootstrap script that is installed in /opt/minimal-sda_flex-7.2.2
Would it be possible to upgrade this to sda_flex-7.2.3? I have attached this here as a zip file.
[sda_flex-7.2.3-minimal.zip](https://github.com/cnr-ibf-pa/hbp-bsp-issues/files/4148695/sda_flex-7.2.3-minimal.zip)

**Comment by StefanGIT** [comment]
In addition to installing this new SDA version, also the environment variable  SDAHOME needs to be set. The notebook gets the SDA directory by the call  sdaDir = os.environ['SDAHOME']

**Comment by alex4200** [comment]
I need to check with the admins of the Collab on how this can be implemented. But adding a cell like the following 

```
!wget https://github.com/cnr-ibf-pa/hbp-bsp-issues/files/4148695/sda_flex-7.2.3-minimal.zip
!unzip sda_flex-7.2.3-minimal.zip
!cd minimal-sda_flex-7.2.3/src && make clean && make
os.environ['SDAHOME'] = "/home/jovyan/minimal-sda_flex-7.2.3"
```

will install the new version, and make the notebook work with python3.

**Comment by StefanGIT** [comment]
I have copied the change to the private MolecularUseCases area. It was working now using python3. How to get this to the public area?

**Comment by StefanGIT** [comment]
@alex4200  The sda notebook is now working in the public area:
https://collab.humanbrainproject.eu/#/collab/50197/nav/344097
with changes to download sda from github pages. Once SDA can be used from /opt/, let me know.

**Comment by antonelepfl** [comment]
@alex4200  Could you re-check if this is working properly? Is this on the BSP Prod?

**Comment by alex4200** [comment]
Usecase has been checked on STAGE. Will be merged soon to PROD
