### ISSUE TITLE
Installing custom NEST modules in the BSP

### ISSUE THREAD

**Issue by AliceGem** [cnr-ibf-pa/hbp-bsp-issues#513]
For new cerebellar microcircuit use-cases, we need to install NEST 2.18 and a custom NEST module in the BSP. We managed to install the 2.18 NEST version (see Ticket#482709) from Github -
https://github.com/nest/nest-simulator/commits/nest-2.18
(even if it needs to be reinstalled every time the kernel is restarted, which is not so user-friendly) and a custom NEST module - https://github.com/dbbs-lab/cereb-nest, executing all the required steps (see https://nest.github.io/nest-simulator/extension_modules ) with no errors. However, when running the final command to install the module into PyNEST (nest.Install("cerebmodule")), the kernel dies, with no information on the possible cause of the error. 
Jupyter notebook to install NEST 2.18 from Github (the current NEST version on the BSP is 2.12) and then install the custom NEST module for cerebellar neurons and plasticity ("cerebmodule" - https://github.com/dbbs-lab/cereb-nest) is available here: https://collab.humanbrainproject.eu/#/collab/73961/nav/511936

We addressed this in Ticket# 482820.

**Comment by alex4200** [comment]
https://support.humanbrainproject.eu/#ticket/zoom/2820

**Comment by alex4200** [comment]
@AliceGem I was able to reproduce the issue, and the logs in the Collaboratory show the following message:

`/opt/conda/bin/python: symbol lookup error: /home/jovyan/nest-simulator/b/lib/nest/cerebmodule.so: undefined symbol: _ZN4nest25register_connection_modelIN6mynest19STDPAlphaConnectionEEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_28RegisterConnectionModelFlagsE`

**Comment by AliceGem** [comment]
So, that error was due to incompatibility between the last NEST version on 2.18 branch on Github and our custom NEST module version. I solved installing the released 2.18.0 which is on Zenodo instead of using the Github version and all installations and import work fine, even if they need to be done at each Kernel restart.
