### ISSUE TITLE
Service Account - TSI Unavailable 

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#517]
I cannot submit any job due the TSI is not available.

Is the UnicoreTSI for the Service Account on Cineca right?

@lbologna any ideas?

**Comment by antonelepfl** [comment]
I guess @rcsm17 You got the email about service account going down right? Can you try to bring it up please?

**Comment by lbologna** [comment]
@antonelepfl,  we are working on some issue that we found on the job result fetching so probably this is the reason. I just added @rcsm17 in the status cake notification service. The service should be up again now.

**Comment by antonelepfl** [comment]
Perfect ! thank you

**Comment by antonelepfl** [comment]
I'm getting Unicore TSIUnavailableException 
```{"errorMessage":"Error downloading from '/BlueConfig': de.fzj.unicore.xnjs.tsi.TSIUnavailableException: TSI unavailable: java.io.IOException: Can't create connection to TSI connector @ daint101.cscs.ch/148.187.26.64:4433: java.net.ConnectException: Connection refused (Connection refused) [XNJS error 10]","status":500}```

Can you have a look @BerndSchuller ?

**Comment by BerndSchuller** [comment]
this is on DAINT so Fabio Verzelloni at CSCS would be the one to look.
Seems the TSI daemon is not running.

**Comment by antonelepfl** [comment]
Thank you Bernd for the prompt reply. I'll contact him then.
