### ISSUE TITLE
Python3 update for Synaptic Events Fitting usecases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#519]
### Expected behavior

Should work for python3

### Actual Behavior (please include screenshot if possible)

Several incompatibility issues. 

### Steps to reproduce the problem

1. Clone notebook
2. Change kernel
3. Run all cells

The following notebooks are affected:

- [x] Synaptic Events Fitting
- [x] Synaptic Events Fitting with user data
- [x] Synaptic Events Fitting with user model
- [x] Synaptic Events Fitting Analysis

## Guidelines

When updating the notebook you might consider some of the [Guidelines](https://collab.humanbrainproject.eu/#/collab/69119/nav/469089) to provide an improved look & feel.

**Comment by clupascu** [comment]
The first version of Python 3 compatible Synaptic events fitting usecases are available for test at https://collab.humanbrainproject.eu/#/collab/71255/nav/483240 are now compatible with Python 3.

@alex4200 can you please continue to test if everything works fine and add comments here?

**Comment by alex4200** [comment]
@clupascu  In the very big code cell you need to import the packages first, then define the `RadioButton`. When I fix that manually, the notebook seems to work (at least for Jureca).

**Comment by clupascu** [comment]
@alex4200 What packages should I import first? This ones

import plotly
import os
?

**Comment by alex4200** [comment]
@clupascu  Here is a part of your code:

```
RB1=RadioButtons(description= 'Select mod file', options=['default','local'])
display(RB1)
DM=Text()
DM.value='ProbGABAAB_EMS_GEPH_g.mod'
DM.visible=True
DM.disabled=True
display(DM)
import warnings
warnings.filterwarnings('ignore')           
from ipywidgets import widgets
from IPython.display import *
from ipywidgets import *
import requests
import json
import time
import _thread
import sys
from IPython.display import HTML,Javascript, display
...
```
You are trying to use an instance of `RadioButtons` _**before**_ you import its definition.

**Comment by clupascu** [comment]
I fixed this. Can you please test again? Thanks.

**Comment by alex4200** [comment]
@clupascu  Yes this works now. 

But I think you have to remove the first two cells in your DEV notebook, as these cells are being added later automatically.

**Comment by clupascu** [comment]
The new DEV notebooks are here

Synaptic Events Fitting https://collab.humanbrainproject.eu/#/collab/9130/nav/528639
Synaptic Events Fitting with user data https://collab.humanbrainproject.eu/#/collab/9130/nav/528640
Synaptic Events Fitting with user model https://collab.humanbrainproject.eu/#/collab/9130/nav/528641
Synaptic Events Fitting Analysis https://collab.humanbrainproject.eu/#/collab/9130/nav/529488
@alex4200 please let me know when I should modify the usecases.json with the new links to the Python3 versions.

**Comment by alex4200** [comment]
@clupascu  Still working on these use cases

**Comment by clupascu** [comment]
@alex4200 Synaptic Events Fitting use case is ready with the new modules on the HPC systems and ipywidgets 7.5.1. The links are the one from the usecases.json. Please test and let me know. Thanks.

**Comment by clupascu** [comment]
@alex4200 Synpatic Events Fitting - user data and user model usecases are also ready with the new modules on the HPC systems and ipywidgets 7.5.1. I updated also Synaptic Events Fitting as I introduced also Galileo. I modified also the names of the folders when they are saved to the storage. The links are the one from the usecases.json. Please test everything and let me know. Thanks.

**Comment by alex4200** [comment]
@alex4200 Put into prod when all if fine
@clupascu Update documentation and figures

**Comment by alex4200** [comment]
Pull request for Production done: https://github.com/antonelepfl/usecases/pull/346

**Comment by clupascu** [comment]
I updated the documentation and figures in the Guidebook. @alex4200 please take a look and let me know when we can close this issue. Thanks.

**Comment by alex4200** [comment]
@clupascu Where to find the updates; I assume you mean the dev version of the guidebook?

**Comment by clupascu** [comment]
Yes. Here's the link for the simple use case: https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/trace_analysis/syn_events_fit/syn_events_fit.html . I updated also the other usecases of course.

**Comment by alex4200** [comment]
@clupascu The pages look good to me, can be put to PROD.

**Comment by alex4200** [comment]
Notebooks are up-to-date, documentation is updated. Closing ticket.
