### ISSUE TITLE
Python3 update for "Rebuild/BuildOwn Single HippoCell" usecases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#520]
### Expected behavior

Should work for python3

### Actual Behavior (please include screenshot if possible)

Several incompatibility issues. 

### Steps to reproduce the problem

1. Clone notebook
2. Change kernel
3. Run all cells

The following notebooks are affected:

- [x] Rebuild Single HippoCell - Config
- [x] Rebuild Single HippoCell - Analysis
- [x] Rebuild Single HippoCell - NSG Job Manager
- [x] BuildOwn Single HippoCell - Config
- [x] BuildOwn Single HippoCell - Config
- [x] BuildOwn Single HippoCell - Config

## Guidelines

When updating the notebook you might consider some of the [Guidelines](https://collab.humanbrainproject.eu/#/collab/69119/nav/469089) to provide an improved look & feel.

**Comment by clupascu** [comment]
@alex4200 you can find Python3 compatible notebooks for Rebuild Single HippoCell here https://collab.humanbrainproject.eu/#/collab/78266/nav/529788. Can you please test them and let me know? Thanks.

**Comment by alex4200** [comment]
@clupascu I did not start actual testing, but I noticed two issues with these notebooks:

1. They have the header which are copied into the notebook  when you clone the notebook in production (the first two cells). Please remove them in every notebook.
2. The model URL is set. I guess it has to be something like `model_url = "REPLACEURL"` or something

**Comment by clupascu** [comment]
yes. I am aware of both issues. It is just a temporary DEV that I use for test. When the test is finished I will move the notebooks into the 'original' DEV collab and I will remove header and I will replace model URL.

**Comment by clupascu** [comment]
@alex4200 can you please test Rebuild Single HippoCell from DEV. It should be Python3 compatible now. Please let me know if you find any issues. Thanks.

**Comment by clupascu** [comment]
@alex4200 you can now test also Build Single HippoCell from DEV now. It is Python3 compatible. Please let me know if you find any issues. Thanks.

**Comment by alex4200** [comment]
@clupascu This use case still seems to downgrade to the old ipywidgets. Can you fix that please as well?

**Comment by clupascu** [comment]
@alex4200 Are you cloning from the link I replaced in usecases.json? This one? https://collab.humanbrainproject.eu/#/collab/9132/nav/537802

**Comment by antonelepfl** [comment]
This PR https://github.com/antonelepfl/usecases/pull/321 is not merged yet.. Based on what I saw there are some notebooks that don't work properly.

**Comment by clupascu** [comment]
ok. We will discuss about this in 30 minutes during the meeting.

**Comment by antonelepfl** [comment]
The change https://github.com/antonelepfl/usecases/pull/321 This should be in Prod now.
We need the changes for Rebuild right? @clupascu

**Comment by alex4200** [comment]
The Rebuild notebook are in production and seem to work. 

I will test the BuildOwn usecases in DEV later.

**Comment by antonelepfl** [comment]
I'm a bit lost here ... If I'm not mistaken, Carmen only changed the BuildOwn (see my comment above) the rebuild was not submitted yet.
Please Carmen correct me if I missed something

**Comment by clupascu** [comment]
@antonelepfl I don't remember the commit number, but I changed both "Rebuild Single HippoCell" and "BuildOwn Single HippoCell".

**Comment by clupascu** [comment]
Commit #321 for "BuildOwn Single HippoCell".

**Comment by clupascu** [comment]
Commit #310 for "Rebuild Single HippoCell".

**Comment by alex4200** [comment]
Updated notebooks pushed to usecases, PR [331](https://github.com/antonelepfl/usecases/pull/331). 
Waiting to be finally tested on STAGE.

**Comment by alex4200** [comment]
Changes has been pushed to PROD
