### ISSUE TITLE
Installation of bluepyopt on Marconi Broadwell and Galileo

### ISSUE THREAD

**Issue by pramodk** [cnr-ibf-pa/hbp-bsp-issues#522]
Here is the email:

```
As Marconi KNL is down at the moment, would it be possible that you or your
collaborators install BluePyOpt on Marconi Broadwell and Galileo?

Please let me know if it is possible and how long the process would take.
```

- [x] bluepyopt working on Marconi Broadwell
- [x] bluepyopt working on Galileo

Related task: #533

**Comment by pramodk** [comment]
Here is how modules can be used:


### Galileo 

```
export MODULEPATH=$MODULEPATH:/gpfs/work/HBP_CDP21_it_1/pkumbhar/HBP/galileo/install/latest
module purge
module load anaconda/2019.07 python/3.6.4 py-bluepyopt

$ nrnivmodl .

$ python3
Python 3.6.4 (default, Feb 14 2018, 14:45:07)
...
>>> from neuron import h
>>> import bluepyopt as bpop
>>> import bluepyopt.ephys as ephys
>>> import matplotlib
>>> import numpy
>>>
```

### Marconi Broadwell

```
export MODULEPATH=$MODULEPATH:/marconi_work/HBP_CDP2_it/pkumbhar/HBP/marconi/install/latest
module purge
module load python/3.6.4 anaconda && module unload python/3.6.4
module load python/3.6.4 py-bluepyopt py-matplotlib/3.1.1

$ nrnivmodl .

$ python3
Python 3.6.4 (default, Feb 14 2018, 14:45:07)
...
>>> from neuron import h
>>> import bluepyopt as bpop
>>> import bluepyopt.ephys as ephys
>>> import matplotlib
>>> import numpy
>>>
````

**Comment by clupascu** [comment]
Thank you @pramodk. I will test both and let you know.

**Comment by SteMasoli** [comment]
Marconi A2 (KNL) was under decommission  starting with the 15th of january.

**Comment by mmigliore** [comment]
Correct. This is why BluePyOpt is being deployed and tested on the
broadwell partition of Marconi and on Galileo.


Il gio 6 feb 2020, 10:00 Stefano <notifications@github.com> ha scritto:

**Comment by clupascu** [comment]
@pramodk the modules that you shared work fine on Marconi Broadwelll and Galileo through ssh. I am still waiting for the installation of Unicore in order to test the modules on Unicore too. I will update the ticket when the Unicore installation will be complete.

**Comment by clupascu** [comment]
@pramodk can you please install also on jureca the bluepyopt python3 version? Thank you. Please keep also the already available python2 version on jureca if possible.

**Comment by alex4200** [comment]
@clupascu  Needs to test the new installation

**Comment by clupascu** [comment]
@pramodk any news on the installation of bluepyopt python3 on jureca?

**Comment by pramodk** [comment]
> @pramodk any news on the installation of bluepyopt python3 on jureca?

this was bit mixed with neuron3 installation in  #525. Sorry.

@jorblancoa is enabling python3 module for bluepyopt as well and should be available as documented [here](https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/525#issuecomment-592614343). we will update here once that is done.

**Comment by jorblancoa** [comment]
It should be already available.
Module name: py-bluepyopt/1.6.56-gcc-serial-python3

**Comment by clupascu** [comment]
When I load the above module on jureca I get

+ module load py-bluepyopt/1.6.56-gcc-serial-python3
++ /usr/local/software/lmod/7.7.6/libexec/lmod bash load py-bluepyopt/1.6.56-gcc-serial-python3
Lmod has detected the following error: The following module(s) are unknown:
"py-bluepyopt/1.6.56-gcc-serial-python3"

**Comment by jorblancoa** [comment]
Sorry I forgot to mention that you need to load 26-02 modules:
`module use /p/project/cvsk25/software-deployment/HBP/jureca-booster/26-02-2020/modules/tcl/linux-centos7-haswell`
`module load py-bluepyopt/1.6.56-gcc-serial-python3`

**Comment by clupascu** [comment]
Now my job fails with some errors 

PSI: handleAnswer: spawn to node 3631 failed: "testExecutable: stat(ipengine): No such file or directory"
Could not spawn 'ipengine' process 143: No such file or directory
spawnSingleExecutable: PSI_spawn() failed.
Unable to start all processes. Aborting.
srun: error: jrc5631: tasks 0-23: Exited with exit code 2

**Comment by clupascu** [comment]
@pramodk opened a ticket on Jureca requesting the installation of some packages. Ipyparallel is one of the packages needed that was creating the error from my previous comment (I think).

**Comment by pramodk** [comment]
@clupascu : we started looking into this last friday and saw that some of the packages are missing on JURECA booster which were previously available. So we are checking if those can be installed.

**Comment by alex4200** [comment]
Hi, can you please tick the boxes in the top-most main comment to mark the cases that are done?

**Comment by pramodk** [comment]
See #533, bluepyopt is installed on both systems.

**Comment by clupascu** [comment]
I am closing this issue. We will continue commenting on #533.
