### ISSUE TITLE
Import Error in "Calculate the electrostatic potential of a protein from its atomic structure" use case

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#523]
Usecase will be excluded from automated tests.

### Expected behavior

Notebook runs fine

### Actual Behavior (please include screenshot if possible)

After the package 'multipipsa' has been installed (version 4.0.3) it's import will fail in the next cell. 

`from multipipsa.multipipsa import ApbsRun
`
```
ImportErrorTraceback (most recent call last)
<ipython-input-2-9efe82e59be5> in <module>()
----> 1 from multipipsa.multipipsa import ApbsRun

/opt/conda/envs/python2/lib/python2.7/site-packages/multipipsa/multipipsa.py in <module>()
     21 import warnings
     22 from pprint import pformat
---> 23 from multipipsa.clusterpipsa import ClusterPipsa
     24 from multipipsa.pipsatypes import ScoreType
     25 from multipipsa.pipsatypes import SimilarityType

ImportError: No module named clusterpipsa
```

### Steps to reproduce the problem

```
! pip install --extra-index-url https://projects.h-its.org/pypi multipipsa
from multipipsa.multipipsa import ApbsRun
```

### Optional infrastructural data (user, platform, browser, environment, ...)

PROD

**Comment by StefanGIT** [comment]
The notebook was fixed by upgrading the multipipsa package from 4.0.2 to 4.0.3. However it looks like if 4.0.2 is already installed on the Collab it thinks the requirement is already satisfied.

I have now made the 4.0.3 in the notebook explicit:
pip install --extra-index-url https://projects.h-its.org/pypi multipipsa==4.0.3
and copied the modified notebook to the MolecularUsecase Collab.

**Comment by alex4200** [comment]
@StefanGIT I see no change in the DEV location https://collab.humanbrainproject.eu/#/collab/50197/nav/350840
 Are you sure you have updated the notebook and saved it?

**Comment by StefanGIT** [comment]
@alex4200  ok, i copied it now to MolecularUseCases_pub, but now there are two notebooks. The one with multipipsa==4.0.3 is correct. Can/Should i delete the other one?

**Comment by alex4200** [comment]
@StefanGIT Please proceed with the following procedure:

- Delete the new notebook you created. It contains a header that is added to that notebook when you clone it. This is not what we want. 
- Edit/correct your ORIGINAL notebook in that Collab, do not create a new notebook. This will make things only more complicated (for you and me). 
- If you have corrected your ORIGINAL notebook let me know. Then I will test it and - if everything works fine - update the PRODUCTION notebook which are stored in a safe place in a github repository.

**Comment by StefanGIT** [comment]
Hi Alex,


i have now edited the original, set the kernel to python 3 and the multipipsa version to 4.0.3. See:

https://collab.humanbrainproject.eu/#/collab/50197/nav/350840

I hope this is ok now.

Best,

Stefan?

?

________________________________
Von: alex4200 <notifications@github.com>
Gesendet: Freitag, 7. Februar 2020 07:08
An: cnr-ibf-pa/hbp-bsp-issues
Cc: Richter, Stefan; Mention
Betreff: Re: [cnr-ibf-pa/hbp-bsp-issues] Import Error in "Calculate the electrostatic potential of a protein from its atomic structure" use case (#523)


@StefanGIT<https://github.com/StefanGIT> Please proceed with the following procedure:

  *   Delete the new notebook you created. It contains a header that is added to that notebook when you clone it. This is not what we want.
  *   Edit/correct your ORIGINAL notebook in that Collab, do not create a new notebook. This will make things only more complicated (for you and me).
  *   If you have corrected your ORIGINAL notebook let me know. Then I will test it and - if everything works fine - update the PRODUCTION notebook which are stored in a safe place in a github repository.

-

**Comment by alex4200** [comment]
@StefanGIT Thank you for the update. The notebook seems to work. 

However, I have one request: Can you please remove the try-except clause in the second cell? Because in the case something is wrong with the setup, you only get a note saying that _something_ is wrong with the setup, but not what. I think it is best to let the cell fail with the appropriate error. 

Thank you

**Comment by StefanGIT** [comment]
I have removed the try except in the second cell and saved it again.
Best,

**Comment by alex4200** [comment]
@StefanGIT Thanks a lot - that is all that is required from your side. 

I will update the notebook in production and close this ticket once it is in production.

**Comment by DKokh** [comment]
Alex, as  the notebook is in production, may I close this ticket?

**Comment by alex4200** [comment]
@DKokh I will do a quick check first.

**Comment by alex4200** [comment]
Notebook seems to wotk in prod. closing ticket
