### ISSUE TITLE
New title GUI element overlaps 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#53]
### Actual Behavior

New title element is overlapping other elements. On the feature selection page I am not able to click the tab "Spike events features" (see screenshot).

![selection_067](https://user-images.githubusercontent.com/12729291/32443455-6131289e-c2ff-11e7-8267-0b62e10e0bc6.png)
![selection_068](https://user-images.githubusercontent.com/12729291/32443457-61491896-c2ff-11e7-8823-89d172f9f9b8.png)

### Steps to reproduce the problem

Just follow the use case

### Optional infrastructural data (user, platform, browser, environment, ...)

Chrome on Ubuntu. In Firefox (Ubuntu/Mac) it seems to work!

**Comment by lbologna** [comment]
This issue should be solved now. Could you check again please?

**Comment by alex4200** [comment]
Issue solved...
