### ISSUE TITLE
New Use Case: Cerebro-cerebellar loops

### ISSUE THREAD

**Issue by alberto-antonietti** [cnr-ibf-pa/hbp-bsp-issues#532]
## New Use Case
  
Aspect | Detail
------------ | -------------
Summary | This use-case shows a modeling effort of whole brain functionalities by leveraging on the existing cerebellar models. We model and simulate the forward and inverse controller functions of the cerebrocortical-cerebellar loops in a closed-loop setting, emulating error-based learning and action prediction. The cerebellum model, made of single-point neurons with non-linear dynamics), leverages on the scaffold developed in Task 6.2.2 (see Use-case #529) and is embedded with long-term synaptic plasticity rules for implicit learning. The cerebellum models are split into two modules, one operating in feed-forward mode (receiving motor command, i.e. the efference copy, and generating a sensory error prediction) and the other operating in inverse mode (receiving the sensory information of the desired target and generating compensatory motor commands). The model is used to simulate a specific sensorimotor task in closed-loop. We emulate a pointing task perturbed by prismatic glasses. The cerebellar modules allow to achieve complementary processing able to predict a sensory discrepancy and compensatory motor commands. Therefore, the cerebellum works as a general-purpose massive predictive machine in whole-brain modular systems.
Usecase Group | Brain Area Circuit In Silico Experiments
Expert | Alberto Antonietti
Scientific User |
Deadline | March 2020
Target audience | Developers, Computational Neuroscientists
Target interface | Notebook
HPC Requirements | OpenMP
Dependencies | libraries needed are compiled if not present
Nominal runtime | 2 hours

## List of features
This use case:
1) [Prepares the environment with all needed libraries and Python packages](https://collab.humanbrainproject.eu/#/collab/79916/nav/541058):
 - NEST 2.18.0
 - NEST additional modules: cereb-nest and extra-cereb-nest
 - cerebellum-scaffold library
2) [Creates the cerebro-cerebellar network and calibrates it](https://collab.humanbrainproject.eu/#/collab/79916/nav/541059) (i.e., the output of the spiking neural network has to be transformed into a meaningful variable - angular deviation)

3)  [Creates the cerebro-cerebellar network and generates two simulations](https://collab.humanbrainproject.eu/#/collab/79916/nav/541060)
 - A first simulation with a static model of the cerebellar modules (i.e., the plasticity is not active). As a result, the error remains high, around 25°.
- A second simulation with a plastic model of the cerebellar modules (i.e., the plasticity is active). As a result, the error decreases trial after trial, thanks to cerebellar adaptation.

     
## Acceptance Criteria
The three notebooks have to run, the user can perform the calibration and then the two simulations.
  
### System
The notebooks have been tested in CollabV1 and it uses OpenMP (the 16 threads available for Notebooks)
  
### Performance
Preparation of the environment: 30 minutes
Calibration: 30 minutes
Simulation: 1 hour

**Comment by alberto-antonietti** [comment]
The use-case in now in PROD in the BSP.

**Comment by alberto-antonietti** [comment]
PR created to add this UC in the BSP guidebook.

https://github.com/lbologna/hbp-sp6-guidebook/pull/77

**Comment by lbologna** [comment]
Hello, 
I accepted the PR and did some minor changes/typos correction:

https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/brain_area_circuit_in_silico_experiments/cerebrocerebellar/cerebrocerebellar_closed_loop_experiment/cerebrocerebellar_closed_loop_experiment.html

@alex4200 , @alberto-antonietti could you have a look before pushing to prod?
Thanks.

**Comment by alberto-antonietti** [comment]
Thanks Luca!

I pushed a few minor changes, I am good with the rest.

**Comment by alberto-antonietti** [comment]
The documentation of this UC is now in the guidebook. Shall we close this issue?

**Comment by alex4200** [comment]
@alberto-antonietti @lbologna I found a small typo for this documentation, in the section "Output":

![Screenshot 2020-05-13 at 10 48 28](https://user-images.githubusercontent.com/12729291/81791720-5ca75000-9507-11ea-868b-fcad8476bbfb.png)

**Comment by alex4200** [comment]
Fix on production, closing ticket
