### ISSUE TITLE
Unicore - Nodes allocation

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#535]
Hi @BerndSchuller,

We would like to know if the jobs that Unicore allocate are in exclusive nodes or a node can be shared with multiple users. I did not find this on the [documentation](https://www.unicore.eu/documentation/manual-archive)

**Comment by BerndSchuller** [comment]
UNICORE delegates to Slurm - what UNICORE does is create a file (named "bss_submit_...") and invoke "sbatch bss_submit_...".

Usually, nodes are not shared.

**Comment by antonelepfl** [comment]
Is there any way to confirm that the Nodes are not shared?
It would be possible to add and extra param on Unicore so we can add the `--exclusive` flag to the `bss_..`

**Comment by BerndSchuller** [comment]
on which system is this?

in principle it's possible to either add a flag or to hard code it in the TSI, but I'm pretty sure that on HPC systems compute nodes are not shared.

**Comment by antonelepfl** [comment]
It is in Piz-Daint (CSCS)
Ok I just wanted some more information due I'm not an expert on this

**Comment by BerndSchuller** [comment]
OK
