### ISSUE TITLE
Service Account - /core get anonymus info

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#536]
When I get the information on `https://bspsa.cineca.it/advanced/pizdaint/rest/core`

I have missing information:
<img width="901" alt="Screenshot 2020-04-14 at 13 16 28" src="https://user-images.githubusercontent.com/24406041/79219275-3e8bf880-7e52-11ea-9330-f34cf94e4dbd.png">

In normal PizDaint I get the correct information:
<img width="837" alt="Screenshot 2020-04-14 at 13 20 27" src="https://user-images.githubusercontent.com/24406041/79219568-d0940100-7e52-11ea-9b26-a93770d6e87d.png">

I think this might be a Unicore related issue. Maybe restarting the service helps

**Comment by BerndSchuller** [comment]
Since you are asking, UNICORE is working fine. I am correctly authenticated at Piz Daint with both my old and new collab accounts (BTW your second screenshot is from Jureca, not DAINT)

As to accessing https://bspsa.cineca.it/advanced/pizdaint/rest/core I see the same issue: the "anonymous" DN.

**Comment by antonelepfl** [comment]
Right Bernd, in PizDaint I also get the correct information:

<img width="786" alt="Screenshot 2020-04-14 at 13 47 40" src="https://user-images.githubusercontent.com/24406041/79221707-975d9000-7e56-11ea-9aa9-a94238c2daa2.png">

**Comment by lbologna** [comment]
Hello @antonelepfl @BerndSchuller,

last week we moved the vm where the Service Account is running to a different machine on CINECA. This implied the change of the IP but the domain has remained the same and the vm is up:
https://bspsa.cineca.it/status/

@BerndSchuller may this IP change have caused a mulfunctioning of the mapping to the HPC system user (the submission is not performed through token authentication but via username and password insertion)? 

Here we report the entire error message of a test call, where an IP address issue seems to be raised:
400
'"{\\"errorMessage\\":\\"Could not submit job: eu.unicore.security.AuthorisationException: There are no accessible targetsystem factories for: Name: CN=ANONYMOUS,O=UNKNOWN,OU=UNKNOWN\\\\nXlogin: uid: [], gids: [addingOSgroups: true]\\\\nRole: anonymous: No role information available\\\\nSecurity tokens: Delegation to consignor status: false, core delegation status: false\\\\nMessage signature status: UNCHECKED\\\\nClient\'s original IP: 131.175.198.110 Please check your security setup!\\",\\"status\\":500}"'

Thanks.

**Comment by BerndSchuller** [comment]
hi Luca, all,
 
> @BerndSchuller may this IP change have caused a mulfunctioning of the mapping to the HPC system user (the submission is not performed through token authentication but via username and password insertion)?

Last week Fabio Verzelloni from CSCS updated the UNICORE installation. It is possible that the special mapping for the service account was not ported over properly. Please contact him!

**Comment by lbologna** [comment]
Hello @BerndSchuller ,

thank you, I will write to Fabio.

**Comment by antonelepfl** [comment]
@lbologna do we have any update on this?

**Comment by lbologna** [comment]
Hello @antonelepfl,

Fabio at CSCS solved the authentication issue.
Now the submission works but it seems we are getting html text as response, instead of json as it was before.

@BerndSchuller is this due to the new UNICORE version? maybe we are we disregarding some parameters in the job submission?

Thanks.

**Comment by BerndSchuller** [comment]
always add a "Accept: application/json" header to your REST calls

**Comment by lbologna** [comment]
Thanks @BerndSchuller,

we found a misprint in the call code and were using "Content-Type" (as for POST) instead of "Accept". Strangely enough, never gave any problem before.
Now it seems to work again.

@antonelepfl could you please try again? Thanks.

**Comment by antonelepfl** [comment]
Hi @lbologna so the issue with `/core` is fixed but now when I try to submit a job I get:

`{"errorMessage":"Error uploading to '/BlueConfig': java.io.IOException: Execution on TSI server failed. Reply was TSI_FAILED: [Errno 13] Permission denied: '/scratch/snx3000/unicore/FILESPACE/29afbc2c-78e5-46a3-a80a-2daf939c501b///BlueConfig'\n","status":500}`

Not very sure if it is related to the change of `Content-Type` that you did though. (see that sometimes you need to use [both](https://sourceforge.net/p/unicore/wiki/REST_API/#media-types) and for [upload](https://sourceforge.net/p/unicore/wiki/REST_API/#data-upload-and-download) too)

**Comment by rcsm17** [comment]
> 
> 
> Hi @lbologna so the issue with `/core` is fixed but now when I try to submit a job I get:
> 
> `{"errorMessage":"Error uploading to '/BlueConfig': java.io.IOException: Execution on TSI server failed. Reply was TSI_FAILED: [Errno 13] Permission denied: '/scratch/snx3000/unicore/FILESPACE/29afbc2c-78e5-46a3-a80a-2daf939c501b///BlueConfig'\n","status":500}`
> 
> Not very sure if it is related to the change of `Content-Type` that you did though. (see that sometimes you need to use [both](https://sourceforge.net/p/unicore/wiki/REST_API/#media-types) and for [upload](https://sourceforge.net/p/unicore/wiki/REST_API/#data-upload-and-download) too)

Hi @antonelepfl can you try again now ?

**Comment by antonelepfl** [comment]
Yes now it works! Thanks.
We can close this ticket
