### ISSUE TITLE
Documentation still missing for usecase "Multicompartmental simulation of the cerebellum"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#538]
Documentation

## Documentation
 
Aspect | Detail
------------ | -------------
Summary | Documentation missing
Expert | @Helveg 

Short summary of the use case is missing in the [Guidebook](https://collab.humanbrainproject.eu/#/collab/1655/nav/18580).

See [here](https://docs.google.com/document/d/19Ni5fGFv6PTTM1D_D2FN4dj5IRhtfq1D0V2OWjXxJww/edit#heading=h.pnxj2hjfo7iq) for implementation details.

**Comment by Helveg** [comment]
Under which path and filename should my documentation file be added?

**Comment by alex4200** [comment]
@Helveg Please see the other entries in the guidebook, that should give you an ideas. 

But I would say it should go under source/online_usecases/brain_area_circuit_in_silico_experiments/cerebellum with a concise filename not containing any whitespaces. 

@lbologna Do you have some input on that?

**Comment by alex4200** [comment]
@Helveg Do you have any updates on this issue?

**Comment by Helveg** [comment]
Sorry I lost track of this, I'll do it today

**Comment by alex4200** [comment]
Documentation in PROD
