### ISSUE TITLE
Allocation memory problem on Jureca booster when running BluePyOpt

### ISSUE THREAD

**Issue by clupascu** [cnr-ibf-pa/hbp-bsp-issues#540]
### Expected behavior
BluePyOpt optimization runs without problems with the Python3 modules from issue #533 
### Actual Behavior 
When runnning the optimization with 
OFFSPRING_SIZE=128
MAX_NGEN=2
I get
[0;31mBrokenProcessPool[0m: [Errno 12] Cannot allocate memory

### Steps to reproduce the problem
The same issue does not happen with Python2.
The job runs successfully in less than 7 minutes. 
The working Python2 script can be found at /p/home/jusers/lupascu1/jureca/test_jaro_morph3_young_control/
The log of the working job is this one /p/home/jusers/lupascu1/jureca/test_jaro_morph3_young_control/logs/ipyparallel_8196473.log 
The sbatch file to run the job is ipyparallel_jureca.sbatch

The not working Python3 script can be found at /p/home/jusers/lupascu1/jureca/test_jaro_morph_young_control_Py3/
The log of the not working job is this one /p/home/jusers/lupascu1/jureca/test_jaro_morph_young_control_Py3/logs/ipyparallel_8196500.log
The sbatch file to run the job is ipyparallel_jureca22042020.sbatch

The Python3 script works perfectly though with 
OFFSPRING_SIZE=10
MAX_NGEN=2
The log is this one /p/home/jusers/lupascu1/jureca/test_jaro_morph_young_control_Py3/logs/ipyparallel_8196701.log
The sbatch file to run the job is ipyparallel_jureca22042020_2.sbatch

**Comment by clupascu** [comment]
@jorblancoa

**Comment by clupascu** [comment]
@pramodk @jorblancoa any news on this?

**Comment by jorblancoa** [comment]
Hi @clupascu 

We will run some tests next week and contact support if necessary and we will get back to you as soon as possible.

**Comment by jorblancoa** [comment]
hi @clupascu 

Right now Juelich systems are down, but once they are up and running and I would be able to run some test I will let you know.

**Comment by pramodk** [comment]
I believe this is no longer relevant ticket.
