### ISSUE TITLE
NEO visualizer has been updated

### ISSUE THREAD

**Issue by appukuttan-shailesh** [cnr-ibf-pa/hbp-bsp-issues#542]
Our team recently released a new version of the neo visualizer (used for viewing electrophysiological traces online). We moved to a new plotting library and this results in much faster (~ 5x) plotting of traces, even without using the 'downsampling' option.

This necessitated some changes in all the live papers that used this feature. I have updated the following use cases accordingly:

**2018**
2018/eyal_et_al_2018/eyal_et_al_2018.html
2018/migliore_et_al_2018/migliore_et_al_2018.html

**2019**
2019/amsalem_et_al_2019/amsalem_et_al_2019.html
2019/amsalem_et_al_2019/test_bokeh.html
2019/casali_et_al_2019/casali_et_al_2019.html
2019/geminiani_et_al_2019/geminiani_et_al_2019.html
2019/martinello_et_al_2019/martinello_et_al_2019.html
2019/masoli_et_al_2019/masoli_et_al_2019.html
2019/solinas_et_al_2019/solinas_et_al_2019.html

**2020**
2020/amsalem_et_al_2020/amsalem_et_al_2020.html
2020/giacopelli_et_al_2020/giacopelli_et_al_2020.html
2020/hjorth_et_al_2020/hjorth_et_al_2020.html

**Other files:**
index.html
static/template/network_paper_template.html

I have made a [PR](https://github.com/cnr-ibf-pa/hbp-bsp-live-papers-dev/pull/37) for the live papers, and the changes shall be visible on the live papers soon.
Once available, I would request @alex4200 and/or live paper owners to verify that the visualizer continues to work as expected on their live papers.

@lbologna : could you update here once the PR has been merged? Thanks.

**Comment by lbologna** [comment]
Hello @appukuttan-shailesh, Hello @alex4200,

I accepted the pull request. Most of the live papers are not using the neo-visualizer but given that this is a general purpose library that might be used elsewhere, a check could be useful.
I checked Migliore et al 2018 and found that the following traces cannot be visualized correctly:
	pyr-cac ->  95914003.abf not working
 	pyr-cac ->  95810031.abf not working
 	pyr-cac ->  95810011.abf not working
	int-cAC ->  97509009.abf not working

On a side note, I saw that all the 3D view morphologies in Eyal et al 2018 cannot be visualized anymore:
https://cnr-ibf-pa.github.io/hbp-bsp-live-papers-dev/2018/eyal_et_al_2018/eyal_et_al_2018.html
They refer to the Model Catalog. Is it possible that the ids have been changed and the source model cannot be found?
(@appukuttan-shailesh I removed the amsalem_et_al_2019 folder, because this was a leftover. The live paper is now  amsalem_et_al_2020)

**Comment by appukuttan-shailesh** [comment]
Thanks for the quick response @lbologna .
I had done a `grep` across all the live papers to find all that were loading the visualizer script files, and found all those listed above. But you are right, maybe many of them don't actually use it. The code might have been copied over from the template when they started making the live papers.

 I tested all the above 4 signals in Migliore et al 2018 just now and they all worked fine for me. Can you check once again? If you still find some problem, can you share a screenshot so that I can convey the same to the people handling it?

Regarding the 3D morphologies from Eyal et al 2018.... yes I can see that there is some problem with their entries on the model catalog (inaccessible at the moment). Judging from the live paper URLs, the model UUIDs seem to have been:
>022d44be-bf8d-452a-a436-f14794cf5676
5bb35857-007e-4168-b0f2-d6f62aec91d7
fbc08765-e3b3-4365-8f05-40d9f4a64756
e2da9168-da92-4cb8-b7cb-bd1786d992a7
38081019-4428-4eb9-9174-dbb69703987a
e8aec8c4-f080-4ea4-91ae-2b7c0b5ef02b

These don't seem to be valid at the moment. I shall try to see if it was something to do with the migration to KG, and the UUIDs having gotten changed.

p.s. My laptop has broke down, and so I shall have limited connectivity this week. In the process of finding a replacement.

**Comment by alex4200** [comment]
@lbologna I also did a quick check, and for me something is shown for the traces you have listed

**Comment by lbologna** [comment]
Hello @alex4200, @appukuttan-shailesh, 

thanks for checking. I can visualize those traces (in Migliore et al 2018) as well now, but I cannot visualize another one, which is well visualized in a private window, though.
It seems that, after opening a few (5/10/..) traces, some of them cannot be opened anymore and the panel is not filled (simply, the traces do not show up, and no error is generated in the console).

@appukuttan-shailesh, yes I also think the js library import was just inherited by cloning a  previously existing file. I rapidly checked, and it seems that the only live papers that actually use the neo visualizer are the following ones:

Hjorth et al 2020 (soon in production, currently in dev)
Masoli et al 2019
Migliore et al 2018

**Comment by appukuttan-shailesh** [comment]
Just confirmed that the model UUIDs for the models in Eyal et al 2018 had infact changed. For the record, here is the mapping from the old to the new UUIDs:

```
022d44be-bf8d-452a-a436-f14794cf5676 => 4649f8ec-1928-4c86-8ecf-475990286c52
5bb35857-007e-4168-b0f2-d6f62aec91d7 => 32ed233a-3f8a-42df-bfa8-45c7b28f6167
fbc08765-e3b3-4365-8f05-40d9f4a64756 => a81c0155-a8d1-43ae-82d6-dae4e3bb6f30
e2da9168-da92-4cb8-b7cb-bd1786d992a7 => 240dcfda-55b7-421e-b593-d29ea6b6fe88
38081019-4428-4eb9-9174-dbb69703987a => 16f2bdb7-6aec-4c29-b2d0-0d35db3b682a
e8aec8c4-f080-4ea4-91ae-2b7c0b5ef02b => 2f14c756-48fe-49be-a897-479c9cd0af16
```
 I have made the changes to the live paper in the latest PR.
But there seems to be an additional problem with the morphology viewer, as it is not launching even directly from within the model catalog at the moment. See:

https://collab.humanbrainproject.eu/#/collab/1655/nav/75901?state=model.4649f8ec-1928-4c86-8ecf-475990286c52

I will look into this and contact Rembrandt Bakker (who handles the viewer).

**Comment by lbologna** [comment]
Thank you @appukuttan-shailesh for looking into this and following the morphology viewer issue.
I accepted your corrections for the Eyal Live Paper and links work now, so I put already in Prod.

**Comment by alex4200** [comment]
Hi, 

I have some comments to the "Calculation of bimolecular association rates with webSDA" guidebook page:

1. In the first line it reads:"This use case describes how you can predict **protein-protein the** diffusional association rate constant by using the web server version of the SDA (Simulation of Diffusion Association) package." Maybe the "protein-protein" and the "the" are swapped?
2. The bullet points in "Background": There should be more distance between the answer and the next question. It does not look good. Also there is a typo:
![Screenshot 2020-05-08 at 15 55 45](https://user-images.githubusercontent.com/12729291/81412746-99a8c680-9144-11ea-908a-2340505eebfc.png)
3. Typo of "modeled" (with one 'L' is correct in American English):
![Screenshot 2020-05-08 at 16 01 52](https://user-images.githubusercontent.com/12729291/81413264-6adf2000-9145-11ea-8937-900cad12a52e.png)
4. "Setting up data and **runnung** simulations using webSDA" -> running
5. Later in that section: "The final PQR files can be **downloade** here:" -> downloaded

Please let me know when they have been fixed.

Thanks

**Comment by appukuttan-shailesh** [comment]
@alex4200 : are these comments for a different ticket?

**Comment by alex4200** [comment]
yes of course... (I will remove it)

**Comment by appukuttan-shailesh** [comment]
Thanks @lbologna 
We are looking into ways to fix the morphology viewer. Shall update as soon as I have something.

**Comment by appukuttan-shailesh** [comment]
This is still work in progess. With the KG being down at the moment, there isn't much scope for working on this. So might have to wait a week or two longer. Shall update whenever we have something going.

**Comment by alex4200** [comment]
@appukuttan-shailesh  The notebooks seem to be back running.

**Comment by appukuttan-shailesh** [comment]
Thanks for the update @alex4200 .
Still waiting to hear back from the team handling the morphology viewer. Shall send a reminder, and update here once I have something.

**Comment by appukuttan-shailesh** [comment]
This is almost ready.
Details here: https://github.com/HumanBrainProject/hbp-validation-framework/pull/264

Awaiting some final changes on the morphology viewer back-end. Should be soon.

**Comment by appukuttan-shailesh** [comment]
This is now completed. Sample link for testing:
https://collab.humanbrainproject.eu/#/collab/1655/nav/75901?state=model.01284a1d-6fd3-4cc0-8fa7-41eada65d9d9

"View Morphology" button for above will now redirect to:
https://neuroinformatics.nl/HBP/morphology-viewer-dev/?url=https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/Migliore_2018_CA1/models/CA1_int_bAC_011017HP2_20180110153901/CA1_int_bAC_011017HP2_20180110153901/morphology/011017HP2.asc&referrer=https%3A%2F%2Fcollab.humanbrainproject.eu%2F%23%2Fcollab%2F1655%2Fnav%2F75901%3Fstate%3Dmodel.01284a1d-6fd3-4cc0-8fa7-41eada65d9d9%2Cexternal

**Comment by alex4200** [comment]
Seems to work, closing ticket
