### ISSUE TITLE
GUI error for use case "Synaptic events fitting with user model" (DEV)

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#547]
### Expected behavior

Able to specify parameters for the model

### Actual Behavior (please include screenshot if possible)

Although specifying the number of parameters, the GUI does not show the possibilities to insert the parameters

![Screenshot 2020-06-02 at 16 30 46](https://user-images.githubusercontent.com/12729291/83532379-74626a80-a4ee-11ea-82d0-04c49a5e6e52.png)

### Steps to reproduce the problem

1. Select the DEV use case
2. Run all cells. 
3. Insert '5' for number as parameters in the fourth tab

### Optional infrastructural data (user, platform, browser, environment, ...)

DEV environment
Collab B0070

**Comment by clupascu** [comment]
@alex4200 I am able to specify the parameters. 5 rows of text boxes are created when I insert '5' for number as parameters in the fourth tab. Can you please try again and let me know? Thanks.

**Comment by alex4200** [comment]
yes works
