### ISSUE TITLE
client.storage.download_file() not working

### ISSUE THREAD

**Issue by alberto-antonietti** [cnr-ibf-pa/hbp-bsp-issues#548]
### Expected behavior
`client.storage.download_file() `should download a file from a storage location to a Jupyter notebook

### Actual Behavior (please include screenshot if possible)
An error is generated.

```
AttributeErrorTraceback (most recent call last)
<ipython-input-1-8f18f4e1ad0f> in <module>()
      1 get_ipython().system(u'pip install -q --upgrade "hbp-service-client==1.0.0"')
      2 client = get_hbp_service_client()
----> 3 client.storage.download_file("/79916/dbbs_scaffold-3.2.0-cp36-cp36m-linux_x86_64.whl", "dbbs_scaffold-3.2.0-cp36-cp36m-linux_x86_64.whl")
```

AttributeError: 'Client' object has no attribute 'download_file'
### Steps to reproduce the problem

In a new notebook (but this appears also on previously working UCs already in PROD), run a cell with:

```
!pip install -q --upgrade "hbp-service-client==1.0.0"
client = get_hbp_service_client()
client.storage.download_file("/79916/dbbs_scaffold-3.2.0-cp36-cp36m-linux_x86_64.whl", "dbbs_scaffold-3.2.0-cp36-cp36m-linux_x86_64.whl")
```

### Solution

Use

`!pip install hbp_service_client --upgrade`

instead of 

`!pip install -q --upgrade "hbp-service-client==1.0.0"`

(But UCs already in PROD could be broken if not updated, mine is, for example).

**Comment by AliceGem** [comment]
The same happens to mine (Olivo-cerebellar microcircuit - https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/529).

**Comment by clupascu** [comment]
I use hbp-service-client==1.1.0 and client.storage.download_file works fine.

**Comment by alberto-antonietti** [comment]
Thanks for checking Carmen. Today it seems to be working fine, as before
