### ISSUE TITLE
Model Catalog SSLError

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#549]
### Expected behavior
When I try to fetch some models using the url `https://validation-v1.brainsimulation.eu/models/` now I get 
```
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)
```
This started the 9th of August (before it was working properly)

I can use the `requests.get(..., verify=False)` in python but it would be better to know what changed that day.

@apdavison @appukuttan-shailesh

**Comment by appukuttan-shailesh** [comment]
The certificate problem should now be fixed. Can you re-check?

**Comment by antonelepfl** [comment]
Yes perfect thank you!
