### ISSUE TITLE
Simulation UI: Link to documentation

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#55]
A link to the documentation of this use case would be helpful.

**Comment by antonelepfl** [comment]
### Documentation 
# Configure and Launch Simulations
This use case allows a user to configure and launch a simulaiton in Juliech infrestructure using [Unicore API](https://www.unicore.eu/).

### 1) Run Simulations
![run_simulation](https://user-images.githubusercontent.com/24406041/32667514-33e24938-c63b-11e7-842c-761b808b3fa7.png)
---

From the **top** you can configure:
![run_simulation_top](https://user-images.githubusercontent.com/24406041/32667529-350b17f4-c63b-11e7-8d41-f9b889eed85d.png)

* `Duration`: Time length of stimulus duration, given in milliseconds(ms)
* `Forward Skip`: Run without Stimulus or Report for a given duration using a large timestep. This is to get the cells past any initial transience
* `View Simulations`: from here you can see all the history of simulations (explains in section **2**)

---

From the **middle** you can configure:
![run_simulation_middle](https://user-images.githubusercontent.com/24406041/32667526-34c78854-c63b-11e7-9647-4fc5bb02aa29.png)
* With the buttons you can _add_ new stimulus/report, _edit_ or _remove_ an existing one (You can also double-click on the timeline to add or edit)
    ![edit_buttons](https://user-images.githubusercontent.com/24406041/32667519-345d4980-c63b-11e7-8ae8-bfed57a15c16.png)


* `Stimulations`
    * For creation or edition of the item a form will appear
        * _Target_: Name of a target to receive the stimulation
        * _Pattern_: Type of the stimulus [Poission]
        * _Delay_: Time when the stimulus commences. given in milliseconds(ms)
        * _Duration_: Time length of stimulus duration, given in milliseconds(ms)
        * _Lambda_: Configure the random distribution
        * _Weight_: The strength of the created synapse
        * _Number of synapses_: The number of synapses to create
        ![edit_stimulus](https://user-images.githubusercontent.com/24406041/32667516-34101dfe-c63b-11e7-8099-5aa06aaea3a2.png)
  
* `Reports`
    * For creation or edition of the item a form will appear
        * _Target_: Defines the region from where the data will be reported. Note that cell targets versus compartment targets can influence report behavior
        * _Type_: Compartment means that each compartment outputs separately in the report file. Synapse indicates that each synapse will have a separate entry in the report [compartment, synapse]
        * _ReportOn_: The NEURON variable to access
        * _Unit_: The unit of the NEURON variable
        * _StartTime_: Time to start reporting(ms)
        * _EndTime_: Time to stop reporting(ms)
        * _Dt_: The frequency of reporting in milliseconds(ms)
        * _Format_: Defines the report output format [Bin, ASCII, HDF5]
        * _Number of synapses_: The number of synapses to create
       ![edit_report](https://user-images.githubusercontent.com/24406041/32667515-33f746da-c63b-11e7-81d3-da4d619d8317.png)

---

From the **bottom** you can `launch` the simulation:
* This will open a form to configure the parameters before executing the jobs in Juliech
    * _Title_: The title of the job
    * _Computer_: Which supercomputer will run the simulation.
    * _Project_: (optional) If you want to specify under which project the simulation should be run
    * _Nodes_: The amount of nodes that will be allocated and used for the simulation
    * _Run Time_: The max time before timeout
    * _Preview Config_: This will open a new tab with the complete configuration that is going to be sent (BlueConfig)
    ![run_simulation_form](https://user-images.githubusercontent.com/24406041/32667512-33b958de-c63b-11e7-83a1-1266f6bdbe13.png)


### 2) View Simulations
![view_simulation](https://user-images.githubusercontent.com/24406041/32667523-349da3cc-c63b-11e7-89f2-fb58dc5467c9.png)

---

From the **top** you are able to:
![view_simulation_top](https://user-images.githubusercontent.com/24406041/32667509-336e99de-c63b-11e7-9317-33280f3a55a6.png)

* `Filter` by _Title_, _Status_, _Supercomputer_
* `Create Simulation`: this goes back to _Configure and Launch simuation_ page
* `Reload`: to fetch the latest simulations and status

---

From the **middle** you are able to:
![view_simulation_middle](https://user-images.githubusercontent.com/24406041/32667511-33a4c3ce-c63b-11e7-80dc-5cfe41e5734b.png)
* `Check status` of Simulation and Analysis steps:
    * ready ![done](https://user-images.githubusercontent.com/24406041/32667524-34b25326-c63b-11e7-9efc-c6e269a03fbd.png)
    * queue ![sync](https://user-images.githubusercontent.com/24406041/32667513-33cdcf6c-c63b-11e7-9583-2d93e359db10.png)
    * aborted ![block](https://user-images.githubusercontent.com/24406041/32667510-338fc488-c63b-11e7-9a67-0e7effb19b4e.png)
    * failed ![error](https://user-images.githubusercontent.com/24406041/32667528-34f662fa-c63b-11e7-9357-300553b91fdc.png)

* `Run Analysis` if no analysis was launched you can do it from the analysis step
    * This will open a form to configure the parameters before executing the analysis in Juliech system
        * _Title_: Title of the job
        * _Origin_: Supercomputer when the simulation output are located
        * _Destination_: Supercomputer that the output files from simulation will be copied to and start the analysis
        * _Nodes_: Number of nodes dedicated for the analysis job
    ![run_analysis_form](https://user-images.githubusercontent.com/24406041/32667517-343012f8-c63b-11e7-8216-a89d7e128fcc.png)
* `Delete` the simulation
* `Abort` the simulation

### 3) Simulation Details
![simulation_details](https://user-images.githubusercontent.com/24406041/32667942-8bf00ad8-c63c-11e7-89f5-4bf510981fb0.png)

---
From the **top** you are able to see:
![simulation_details_top](https://user-images.githubusercontent.com/24406041/32667530-352085ee-c63b-11e7-8cf8-2bfb47aaf396.png)
* `Simulation` and `Analysis` with the following information
    * _Name_
    * _ID_
    * _Status_
    * _Submission Date_
    * _Auto Sync_ while the job is running reload the information

---
From the **middle** you are able to see:
![simulation_details_middle](https://user-images.githubusercontent.com/24406041/32667518-34478014-c63b-11e7-8025-98e7d49c17bd.png)
* _Analysis_: Plots of the analysis will be shown here
* _BlueConfig_: The configuration that was sent to run the simulation
* _Unicore Logs_
* _Stderr_: Logs of the simulation
* _Stdout_: Output information of the simulation

**Comment by antonelepfl** [comment]
@alex4200 Could you please have a look and give me feedback?

**Comment by alex4200** [comment]
- First sentence:  simulaiton -> simulation; Juliech -> Juelich (or better Jülich)
- First sentence: Maybe some few phrases would help on what simulation is being started?
- Forward Skip: Suggestion: "Time length in milliseconds (ms) of running the simulation without stimulus and without reporting. This is to get the neuronal cells past any initial transience."
- View Simulations: capital 'F' ("From here ..."); "explains" -> "explained"
- Stimulations: Pattern: "Type of the stimulus [Poission]" -> "... [Poisson]"
- Stimulations: Delay: use comma instead of period
- Stimulations: Lambda:We need to talk to Armando about this. Because different distributions have different 'parameter' identifiers. But anyway I would put 'Lambda' directly below the 'Pattern' box...
- Weight: The strength of the created synapses (<- plural s)
- Number of synapses: The number of synapses to create (Unclear to me. Are synapses created? Or just used for the stimulus?)
- *bottom*: Juliech -> Juelich or Jülich (and other occurances)
- Run Time: Suggestion: "The maximum time before timeout (in seconds)"
- "Origin: Supercomputer when the simulation output are located" when -> where? Otherwise the sentence does not make much sense to me

I will comment some more once I was able to finish a simulation myself...

**Comment by jdcourcol** [comment]
@antonelepfl can you put it directly in the Guidebook instead, as a PR ?

**Comment by antonelepfl** [comment]
So the documentation was pull requested.
https://github.com/lbologna/hbp-sp6-guidebook/blob/00be04ae2378b75545a23eda2f49df8b10f4176b/source/online_usecases/small_circuit_in_silico_experiments/configure_launch_simulation_hbp_data/configure_launch_simulation_hbp_data.rst
Please feel free to give feedback

**Comment by alex4200** [comment]
Some small remaining issues (until I am able to look at the whole use case):

- First sentence: infrestructure -> infrastructure
- In stimulations: synapseS -> synapses

**Comment by antonelepfl** [comment]
The documentation was added to the Guidebook
