### ISSUE TITLE
Service Account - working with EBrains

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#550]
I have deployed a new version of the Simulation Launcher using EBrains client but when I try to get some information using the endpoint `https://bspsa.cineca.it/advanced/pizdaint/rest/core` I get 500 error.

If I remember correctly at some point we were protecting the calls to the API allowing only some origins to go thru. Can we add this origin `https://simulation-launcher-bsp-epfl.apps.hbp.eu` that is the webapp deployed in HBP OpenShfit

**Comment by rcsm17** [comment]
I think I fixed it, could you check if it works now ?

**Comment by antonelepfl** [comment]
Yes it seems to work so far! Thank you Roberto
