### ISSUE TITLE
Disk quota exceeded in Jusuf - project cvsk25

### ISSUE THREAD

**Issue by jorblancoa** [cnr-ibf-pa/hbp-bsp-issues#552]
While deploying the software stack under project cvsk25 directory in Jusuf, I got a disk quota exceeded error.
After checking, the soft limit has been reached.

![Screenshot 2020-09-16 at 10 11 29](https://user-images.githubusercontent.com/41900536/93606409-4d11a980-f9c8-11ea-84e1-9df029d801d3.png)

**Comment by pramodk** [comment]
@mmigliore : we are close to finalise the deployment but couldn't finish it due to quota. Could you take a look?
(cc : @wvangeit )

**Comment by mmigliore** [comment]
we have deleted the previous model, freeing several Tb of disk space. Please see if you can also delete large files in your accounts and try again. Consider that the tool on JUDOOR that shows the storage is updated every 9Hrs.

**Comment by jorblancoa** [comment]
It worked fine, thanks!

**Comment by jorblancoa** [comment]
Hi @mmigliore 
I was trying to deploy the new software stack in Judor/Jureca and I encountered the same quota issues.

```
$ jutil project dataquota -U GB -p cvsk25
project      data-usage       data-soft-limit     data-hard-limit 
-------     -------------    ---------------      ----------------
 cvsk25      11262.411GB        10240.000GB        11264.000GB    
```
I checked how much space we are using with our deployment and in total (between Jusuf and Jureca) we are using 24 GB, so even if i delete some old deployed versions it wont be enough.

Could you have a look?
Thanks!

**Comment by mmigliore** [comment]
Hi Jorge,
you should deploy on the new account for JUSUF, where we have 17Tb of disk
space.
icei-hbp-2020-0001

not on the cvsk25, which is for JURECA Booster.
Best
Michele

**Comment by jorblancoa** [comment]
Thanks @mmigliore !
I redeployed in the icei-hbp-2020-0001 for JUSUF.
What about jureca-booster? Shall we stop deploying?

**Comment by mmigliore** [comment]
Thank you.
Yes, the allocation on jureca has expired and will not be renewed.
Could you post the instructions to load the different modules and the
simulation script templates?
Best
Michele

**Comment by jorblancoa** [comment]
You can find the instructions here:
https://github.com/BlueBrain/spack/wiki/JUSUF-Deployment
