### ISSUE TITLE
500 when calling https://bspsa.cineca.it/advanced/pizdaint/rest/core/jobs

### ISSUE THREAD

**Issue by ppodhajski** [cnr-ibf-pa/hbp-bsp-issues#554]
Hello,
When I call **https://bspsa.cineca.it/advanced/pizdaint/rest/core/jobs**  I receive error 500 with this errorMessage: 
`Could not submit job: de.fzj.unicore.xnjs.ems.ExecutionException: Could not create directory. [XNJS error 0]`

This is an intermittent behavior, I'd say 50% chance I will get an error.

Request payload:
`
{"Name":"05/10/_3","Executable":"/bin/bash input.sh","haveClientStageIn":"true","Resources":{"Nodes":1,"CPUsPerNode":36,"Runtime":3600,"NodeConstraints":"mc","CPUs":36},"Tags":["simulation","hippo_mooc_sa_microcircuit"]}
`

![Screenshot from 2020-10-05 10-59-21](https://user-images.githubusercontent.com/19837347/95060555-b8fb4e00-06fa-11eb-9c2c-c0a97d058346.png)
![Screenshot from 2020-10-05 10-59-12](https://user-images.githubusercontent.com/19837347/95060560-b993e480-06fa-11eb-87c9-bdd26f90769e.png)

**Comment by antonelepfl** [comment]
This was fixed

**Comment by antonelepfl** [comment]
Fabio was contacted to fix this again.
I got this error accessing directly with my personal account too
