### ISSUE TITLE
Redeploy new stack on PizDaint after the maintenance on 16th of March 2021

### ISSUE THREAD

**Issue by clupascu** [cnr-ibf-pa/hbp-bsp-issues#556]
# Expected behavior

loading modules without problems

# Actual Behavior (please include screenshot if possible)

module load daint-mc cray-python/3.8.2.1 PyExtensions/python3-CrayGNU-20.08
module load intel/19.0.1.144
module use /apps/hbp/ich002/hbp-spack-deployments/softwares/27-10-2020/install/modules/tcl/cray-cnl7-haswell
module load neuron/7.9.0a
module load py-bluepyopt

after loading the modules above I get

PyExtensions(45):ERROR:105: Unable to locate a modulefile for 'PyExtensions/python3-CrayGNU-20.08'
cray-mpich/7.7.15(9):ERROR:150: Module 'cray-mpich/7.7.15' conflicts with the currently loaded module(s) 'cray-mpich/7.7.16'
cray-mpich/7.7.15(9):ERROR:102: Tcl command execution failed: conflict cray-mpich

# Steps to reproduce the problem

On PizDaint
module load daint-mc cray-python/3.8.2.1 PyExtensions/python3-CrayGNU-20.08
module load intel/19.0.1.144
module use /apps/hbp/ich002/hbp-spack-deployments/softwares/27-10-2020/install/modules/tcl/cray-cnl7-haswell
module load neuron/7.9.0a
module load py-bluepyopt

# Optional infrastructural data (user, platform, browser, environment, ...)

PizDaint

**Comment by antonelepfl** [comment]
Hi Carmen, 
HPC have deployed the latest version of the software stack on 12-02-2021 [instructions](https://github.com/BlueBrain/spack/wiki/Piz-Daint-Deployment). (see **Run a simulation with small circuit target**)
Do you need a specific version of some software or the latest should be fine?

**Comment by clupascu** [comment]
Hi Stefano,

I get the same results even when I load the modules as suggested in the instructions that you linked. 

module load daint-mc cray-python/3.8.2.1 PyExtensions/python3-CrayGNU-20.08
module load intel/19.0.1.144
module use /apps/hbp/ich002/hbp-spack-deployments/softwares/27-10-2020/install/modules/tcl/cray-cnl7-haswell
module load neuron/8.0a
module load py-bluepyopt

I do not need any specific version, just the latest working one.

Thank you for your reply.

**Comment by antonelepfl** [comment]
Yes so, apparently the module `PyExtensions/python3-CrayGNU-20.08` has been replaced by `PyExtensions/python3-CrayGNU-20.11`

**Comment by clupascu** [comment]
Still get 

cray-mpich/7.7.15(9):ERROR:150: Module 'cray-mpich/7.7.15' conflicts with the currently loaded module(s) 'cray-mpich/7.7.16'
cray-mpich/7.7.15(9):ERROR:102: Tcl command execution failed: conflict cray-mpich

when I do module load py-bluepyopt

**Comment by jorblancoa** [comment]
Hi @clupascu 

As @antonelepfl mentioned they updated the PyExtensions module.
Regarding cray-mpich issue, they also changed the default version of mpich to 7.7.16 which is loaded by default. That is why it conflicts when trying to load the previous version. 
This has been fixed in the latest version of the software stack on 12-02-2021.
I also updated the [instructions](https://github.com/BlueBrain/spack/wiki/Piz-Daint-Deployment) accordingly.

Let me know if you have any other issues!
Jorge

**Comment by clupascu** [comment]
Hi @jorblancoa,

yes. But it seems in a new ssh session just doing 

module load daint-mc cray-python/3.8.2.1 PyExtensions/python3-CrayGNU-20.11
module load intel/19.0.1.144

module use /apps/hbp/ich002/hbp-spack-deployments/softwares/27-10-2020/install/modules/tcl/cray-cnl7-haswell
module load neuron/8.0a
module load py-bluepyopt

without doing module purge gives the error. I added module purge too and now it works. Let me run a simulation too and I will then close this issue.

Thank you.

**Comment by jorblancoa** [comment]
I updated the mpich version in the modules of 12-02-2021
If you want to keep using the modules of 27-10-2020 I could update them also.

**Comment by jorblancoa** [comment]
I have updated also 27-10-2020 modules, you should be able to run the script without the module purge now

**Comment by clupascu** [comment]
Everything works fine. I am closing the ticket. Thank you @pramodk @jorblancoa and @antonelepfl
