### ISSUE TITLE
Simulation UI: Dynamic feedback

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#57]
When changing the value of "Duration", the GUI reacts immediately. 

However, when editing it in the popup of the edit field, I have to save it first. The GUI does NOT react immediately.

**Comment by antonelepfl** [comment]
I think this issue is minor and the resolution will take too much time. Due it is not an essential issue that blocks the user to proceed, I propose to close it.
