### ISSUE TITLE
Simulation UI/ Reports page: Hover texts for edits

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#60]
When hovering the mouse over the items to edit: 

- Target hover text reads "Defines what is to be reported". I would rather say that this defines the region _where_ things are reported from, but not _what_...
- Type hover text: Not clear to me what the text means.

**Comment by antonelepfl** [comment]
Something like `Defines the region from where the data will be reported` is right?

**Comment by antonelepfl** [comment]
For the Type currently we have

> Compartment means that each compartment outputs separately in the report file. Synapse indicates that each synapse will have a separate entry in the report

Probably Michele or Armando should know how to make a better description

**Comment by alex4200** [comment]
@antonelepfl I will clarify with Michele/Armando and come back to you

**Comment by alex4200** [comment]
@antonelepfl Decision: 

1. Hover text for 'Target': Remove the second sentence
2. Make sure that when the user selects Target="AllCompartments" then the Type only can be compartment
3. Please make "Synapse" and "Compartment" both start with a capital letter

**Comment by antonelepfl** [comment]
Deployed. Please try it and close it after you tested it.

**Comment by alex4200** [comment]
@antonelepfl : One tiny thing: When you start with a Target != "AllCompartments" you can select Type="Synapses" . After that you can select Target="AllCompartments"  and the Type is still Synapses. You can even save this configuration. 
Could a check be implemented that checks the content of Type whenever 'Target' is updated? Or is that too complex?

**Comment by antonelepfl** [comment]
Thanks for pointing that! Could you re-check here? https://bbp.epfl.ch/public/dev.simulationapp/index.html?#/

**Comment by alex4200** [comment]
Yes perfect, thanks...
