### ISSUE TITLE
Simulation UI/Report page: Input check for 'ReportOn'

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#61]
Report: I guess you can any characters for 'ReportOn'? Or even html code? 
<img src="https://www.w3schools.com/images/w3schools_green.jpg" alt="W3Schools.com">

![selection_055](https://user-images.githubusercontent.com/12729291/32454177-bd7a3ec8-c31e-11e7-9bb1-f07c610607cd.png)

**Comment by antonelepfl** [comment]
For this I don't know the possible values to compare or filter.
