### ISSUE TITLE
Login NSG error.

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#65]
### Expected behavior

Login to NSG works as in other use cases

### Actual Behavior

When clicking on  "Login NSG" I see the popup with an error "NameError: name 'checkloginNSG' is not defined"

![selection_072](https://user-images.githubusercontent.com/12729291/32599465-ebbb22dc-c53c-11e7-986f-0106bc184959.png)

### Steps to reproduce the problem

Just try to log in

### Optional infrastructural data (user, platform, browser, environment, ...)

Linux, Chrome

**Comment by clupascu** [comment]
I fixed this. Can you test again please? Thanks.

**Comment by alex4200** [comment]
@clupascu : It is fixed in the case "Synaptic events fitting with user model" but not in the case "Synaptic events fitting with user data"...

**Comment by clupascu** [comment]
I fixed this. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Yep fixed
