### ISSUE TITLE
Unable to load some models for NaaS

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#68]
### Expected behavior

Able to load every model 

### Actual Behavior

Some models can be loaded, some cannot (Error: Model loading failed)

### Steps to reproduce the problem

Use case "_Single cell in silico experiments under current/voltage clamp_"

**Comment by alex4200** [comment]
@genric : Any news on that issue?

**Comment by liesbethvanherpe** [comment]
Hi @alex4200, this is probably related to this issue: https://github.com/lbologna/bsp_data_repository/issues/23.

**Comment by genric** [comment]
Yep, thanks @liesbethvanherpe.

**Comment by genric** [comment]
Should be fixed, please retest. Thanks.

**Comment by alex4200** [comment]
Yes seems to work now again.
