### ISSUE TITLE
Rerunning NSG simulation on same notebook not handled gracefully 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#69]
### Expected behavior

Rerun the same notebook with modified input data etc. 

### Actual Behavior

The second time I click on "Run NSG simulation" I get an OSError

### Steps to reproduce the problem

1. Choose exp file, model, Create config file
2. Login to NSG start simulation
3. Logout of Laptop/computer account
4. Click "Run NSG simulation" again

### Optional infrastructural data (user, platform, browser, environment, ...)

![screen shot 2017-11-15 at 13 31 29](https://user-images.githubusercontent.com/12729291/32836200-517d06c8-ca09-11e7-9cd8-01258297b802.png)

**Comment by clupascu** [comment]
Actually you are not supposed to save the notebook before step3 Logout of Laptop/computer account. Every time you enter again you should run all cells again and have the clean graphical user interface again and be able to start from the beginning.

**Comment by alex4200** [comment]
@clupascu Then this issue related to issue #17 : It must be clearly stated in the top-level notebook cell how to run this use case (run all), and that you have to stay connected until this use case has finished. 

Can you add such a README cell to the notebook? 

Thanks

**Comment by clupascu** [comment]
I inserted a markdown in the top-level notebook cell of all my usecases to clearly state how to run this use case (run all) and that you have to stay connected until this use case has finished. Please let me know if the text is clear. Thanks.

**Comment by alex4200** [comment]
Very clear and precise, thanks
