### ISSUE TITLE
Link to the Neo library seems to be outdated or incorrect.

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#7]
### Expected behavior

Clicking on the link to the Neo library opens the correct page

### Actual Behavior

404 Not Found

### Steps to reproduce the problem

![screen shot 2017-09-29 at 11 44 43](https://user-images.githubusercontent.com/12729291/31010590-aaa96e58-a50b-11e7-9ce2-fb005c8e6bb0.png)

### Optional infrastructural data (user, platform, browser, environment, ...)

Mac, Firefox

**Comment by lbologna** [comment]
Broken link fixed
