### ISSUE TITLE
TypeError when analysing results 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#70]
### Expected behavior

No error at all

### Actual Behavior

Type error. Some variables seem to be 'None'.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-3520e2d87e29> in tabledata(_)
    219             if storage.exists(get_collab_storage_path()+os.sep+'resultsNSG')==True:
    220                 if storage.exists(get_collab_storage_path()+os.sep+'resultsNSG'+os.sep+SF.value)==True:
--> 221                     storage.download_file(get_collab_storage_path()+os.sep+'resultsNSG'+os.sep+SF.value+os.sep+myboxRB.children[0].value,myboxRB.children[0].value)
    222                     storage.download_file(get_collab_storage_path()+os.sep+'resultsNSG'+os.sep+SF.value+os.sep+myboxRB.children[1].value,myboxRB.children[1].value)
    223                     storage.download_file(get_collab_storage_path()+os.sep+'resultsNSG'+os.sep+SF.value+os.sep+myboxRB.children[2].value,myboxRB.children[2].value)

TypeError: coercing to Unicode: need string or buffer, NoneType found
```
Very hard to debug error, because once you click again on the same button, you get a different error:

```
OSError                                   Traceback (most recent call last)
<ipython-input-14-3520e2d87e29> in tabledata(_)
    161 def tabledata(_):
    162     clear_output()
--> 163     os.chdir('transfer')
    164     import readconffile as rcf
    165     os.chdir('..')

OSError: [Errno 2] No such file or directory: 'transfer'
```
### Steps to reproduce the problem

Follow the use case with an exp file, an mod file, and 2 fitting parameters (synapse.tau1 and synapse.tau2 between 0 and 10). Select the data in the storage and click on 'Results table'. 

### Additional information

The reason for this error is probably because of the nonexistence of the exp/mod files. But you cannot select these files:

![screen shot 2017-11-15 at 15 21 32](https://user-images.githubusercontent.com/12729291/32840749-daf4ac30-ca18-11e7-9443-7a009db608c8.png)

**Comment by clupascu** [comment]
can you point me to this test collab you created so that I can see what is inside output_... folders?
Thanks.

**Comment by alex4200** [comment]
@clupascu Added you to collab Test-A3-1

**Comment by clupascu** [comment]
I fixed this.  In the case the output folder has no txt or no csv file in it, an alert is displayed saying 'no txt or csv files in the output folder'. Can you please test again? Thanks.

**Comment by clupascu** [comment]
I fixed this. You should try 'singletrace' option with trace number 20. In this case you should get some result in the csv file. I changed also the tool, now everything is running on STAMPEDE2KNL Can you please test again? Thanks.

**Comment by clupascu** [comment]
This should be fixed. I commented issue #99. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Yes fixed now
