### ISSUE TITLE
NSG Input boxed not aligned

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#78]
### Expected behavior

Input boxes aligned correctly

### Actual Behavior

Input boxes not quite aligned in the notebook "NSG Job Manager"

### Steps to reproduce the problem

Just "run all"

Chrome on Linux
![selection_088](https://user-images.githubusercontent.com/12729291/33006744-d4fe965e-cdcb-11e7-9b21-9487d9d57997.png)

**Comment by clupascu** [comment]
I fixed this. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Fixed
