### ISSUE TITLE
Hard to distinguish and select features for the feature extraction

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#8]
On the feature selection page:

![screen shot 2017-09-29 at 11 55 28](https://user-images.githubusercontent.com/12729291/31011081-525f416c-a50d-11e7-99ec-2845f96e0d6f.png)

it is a bit hard to select the single features. They are hard to distinguish from each other. Maybe some space between each feature would help.

**Comment by lbologna** [comment]
This should be fixed now. Would you check again please?
Thanks

**Comment by alex4200** [comment]
Yes that better I would say...
