### ISSUE TITLE
CDP2-P2: Single model benchmark and validation suite, first public release

### ISSUE THREAD

**Issue by apdavison** [cnr-ibf-pa/hbp-bsp-issues#83]
- [x] tag validation suite packages on Github
  - [x] Hippounit
  - [x] Cerebunit
  - [x] eFELunit
  - [x] Basalunit
  - [x] Morphounit
- [x] Software Catalog entries for each package
  - [x] Hippounit
  - [x] Cerebunit
  - [x] eFELunit
  - [x] Basalunit
  - [x] Morphounit
- [x] create [Collab](https://collab.humanbrainproject.eu/#/collab/8123/nav/61654) giving an overview of the validation suite
- [x] create Jupyter notebook for each model, demonstrating how to validate models
  - [x] Hippounit
  - [x] Cerebunit
  - [x] eFELunit
  - [x] Basalunit
  - [x] Morphounit
- [x] create Online Use Case which installs the notebooks in a user's collab
  - [x] Hippounit
  - [x] Cerebunit
  - [x] eFELunit
  - [x] Basalunit
  - [x] Morphounit

**Comment by alex4200** [comment]
First workable use cases expected in 1-2 weeks (i.e. until about 14 Feb 2018)

**Comment by appukuttan-shailesh** [comment]
- `MorphoUnit` is currently inactive (no immediate demands from model developers); and therefore not expecting any progress in the near future
- Use case for `HippoUnit` will be ready by mid-March (latest)
- `BasalUnit` usecase is already online; but will have a few more quick updates adding more features
- `SubCellUnit` could likely be ready in mid-March, and so could be added to the list and introduced as a usecase.
- `CerebUnit` (?)

The issue as a whole will probably only be completed by end of March (with `MorphoUnit` being taken out?).

**Comment by alex4200** [comment]
@appukuttan-shailesh Any update on this issue? The use cases should be ready _before_ the end of the deadline...

**Comment by appukuttan-shailesh** [comment]
We are working on three more use cases... 2 of these are expected in a day or two...... and that will probably be our target. `Morphounit` is still too nascent to merit its own usecase. But given that we have two more weeks, we shall see if something basic is doable (if there are no other deliverables with higher priority).

@apdavison: could you confirm if this is fine?

**Comment by apdavison** [comment]
Yes, I think that's fine (note that the online use cases are not part of the formal deliverables for our task, they are an extra activity, although I think they're very useful for demonstrating how to use the tools).

**Comment by alex4200** [comment]
According to @appukuttan-shailesh 3 validation use cases ready for 16 March 2018

**Comment by appukuttan-shailesh** [comment]
Another use case ready for testing:
"Hippocampus Single Cell - BluePyOpt Optimized Model Validation"

**Comment by appukuttan-shailesh** [comment]
@alex4200: Another use case ready for testing:
"Validation Framework Demo (Walkthrough)"

**Comment by jdcourcol** [comment]
Probably end of week (Apr 20th)

**Comment by apdavison** [comment]
Why is this ticket still open? The first public release of the benchmark suite was in January if I remember correctly. If we wish to track additional use cases beyond the first release, maybe there should be a separate ticket?

**Comment by appukuttan-shailesh** [comment]
That's true, the current discussion is regarding additional usecases. I suppose we ended up continuing the discussions here as not all the targets (checkboxes) were ticked... I should probably have deleted the parts not being addressed in the first release.

As of now, only one item is left and that is expected to complete this week. So shall anyhow have this ticket closed by the end of the week.

**Comment by appukuttan-shailesh** [comment]
@alex4200 : The final usecase (under these tasks) is now uploaded. So we can close this issue, and discuss any specific problems (hopefully none!) in their respective issues.

**Comment by alex4200** [comment]
Ok can be closed, thanks
