### ISSUE TITLE
Add statistics gathering to Validation Service

### ISSUE THREAD

**Issue by apdavison** [cnr-ibf-pa/hbp-bsp-issues#86]

**Comment by alex4200** [comment]
@apdavison  : can you please assign this issue to a month-milestone? Thanks

**Comment by apdavison** [comment]
This is for SGA2, unless someone tells me it is needed urgently.

**Comment by alex4200** [comment]
@appukuttan-shailesh Hi, is this ticket something you can work on? please let me know, thanks...

**Comment by apdavison** [comment]
I created this ticket based on something @jdcourcol mentioned, but I don't know much about it. Could @jdcourcol give us more information about what is needed?

**Comment by jdcourcol** [comment]
@apdavison the idea is to be able to collect statistics for the EU report that will ask for the number of users of your application.
We can get that number through the use cases as we collect statistics from that GUI. if there is another way to access your application (such as a direct URL), then I think you should collect the statistics from your app.

**Comment by apdavison** [comment]
ok, since people can also access the service through a REST API and Python client, it would be best to collect these statistics directly. In that case, I propose to rename this issue "Add statistics gathering to Validation Service" if you agree @alex4200

**Comment by alex4200** [comment]
@apdavison Yes I agree to that better naming of this issue...

**Comment by alex4200** [comment]
Covered by Luca's BSP statistics.
