### ISSUE TITLE
Syntax error in "Synaptic events fitting with user model"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#87]
There is a syntax error in this use case, cell 4: a missing bracket

Instead of 
`copy2(os.path.join('..','transfer','fitness.py','fitness.py')`

if must be 
`copy2(os.path.join('..','transfer','fitness.py'),'fitness.py')`

**Comment by clupascu** [comment]
I fixed this. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Ok fixed
