### ISSUE TITLE
Syntax error in Synaptic Ev Fitting with User Date Notebook

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#88]
Syntax error in notebook "Synaptic events fitting with user data".

line 177 , in function  "tabledata(_):"

`        copy2(conff,os.path.join('..','transfer/')`

should be

`        copy2(conff,os.path.join('..','transfer/'))`

**Comment by clupascu** [comment]
I fixed this. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Ok
