### ISSUE TITLE
Cell Placement Hippocampus: Circuit placement save suggestion

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#89]
I have a suggestion for saving the cell placement at the end of the notebook, and to copy this file to the storage for the notebook so a user can download this file for his/her purposes:

```
import os, time
timestamp = time.strftime('%Y%m%d_%H%M%S')
cells_filename = 'circuit_'+timestamp+'.mvd3'
cells_file = os.path.join(DATA_DIR, cells_filename)
cells.save(cells_file)

clients = get_hbp_service_client()
collab_path = get_collab_storage_path()

_=clients.storage.upload_file(cells_file, os.path.join(collab_path, cells_filename), 'text/plain')
print("Placement has been saved in "+cells_filename)
```

**Comment by antonelepfl** [comment]
@jdcourcol Do we need to implement this in the 'Template / Base' notebook or is it a decision of the user to do it?

**Comment by alex4200** [comment]
@antonelepfl @jdcourcol Any news for this issue?

**Comment by antonelepfl** [comment]
I have already implemented. Check if you are able to save them.

**Comment by alex4200** [comment]
Just one more thing: You need to upgrade the hbp client to version 1.0.0 somewhere at the begin of the notebook:

!pip install --upgrade "hbp-service-client==1.0.0"

Can you just insert this line, maybe in the second cell? Thanks
