### ISSUE TITLE
No preview of 'grand means' provided as mentioned in the description

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#9]
### Expected behavior

A preview of grand means from the json file at the end of the use case, as described in the description:

![screen shot 2017-09-29 at 11 47 50](https://user-images.githubusercontent.com/12729291/31011257-e4636ae8-a50d-11e7-8cca-4c4af92b68cb.png)

### Actual Behavior

No such preview is visible

### Steps to reproduce the problem

Perform the whole use case

**Comment by lbologna** [comment]
Experimentalists gave feedback as how the preview was not really helpful.
We removed the preview and left the link to all the entire set of results
