### ISSUE TITLE
Computer clusters to use

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#90]
In the use cases "Synaptic events fitting" currently the systems JURECA, MARCONI and NSG can be selected. 
Is that the correct choice, or will that be changed to JURON, JULIA and NSG?

**Comment by clupascu** [comment]
For now the systems JURECA, MARCONI and NSG can be selected. JUQUEEN will be added shortly. JULIA maybe in the future...

**Comment by alex4200** [comment]
The possible cluster depends on the use case and on the tools installed on the respective clusters...

**Comment by alex4200** [comment]
The custer usage will not be transparent to the end user. Therefore, a choice of clusters options must be offerered.
