### ISSUE TITLE
Optimization of CA3 cells (mouse)

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#91]
The task is to have a new model (for the CA3 region for mouse), for which electrophysiological data are required (from external sources).

Similar tasks: #92 #120

**Comment by mmigliore** [comment]
@alex4200: please split this in two different issues for rat and mouse. 
Data for mouse is available from KOKI and optimization is at the preliminary stage.
Data for rat is still unavailable.

**Comment by alex4200** [comment]
Data for mouse is available from KOKI and optimization is at the preliminary stage.

**Comment by mmigliore** [comment]
Please move it to SGA2.

**Comment by mmigliore** [comment]
preliminary optimizations are in progress. First results can be expected in two months

**Comment by clupascu** [comment]
@szkali any news on the first release of the CA3 optimizations?

**Comment by szkali** [comment]
We have some preliminary results on mouse CA3 pyramidal cells and PV+ basket cells, but we did not have the bandwidth to pursue this more intensively because we were focusing on other tasks. We plan to take this up again soon, so that we can hopefully have a release (including at least these two cell types) some time in the fall.
I also think it would be useful to run some optimizations using the same methods that were used, e.g., in Migliore et al. (2018), and compare the results. We will try to do this ourselves, but we will probably ask for some help in running the optimizations on the HPC systems.

**Comment by alex4200** [comment]
The expected time-frame for the release of optimized CA3 models is still fall 2019.

**Comment by alex4200** [comment]
@szkali Can you please give an updated status for this ticket?

**Comment by szkali** [comment]
We recently started working on this task again. I will update this ticket when we have the results.

**Comment by alex4200** [comment]
@szkali Hi, do you have any updates regarding this issue? Is the plan still to have results by the end of SGA2?

**Comment by szkali** [comment]
There has been some progress, but the student working on this task is currently on vacation. We will provide an update on the status when she gets back (in about two weeks).

**Comment by lbologna** [comment]
Hello @szkali,

is there any news on this issue?
Thank you

**Comment by szkali** [comment]
Our earlier attempts to fit the mouse CA3 PCs did not produce satisfactory results. We have now obtained additional data from an external collaborator, which will allow us to constrain channel properties, and should lead to better results.
However, I do not expect to have release-quality final results before the end of March.

**Comment by lbologna** [comment]
Hello @szkali,

thanks for the update.
Being this a standalone issue with work in progress and not related to a specific use case, I suggest that we close it at the moment.
When some data will be available to be integrated in specific use cases, we can then open new issues tailored to those.
If you agree I can't take care of closing the issue.
Thank you.

**Comment by szkali** [comment]
Hi @lbologna ,
Thanks for your feedback. I agree with your proposed solution - there is no point in keeping this issue open for the rest of SGA2.

**Comment by lbologna** [comment]
Ok, thanks.
Closing the issue.
