### ISSUE TITLE
Optimization of DG cells (mouse)

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#92]
The task is to have a new model (for the DG region for mouse and rat), for which electrophysiological data are required (from external sources).  

Similar tasks: #91 #120

**Comment by mmigliore** [comment]
No data. Please move it to SGA2

**Comment by mmigliore** [comment]
No updates to report so far. A first set of models is expected in one month.

**Comment by mmigliore** [comment]
Done. First release for 20 models stored on container
