### ISSUE TITLE
add Werner L5PC's single cell optimization in BSP (non runnable for now)

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#93]

**Comment by wvangeit** [comment]
Not sure I understand this ticket. With 'Werner L5PC single cell optimization'. Do you mean the example in BluePyOpt ?
There is an example notebook for this use case in the collab. Do you mean that that doesn't work anymore, or that it needs to change ?

**Comment by jdcourcol** [comment]
We need an example of a L5PC optimization to be registered in Michele's 'NIP' repository, so that it can be consumed in the use cases

**Comment by wvangeit** [comment]
Could somebody also point me to the exact page of the use cases ? Are these the BlueNAAS use cases ? Or is it some place from where one can run an optimisation ? (or is there some doc somewhere ?)

**Comment by alex4200** [comment]
Low priority issue.

**Comment by jdcourcol** [comment]
This is on hold. Priority is given to get BluePyMM to be open sourced.

**Comment by alex4200** [comment]
Decided to not pursue this item, as it would mean to refactor all the models.
