### ISSUE TITLE
User Documentation: collab -> Collab

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#95]
On the user documentation for Morphology Analysis [HERE](https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/morphology_analysis/morphology_analysis/morphology_analysis.html) I suggest to replace each occurrence of 'collab' by 'Collab' (as its more like a name of something).

**Comment by liesbethvanherpe** [comment]
I changed 'collab' to 'Collab' as requested.
