### ISSUE TITLE
Naming of use case in Collab for (Re)building single hippocampus cell

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#97]
### Expected behavior

Use case is similar or the same as when it has been selected ("Rebuild an existing single hippocampal cell model"/"Build your own single hippocampal cell model using HBP data")

### Actual Behavior

Naming is:

- BluePyOpt Browse all
- NSG Job Manager
- BlueByOpt Analysis

### Steps to reproduce the problem

- Choose the use case and create a new collab

Suggestion: 
Maybe something like
- Rebuild Single HippoCell - Config
- Rebuild Single HippoCell - Analysis
- BuildOwn Single HippoCell - Config
- BuildOwn Single HippoCell - Analysis

together with the optional name of the model

**Comment by clupascu** [comment]
I fixed this as you suggested. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Yes better...
