### ISSUE TITLE
NameError in "Synaptic events fitting with user model"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#99]
Error message: 

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-01193dca777a> in checksimnsg(CheckSNSG)
    573 def checksimnsg(CheckSNSG):
    574     headers = {'cipres-appkey' : KEY}
--> 575     r = requests.get(selfuri, auth=(CRA_USER, PASSWORD), headers=headers)
    576     #print(r.text)
    577     root = xml.etree.ElementTree.fromstring(r.text)

NameError: global name 'selfuri' is not defined
```

My guess is an error in the function 'runNSG', as the variable 'selfuri' will not be defined in every case. 

![selection_109](https://user-images.githubusercontent.com/12729291/33553678-f80a7a44-d8f9-11e7-9d9a-53b0e16567b1.png)

Relates to #70

**Comment by clupascu** [comment]
This should be fixed now, When I changed the TOOL from NEURON74_PY_TG to NEURON74_PY_STAMPEDE2KNL, the job was not submitted as the tool is invalid, that is why you get the above error. I fixed this by restoring the TOOL to NEURON74_PY_TG, so everything is submitted again on COMET. I opened an issue on NSG to understand if we can submit on STAMPEDE using REST API's. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Ok, is fixed...
